souffle: souffle::WriteStream Class Reference
souffle::WriteStream Class Reference abstract
#include <WriteStream.h>
Public Member Functions
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::vector< bool > &symbolMask, const SymbolTable &symbolTable, const bool prov, bool summary=false)
virtual ~WriteStream ()=default
Protected Member Functions
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeNextTuple (const RamDomain *tuple)=0
virtual void writeNullary ()=0
virtual void writeSize (std::size_t size)
Protected Attributes
const size_t arity
const bool isProvenance
const bool summary
const std::vector< bool > & symbolMask
const SymbolTable & symbolTable
Detailed Description
Definition at line 27 of file WriteStream.h.
Constructor & Destructor Documentation
souffle::WriteStream::WriteStream (const std::vector< bool > & symbolMask, const SymbolTable & symbolTable, const bool prov, bool summary = false) inline
Definition at line 29 of file WriteStream.h.
             : symbolMask(symbolMask), symbolTable(symbolTable), isProvenance(prov), summary(summary),
               arity(symbolMask.size() - (prov ? 2 : 0)) {}
virtual souffle::WriteStream::~WriteStream () virtual default
Referenced by writeSize().
Member Function Documentation
template<typename T > void souffle::WriteStream::writeAll (const T & relation) inline
Definition at line 34 of file WriteStream.h.
References souffle::SymbolTable::acquireLock(), arity, summary, symbolTable, writeNext(), writeNullary(), and writeSize().
{
         if (summary) {
             return writeSize(relation.size());
         }
         auto lease = symbolTable.acquireLock();
         (void)lease;
         if (arity == 0) {
             if (relation.begin() != relation.end()) {
                 writeNullary();
             }
             return;
         }
         for (const auto& current : relation) {
             writeNext(current);
         }
     }
template<typename Tuple > void souffle::WriteStream::writeNext (const Tuple tuple) inline protected
Definition at line 70 of file WriteStream.h.
References writeNextTuple().
Referenced by writeAll().
{
         writeNextTuple(tuple.data);
     }
template<> void souffle::WriteStream::writeNext (const RamDomain * tuple) inline
Definition at line 84 of file WriteStream.h.
References writeNextTuple().
{
     writeNextTuple(tuple);
 }
virtual void souffle::WriteStream::writeNextTuple (const RamDomain * tuple) protected pure virtual
Implemented in souffle::WriteCoutPrintSize, souffle::WriteCoutCSV, souffle::WriteFileCSV, and souffle::WriteStreamSQLite.
Referenced by writeNext().
virtual void souffle::WriteStream::writeNullary () protected pure virtual
Implemented in souffle::WriteCoutPrintSize, souffle::WriteCoutCSV, souffle::WriteFileCSV, and souffle::WriteStreamSQLite.
Referenced by writeAll().
template<typename T > void souffle::WriteStream::writeSize (const T & relation) inline
Definition at line 51 of file WriteStream.h.
References ~WriteStream().
Referenced by writeAll().
{
         writeSize(relation.size());
     }
virtual void souffle::WriteStream::writeSize (std::size_t size) inline protected virtual
Reimplemented in souffle::WriteCoutPrintSize.
Definition at line 66 of file WriteStream.h.
{
         assert(false && "attempting to print size of a write operation");
     }
Field Documentation
const size_t souffle::WriteStream::arity protected
Definition at line 62 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::createRelationTable(), souffle::WriteStreamSQLite::createRelationView(), souffle::WriteStreamSQLite::prepareInsertStatement(), writeAll(), and souffle::WriteStreamSQLite::writeNextTuple().
const bool souffle::WriteStream::isProvenance protected
Definition at line 60 of file WriteStream.h.
const bool souffle::WriteStream::summary protected
Definition at line 61 of file WriteStream.h.
Referenced by writeAll().
const std::vector<bool>& souffle::WriteStream::symbolMask protected
Definition at line 58 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::createRelationView(), souffle::WriteSQLiteFactory::getWriter(), and souffle::WriteStreamSQLite::writeNextTuple().
const SymbolTable& souffle::WriteStream::symbolTable protected
Definition at line 59 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::getSymbolTableID(), souffle::WriteStreamSQLite::getSymbolTableIDFromDB(), souffle::WriteSQLiteFactory::getWriter(), and writeAll().
The documentation for this class was generated from the following file:
WriteStream.h