souffle: souffle::DebugReportSection Class Reference
souffle::DebugReportSection Class Reference
Class representing a section of a HTML report.
#include <DebugReport.h>
Public Member Functions
DebugReportSection (const std::string &id, std::string title, std::vector< DebugReportSection > subsections, std::string body)
bool hasSubsections () const
void printContent (std::ostream &out) const
Outputs the HTML code for the content of the section to the given stream, consisting of the title header, the body text, followed by the content for each subsection.
void printIndex (std::ostream &out) const
Outputs the HTML code for the index to the given stream, consisting of a link to the section body followed by a list of the indices for each subsection.
void printTitle (std::ostream &out) const
Outputs the HTML code for the title header to the given stream.
Static Private Member Functions
static std::string generateUniqueID (const std::string &id)
Private Attributes
std::string body
std::string id
std::vector< DebugReportSection > subsections
std::string title
Detailed Description
Class representing a section of a HTML report.
Consists of a unique identifier, a title, a number of subsections, and the HTML code for the body of the section.
Definition at line 39 of file DebugReport.h.
Constructor & Destructor Documentation
souffle::DebugReportSection::DebugReportSection (const std::string & id, std::string title, std::vector< DebugReportSection > subsections, std::string body) inline
Definition at line 41 of file DebugReport.h.
References printContent(), printIndex(), and printTitle().
Referenced by souffle::DebugReporter::generateDebugReport(), souffle::DebugReporter::getCodeSection(), souffle::DebugReporter::getDotGraphSection(), and souffle::DebugReporter::transform().
             : id(generateUniqueID(id)), title(std::move(title)), subsections(std::move(subsections)),
               body(std::move(body)) {}
Member Function Documentation
static std::string souffle::DebugReportSection::generateUniqueID (const std::string & id) inline static private
Definition at line 75 of file DebugReport.h.
{
         static int count = 0;
         return id + std::to_string(count++);
     }
bool souffle::DebugReportSection::hasSubsections () const inline
Definition at line 65 of file DebugReport.h.
References subsections.
{
         return !subsections.empty();
     }
void souffle::DebugReportSection::printContent (std::ostream & out) const
Outputs the HTML code for the content of the section to the given stream, consisting of the title header, the body text, followed by the content for each subsection.
Definition at line 100 of file DebugReport.cpp.
References body, printTitle(), and subsections.
Referenced by DebugReportSection().
{
     printTitle(out);
     out << "<div style='padding-left: 1em'>\n";
     out << body << "\n";
     for (const DebugReportSection& subsection : subsections) {
         subsection.printContent(out);
     }
     out << "</div>\n";
 }
void souffle::DebugReportSection::printIndex (std::ostream & out) const
Outputs the HTML code for the index to the given stream, consisting of a link to the section body followed by a list of the indices for each subsection.
Definition at line 70 of file DebugReport.cpp.
References subsections, and title.
Referenced by DebugReportSection().
{
     out << "<a href=\"#" << id << "\">" << title << "</a>\n";
     out << "<ul>\n";
     bool isLeaf = true;
     for (const DebugReportSection& subsection : subsections) {
         if (subsection.hasSubsections()) {
             isLeaf = false;
             break;
         }
     }
     for (const DebugReportSection& subsection : subsections) {
         if (isLeaf) {
             out << "<li class='leaf'>";
         } else {
             out << "<li>";
         }
         subsection.printIndex(out);
         out << "</li>";
     }
     out << "</ul>\n";
 }
void souffle::DebugReportSection::printTitle (std::ostream & out) const
Outputs the HTML code for the title header to the given stream.
Definition at line 92 of file DebugReport.cpp.
References title.
Referenced by DebugReportSection(), and printContent().
{
     out << "<a id=\"" << id << "\"></a>\n";
     out << "<div class='headerdiv'>\n";
     out << "<h1>" << title << "</h1>\n";
     out << "<a href='#'>(return to top)</a>\n";
     out << "</div><div style='clear:both'></div>\n";
 }
Field Documentation
std::string souffle::DebugReportSection::body private
Definition at line 73 of file DebugReport.h.
Referenced by printContent().
std::string souffle::DebugReportSection::id private
Definition at line 70 of file DebugReport.h.
std::vector<DebugReportSection> souffle::DebugReportSection::subsections private
Definition at line 72 of file DebugReport.h.
Referenced by hasSubsections(), printContent(), and printIndex().
std::string souffle::DebugReportSection::title private
Definition at line 71 of file DebugReport.h.
Referenced by souffle::DebugReporter::getName(), printIndex(), and printTitle().
The documentation for this class was generated from the following files:
DebugReport.h
DebugReport.cpp