souffle: souffle::AstTranslationUnit Class Reference
souffle::AstTranslationUnit Class Reference
AstTranslationUnit class.
#include <AstTranslationUnit.h>
Public Member Functions
AstTranslationUnit (std::unique_ptr< AstProgram > program, SymbolTable &s, ErrorReport &e, DebugReport &d, bool nowarn=false)
template<class Analysis >
Analysis * getAnalysis () const
get analysis: analysis is generated on the fly if not present
DebugReport & getDebugReport ()
get debug report
const DebugReport & getDebugReport () const
get debug report
ErrorReport & getErrorReport ()
get error report
const ErrorReport & getErrorReport () const
get error report
AstProgram * getProgram ()
get the AST program
const AstProgram * getProgram () const
get the AST program
souffle::SymbolTable & getSymbolTable ()
get symbol table
const souffle::SymbolTable & getSymbolTable () const
get symbol table
void invalidateAnalyses ()
destroy all cached analyses of translation unit
virtual ~AstTranslationUnit ()=default
Private Attributes
std::map< std::string, std::unique_ptr< AstAnalysis > > analyses
cached analyses
DebugReport & debugReport
HTML debug report.
ErrorReport & errorReport
Error report capturing errors while compiling.
std::unique_ptr< AstProgram > program
AST program.
SymbolTable & symbolTable
Symbol table of AST program.
Detailed Description
AstTranslationUnit class.
Definition at line 36 of file AstTranslationUnit.h.
Constructor & Destructor Documentation
souffle::AstTranslationUnit::AstTranslationUnit (std::unique_ptr< AstProgram > program, SymbolTable & s, ErrorReport & e, DebugReport & d, bool nowarn = false) inline
Definition at line 38 of file AstTranslationUnit.h.
References ~AstTranslationUnit().
             : program(std::move(program)), symbolTable(s), errorReport(e), debugReport(d) {}
virtual souffle::AstTranslationUnit::~AstTranslationUnit () virtual default
Referenced by AstTranslationUnit().
Member Function Documentation
template<class Analysis > Analysis* souffle::AstTranslationUnit::getAnalysis () const inline
get analysis: analysis is generated on the fly if not present
Definition at line 46 of file AstTranslationUnit.h.
References analyses.
Referenced by souffle::RelationSchedule::computeRelationExpirySchedule(), souffle::BddBddBTranslator::convert(), souffle::LogicbloxConverter::convert(), souffle::DebugReporter::generateDebugReport(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::TypeAnalysis::run(), souffle::RedundantRelations::run(), souffle::SCCGraph::run(), souffle::Adornment::run(), souffle::TopologicallySortedSCCGraph::run(), souffle::RelationSchedule::run(), souffle::AstComponentChecker::transform(), souffle::AstSemanticChecker::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::ComponentInstantiationTransformer::transform(), souffle::RemoveRedundantRelationsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), and souffle::AstTranslator::translateProgram().
{
         std::string name = Analysis::name;
         auto it = analyses.find(name);
         if (it == analyses.end()) {
             // analysis does not exist yet, create instance and run it.
             analyses[name] = std::make_unique<Analysis>();
             analyses[name]->run(*this);
         }
         return dynamic_cast<Analysis*>(analyses[name].get());
     }
DebugReport& souffle::AstTranslationUnit::getDebugReport () inline
get debug report
Definition at line 93 of file AstTranslationUnit.h.
References debugReport.
Referenced by souffle::DebugReporter::generateDebugReport(), souffle::DebugReporter::transform(), and souffle::AstTranslator::translateUnit().
{
         return debugReport;
     }
const DebugReport& souffle::AstTranslationUnit::getDebugReport () const inline
get debug report
Definition at line 98 of file AstTranslationUnit.h.
References debugReport.
{
         return debugReport;
     }
ErrorReport& souffle::AstTranslationUnit::getErrorReport () inline
get error report
Definition at line 78 of file AstTranslationUnit.h.
References errorReport.
Referenced by souffle::MetaTransformer::applySubtransformer(), souffle::AstComponentChecker::transform(), souffle::AstSemanticChecker::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::ComponentInstantiationTransformer::transform(), and souffle::AstTranslator::translateUnit().
{
         return errorReport;
     }
const ErrorReport& souffle::AstTranslationUnit::getErrorReport () const inline
get error report
Definition at line 83 of file AstTranslationUnit.h.
References errorReport.
{
         return errorReport;
     }
AstProgram* souffle::AstTranslationUnit::getProgram () inline
get the AST program
Definition at line 58 of file AstTranslationUnit.h.
References program.
Referenced by souffle::RecursiveClauses::computeIsRecursive(), souffle::BddBddBTranslator::convert(), souffle::LogicbloxConverter::convert(), souffle::DebugReporter::generateDebugReport(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::IOType::run(), souffle::TypeEnvironmentAnalysis::run(), souffle::TypeAnalysis::run(), souffle::PrecedenceGraph::run(), souffle::RedundantRelations::run(), souffle::ComponentLookup::run(), souffle::RecursiveClauses::run(), souffle::SCCGraph::run(), souffle::Adornment::run(), souffle::AstComponentChecker::transform(), souffle::AstSemanticChecker::transform(), souffle::ResolveAliasesTransformer::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::AstPragmaChecker::transform(), souffle::ComponentInstantiationTransformer::transform(), souffle::UniqueAggregationVariablesTransformer::transform(), souffle::RemoveRedundantRelationsTransformer::transform(), souffle::MinimiseProgramTransformer::transform(), souffle::ProvenanceTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::NormaliseConstraintsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::RemoveTypecastsTransformer::transform(), and souffle::AstTranslator::translateUnit().
{
         return program.get();
     }
const AstProgram* souffle::AstTranslationUnit::getProgram () const inline
get the AST program
Definition at line 63 of file AstTranslationUnit.h.
References program.
{
         return program.get();
     }
souffle::SymbolTable& souffle::AstTranslationUnit::getSymbolTable () inline
get symbol table
Definition at line 68 of file AstTranslationUnit.h.
References symbolTable.
Referenced by souffle::makeInfoRelation(), souffle::MagicSetTransformer::transform(), and souffle::AstTranslator::translateUnit().
{
         return symbolTable;
     }
const souffle::SymbolTable& souffle::AstTranslationUnit::getSymbolTable () const inline
get symbol table
Definition at line 73 of file AstTranslationUnit.h.
References symbolTable.
{
         return symbolTable;
     }
void souffle::AstTranslationUnit::invalidateAnalyses () inline
destroy all cached analyses of translation unit
Definition at line 88 of file AstTranslationUnit.h.
References analyses.
Referenced by souffle::AstTransformer::apply().
{
         analyses.clear();
     }
Field Documentation
std::map<std::string, std::unique_ptr<AstAnalysis> > souffle::AstTranslationUnit::analyses mutable private
cached analyses
Definition at line 104 of file AstTranslationUnit.h.
Referenced by getAnalysis(), and invalidateAnalyses().
DebugReport& souffle::AstTranslationUnit::debugReport private
HTML debug report.
Definition at line 116 of file AstTranslationUnit.h.
Referenced by getDebugReport().
ErrorReport& souffle::AstTranslationUnit::errorReport private
Error report capturing errors while compiling.
Definition at line 113 of file AstTranslationUnit.h.
Referenced by getErrorReport().
std::unique_ptr<AstProgram> souffle::AstTranslationUnit::program private
AST program.
Definition at line 107 of file AstTranslationUnit.h.
Referenced by getProgram().
SymbolTable& souffle::AstTranslationUnit::symbolTable private
Symbol table of AST program.
Definition at line 110 of file AstTranslationUnit.h.
Referenced by getSymbolTable().
The documentation for this class was generated from the following file:
AstTranslationUnit.h