souffle: souffle::RamBreak Class Reference
souffle::RamBreak Class Reference
Break statement.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamBreak * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getCondition () const
Get break condition.
void print (std::ostream &os, int tabpos) const override
RamBreak (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Abstract equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamCondition > condition
Condition that is checked for each obtained tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Break statement.
Definition at line 769 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamBreak::RamBreak (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 771 of file RamOperation.h.
             : RamNestedOperation(std::move(nested), std::move(profileText)), condition(std::move(cond)) {}
Member Function Documentation
void souffle::RamBreak::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 797 of file RamOperation.h.
References souffle::RamNestedOperation::apply().
{
         RamNestedOperation::apply(map);
         condition = map(std::move(condition));
     }
RamBreak* souffle::RamBreak::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 792 of file RamOperation.h.
{
         return new RamBreak(std::unique_ptr<RamCondition>(condition->clone()),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
     }
bool souffle::RamBreak::equal (const RamNode & other) const inline override protected virtual
Abstract equality check for two RAM nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 810 of file RamOperation.h.
References souffle::RamNestedOperation::equal().
{
         assert(nullptr != dynamic_cast<const RamBreak*>(&node));
         const auto& other = static_cast<const RamBreak&>(node);
         return RamNestedOperation::equal(node) && getCondition() == other.getCondition();
     }
std::vector<const RamNode*> souffle::RamBreak::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 786 of file RamOperation.h.
References souffle::RamNestedOperation::getChildNodes().
{
         auto res = RamNestedOperation::getChildNodes();
         res.push_back(condition.get());
         return res;
     }
const RamCondition& souffle::RamBreak::getCondition () const inline
Get break condition.
Definition at line 776 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), and souffle::LVMGenerator::visitBreak().
{
         return *condition;
     }
void souffle::RamBreak::print (std::ostream & os, int tabpos) const inline override virtual
Reimplemented from souffle::RamNestedOperation.
Definition at line 780 of file RamOperation.h.
References souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "IF " << getCondition() << " BREAK" << std::endl;
         RamNestedOperation::print(os, tabpos);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamBreak::condition protected
Condition that is checked for each obtained tuple.
If condition is a nullptr, then no condition applies
Definition at line 808 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h