souffle: souffle::RamIndexScan Class Reference
souffle::RamIndexScan Class Reference
Relation Scan with Index.
#include <RamOperation.h>
Public Member Functions
RamIndexScan * clone () const override
Create a clone (i.e.
void print (std::ostream &os, int tabpos) const override
RamIndexScan (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexRelationSearch
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getRangePattern () const
Get range pattern.
RamIndexRelationSearch (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationSearch
const RamRelation & getRelation () const
Get search relation.
RamRelationSearch (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamSearch
int getTupleId () const
Get identifier.
RamSearch (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamIndexRelationSearch
bool equal (const RamNode &node) const override
Abstract equality check for two RAM nodes.
Protected Attributes inherited from souffle::RamIndexRelationSearch
std::vector< std::unique_ptr< RamExpression > > queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationSearch
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamSearch
const int identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Relation Scan with Index.
Search for tuples of a relation matching a criteria
Definition at line 249 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamIndexScan::RamIndexScan (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 251 of file RamOperation.h.
             : RamIndexRelationSearch(std::move(r), ident, std::move(queryPattern), std::move(nested),
                       std::move(profileText)) {}
Member Function Documentation
RamIndexScan* souffle::RamIndexScan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 277 of file RamOperation.h.
References i.
{
         std::vector<std::unique_ptr<RamExpression>> resQueryPattern(queryPattern.size());
         for (unsigned int i = 0; i < queryPattern.size(); ++i) {
             if (nullptr != queryPattern[i]) {
                 resQueryPattern[i] = std::unique_ptr<RamExpression>(queryPattern[i]->clone());
             }
         }
         RamIndexScan* res = new RamIndexScan(std::unique_ptr<RamRelationReference>(relationRef->clone()),
                 getTupleId(), std::move(resQueryPattern),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
         return res;
     }
void souffle::RamIndexScan::print (std::ostream & os, int tabpos) const inline override virtual
Reimplemented from souffle::RamNestedOperation.
Definition at line 257 of file RamOperation.h.
References souffle::RamRelation::getArg(), souffle::RamRelation::getArity(), souffle::RamRelation::getName(), i, souffle::RamNestedOperation::print(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "SEARCH " << rel.getName() << " AS t" << getTupleId() << " ON INDEX ";
         bool first = true;
         for (unsigned int i = 0; i < rel.getArity(); ++i) {
             if (queryPattern[i] != nullptr) {
                 if (first) {
                     first = false;
                 } else {
                     os << " and ";
                 }
                 os << "t" << getTupleId() << "." << rel.getArg(i) << "=";
                 queryPattern[i]->print(os);
             }
         }
         os << std::endl;
         RamIndexRelationSearch::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
RamOperation.h