souffle: souffle::WriteCoutCSV Class Reference
souffle::WriteCoutCSV Class Reference
#include <WriteStreamCSV.h>
Public Member Functions
WriteCoutCSV (const std::vector< bool > &symbolMask, const SymbolTable &symbolTable, const IODirectives &ioDirectives, const bool provenance=false)
~WriteCoutCSV () override
Public Member Functions inherited from souffle::WriteStream
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::vector< bool > &symbolMask, const SymbolTable &symbolTable, const bool prov, bool summary=false)
virtual ~WriteStream ()=default
Protected Member Functions
void writeNextTuple (const RamDomain *tuple) override
void writeNullary () override
Protected Member Functions inherited from souffle::WriteStreamCSV
virtual std::string getDelimiter (const IODirectives &ioDirectives) const
Protected Member Functions inherited from souffle::WriteStream
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeSize (std::size_t size)
Protected Attributes
const std::string delimiter
Protected Attributes inherited from souffle::WriteStream
const size_t arity
const bool isProvenance
const bool summary
const std::vector< bool > & symbolMask
const SymbolTable & symbolTable
Detailed Description
Definition at line 123 of file WriteStreamCSV.h.
Constructor & Destructor Documentation
souffle::WriteCoutCSV::WriteCoutCSV (const std::vector< bool > & symbolMask, const SymbolTable & symbolTable, const IODirectives & ioDirectives, const bool provenance = false) inline
Definition at line 125 of file WriteStreamCSV.h.
References souffle::IODirectives::get(), souffle::IODirectives::getRelationName(), and souffle::IODirectives::has().
             : WriteStream(symbolMask, symbolTable, provenance), delimiter(getDelimiter(ioDirectives)) {
         std::cout << "---------------\n" << ioDirectives.getRelationName();
         if (ioDirectives.has("headers") && ioDirectives.get("headers") == "true") {
             std::cout << "\n" << ioDirectives.get("attributeNames");
         }
         std::cout << "\n===============\n";
     }
souffle::WriteCoutCSV::~WriteCoutCSV () inline override
Definition at line 135 of file WriteStreamCSV.h.
{
         std::cout << "===============\n";
     }
Member Function Documentation
void souffle::WriteCoutCSV::writeNextTuple (const RamDomain * tuple) inline override protected virtual
Implements souffle::WriteStream.
Definition at line 144 of file WriteStreamCSV.h.
References arity.
{
         if (symbolMask.at(0)) {
             std::cout << symbolTable.unsafeResolve(tuple[0]);
         } else {
             std::cout << tuple[0];
         }
         for (size_t col = 1; col < arity; ++col) {
             std::cout << delimiter;
             if (symbolMask.at(col)) {
                 std::cout << symbolTable.unsafeResolve(tuple[col]);
             } else {
                 std::cout << tuple[col];
             }
         }
         std::cout << "\n";
     }
void souffle::WriteCoutCSV::writeNullary () inline override protected virtual
Implements souffle::WriteStream.
Definition at line 140 of file WriteStreamCSV.h.
{
         std::cout << "()\n";
     }
Field Documentation
const std::string souffle::WriteCoutCSV::delimiter protected
Definition at line 161 of file WriteStreamCSV.h.
The documentation for this class was generated from the following file:
WriteStreamCSV.h