souffle: souffle::AstConstant Class Reference
souffle::AstConstant Class Reference
Subclass of Argument that represents a datalog constant value.
#include <AstArgument.h>
Public Member Functions
void apply (const AstNodeMapper &) override
Mutates this node.
AstConstant (AstDomain i)
AstDomain getIndex () const
Public Member Functions inherited from souffle::AstArgument
AstArgument * clone () const override=0
Create clone.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
AstDomain idx
Index of this Constant in the SymbolTable.
Detailed Description
Subclass of Argument that represents a datalog constant value.
Definition at line 169 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstConstant::AstConstant (AstDomain i) inline
Definition at line 171 of file AstArgument.h.
 : AstArgument(), idx(i) {}
Member Function Documentation
void souffle::AstConstant::apply (const AstNodeMapper &) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 179 of file AstArgument.h.
{
         // no sub-nodes to consider within constants
     }
bool souffle::AstConstant::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 188 of file AstArgument.h.
References idx.
{
         assert(nullptr != dynamic_cast<const AstConstant*>(&node));
         const auto& other = static_cast<const AstConstant&>(node);
         return idx == other.idx;
     }
AstDomain souffle::AstConstant::getIndex () const inline
Returns
Return the index of this constant in the SymbolTable
Definition at line 174 of file AstArgument.h.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::AstTranslator::translateValue(), and souffle::BddBddBTranslator::visitStringConstant().
{
         return idx;
     }
Field Documentation
AstDomain souffle::AstConstant::idx protected
Index of this Constant in the SymbolTable.
Definition at line 185 of file AstArgument.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstArgument.h