souffle: souffle::ReduceExistentialsTransformer Class Reference
souffle::ReduceExistentialsTransformer Class Reference
Transformation pass to reduce unnecessary computation for relations that only appear in the form A(_,...,_).
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to reduce unnecessary computation for relations that only appear in the form A(_,...,_).
Definition at line 269 of file AstTransforms.h.
Member Function Documentation
std::string souffle::ReduceExistentialsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 271 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "ReduceExistentialsTransformer";
     }
bool souffle::ReduceExistentialsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 767 of file AstTransforms.cpp.
References souffle::AstProgram::appendRelation(), souffle::AstProgram::apply(), EQREL_RELATION, souffle::AstTranslationUnit::getAnalysis(), souffle::AstRelation::getClauses(), souffle::AstRelationIdentifier::getName(), souffle::AstAtom::getName(), souffle::AstTranslationUnit::getProgram(), souffle::AstRelation::getQualifier(), souffle::AstProgram::getRelation(), souffle::AstProgram::getRelations(), souffle::AstNode::getSrcLoc(), souffle::Graph< Vertex, Compare >::insert(), souffle::IOType::isIO(), relation, relations, souffle::AstRelation::setName(), souffle::Graph< Vertex, Compare >::visitDepthFirst(), and souffle::visitDepthFirst().
{
     AstProgram& program = *translationUnit.getProgram();
     // Checks whether a given clause is recursive
     auto isRecursiveClause = [&](const AstClause& clause) {
         AstRelationIdentifier relationName = clause.getHead()->getName();
         bool recursive = false;
         visitDepthFirst(clause.getBodyLiterals(), [&](const AstAtom& atom) {
             if (atom.getName() == relationName) {
                 recursive = true;
             }
         });
         return recursive;
     };
     // Checks whether an atom is of the form a(_,_,...,_)
     auto isExistentialAtom = [&](const AstAtom& atom) {
         for (AstArgument* arg : atom.getArguments()) {
             if (!dynamic_cast<AstUnnamedVariable*>(arg)) {
                 return false;
             }
         }
         return true;
     };
     // Construct a dependency graph G where:
     // - Each relation is a node
     // - An edge (a,b) exists iff a uses b "non-existentially" in one of its *recursive* clauses
     // This way, a relation can be transformed into an existential form
     // if and only if all its predecessors can also be transformed.
     Graph<AstRelationIdentifier> relationGraph = Graph<AstRelationIdentifier>();
     // Add in the nodes
     for (AstRelation* relation : program.getRelations()) {
         relationGraph.insert(relation->getName());
     }
     // Keep track of all relations that cannot be transformed
     std::set<AstRelationIdentifier> minimalIrreducibleRelations;
     IOType* ioType = translationUnit.getAnalysis<IOType>();
     for (AstRelation* relation : program.getRelations()) {
         // No I/O relations can be transformed
         if (ioType->isIO(relation)) {
             minimalIrreducibleRelations.insert(relation->getName());
         }
         for (AstClause* clause : relation->getClauses()) {
             bool recursive = isRecursiveClause(*clause);
             visitDepthFirst(*clause, [&](const AstAtom& atom) {
                 if (atom.getName() == clause->getHead()->getName()) {
                     return;
                 }
                 if (!isExistentialAtom(atom)) {
                     if (recursive) {
                         // Clause is recursive, so add an edge to the dependency graph
                         relationGraph.insert(clause->getHead()->getName(), atom.getName());
                     } else {
                         // Non-existential apperance in a non-recursive clause, so
                         // it's out of the picture
                         minimalIrreducibleRelations.insert(atom.getName());
                     }
                 }
             });
         }
     }
     // TODO (see issue #564): Don't transform relations appearing in aggregators
     //                        due to aggregator issues with unnamed variables.
     visitDepthFirst(program, [&](const AstAggregator& aggr) {
         visitDepthFirst(
                 aggr, [&](const AstAtom& atom) { minimalIrreducibleRelations.insert(atom.getName()); });
     });
     // Run a DFS from each 'bad' source
     // A node is reachable in a DFS from an irreducible node if and only if it is
     // also an irreducible node
     std::set<AstRelationIdentifier> irreducibleRelations;
     for (AstRelationIdentifier relationName : minimalIrreducibleRelations) {
         relationGraph.visitDepthFirst(relationName,
                 [&](const AstRelationIdentifier& subRel) { irreducibleRelations.insert(subRel); });
     }
     // All other relations are necessarily existential
     std::set<AstRelationIdentifier> existentialRelations;
     for (AstRelation* relation : program.getRelations()) {
         if (!relation->getClauses().empty() && relation->getArity() != 0 &&
                 irreducibleRelations.find(relation->getName()) == irreducibleRelations.end()) {
             existentialRelations.insert(relation->getName());
         }
     }
     // Reduce the existential relations
     for (AstRelationIdentifier relationName : existentialRelations) {
         AstRelation* originalRelation = program.getRelation(relationName);
         std::stringstream newRelationName;
         newRelationName << "+?exists_" << relationName;
         auto newRelation = std::make_unique<AstRelation>();
         newRelation->setName(newRelationName.str());
         newRelation->setSrcLoc(originalRelation->getSrcLoc());
         // EqRel relations require two arguments, so remove it from the qualifier
         newRelation->setQualifier(originalRelation->getQualifier() & ~(EQREL_RELATION));
         // Keep all non-recursive clauses
         for (AstClause* clause : originalRelation->getClauses()) {
             if (!isRecursiveClause(*clause)) {
                 auto newClause = std::make_unique<AstClause>();
                 newClause->setSrcLoc(clause->getSrcLoc());
                 if (const AstExecutionPlan* plan = clause->getExecutionPlan()) {
                     newClause->setExecutionPlan(std::unique_ptr<AstExecutionPlan>(plan->clone()));
                 }
                 newClause->setGenerated(clause->isGenerated());
                 newClause->setFixedExecutionPlan(clause->hasFixedExecutionPlan());
                 newClause->setHead(std::make_unique<AstAtom>(newRelationName.str()));
                 for (AstLiteral* lit : clause->getBodyLiterals()) {
                     newClause->addToBody(std::unique_ptr<AstLiteral>(lit->clone()));
                 }
                 newRelation->addClause(std::move(newClause));
             }
         }
         program.appendRelation(std::move(newRelation));
     }
     // Mapper that renames the occurrences of marked relations with their existential
     // counterparts
     struct renameExistentials : public AstNodeMapper {
         const std::set<AstRelationIdentifier>& relations;
         renameExistentials(std::set<AstRelationIdentifier>& relations) : relations(relations) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* clause = dynamic_cast<AstClause*>(node.get())) {
                 if (relations.find(clause->getHead()->getName()) != relations.end()) {
                     // Clause is going to be removed, so don't rename it
                     return node;
                 }
             } else if (auto* atom = dynamic_cast<AstAtom*>(node.get())) {
                 if (relations.find(atom->getName()) != relations.end()) {
                     // Relation is now existential, so rename it
                     std::stringstream newName;
                     newName << "+?exists_" << atom->getName();
                     return std::make_unique<AstAtom>(newName.str());
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     renameExistentials update(existentialRelations);
     program.apply(update);
     bool changed = !existentialRelations.empty();
     return changed;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp