souffle: souffle::RamMerge Class Reference
souffle::RamMerge Class Reference
Merge tuples from a source into target relation.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamMerge * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelation & getSourceRelation () const
Get source relation.
const RamRelation & getTargetRelation () const
Get target relation.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamMerge (std::unique_ptr< RamRelationReference > tRef, std::unique_ptr< RamRelationReference > sRef)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamRelationReference > sourceRef
std::unique_ptr< RamRelationReference > targetRef
Detailed Description
Merge tuples from a source into target relation.
Note that semantically uniqueness of tuples is not checked.
Definition at line 225 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamMerge::RamMerge (std::unique_ptr< RamRelationReference > tRef, std::unique_ptr< RamRelationReference > sRef) inline
Definition at line 227 of file RamStatement.h.
References souffle::RamRelation::getArgTypeQualifier(), souffle::RamRelation::getArity(), and i.
             : RamStatement(), targetRef(std::move(tRef)), sourceRef(std::move(sRef)) {
         const RamRelation* source = sourceRef->get();
         const RamRelation* target = targetRef->get();
         assert(source->getArity() == target->getArity() && "mismatching relations");
         for (size_t i = 0; i < source->getArity(); i++) {
             assert(source->getArgTypeQualifier(i) == target->getArgTypeQualifier(i) && "mismatching type");
         }
     }
Member Function Documentation
void souffle::RamMerge::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 267 of file RamStatement.h.
{
         sourceRef = map(std::move(sourceRef));
         targetRef = map(std::move(targetRef));
     }
RamMerge* souffle::RamMerge::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 260 of file RamStatement.h.
{
         RamMerge* res = new RamMerge(std::unique_ptr<RamRelationReference>(targetRef->clone()),
                 std::unique_ptr<RamRelationReference>(sourceRef->clone()));
         return res;
     }
bool souffle::RamMerge::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 277 of file RamStatement.h.
References getTargetRelation().
{
         assert(nullptr != dynamic_cast<const RamMerge*>(&node));
         const auto& other = static_cast<const RamMerge&>(node);
         return getTargetRelation() == other.getTargetRelation() &&
                getSourceRelation() == other.getSourceRelation();
     }
std::vector<const RamNode*> souffle::RamMerge::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 255 of file RamStatement.h.
{
         return {sourceRef.get(), targetRef.get()};
     }
const RamRelation& souffle::RamMerge::getSourceRelation () const inline
Get source relation.
Definition at line 238 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitMerge().
{
         return *sourceRef->get();
     }
const RamRelation& souffle::RamMerge::getTargetRelation () const inline
Get target relation.
Definition at line 243 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalStmt(), and souffle::LVMGenerator::visitMerge().
{
         return *targetRef->get();
     }
void souffle::RamMerge::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 248 of file RamStatement.h.
References souffle::times().
{
         os << times(" ", tabpos);
         os << "MERGE " << getTargetRelation().getName() << " WITH " << getSourceRelation().getName();
         os << std::endl;
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamMerge::sourceRef protected
Definition at line 274 of file RamStatement.h.
std::unique_ptr<RamRelationReference> souffle::RamMerge::targetRef protected
Definition at line 273 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h