souffle: souffle::AstNegation Class Reference
souffle::AstNegation Class Reference
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
#include <AstLiteral.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Mutates this node.
AstNegation (std::unique_ptr< AstAtom > atom)
AstNegation * clone () const override
Creates a clone of this AST sub-structure.
const AstAtom * getAtom () const override
Returns the nested atom as the referenced atom.
AstAtom * getAtom ()
Return the negated atom.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
void print (std::ostream &os) const override
Output to a given stream.
~AstNegation () override=default
Public Member Functions inherited from souffle::AstLiteral
AstLiteral ()=default
~AstLiteral () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::unique_ptr< AstAtom > atom
A pointer to the negated Atom.
Detailed Description
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
A Negated atom occurs in a body of clause and cannot occur in a head of a clause.
Definition at line 175 of file AstLiteral.h.
Constructor & Destructor Documentation
souffle::AstNegation::AstNegation (std::unique_ptr< AstAtom > atom) inline
Definition at line 177 of file AstLiteral.h.
 : atom(std::move(atom)) {}
souffle::AstNegation::~AstNegation () override default
Member Function Documentation
void souffle::AstNegation::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 205 of file AstLiteral.h.
{
         atom = map(std::move(atom));
     }
AstNegation* souffle::AstNegation::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstLiteral.
Definition at line 198 of file AstLiteral.h.
References souffle::AstNode::getSrcLoc(), and souffle::AstNode::setSrcLoc().
{
         AstNegation* res = new AstNegation(std::unique_ptr<AstAtom>(atom->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstNegation::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 219 of file AstLiteral.h.
References atom.
{
         assert(nullptr != dynamic_cast<const AstNegation*>(&node));
         const auto& other = static_cast<const AstNegation&>(node);
         return *atom == *other.atom;
     }
const AstAtom* souffle::AstNegation::getAtom () const inline override virtual
Returns the nested atom as the referenced atom.
Implements souffle::AstLiteral.
Definition at line 182 of file AstLiteral.h.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkInlining(), souffle::getGroundedTerms(), souffle::Adornment::run(), souffle::AstTranslator::translateConstraint(), souffle::BddBddBTranslator::visitNegation(), and souffle::LogicbloxConverter::visitNegation().
{
         return atom.get();
     }
AstAtom* souffle::AstNegation::getAtom () inline
Return the negated atom.
Definition at line 187 of file AstLiteral.h.
{
         return atom.get();
     }
std::vector<const AstNode*> souffle::AstNegation::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 210 of file AstLiteral.h.
{
         return {atom.get()};
     }
void souffle::AstNegation::print (std::ostream & os) const inline override virtual
Output to a given stream.
Implements souffle::AstNode.
Definition at line 192 of file AstLiteral.h.
{
         os << "!";
         atom->print(os);
     }
Field Documentation
std::unique_ptr<AstAtom> souffle::AstNegation::atom protected
A pointer to the negated Atom.
Definition at line 216 of file AstLiteral.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstLiteral.h