souffle: souffle::DebugReport Class Reference
souffle::DebugReport Class Reference
Class representing a HTML report, consisting of a list of sections.
#include <DebugReport.h>
Public Member Functions
void addSection (const DebugReportSection &section)
bool empty () const
void print (std::ostream &out) const
Outputs a complete HTML document to the given stream, consisting of an index of all of the sections of the report, followed by the content of each section.
~DebugReport ()
Private Attributes
std::vector< DebugReportSection > sections
Friends
std::ostream & operator<< (std::ostream &out, const DebugReport &report)
Detailed Description
Class representing a HTML report, consisting of a list of sections.
Definition at line 84 of file DebugReport.h.
Constructor & Destructor Documentation
souffle::DebugReport::~DebugReport () inline
Definition at line 86 of file DebugReport.h.
References souffle::Global::config().
                    {
         if (!empty()) {
             std::ofstream debugReportStream(Global::config().get("debug-report"));
             debugReportStream << *this;
         }
     }
Member Function Documentation
void souffle::DebugReport::addSection (const DebugReportSection & section) inline
Definition at line 96 of file DebugReport.h.
Referenced by souffle::DebugReporter::generateDebugReport(), souffle::DebugReporter::transform(), and souffle::AstTranslator::translateUnit().
{
         sections.push_back(section);
     }
bool souffle::DebugReport::empty () const inline
Definition at line 92 of file DebugReport.h.
{
         return sections.empty();
     }
void souffle::DebugReport::print (std::ostream & out) const
Outputs a complete HTML document to the given stream, consisting of an index of all of the sections of the report, followed by the content of each section.
Definition at line 110 of file DebugReport.cpp.
{
     out << "<!DOCTYPE html>\n";
     out << "<html>\n";
     out << "<head>\n";
     out << "<meta charset=\"UTF-8\">\n";
     out << "<title>Souffle Debug Report</title>\n";
     out << "<style>\n";
     out << "ul { list-style-type: none; }\n";
     out << "ul > li.leaf { display: inline-block; padding: 0em 1em; }\n";
     out << "ul > li.nonleaf { padding: 0em 1em; }\n";
     out << "* { font-family: sans-serif; }\n";
     out << "pre { white-space: pre-wrap; font-family: monospace; }\n";
     out << "a:link { text-decoration: none; color: blue; }\n";
     out << "a:visited { text-decoration: none; color: blue; }\n";
     out << "div.headerdiv { background-color:lightgrey; margin:10px; padding-left:10px; padding-right:10px; "
            "padding-top:3px; padding-bottom:3px; border-radius:5px }\n";
     out << ".headerdiv h1 { display:inline; }\n";
     out << ".headerdiv a { float:right; }\n";
     out << "</style>\n";
     out << "<script type=\"text/javascript\">\n";
     out << "function toggleVisibility(id) {\n";
     out << "  var element = document.getElementById(id);\n";
     out << "  if (element.style.display == 'none') {\n";
     out << "    element.style.display = 'block';\n";
     out << "  } else {\n";
     out << "    element.style.display = 'none';\n";
     out << "  }\n";
     out << "}\n";
     out << "</script>\n";
     out << "</head>\n";
     out << "<body>\n";
     out << "<div class='headerdiv'><h1>Souffle Debug Report</h1></div>\n";
     for (const DebugReportSection& section : sections) {
         section.printIndex(out);
     }
     for (const DebugReportSection& section : sections) {
         section.printContent(out);
     }
     out << "<a href='#'>(return to top)</a>\n";
     out << "</body>\n";
     out << "</html>\n";
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const DebugReport & report) friend
Definition at line 107 of file DebugReport.h.
{
         report.print(out);
         return out;
     }
Field Documentation
std::vector<DebugReportSection> souffle::DebugReport::sections private
Definition at line 113 of file DebugReport.h.
The documentation for this class was generated from the following files:
DebugReport.h
DebugReport.cpp