souffle: souffle::AstPrintSize Class Reference
souffle::AstPrintSize Class Reference
Intermediate representation of a summary store operation.
#include <AstIO.h>
Public Member Functions
AstPrintSize (const AstIO &io)
AstPrintSize ()
AstPrintSize * clone () const override
Creates a clone of this AST sub-structure.
bool equal (const AstNode &node) const override
An internal function to determine equality to another node.
void print (std::ostream &os) const override
Output to a given output stream.
~AstPrintSize () override=default
Public Member Functions inherited from souffle::AstStore
AstStore (const AstIO &io)
AstStore ()=default
~AstStore () override=default
Public Member Functions inherited from souffle::AstIO
void addKVP (const std::string &key, const std::string &value)
void addName (const AstRelationIdentifier &name)
Set kvp map name.
void apply (const AstNodeMapper &) override
No nested nodes to apply to.
AstIO ()=default
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const std::map< std::string, std::string > & getIODirectiveMap () const
const AstRelationIdentifier & getName () const
Return the name of this kvp map.
const std::set< AstRelationIdentifier > & getNames () const
Return the names of this kvp map.
void setName (const AstRelationIdentifier &name)
Set kvp map name.
~AstIO () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::AstIO
AstIO (const AstIO &io)
std::string unescape (const std::string &inputString) const
std::string unescape (const std::string &inputString, const std::string &needle, const std::string &replacement) const
Protected Attributes inherited from souffle::AstIO
std::map< std::string, std::string > kvps
kvp map
std::set< AstRelationIdentifier > names
Name of the kvp.
Detailed Description
Intermediate representation of a summary store operation.
Definition at line 218 of file AstIO.h.
Constructor & Destructor Documentation
souffle::AstPrintSize::AstPrintSize (const AstIO & io) inline
Definition at line 220 of file AstIO.h.
References souffle::AstIO::addKVP().
                                   : AstStore(io) {
         addKVP("IO", "stdoutprintsize");
     }
souffle::AstPrintSize::AstPrintSize () inline
Definition at line 223 of file AstIO.h.
References souffle::AstIO::addKVP().
                    {
         addKVP("IO", "stdoutprintsize");
     }
souffle::AstPrintSize::~AstPrintSize () override default
Member Function Documentation
AstPrintSize* souffle::AstPrintSize::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Reimplemented from souffle::AstStore.
Definition at line 242 of file AstIO.h.
References souffle::AstNode::getSrcLoc(), souffle::AstIO::kvps, and souffle::AstIO::names.
{
         auto res = new AstPrintSize();
         res->names = names;
         res->kvps = kvps;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstPrintSize::equal (const AstNode & node) const inline override virtual
An internal function to determine equality to another node.
Reimplemented from souffle::AstStore.
Definition at line 235 of file AstIO.h.
References souffle::AstIO::names.
{
         assert(nullptr != dynamic_cast<const AstPrintSize*>(&node));
         const auto& other = static_cast<const AstPrintSize&>(node);
         return other.names == names;
     }
void souffle::AstPrintSize::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Reimplemented from souffle::AstStore.
Definition at line 229 of file AstIO.h.
References souffle::AstIO::print().
{
         os << ".printsize ";
         AstIO::print(os);
     }
The documentation for this class was generated from the following file:
AstIO.h