souffle: souffle::RamExistenceCheckAnalysis Class Reference
souffle::RamExistenceCheckAnalysis Class Reference
#include <RamExistenceCheckAnalysis.h>
Public Member Functions
SearchColumns getKey (const RamExistenceCheck *existCheck) const
get key
bool isTotal (const RamExistenceCheck *existCheck) const
is key total
void run (const RamTranslationUnit &translationUnit) override
run existence check analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "existence-check-analysis"
name of analysis
Detailed Description
Definition at line 29 of file RamExistenceCheckAnalysis.h.
Member Function Documentation
SearchColumns souffle::RamExistenceCheckAnalysis::getKey (const RamExistenceCheck * existCheck) const
get key
Get key.
Definition at line 24 of file RamExistenceCheckAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues(), and i.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), run(), and souffle::IndexSetAnalysis::run().
{
     const auto values = existCheck->getValues();
     SearchColumns res = 0;
     for (std::size_t i = 0; i < values.size(); i++) {
         if (values[i] != nullptr) {
             res |= (1 << i);
         }
     }
     return res;
 }
bool souffle::RamExistenceCheckAnalysis::isTotal (const RamExistenceCheck * existCheck) const
is key total
Is key total.
Definition at line 36 of file RamExistenceCheckAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), and run().
{
     for (const auto& cur : existCheck->getValues()) {
         if (cur == nullptr) {
             return false;
         }
     }
     return true;
 }
void souffle::RamExistenceCheckAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run existence check analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 35 of file RamExistenceCheckAnalysis.h.
References getKey(), and isTotal().
 {}
Field Documentation
constexpr const char* souffle::RamExistenceCheckAnalysis::name = "existence-check-analysis" static
name of analysis
Definition at line 32 of file RamExistenceCheckAnalysis.h.
The documentation for this class was generated from the following files:
RamExistenceCheckAnalysis.h
RamExistenceCheckAnalysis.cpp