souffle: souffle::RamRelation Class Reference
souffle::RamRelation Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamRelation * clone () const override
Create clone.
const std::string getArg (uint32_t i) const
Get argument.
const std::string getArgTypeQualifier (uint32_t i) const
Get Argument Type Qualifier.
unsigned getArity () const
const std::vector< std::string > & getAttributeTypeQualifiers () const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getName () const
Get name.
const RelationRepresentation getRepresentation () const
Relation representation type.
const bool isNullary () const
Is nullary relation.
const bool isTemp () const
Is temporary relation (for semi-naive evaluation)
bool operator< (const RamRelation &other) const
void print (std::ostream &out) const override
Print RAM node.
RamRelation (const std::string name, const size_t arity, const std::vector< std::string > attributeNames, const std::vector< std::string > attributeTypeQualifiers, const RelationRepresentation representation)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
const size_t arity
Arity, i.e., number of attributes.
const std::vector< std::string > attributeNames
Name of attributes.
const std::vector< std::string > attributeTypeQualifiers
Type of attributes.
const std::string name
Name of relation.
const RelationRepresentation representation
Data-structure representation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 38 of file RamRelation.h.
Constructor & Destructor Documentation
souffle::RamRelation::RamRelation (const std::string name, const size_t arity, const std::vector< std::string > attributeNames, const std::vector< std::string > attributeTypeQualifiers, const RelationRepresentation representation) inline
Definition at line 56 of file RamRelation.h.
Referenced by clone().
             : RamNode(), name(std::move(name)), arity(arity), attributeNames(std::move(attributeNames)),
               attributeTypeQualifiers(std::move(attributeTypeQualifiers)), representation(representation) {
         assert(this->attributeNames.size() == arity || this->attributeNames.empty());
         assert(this->attributeTypeQualifiers.size() == arity || this->attributeTypeQualifiers.empty());
     }
Member Function Documentation
void souffle::RamRelation::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 144 of file RamRelation.h.
 {}
RamRelation* souffle::RamRelation::clone () const inline override virtual
Create clone.
Implements souffle::RamNode.
Definition at line 137 of file RamRelation.h.
References RamRelation().
Referenced by souffle::RamProgram::clone().
{
         RamRelation* res =
                 new RamRelation(name, arity, attributeNames, attributeTypeQualifiers, representation);
         return res;
     }
bool souffle::RamRelation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 148 of file RamRelation.h.
References isTemp(), and name.
{
         assert(nullptr != dynamic_cast<const RamRelation*>(&node));
         const auto& other = static_cast<const RamRelation&>(node);
         return name == other.name && arity == other.arity && attributeNames == other.attributeNames &&
                attributeTypeQualifiers == other.attributeTypeQualifiers &&
                representation == other.representation && isTemp() == other.isTemp();
     }
const std::string souffle::RamRelation::getArg (uint32_t i) const inline
Get argument.
Definition at line 71 of file RamRelation.h.
References i.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface(), print(), souffle::IndexSetAnalysis::print(), souffle::RamIndexScan::print(), souffle::RamIndexChoice::print(), and souffle::RamIndexAggregate::print().
{
         if (!attributeNames.empty()) {
             return attributeNames[i];
         }
         if (arity == 0) {
             return "";
         }
         return "c" + std::to_string(i);
     }
const std::string souffle::RamRelation::getArgTypeQualifier (uint32_t i) const inline
Get Argument Type Qualifier.
Definition at line 82 of file RamRelation.h.
Referenced by souffle::InterpreterProgInterface::InterpreterProgInterface(), and souffle::RamMerge::RamMerge().
{
         return (i < attributeTypeQualifiers.size()) ? attributeTypeQualifiers[i] : "";
     }
unsigned souffle::RamRelation::getArity () const inline
Definition at line 106 of file RamRelation.h.
References arity.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::RAMI::evalStmt(), souffle::Synthesiser::generateCode(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::IndexSetAnalysis::print(), souffle::RamIndexScan::print(), souffle::RamIndexChoice::print(), souffle::RamIndexAggregate::print(), souffle::RamMerge::RamMerge(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::MakeIndexTransformer::rewriteScan(), souffle::LVMGenerator::visitCreate(), souffle::LVMGenerator::visitExistenceCheck(), souffle::LVMGenerator::visitFact(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), souffle::LVMGenerator::visitProject(), and souffle::LVMGenerator::visitProvenanceExistenceCheck().
{
         return arity;
     }
const std::vector<std::string>& souffle::RamRelation::getAttributeTypeQualifiers () const inline
Definition at line 86 of file RamRelation.h.
References attributeTypeQualifiers.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalStmt(), souffle::Synthesiser::generateCode(), and souffle::LVMGenerator::visitCreate().
{
         return attributeTypeQualifiers;
     }
std::vector<const RamNode*> souffle::RamRelation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 132 of file RamRelation.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
const std::string& souffle::RamRelation::getName () const inline
Get name.
Definition at line 66 of file RamRelation.h.
References name.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), souffle::RAMI::evalStmt(), souffle::RAMI::executeMain(), souffle::LVM::executeMain(), souffle::Synthesiser::generateCode(), souffle::IndexSetAnalysis::getIndexes(), souffle::Synthesiser::getRelationName(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::RamCreate::print(), souffle::RamLoad::print(), souffle::RamStore::print(), souffle::RamClear::print(), souffle::RamDrop::print(), souffle::RamIndexScan::print(), souffle::RamIndexChoice::print(), souffle::RAMI::swapRelation(), souffle::LVMGenerator::visitAggregate(), souffle::LVMGenerator::visitChoice(), souffle::LVMGenerator::visitClear(), souffle::LVMGenerator::visitCreate(), souffle::LVMGenerator::visitDrop(), souffle::LVMGenerator::visitEmptinessCheck(), souffle::LVMGenerator::visitExistenceCheck(), souffle::LVMGenerator::visitFact(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), souffle::LVMGenerator::visitLoad(), souffle::LVMGenerator::visitLogSize(), souffle::LVMGenerator::visitLogTimer(), souffle::LVMGenerator::visitMerge(), souffle::LVMGenerator::visitProject(), souffle::LVMGenerator::visitProvenanceExistenceCheck(), souffle::LVMGenerator::visitScan(), souffle::LVMGenerator::visitStore(), and souffle::LVMGenerator::visitSwap().
{
         return name;
     }
const RelationRepresentation souffle::RamRelation::getRepresentation () const inline
Relation representation type.
Definition at line 96 of file RamRelation.h.
References representation.
Referenced by souffle::Synthesiser::emitCode(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::RamCreate::print(), and souffle::LVMGenerator::visitCreate().
{
         return representation;
     }
const bool souffle::RamRelation::isNullary () const inline
Is nullary relation.
Definition at line 91 of file RamRelation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::SynthesiserRelation::getSynthesiserRelation().
{
         return arity == 0;
     }
const bool souffle::RamRelation::isTemp () const inline
Is temporary relation (for semi-naive evaluation)
Definition at line 101 of file RamRelation.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalCond(), and souffle::Synthesiser::generateCode().
{
         return name.at(0) == '@';
     }
bool souffle::RamRelation::operator< (const RamRelation & other) const inline
Definition at line 111 of file RamRelation.h.
References name.
{
         return name < other.name;
     }
void souffle::RamRelation::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 116 of file RamRelation.h.
References arity, getArg(), i, name, and representation.
{
         out << name;
         if (arity > 0) {
             out << "(" << getArg(0) << ":" << attributeTypeQualifiers[0];
             for (unsigned i = 1; i < arity; i++) {
                 out << ",";
                 out << getArg(i) << ":" << attributeTypeQualifiers[i];
             }
             out << ")";
             out << " " << representation;
         } else {
             out << " nullary";
         }
     }
Field Documentation
const size_t souffle::RamRelation::arity protected
Arity, i.e., number of attributes.
Definition at line 44 of file RamRelation.h.
Referenced by getArity(), and print().
const std::vector<std::string> souffle::RamRelation::attributeNames protected
Name of attributes.
Definition at line 47 of file RamRelation.h.
const std::vector<std::string> souffle::RamRelation::attributeTypeQualifiers protected
Type of attributes.
Definition at line 50 of file RamRelation.h.
Referenced by getAttributeTypeQualifiers().
const std::string souffle::RamRelation::name protected
Name of relation.
Definition at line 41 of file RamRelation.h.
Referenced by equal(), getName(), operator<(), and print().
const RelationRepresentation souffle::RamRelation::representation protected
Data-structure representation.
Definition at line 53 of file RamRelation.h.
Referenced by getRepresentation(), and print().
The documentation for this class was generated from the following file:
RamRelation.h