souffle: souffle::AstTranslator::ClauseTranslator Class Reference
souffle::AstTranslator::ClauseTranslator Class Reference
translate AST clause to RAM code
Public Member Functions
ClauseTranslator (AstTranslator &translator)
std::unique_ptr< RamStatement > translateClause (const AstClause &clause, const AstClause &originalClause, const int version=0)
generate RAM code for a clause
Protected Member Functions
virtual std::unique_ptr< RamCondition > createCondition (const AstClause &originalClause)
virtual std::unique_ptr< RamOperation > createOperation (const AstClause &clause)
Protected Attributes
int level = 0
AstTranslator & translator
ValueIndex valueIndex
Private Types
using arg_list = std::vector< AstArgument * >
Private Member Functions
void createValueIndex (const AstClause &clause)
index values in rule
arg_list * getArgList (const AstNode *curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> &nodeArgs) const
std::unique_ptr< AstClause > getReorderedClause (const AstClause &clause, const int version) const
void indexValues (const AstNode *curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> &nodeArgs, std::map< const arg_list *, int > &arg_level, RamRelationReference *relation)
Private Attributes
std::vector< const AstAggregator * > aggregators
std::vector< const AstNode * > op_nesting
Detailed Description
translate AST clause to RAM code
Definition at line 322 of file AstTranslator.h.
Member Typedef Documentation
using souffle::AstTranslator::ClauseTranslator::arg_list = std::vector<AstArgument*> private
Definition at line 324 of file AstTranslator.h.
Constructor & Destructor Documentation
souffle::AstTranslator::ClauseTranslator::ClauseTranslator (AstTranslator & translator) inline
Definition at line 355 of file AstTranslator.h.
 : translator(translator) {}
Member Function Documentation
std::unique_ptr< RamCondition > souffle::AstTranslator::ClauseTranslator::createCondition (const AstClause & originalClause) protected virtual
Reimplemented in souffle::AstTranslator::ProvenanceClauseTranslator.
Definition at line 612 of file AstTranslator.cpp.
References souffle::AstClause::getHead().
{
     const auto head = originalClause.getHead();
     // add stopping criteria for nullary relations
     // (if it contains already the null tuple, don't re-compute)
     if (head->getArity() == 0) {
         return std::make_unique<RamEmptinessCheck>(translator.translateRelation(head));
     }
     return nullptr;
 }
std::unique_ptr< RamOperation > souffle::AstTranslator::ClauseTranslator::createOperation (const AstClause & clause) protected virtual
Reimplemented in souffle::AstTranslator::ProvenanceClauseTranslator.
Definition at line 531 of file AstTranslator.cpp.
References arity, souffle::Global::config(), souffle::AstClause::getHead(), i, and souffle::visitDepthFirst().
{
     const auto head = clause.getHead();
     std::vector<std::unique_ptr<RamExpression>> values;
     for (AstArgument* arg : head->getArguments()) {
         values.push_back(translator.translateValue(arg, valueIndex));
     }
     std::unique_ptr<RamOperation> project =
             std::make_unique<RamProject>(translator.translateRelation(head), std::move(values));
     if (head->getArity() == 0) {
         project = std::make_unique<RamFilter>(
                 std::make_unique<RamEmptinessCheck>(translator.translateRelation(head)), std::move(project));
     }
     // check existence for original tuple if we have provenance
     // only if we don't compile
     if (Global::config().has("provenance") &&
             ((!Global::config().has("compile") && !Global::config().has("dl-program") &&
                     !Global::config().has("generate")))) {
         auto arity = head->getArity() - 2;
         std::vector<std::unique_ptr<RamExpression>> values;
         bool isVolatile = true;
         // add args for original tuple
         for (size_t i = 0; i < arity; i++) {
             auto arg = head->getArgument(i);
             // don't add counters
             visitDepthFirst(*arg, [&](const AstCounter& cur) { isVolatile = false; });
             values.push_back(translator.translateValue(arg, valueIndex));
         }
         // add two unnamed args for provenance columns
         values.push_back(nullptr);
         values.push_back(nullptr);
         if (isVolatile) {
             return std::make_unique<RamFilter>(
                     std::make_unique<RamNegation>(std::make_unique<RamExistenceCheck>(
                             translator.translateRelation(head), std::move(values))),
                     std::move(project));
         }
     }
     // build up insertion call
     return project;  // start with innermost
 }
void souffle::AstTranslator::ClauseTranslator::createValueIndex (const AstClause & clause) private
index values in rule
Definition at line 492 of file AstTranslator.cpp.
References souffle::any_of(), souffle::AstAtom::getArgument(), souffle::AstAtom::getArguments(), souffle::AstClause::getAtoms(), souffle::AstAggregator::getBodyLiterals(), and souffle::visitDepthFirstPostOrder().
{
     for (const AstAtom* atom : clause.getAtoms()) {
         // std::map<const arg_list*, int> arg_level;
         std::map<const AstNode*, std::unique_ptr<arg_list>> nodeArgs;
         std::map<const arg_list*, int> arg_level;
         nodeArgs[atom] = std::make_unique<arg_list>(atom->getArguments());
         // the atom is obtained at the current level
         // increment nesting level for the atom
         arg_level[nodeArgs[atom].get()] = level++;
         op_nesting.push_back(atom);
         indexValues(atom, nodeArgs, arg_level, translator.translateRelation(atom).get());
     }
     // add aggregation functions
     visitDepthFirstPostOrder(clause, [&](const AstAggregator& cur) {
         // add each aggregator expression only once
         if (any_of(aggregators, [&](const AstAggregator* agg) { return *agg == cur; })) {
             return;
         }
         int aggLoc = level++;
         valueIndex.setAggregatorLocation(cur, Location({aggLoc, 0}));
         // bind aggregator variables to locations
         assert(nullptr != dynamic_cast<const AstAtom*>(cur.getBodyLiterals()[0]));
         const AstAtom& atom = static_cast<const AstAtom&>(*cur.getBodyLiterals()[0]);
         for (size_t pos = 0; pos < atom.getArguments().size(); ++pos) {
             if (const auto* var = dynamic_cast<const AstVariable*>(atom.getArgument(pos))) {
                 valueIndex.addVarReference(*var, aggLoc, (int)pos, translator.translateRelation(&atom));
             }
         };
         // and remember aggregator
         aggregators.push_back(&cur);
     });
 }
AstTranslator::ClauseTranslator::arg_list * souffle::AstTranslator::ClauseTranslator::getArgList (const AstNode * curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> & nodeArgs) const private
Definition at line 444 of file AstTranslator.cpp.
{
     if (!nodeArgs.count(curNode)) {
         if (auto rec = dynamic_cast<const AstRecordInit*>(curNode)) {
             nodeArgs[curNode] = std::make_unique<arg_list>(rec->getArguments());
         } else if (auto atom = dynamic_cast<const AstAtom*>(curNode)) {
             nodeArgs[curNode] = std::make_unique<arg_list>(atom->getArguments());
         } else {
             assert(false && "node type doesn't have arguments!");
         }
     }
     return nodeArgs[curNode].get();
 }
std::unique_ptr< AstClause > souffle::AstTranslator::ClauseTranslator::getReorderedClause (const AstClause & clause, const int version) const private
Definition at line 414 of file AstTranslator.cpp.
References souffle::AstClause::clone(), souffle::AstClause::getExecutionPlan(), souffle::AstExecutionPlan::getOrderFor(), and i.
{
     const auto plan = clause.getExecutionPlan();
     // check whether there is an imposed order constraint
     if (plan != nullptr && plan->hasOrderFor(version)) {
         // get the imposed order
         const auto& order = plan->getOrderFor(version);
         // create a copy and fix order
         std::unique_ptr<AstClause> reorderedClause(clause.clone());
         // Change order to start at zero
         std::vector<unsigned int> newOrder(order.size());
         std::transform(order.begin(), order.end(), newOrder.begin(),
                 [](unsigned int i) -> unsigned int { return i - 1; });
         // re-order atoms
         reorderedClause->reorderAtoms(newOrder);
         // clear other order and fix plan
         reorderedClause->clearExecutionPlan();
         reorderedClause->setFixedExecutionPlan();
         return reorderedClause;
     }
     return nullptr;
 }
void souffle::AstTranslator::ClauseTranslator::indexValues (const AstNode * curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> & nodeArgs, std::map< const arg_list *, int > & arg_level, RamRelationReference * relation) private
Definition at line 458 of file AstTranslator.cpp.
References souffle::RamRelationReference::clone().
{
     arg_list* cur = getArgList(curNode, nodeArgs);
     for (size_t pos = 0; pos < cur->size(); ++pos) {
         // get argument
         auto& arg = (*cur)[pos];
         // check for variable references
         if (auto var = dynamic_cast<const AstVariable*>(arg)) {
             if (pos < relation->get()->getArity()) {
                 valueIndex.addVarReference(
                         *var, arg_level[cur], pos, std::unique_ptr<RamRelationReference>(relation->clone()));
             } else {
                 valueIndex.addVarReference(*var, arg_level[cur], pos);
             }
         }
         // check for nested records
         if (auto rec = dynamic_cast<const AstRecordInit*>(arg)) {
             // introduce new nesting level for unpack
             op_nesting.push_back(rec);
             arg_level[getArgList(rec, nodeArgs)] = level++;
             // register location of record
             valueIndex.setRecordDefinition(*rec, arg_level[cur], pos);
             // resolve nested components
             indexValues(rec, nodeArgs, arg_level, relation);
         }
     }
 }
std::unique_ptr< RamStatement > souffle::AstTranslator::ClauseTranslator::translateClause (const AstClause & clause, const AstClause & originalClause, const int version = 0)
generate RAM code for a clause
Definition at line 630 of file AstTranslator.cpp.
References souffle::AstAtom::argSize(), souffle::Global::config(), souffle::COUNT, souffle::AstAggregator::count, souffle::EQ, souffle::AstAtom::getArgument(), souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), souffle::AstClause::getBodyLiterals(), souffle::AstAggregator::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstAtom::getName(), souffle::AstAggregator::getOperator(), souffle::AstAggregator::getTargetExpression(), souffle::AstTranslator::Location::identifier, souffle::AstClause::isFact(), souffle::AstClause::isRule(), souffle::AstTranslator::makeRamElementAccess(), souffle::MAX, souffle::AstAggregator::max, souffle::MIN, souffle::AstAggregator::min, souffle::profile::ss, souffle::stringify(), souffle::SUM, souffle::AstAggregator::sum, and souffle::toString().
Referenced by souffle::AstTranslator::makeSubproofSubroutine(), souffle::AstTranslator::translateNonRecursiveRelation(), and souffle::AstTranslator::translateRecursiveRelation().
{
     if (auto reorderedClause = getReorderedClause(clause, version)) {
         // translate reordered clause
         return translateClause(*reorderedClause, originalClause, version);
     }
     // get extract some details
     const AstAtom* head = clause.getHead();
     // handle facts
     if (clause.isFact()) {
         // translate arguments
         std::vector<std::unique_ptr<RamExpression>> values;
         for (auto& arg : head->getArguments()) {
             values.push_back(translator.translateValue(arg, ValueIndex()));
         }
         // create a fact statement
         return std::make_unique<RamFact>(translator.translateRelation(head), std::move(values));
     }
     // the rest should be rules
     assert(clause.isRule());
     createValueIndex(clause);
     // -- create RAM statement --
     std::unique_ptr<RamOperation> op = createOperation(clause);
     /* add equivalence constraints imposed by variable binding */
     for (const auto& cur : valueIndex.getVariableReferences()) {
         // the first appearance
         const Location& first = *cur.second.begin();
         // all other appearances
         for (const Location& loc : cur.second) {
             if (first != loc && !valueIndex.isAggregator(loc.identifier)) {
                 op = std::make_unique<RamFilter>(
                         std::make_unique<RamConstraint>(BinaryConstraintOp::EQ, makeRamElementAccess(first),
                                 makeRamElementAccess(loc)),
                         std::move(op));
             }
         }
     }
     /* add conditions caused by atoms, negations, and binary relations */
     for (const auto& lit : clause.getBodyLiterals()) {
         if (auto condition = translator.translateConstraint(lit, valueIndex)) {
             op = std::make_unique<RamFilter>(std::move(condition), std::move(op));
         }
     }
     // add aggregator conditions
     size_t curLevel = op_nesting.size() - 1;
     for (auto it = op_nesting.rbegin(); it != op_nesting.rend(); ++it, --curLevel) {
         const AstNode* cur = *it;
         if (const auto* atom = dynamic_cast<const AstAtom*>(cur)) {
             // add constraints
             for (size_t pos = 0; pos < atom->argSize(); ++pos) {
                 if (auto* agg = dynamic_cast<AstAggregator*>(atom->getArgument(pos))) {
                     auto loc = valueIndex.getAggregatorLocation(*agg);
                     op = std::make_unique<RamFilter>(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                                              std::make_unique<RamElementAccess>(curLevel, pos,
                                                                      translator.translateRelation(atom)),
                                                              makeRamElementAccess(loc)),
                             std::move(op));
                 }
             }
         }
     }
     // add aggregator levels
     --level;
     for (auto it = aggregators.rbegin(); it != aggregators.rend(); ++it, --level) {
         const AstAggregator* cur = *it;
         // translate aggregation function
         AggregateFunction fun = souffle::MIN;
         switch (cur->getOperator()) {
             case AstAggregator::min:
                 fun = souffle::MIN;
                 break;
             case AstAggregator::max:
                 fun = souffle::MAX;
                 break;
             case AstAggregator::count:
                 fun = souffle::COUNT;
                 break;
             case AstAggregator::sum:
                 fun = souffle::SUM;
                 break;
         }
         // condition for aggregate and helper function to add terms
         std::unique_ptr<RamCondition> aggCondition;
         auto addAggCondition = [&](std::unique_ptr<RamCondition>& arg) {
             if (aggCondition == nullptr) {
                 aggCondition = std::move(arg);
             } else {
                 aggCondition = std::make_unique<RamConjunction>(std::move(aggCondition), std::move(arg));
             }
         };
         // translate constraints of sub-clause
         for (const auto& lit : cur->getBodyLiterals()) {
             if (auto newCondition = translator.translateConstraint(lit, valueIndex)) {
                 addAggCondition(newCondition);
             }
         }
         // get the first predicate of the sub-clause
         // NB: at most one atom is permitted in a sub-clause
         const AstAtom* atom = nullptr;
         for (const auto& lit : cur->getBodyLiterals()) {
             if (atom == nullptr) {
                 atom = dynamic_cast<const AstAtom*>(lit);
             } else {
                 assert(dynamic_cast<const AstAtom*>(lit) != nullptr &&
                         "Unsupported complex aggregation body encountered!");
             }
         }
         // translate arguments's of atom (if exists) to conditions
         if (atom != nullptr) {
             for (size_t pos = 0; pos < atom->argSize(); ++pos) {
                 // variable bindings are issued differently since we don't want self
                 // referential variable bindings
                 if (const auto* var = dynamic_cast<const AstVariable*>(atom->getArgument(pos))) {
                     for (const Location& loc :
                             valueIndex.getVariableReferences().find(var->getName())->second) {
                         if (level != loc.identifier || (int)pos != loc.element) {
                             std::unique_ptr<RamCondition> newCondition = std::make_unique<RamConstraint>(
                                     BinaryConstraintOp::EQ, makeRamElementAccess(loc),
                                     std::make_unique<RamElementAccess>(
                                             level, pos, translator.translateRelation(atom)));
                             addAggCondition(newCondition);
                             break;
                         }
                     }
                 } else if (atom->getArgument(pos) != nullptr) {
                     std::unique_ptr<RamExpression> value =
                             translator.translateValue(atom->getArgument(pos), valueIndex);
                     if (value != nullptr) {
                         std::unique_ptr<RamCondition> newCondition =
                                 std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                         std::make_unique<RamElementAccess>(
                                                 level, pos, translator.translateRelation(atom)),
                                         std::move(value));
                         addAggCondition(newCondition);
                     }
                 }
             }
         }
         // translate aggregate expression
         std::unique_ptr<RamExpression> expr =
                 translator.translateValue(cur->getTargetExpression(), valueIndex);
         // add Ram-Aggregation layer
         std::unique_ptr<RamAggregate> aggregate = std::make_unique<RamAggregate>(std::move(op), fun,
                 translator.translateRelation(atom), std::move(expr), std::move(aggCondition), level);
         op = std::move(aggregate);
     }
     // build operation bottom-up
     while (!op_nesting.empty()) {
         // get next operator
         const AstNode* cur = op_nesting.back();
         op_nesting.pop_back();
         // get current nesting level
         auto level = op_nesting.size();
         if (const auto* atom = dynamic_cast<const AstAtom*>(cur)) {
             // add constraints
             for (size_t pos = 0; pos < atom->argSize(); ++pos) {
                 if (auto* c = dynamic_cast<AstConstant*>(atom->getArgument(pos))) {
                     op = std::make_unique<RamFilter>(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                                              std::make_unique<RamElementAccess>(level, pos,
                                                                      translator.translateRelation(atom)),
                                                              std::make_unique<RamNumber>(c->getIndex())),
                             std::move(op));
                 }
             }
             // add check for emptiness for an atom
             op = std::make_unique<RamFilter>(
                     std::make_unique<RamNegation>(
                             std::make_unique<RamEmptinessCheck>(translator.translateRelation(atom))),
                     std::move(op));
             // add a scan level
             if (atom->getArity() != 0) {
                 if (head->getArity() == 0) {
                     op = std::make_unique<RamBreak>(
                             std::make_unique<RamNegation>(
                                     std::make_unique<RamEmptinessCheck>(translator.translateRelation(head))),
                             std::move(op));
                 }
                 if (Global::config().has("profile")) {
                     std::stringstream ss;
                     ss << head->getName();
                     ss.str("");
                     ss << "@frequency-atom" << ';';
                     ss << originalClause.getHead()->getName() << ';';
                     ss << version << ';';
                     ss << stringify(toString(clause)) << ';';
                     ss << stringify(toString(*atom)) << ';';
                     ss << stringify(toString(originalClause)) << ';';
                     ss << level << ';';
                     op = std::make_unique<RamScan>(
                             translator.translateRelation(atom), level, std::move(op), ss.str());
                 } else {
                     op = std::make_unique<RamScan>(translator.translateRelation(atom), level, std::move(op));
                 }
             }
             // TODO: support constants in nested records!
         } else if (const auto* rec = dynamic_cast<const AstRecordInit*>(cur)) {
             // add constant constraints
             for (size_t pos = 0; pos < rec->getArguments().size(); ++pos) {
                 if (AstConstant* c = dynamic_cast<AstConstant*>(rec->getArguments()[pos])) {
                     op = std::make_unique<RamFilter>(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                                              std::make_unique<RamElementAccess>(level, pos),
                                                              std::make_unique<RamNumber>(c->getIndex())),
                             std::move(op));
                 } else if (AstFunctor* func = dynamic_cast<AstFunctor*>(rec->getArguments()[pos])) {
                     op = std::make_unique<RamFilter>(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                                              std::make_unique<RamElementAccess>(level, pos),
                                                              translator.translateValue(func, valueIndex)),
                             std::move(op));
                 }
             }
             // add an unpack level
             const Location& loc = valueIndex.getDefinitionPoint(*rec);
             op = std::make_unique<RamUnpackRecord>(
                     std::move(op), level, loc.identifier, loc.element, rec->getArguments().size());
         } else {
             assert(false && "Unsupported AST node for creation of scan-level!");
         }
     }
     /* generate the final RAM Insert statement */
     std::unique_ptr<RamCondition> cond = createCondition(originalClause);
     if (cond != nullptr) {
         return std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(cond), std::move(op)));
     } else {
         return std::make_unique<RamQuery>(std::move(op));
     }
 }
Field Documentation
std::vector<const AstAggregator*> souffle::AstTranslator::ClauseTranslator::aggregators private
Definition at line 326 of file AstTranslator.h.
int souffle::AstTranslator::ClauseTranslator::level = 0 protected
Definition at line 349 of file AstTranslator.h.
std::vector<const AstNode*> souffle::AstTranslator::ClauseTranslator::op_nesting private
Definition at line 329 of file AstTranslator.h.
AstTranslator& souffle::AstTranslator::ClauseTranslator::translator protected
Definition at line 343 of file AstTranslator.h.
ValueIndex souffle::AstTranslator::ClauseTranslator::valueIndex protected
Definition at line 346 of file AstTranslator.h.
The documentation for this class was generated from the following files:
AstTranslator.h
AstTranslator.cpp