souffle: souffle::AstPragmaChecker Class Reference
souffle::AstPragmaChecker Class Reference
#include <AstPragma.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &) override
Detailed Description
Definition at line 90 of file AstPragma.h.
Member Function Documentation
std::string souffle::AstPragmaChecker::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 92 of file AstPragma.h.
{
         return "AstPragmaChecker";
     }
bool souffle::AstPragmaChecker::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 25 of file AstPragma.cpp.
References souffle::Global::config(), souffle::AstPragma::getkvp(), souffle::AstTranslationUnit::getProgram(), souffle::splitString(), and souffle::visitDepthFirst().
{
     bool changed = false;
     AstProgram* program = translationUnit.getProgram();
     // Take in pragma options from the command line
     if (Global::config().has("pragma")) {
         std::vector<std::string> configOptions = splitString(Global::config().get("pragma"), ';');
         for (const std::string& option : configOptions) {
             size_t splitPoint = option.find(':');
             std::string optionName = option.substr(0, splitPoint);
             std::string optionValue =
                     (splitPoint == std::string::npos) ? "" : option.substr(splitPoint + 1, option.length());
             if (!Global::config().has(optionName)) {
                 changed = true;
                 Global::config().set(optionName, optionValue);
             }
         }
     }
     // Take in pragma options from the datalog file itself
     visitDepthFirst(*program, [&](const AstPragma& pragma) {
         std::pair<std::string, std::string> kvp = pragma.getkvp();
         // Command line options take precedence
         if (!Global::config().has(kvp.first)) {
             changed = true;
             Global::config().set(kvp.first, kvp.second);
         }
     });
     return changed;
 }
The documentation for this class was generated from the following files:
AstPragma.h
AstPragma.cpp