souffle: souffle::AstPragma Class Reference
souffle::AstPragma Class Reference
Representation of a global option.
#include <AstPragma.h>
Public Member Functions
void apply (const AstNodeMapper &mapper) override
No nested nodes to apply to.
AstPragma ()=default
AstPragma (std::string k, std::string v)
AstPragma * clone () const override
Creates a clone of this AST sub-structure.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
std::pair< std::string, std::string > getkvp () const
void print (std::ostream &os) const override
Output to a given output stream.
~AstPragma () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Data Fields
std::string key
Name of the key.
std::string value
Value.
Protected Member Functions
bool equal (const AstNode &node) const override
An internal function to determine equality to another node.
Friends
std::ostream & operator<< (std::ostream &out, const AstPragma &arg)
Detailed Description
Representation of a global option.
Definition at line 35 of file AstPragma.h.
Constructor & Destructor Documentation
souffle::AstPragma::~AstPragma () override default
souffle::AstPragma::AstPragma () default
Referenced by clone().
souffle::AstPragma::AstPragma (std::string k, std::string v) inline
Definition at line 41 of file AstPragma.h.
 : key(std::move(k)), value(std::move(v)) {}
Member Function Documentation
void souffle::AstPragma::apply (const AstNodeMapper & mapper) inline override virtual
No nested nodes to apply to.
Implements souffle::AstNode.
Definition at line 59 of file AstPragma.h.
 {}
AstPragma* souffle::AstPragma::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Definition at line 50 of file AstPragma.h.
References AstPragma(), souffle::AstNode::getSrcLoc(), key, and value.
{
         auto res = new AstPragma();
         res->key = key;
         res->value = value;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstPragma::equal (const AstNode & node) const inline override protected virtual
An internal function to determine equality to another node.
Implements souffle::AstNode.
Definition at line 83 of file AstPragma.h.
References key, and value.
{
         assert(nullptr != dynamic_cast<const AstPragma*>(&node));
         const auto& other = static_cast<const AstPragma&>(node);
         return other.key == key && other.value == value;
     }
std::vector<const AstNode*> souffle::AstPragma::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 44 of file AstPragma.h.
{
         // type is just cached, not essential
         return std::vector<const AstNode*>();
     }
std::pair<std::string, std::string> souffle::AstPragma::getkvp () const inline
Definition at line 66 of file AstPragma.h.
References key, and value.
Referenced by souffle::AstPragmaChecker::transform().
{
         return std::pair<std::string, std::string>(key, value);
     }
void souffle::AstPragma::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 62 of file AstPragma.h.
References key, and value.
{
         os << ".pragma " << key << " " << value << "\n";
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const AstPragma & arg) friend
Definition at line 70 of file AstPragma.h.
{
         out << arg.key << " \"" << arg.value << "\"";
         return out;
     }
Field Documentation
std::string souffle::AstPragma::key
Name of the key.
Definition at line 76 of file AstPragma.h.
Referenced by clone(), equal(), getkvp(), and print().
std::string souffle::AstPragma::value
Value.
Definition at line 79 of file AstPragma.h.
Referenced by clone(), equal(), getkvp(), and print().
The documentation for this class was generated from the following file:
AstPragma.h