souffle: souffle::AstComponentType Class Reference
souffle::AstComponentType Class Reference
A component type is the class utilized to represent a construct of the form.
#include <AstComponent.h>
Public Member Functions
void apply (const AstNodeMapper &) override
Apply the mapper to all child nodes.
AstComponentType (std::string name="", std::vector< AstTypeIdentifier > params=std::vector< AstTypeIdentifier >())
Creates a new component type based on the given name and parameters.
AstComponentType * clone () const override
Create a clone (i.e.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
const std::string & getName () const
const std::vector< AstTypeIdentifier > & getTypeParameters () const
void print (std::ostream &os) const override
Output to a given output stream.
void setName (const std::string &n)
void setTypeParameters (const std::vector< AstTypeIdentifier > &params)
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Private Attributes
std::string name
The name of the addressed component.
std::vector< AstTypeIdentifier > typeParams
The list of associated type parameters.
Detailed Description
A component type is the class utilized to represent a construct of the form.
name < Type, Type, ... >
where name is the name of the component and < Type, Type, ... > is an optional list of type parameters.
Definition at line 40 of file AstComponent.h.
Constructor & Destructor Documentation
souffle::AstComponentType::AstComponentType (std::string name = "", std::vector< AstTypeIdentifier > params = std::vector<AstTypeIdentifier>()) inline
Creates a new component type based on the given name and parameters.
Definition at line 45 of file AstComponent.h.
Referenced by clone().
             : name(std::move(name)), typeParams(std::move(params)) {}
Member Function Documentation
void souffle::AstComponentType::apply (const AstNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Implements souffle::AstNode.
Definition at line 74 of file AstComponent.h.
{
         // nothing to do
     }
AstComponentType* souffle::AstComponentType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 78 of file AstComponent.h.
References AstComponentType(), souffle::AstNode::getSrcLoc(), name, souffle::AstNode::setSrcLoc(), and typeParams.
{
         AstComponentType* res = new AstComponentType(name, typeParams);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstComponentType::equal (const AstNode & other) const inline override protected virtual
Abstract equality check for two AST nodes.
Implements souffle::AstNode.
Definition at line 92 of file AstComponent.h.
References name, and typeParams.
{
         assert(nullptr != dynamic_cast<const AstComponentType*>(&node));
         const auto& other = static_cast<const AstComponentType&>(node);
         return name == other.name && typeParams == other.typeParams;
     }
std::vector<const AstNode*> souffle::AstComponentType::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Implements souffle::AstNode.
Definition at line 69 of file AstComponent.h.
{
         std::vector<const AstNode*> res;
         return res;  // no child nodes
     }
const std::string& souffle::AstComponentType::getName () const inline
Definition at line 51 of file AstComponent.h.
References name.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return name;
     }
const std::vector<AstTypeIdentifier>& souffle::AstComponentType::getTypeParameters () const inline
Definition at line 59 of file AstComponent.h.
References typeParams.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return typeParams;
     }
void souffle::AstComponentType::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 84 of file AstComponent.h.
References souffle::join(), name, and typeParams.
{
         os << name;
         if (!typeParams.empty()) {
             os << "<" << join(typeParams, ",") << ">";
         }
     }
void souffle::AstComponentType::setName (const std::string & n) inline
Definition at line 55 of file AstComponent.h.
References n, and name.
{
         name = n;
     }
void souffle::AstComponentType::setTypeParameters (const std::vector< AstTypeIdentifier > & params) inline
Definition at line 63 of file AstComponent.h.
References typeParams.
{
         typeParams = params;
     }
Field Documentation
std::string souffle::AstComponentType::name private
The name of the addressed component.
Definition at line 100 of file AstComponent.h.
Referenced by clone(), equal(), getName(), print(), souffle::AstComponentInit::setInstanceName(), and setName().
std::vector<AstTypeIdentifier> souffle::AstComponentType::typeParams private
The list of associated type parameters.
Definition at line 103 of file AstComponent.h.
Referenced by clone(), equal(), getTypeParameters(), print(), and setTypeParameters().
The documentation for this class was generated from the following file:
AstComponent.h