souffle: souffle::AstAttribute Class Reference
souffle::AstAttribute Class Reference
Intermediate representation of an attribute which stores the name and the type of an attribute.
#include <AstAttribute.h>
Public Member Functions
void apply (const AstNodeMapper &) override
Mutates this node.
AstAttribute (std::string n, AstTypeIdentifier t, const Type *=nullptr)
AstAttribute * clone () const override
Creates a clone of this AST sub-structure.
const std::string & getAttributeName () const
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const AstTypeIdentifier & getTypeName () const
void print (std::ostream &os) const override
Output to a given output stream.
void setTypeName (const AstTypeIdentifier &name)
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Private Attributes
std::string name
Attribute name.
AstTypeIdentifier typeName
Type name.
Detailed Description
Intermediate representation of an attribute which stores the name and the type of an attribute.
Attribute has the only name attribute
Definition at line 40 of file AstAttribute.h.
Constructor & Destructor Documentation
souffle::AstAttribute::AstAttribute (std::string n, AstTypeIdentifier t, const Type * = nullptr) inline
Definition at line 42 of file AstAttribute.h.
Referenced by clone().
             : name(std::move(n)), typeName(std::move(t)) {}
Member Function Documentation
void souffle::AstAttribute::apply (const AstNodeMapper &) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 69 of file AstAttribute.h.
{
         // no nested AST nodes
     }
AstAttribute* souffle::AstAttribute::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Definition at line 62 of file AstAttribute.h.
References AstAttribute(), souffle::AstNode::getSrcLoc(), name, souffle::AstNode::setSrcLoc(), and typeName.
{
         AstAttribute* res = new AstAttribute(name, typeName);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstAttribute::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 80 of file AstAttribute.h.
References name, and typeName.
{
         assert(nullptr != dynamic_cast<const AstAttribute*>(&node));
         const auto& other = static_cast<const AstAttribute&>(node);
         return name == other.name && typeName == other.typeName;
     }
const std::string& souffle::AstAttribute::getAttributeName () const inline
Definition at line 45 of file AstAttribute.h.
References name.
Referenced by souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstTranslator::getOutputIODirectives(), and souffle::AstTranslator::translateRelation().
{
         return name;
     }
std::vector<const AstNode*> souffle::AstAttribute::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 74 of file AstAttribute.h.
{
         return std::vector<const AstNode*>();
     }
const AstTypeIdentifier& souffle::AstAttribute::getTypeName () const inline
Definition at line 49 of file AstAttribute.h.
References typeName.
Referenced by souffle::AstSemanticChecker::checkRelation(), souffle::AstSemanticChecker::checkRelationDeclaration(), and souffle::AstTranslator::translateRelation().
{
         return typeName;
     }
void souffle::AstAttribute::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 57 of file AstAttribute.h.
References name, and typeName.
{
         os << name << ":" << typeName;
     }
void souffle::AstAttribute::setTypeName (const AstTypeIdentifier & name) inline
Definition at line 53 of file AstAttribute.h.
References name, and typeName.
{
         typeName = name;
     }
Field Documentation
std::string souffle::AstAttribute::name private
Attribute name.
Definition at line 88 of file AstAttribute.h.
Referenced by clone(), equal(), getAttributeName(), print(), and setTypeName().
AstTypeIdentifier souffle::AstAttribute::typeName private
Type name.
Definition at line 91 of file AstAttribute.h.
Referenced by clone(), equal(), getTypeName(), print(), and setTypeName().
The documentation for this class was generated from the following file:
AstAttribute.h