souffle: souffle::RamProvenanceExistenceCheck Class Reference
souffle::RamProvenanceExistenceCheck Class Reference
Existence check for a relation for provenance existence check.
#include <RamCondition.h>
Public Member Functions
RamProvenanceExistenceCheck * clone () const override
Create clone.
void print (std::ostream &os) const override
Print.
RamProvenanceExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamAbstractExistenceCheck
void apply (const RamNodeMapper &map) override
Apply.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelation & getRelation () const
Get relation.
std::vector< RamExpression * > getValues () const
Get arguments.
RamAbstractExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamCondition
RamCondition ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Additional Inherited Members
Protected Attributes inherited from souffle::RamAbstractExistenceCheck
std::unique_ptr< RamRelationReference > relationRef
std::vector< std::unique_ptr< RamExpression > > values
Pattern – nullptr if undefined.
Detailed Description
Existence check for a relation for provenance existence check.
Definition at line 327 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamProvenanceExistenceCheck::RamProvenanceExistenceCheck (std::unique_ptr< RamRelationReference > relRef, std::vector< std::unique_ptr< RamExpression >> vals) inline
Definition at line 329 of file RamCondition.h.
             : RamAbstractExistenceCheck(std::move(relRef), std::move(vals)) {}
Member Function Documentation
RamProvenanceExistenceCheck* souffle::RamProvenanceExistenceCheck::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 348 of file RamCondition.h.
References souffle::RamExpression::clone().
{
         std::vector<std::unique_ptr<RamExpression>> newValues;
         for (auto& cur : values) {
             RamExpression* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.emplace_back(val);
         }
         RamProvenanceExistenceCheck* res = new RamProvenanceExistenceCheck(
                 std::unique_ptr<RamRelationReference>(relationRef->clone()), std::move(newValues));
         return res;
     }
bool souffle::RamProvenanceExistenceCheck::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamAbstractExistenceCheck.
Definition at line 364 of file RamCondition.h.
References souffle::RamAbstractExistenceCheck::equal().
{
         assert(dynamic_cast<const RamProvenanceExistenceCheck*>(&node));
         return RamAbstractExistenceCheck::equal(node);
     }
void souffle::RamProvenanceExistenceCheck::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 334 of file RamCondition.h.
References souffle::join().
{
         os << "("
            << join(values, ",",
                       [](std::ostream& out, const std::unique_ptr<RamExpression>& value) {
                           if (!value) {
                               out << "_";
                           } else {
                               out << *value;
                           }
                       })
            << ") prov∈ " << getRelation().getName();
     }
The documentation for this class was generated from the following file:
RamCondition.h