souffle: souffle::RamRelationSearch Class Reference
souffle::RamRelationSearch Class Reference
Abstract class for relation searches.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get search relation.
RamRelationSearch (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamSearch
int getTupleId () const
Get identifier.
RamSearch (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
void print (std::ostream &os, int tabpos) const override
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create a clone (i.e.
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Abstract equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamSearch
const int identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Abstract class for relation searches.
Definition at line 133 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamRelationSearch::RamRelationSearch (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 135 of file RamOperation.h.
             : RamSearch(ident, std::move(nested), std::move(profileText)), relationRef(std::move(relRef)) {}
Member Function Documentation
void souffle::RamRelationSearch::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, and souffle::RamIndexRelationSearch.
Definition at line 144 of file RamOperation.h.
References souffle::RamNestedOperation::apply().
Referenced by souffle::RamIndexRelationSearch::apply(), souffle::RamChoice::apply(), souffle::RamIndexChoice::apply(), and souffle::RamAggregate::apply().
{
         RamSearch::apply(map);
         relationRef = map(std::move(relationRef));
     }
bool souffle::RamRelationSearch::equal (const RamNode & other) const inline override protected virtual
Abstract equality check for two RAM nodes.
Reimplemented from souffle::RamSearch.
Reimplemented in souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, and souffle::RamIndexRelationSearch.
Definition at line 159 of file RamOperation.h.
References souffle::RamSearch::equal().
Referenced by souffle::RamIndexRelationSearch::equal(), souffle::RamChoice::equal(), souffle::RamIndexChoice::equal(), and souffle::RamAggregate::equal().
{
         assert(nullptr != dynamic_cast<const RamRelationSearch*>(&node));
         const auto& other = static_cast<const RamRelationSearch&>(node);
         return RamSearch::equal(other) && getRelation() == other.getRelation();
     }
std::vector<const RamNode*> souffle::RamRelationSearch::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamSearch.
Reimplemented in souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexRelationSearch, and souffle::RamScan.
Definition at line 149 of file RamOperation.h.
References souffle::RamSearch::getChildNodes().
Referenced by souffle::RamScan::getChildNodes(), souffle::RamIndexRelationSearch::getChildNodes(), and souffle::RamAggregate::getChildNodes().
{
         auto res = RamSearch::getChildNodes();
         res.push_back(relationRef.get());
         return res;
     }
const RamRelation& souffle::RamRelationSearch::getRelation () const inline
Get search relation.
Definition at line 140 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::LVMGenerator::visitAggregate(), souffle::LVMGenerator::visitChoice(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), and souffle::LVMGenerator::visitScan().
{
         return *relationRef->get();
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamRelationSearch::relationRef protected
Search relation.
Definition at line 157 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h