souffle: souffle::gzfstream::internal::gzfstream Class Reference
souffle::gzfstream::internal::gzfstream Class Reference
#include <gzfstream.h>
Public Member Functions
void close ()
gzfstream ()
gzfstream (const std::string &filename, std::ios_base::openmode mode)
gzfstream (const gzfstream &)=delete
gzfstream (gzfstream &&)=delete
bool is_open ()
void open (const std::string &filename, std::ios_base::openmode mode)
gzfstreambuf * rdbuf () const
~gzfstream () override=default
Protected Attributes
gzfstreambuf buf
Detailed Description
Definition at line 147 of file gzfstream.h.
Constructor & Destructor Documentation
souffle::gzfstream::internal::gzfstream::gzfstream () inline
Definition at line 149 of file gzfstream.h.
                 {
         init(&buf);
     }
souffle::gzfstream::internal::gzfstream::gzfstream (const std::string & filename, std::ios_base::openmode mode) inline
Definition at line 153 of file gzfstream.h.
References souffle::gzfstream::internal::gzfstreambuf::open().
{
         init(&buf);
         open(filename, mode);
     }
souffle::gzfstream::internal::gzfstream::gzfstream (const gzfstream &) delete
souffle::gzfstream::internal::gzfstream::gzfstream (gzfstream &&) delete
souffle::gzfstream::internal::gzfstream::~gzfstream () override default
Member Function Documentation
void souffle::gzfstream::internal::gzfstream::close () inline
Definition at line 174 of file gzfstream.h.
                  {
         if (buf.is_open()) {
             if (!buf.close()) {
                 clear(rdstate() | std::ios::badbit);
             }
         }
     }
bool souffle::gzfstream::internal::gzfstream::is_open () inline
Definition at line 170 of file gzfstream.h.
                    {
         return buf.is_open();
     }
void souffle::gzfstream::internal::gzfstream::open (const std::string & filename, std::ios_base::openmode mode) inline
Definition at line 164 of file gzfstream.h.
Referenced by souffle::gzfstream::igzfstream::open(), and souffle::gzfstream::ogzfstream::open().
{
         if (!buf.open(filename, mode)) {
             clear(rdstate() | std::ios::badbit);
         }
     }
gzfstreambuf* souffle::gzfstream::internal::gzfstream::rdbuf () const inline
Definition at line 182 of file gzfstream.h.
Referenced by souffle::gzfstream::igzfstream::rdbuf(), and souffle::gzfstream::ogzfstream::rdbuf().
{
         return &buf;
     }
Field Documentation
gzfstreambuf souffle::gzfstream::internal::gzfstream::buf mutable protected
Definition at line 187 of file gzfstream.h.
The documentation for this class was generated from the following file:
gzfstream.h