souffle: souffle::RamProvenanceExistenceCheckAnalysis Class Reference
souffle::RamProvenanceExistenceCheckAnalysis Class Reference
#include <RamProvenanceExistenceCheckAnalysis.h>
Public Member Functions
SearchColumns getKey (const RamProvenanceExistenceCheck *existCheck) const
get key
bool isTotal (const RamProvenanceExistenceCheck *existCheck) const
is key total
void run (const RamTranslationUnit &translationUnit) override
run provenance existence check analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "provenance-existence-check-analysis"
name of analysis
Detailed Description
Definition at line 29 of file RamProvenanceExistenceCheckAnalysis.h.
Member Function Documentation
SearchColumns souffle::RamProvenanceExistenceCheckAnalysis::getKey (const RamProvenanceExistenceCheck * existCheck) const
get key
Get key.
Definition at line 24 of file RamProvenanceExistenceCheckAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues(), and i.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalCond(), and run().
{
     const auto values = provExistCheck->getValues();
     SearchColumns res = 0;
     // values.size() - 1 because we discard the height annotation
     for (std::size_t i = 0; i < values.size() - 1; i++) {
         if (values[i] != nullptr) {
             res |= (1 << i);
         }
     }
     return res;
 }
bool souffle::RamProvenanceExistenceCheckAnalysis::isTotal (const RamProvenanceExistenceCheck * existCheck) const
is key total
Is key total.
Definition at line 38 of file RamProvenanceExistenceCheckAnalysis.cpp.
References souffle::RamAbstractExistenceCheck::getValues().
Referenced by run().
{
     for (const auto& cur : provExistCheck->getValues()) {
         if (cur == nullptr) {
             return false;
         }
     }
     return true;
 }
void souffle::RamProvenanceExistenceCheckAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run provenance existence check analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 35 of file RamProvenanceExistenceCheckAnalysis.h.
References getKey(), and isTotal().
 {}
Field Documentation
constexpr const char* souffle::RamProvenanceExistenceCheckAnalysis::name = "provenance-existence-check-analysis" static
name of analysis
Definition at line 32 of file RamProvenanceExistenceCheckAnalysis.h.
The documentation for this class was generated from the following files:
RamProvenanceExistenceCheckAnalysis.h
RamProvenanceExistenceCheckAnalysis.cpp