souffle: souffle::AdornedPredicate Class Reference
souffle::AdornedPredicate Class Reference
#include <MagicSet.h>
Public Member Functions
AdornedPredicate (AstRelationIdentifier name, std::string adornment)
std::string getAdornment () const
AstRelationIdentifier getName () const
~AdornedPredicate ()=default
Private Attributes
std::string adornment
AstRelationIdentifier predicateName
Friends
bool operator< (const AdornedPredicate &p1, const AdornedPredicate &p2)
std::ostream & operator<< (std::ostream &out, const AdornedPredicate &arg)
Detailed Description
Definition at line 39 of file MagicSet.h.
Constructor & Destructor Documentation
souffle::AdornedPredicate::AdornedPredicate (AstRelationIdentifier name, std::string adornment) inline
Definition at line 45 of file MagicSet.h.
References ~AdornedPredicate().
             : predicateName(std::move(name)), adornment(std::move(adornment)) {}
souffle::AdornedPredicate::~AdornedPredicate () default
Referenced by AdornedPredicate().
Member Function Documentation
std::string souffle::AdornedPredicate::getAdornment () const inline
Definition at line 54 of file MagicSet.h.
References adornment.
Referenced by souffle::Adornment::run().
{
         return adornment;
     }
AstRelationIdentifier souffle::AdornedPredicate::getName () const inline
Definition at line 50 of file MagicSet.h.
References predicateName.
Referenced by souffle::Adornment::run().
{
         return predicateName;
     }
Friends And Related Function Documentation
bool operator< (const AdornedPredicate & p1, const AdornedPredicate & p2) friend
Definition at line 63 of file MagicSet.h.
{
         if (p1.getName() != p2.getName()) {
             return p1.getName() < p2.getName();
         } else {
             return p1.getAdornment() < p2.getAdornment();
         }
     }
std::ostream& operator<< (std::ostream & out, const AdornedPredicate & arg) friend
Definition at line 58 of file MagicSet.h.
{
         out << "(" << arg.predicateName << ", " << arg.adornment << ")";
         return out;
     }
Field Documentation
std::string souffle::AdornedPredicate::adornment private
Definition at line 42 of file MagicSet.h.
Referenced by getAdornment().
AstRelationIdentifier souffle::AdornedPredicate::predicateName private
Definition at line 41 of file MagicSet.h.
Referenced by getName().
The documentation for this class was generated from the following file:
MagicSet.h