souffle: souffle::Relation::iterator Class Reference
souffle::Relation::iterator Class Reference
#include <SouffleInterface.h>
Public Member Functions
iterator ()=default
iterator (iterator_base *arg)
iterator (const iterator &o)
bool operator!= (const iterator &o) const
tuple & operator* () const
iterator & operator++ ()
iterator & operator= (const iterator &o)
bool operator== (const iterator &o) const
~iterator ()
Protected Attributes
iterator_base * iter = nullptr
Detailed Description
Definition at line 68 of file SouffleInterface.h.
Constructor & Destructor Documentation
souffle::Relation::iterator::iterator () default
souffle::Relation::iterator::iterator (iterator_base * arg) inline
Definition at line 74 of file SouffleInterface.h.
 : iter(arg) {}
souffle::Relation::iterator::~iterator () inline
Definition at line 75 of file SouffleInterface.h.
                     {
             delete iter;
         }
souffle::Relation::iterator::iterator (const iterator & o) inline
Definition at line 78 of file SouffleInterface.h.
 : iter(o.iter->clone()) {}
Member Function Documentation
bool souffle::Relation::iterator::operator!= (const iterator & o) const inline
Definition at line 94 of file SouffleInterface.h.
References souffle::Relation::begin(), souffle::Relation::contains(), souffle::Relation::end(), souffle::Relation::getArity(), souffle::Relation::getAttrName(), souffle::Relation::getAttrType(), souffle::Relation::getName(), souffle::Relation::getSymbolTable(), souffle::Relation::insert(), o, and souffle::Relation::size().
{
             return !(*this == o);
         }
tuple& souffle::Relation::iterator::operator* () const inline
Definition at line 88 of file SouffleInterface.h.
{
             return *(*iter);
         }
iterator& souffle::Relation::iterator::operator++ () inline
Definition at line 84 of file SouffleInterface.h.
{
             ++(*iter);
             return *this;
         }
iterator& souffle::Relation::iterator::operator= (const iterator & o) inline
Definition at line 79 of file SouffleInterface.h.
References souffle::Relation::iterator_base::clone(), and iter.
{
             delete iter;
             iter = o.iter->clone();
             return *this;
         }
bool souffle::Relation::iterator::operator== (const iterator & o) const inline
Definition at line 91 of file SouffleInterface.h.
References iter.
{
             return (iter == o.iter) || (*iter == *o.iter);
         }
Field Documentation
iterator_base* souffle::Relation::iterator::iter = nullptr protected
Definition at line 70 of file SouffleInterface.h.
Referenced by operator=(), and operator==().
The documentation for this class was generated from the following file:
SouffleInterface.h