souffle: souffle::BddBddBTranslator Class Reference
souffle::BddBddBTranslator Class Reference
Bddbddb converter class.
Public Member Functions
BddBddBTranslator ()=default
void convert (std::ostream &out, const AstTranslationUnit &tu)
Private Member Functions
void visitAtom (const AstAtom &atom, std::ostream &out) override
void visitBinaryConstraint (const AstBinaryConstraint &cnstr, std::ostream &out) override
void visitClause (const AstClause &clause, std::ostream &out) override
Converting a clause.
void visitFunctor (const AstFunctor &fun, std::ostream &out) override
void visitNegation (const AstNegation &neg, std::ostream &out) override
void visitNode (const AstNode &node, std::ostream &) override
void visitNumberConstant (const AstNumberConstant &num, std::ostream &out) override
void visitProgram (const AstProgram &program, std::ostream &out) override
The entry point for the conversion of a program, converting the basic top-level structure.
void visitRelation (const AstRelation &rel, std::ostream &out) override
Converting a relation by creating its declaration.
void visitRelationIdentifier (const AstRelationIdentifier &id, std::ostream &out)
void visitStringConstant (const AstStringConstant &str, std::ostream &out) override
void visitTypeCast (const AstTypeCast &cast, std::ostream &out) override
void visitUnnamedVariable (const AstUnnamedVariable &var, std::ostream &out) override
void visitVariable (const AstVariable &var, std::ostream &out) override
Private Member Functions inherited from souffle::AstVisitor< void, std::ostream & >
void operator() (const AstNode &node, Params...args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const AstNode &node, Params...args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of AstNodes.
virtual ~AstVisitor ()=default
A virtual destructor.
LINK (PrimitiveType, Type)
LINK (RecordType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (ComponentType, Node)
LINK (ComponentInit, Node)
LINK (Component, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (Load, Node)
LINK (Store, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const AstNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
Private Attributes
std::vector< std::string > extra_literals
const IOType * ioTypes
int varCounter = 0
Detailed Description
Bddbddb converter class.
Definition at line 79 of file souffle2bdd.cpp.
Constructor & Destructor Documentation
souffle::BddBddBTranslator::BddBddBTranslator () default
Member Function Documentation
void souffle::BddBddBTranslator::convert (std::ostream & out, const AstTranslationUnit & tu) inline
Definition at line 90 of file souffle2bdd.cpp.
References souffle::AstTranslationUnit::getAnalysis(), and souffle::AstTranslationUnit::getProgram().
Referenced by souffle::toBddbddb().
{
         ioTypes = tu.getAnalysis<IOType>();
         visit(*tu.getProgram(), out);
     }
void souffle::BddBddBTranslator::visitAtom (const AstAtom & atom, std::ostream & out) inline override private
Definition at line 191 of file souffle2bdd.cpp.
References souffle::AstAtom::getArguments(), souffle::AstAtom::getName(), and souffle::join().
{
         visitRelationIdentifier(atom.getName(), out);
         // since no nullary-relations are allowed, we add a dummy value
         if (atom.getArguments().empty()) {
             out << "(0)";
             return;
         }
         out << "(";
         out << join(atom.getArguments(), ",", [&](std::ostream& out, AstArgument* cur) { visit(*cur, out); });
         out << ")";
     }
void souffle::BddBddBTranslator::visitBinaryConstraint (const AstBinaryConstraint & cnstr, std::ostream & out) inline override private
Definition at line 210 of file souffle2bdd.cpp.
References souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), and souffle::toBinaryConstraintSymbol().
{
         visit(*cnstr.getLHS(), out);
         out << toBinaryConstraintSymbol(cnstr.getOperator());
         visit(*cnstr.getRHS(), out);
     }
void souffle::BddBddBTranslator::visitClause (const AstClause & clause, std::ostream & out) inline override private
Converting a clause.
Definition at line 163 of file souffle2bdd.cpp.
References souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstClause::isFact(), souffle::join(), souffle::toString(), and souffle::UnsupportedConstructException::UnsupportedConstructException().
{
         visit(*clause.getHead(), out);
         // if it is a fact, that's it
         if (clause.isFact()) {
             // there must not be any additons
             if (!extra_literals.empty()) {
                 throw UnsupportedConstructException("Unsupported fact: " + toString(clause));
             }
             out << ".\n";
             return;
         }
         // convert the body
         out << " :- ";
         out << join(
                 clause.getBodyLiterals(), ",", [&](std::ostream& out, AstLiteral* cur) { visit(*cur, out); });
         // add extra_literals
         for (const auto& cur : extra_literals) {
             out << "," << cur;
         }
         extra_literals.clear();
         // done
         out << ".\n";
     }
void souffle::BddBddBTranslator::visitFunctor (const AstFunctor & fun, std::ostream & out) inline override private
Definition at line 229 of file souffle2bdd.cpp.
References souffle::getSymbolForFunctorOp(), souffle::toString(), and souffle::UnsupportedConstructException::UnsupportedConstructException().
{
         // create a new variable
         std::string var = "aux_var_" + toString(varCounter++);
         // write variable
         out << var;
         // assign variable in extra clause
         std::stringstream binding;
         binding << var << "=";
         // only intrinsic binary operators supported
         const auto* inf = dynamic_cast<const AstIntrinsicFunctor*>(&fun);
         if (inf != nullptr && inf->getArity() == 2) {
             visit(*inf->getArg(0), binding);
             binding << getSymbolForFunctorOp(inf->getFunction());
             visit(*inf->getArg(1), binding);
         } else {
             throw UnsupportedConstructException("Unsupported function: " + toString(fun));
         }
         extra_literals.push_back(binding.str());
     }
void souffle::BddBddBTranslator::visitNegation (const AstNegation & neg, std::ostream & out) inline override private
Definition at line 205 of file souffle2bdd.cpp.
References souffle::AstNegation::getAtom().
{
         out << "!";
         visit(*neg.getAtom(), out);
     }
void souffle::BddBddBTranslator::visitNode (const AstNode & node, std::ostream &) inline override private
Definition at line 265 of file souffle2bdd.cpp.
References souffle::toString(), and souffle::UnsupportedConstructException::UnsupportedConstructException().
{
         throw UnsupportedConstructException(
                 "Unable to convert the following language construct into bddbddb format: " + toString(node));
     }
void souffle::BddBddBTranslator::visitNumberConstant (const AstNumberConstant & num, std::ostream & out) inline override private
Definition at line 221 of file souffle2bdd.cpp.
{
         out << num;
     }
void souffle::BddBddBTranslator::visitProgram (const AstProgram & program, std::ostream & out) inline override private
The entry point for the conversion of a program, converting the basic top-level structure.
Definition at line 99 of file souffle2bdd.cpp.
References souffle::AstProgram::getRelations(), and i.
{
         // type definition
         out << "N " << std::numeric_limits<RamDomain>::max() << "\n\n";
         // variable order
         int max_attributes = 0;
         for (const auto& rel : program.getRelations()) {
             max_attributes = std::max<int>(max_attributes, rel->getAttributes().size());
         }
         out << ".bddvarorder ";
         for (int i = 0; i < max_attributes; i++) {
             out << "N" << i;
             if (i + 1 != max_attributes) {
                 out << "_";
             }
         }
         out << "\n\n";
         // declarations
         for (const auto& rel : program.getRelations()) {
             // process the relation declaration
             visit(*rel, out);
         }
         out << "\n";
         // rules
         for (const auto& rel : program.getRelations()) {
             for (const auto& clause : rel->getClauses()) {
                 visit(*clause, out);
             }
         }
         out << "\n";
     }
void souffle::BddBddBTranslator::visitRelation (const AstRelation & rel, std::ostream & out) inline override private
Converting a relation by creating its declaration.
Definition at line 136 of file souffle2bdd.cpp.
References souffle::AstRelation::getAttributes(), souffle::AstRelation::getName(), i, souffle::IOType::isInput(), souffle::IOType::isOutput(), and souffle::join().
{
         visitRelationIdentifier(rel.getName(), out);
         // make nullary relations single-element relations
         out << "(";
         if (rel.getAttributes().empty()) {
             out << "dummy:N0";
         }
         int i = 0;
         out << join(rel.getAttributes(), ",", [&](std::ostream& out, AstAttribute* cur) {
             out << cur->getAttributeName() << ":N" << (i++);
         });
         out << ")";
         if (ioTypes->isInput(&rel)) {
             out << " inputtuples";
         }
         if (ioTypes->isOutput(&rel)) {
             out << " outputtuples";
         }
         out << "\n";
     }
void souffle::BddBddBTranslator::visitRelationIdentifier (const AstRelationIdentifier & id, std::ostream & out) inline private
Definition at line 261 of file souffle2bdd.cpp.
References souffle::join().
{
         out << join(id.getNames(), "_");
     }
void souffle::BddBddBTranslator::visitStringConstant (const AstStringConstant & str, std::ostream & out) inline override private
Definition at line 216 of file souffle2bdd.cpp.
References souffle::AstConstant::getIndex().
{
         // we dump the index to the output, not the string itself
         out << str.getIndex();
     }
void souffle::BddBddBTranslator::visitTypeCast (const AstTypeCast & cast, std::ostream & out) inline override private
Definition at line 225 of file souffle2bdd.cpp.
References souffle::AstTypeCast::getValue().
{
         visit(*cast.getValue(), out);
     }
void souffle::BddBddBTranslator::visitUnnamedVariable (const AstUnnamedVariable & var, std::ostream & out) inline override private
Definition at line 257 of file souffle2bdd.cpp.
{
         out << "_";
     }
void souffle::BddBddBTranslator::visitVariable (const AstVariable & var, std::ostream & out) inline override private
Definition at line 253 of file souffle2bdd.cpp.
{
         out << var;
     }
Field Documentation
std::vector<std::string> souffle::BddBddBTranslator::extra_literals private
Definition at line 81 of file souffle2bdd.cpp.
const IOType* souffle::BddBddBTranslator::ioTypes private
Definition at line 83 of file souffle2bdd.cpp.
int souffle::BddBddBTranslator::varCounter = 0 private
Definition at line 85 of file souffle2bdd.cpp.
The documentation for this class was generated from the following file:
souffle2bdd.cpp