souffle: souffle::RamIndexKeysAnalysis Class Reference
souffle::RamIndexKeysAnalysis Class Reference
#include <RamIndexKeys.h>
Public Member Functions
SearchColumns getRangeQueryColumns (const RamIndexRelationSearch *search) const
Get indexable columns of index scan.
void run (const RamTranslationUnit &translationUnit) override
Run keys analysis for a RAM translation unit.
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "index-scan-keys-analysis"
Name of analysis.
Detailed Description
Definition at line 27 of file RamIndexKeys.h.
Member Function Documentation
SearchColumns souffle::RamIndexKeysAnalysis::getRangeQueryColumns (const RamIndexRelationSearch * search) const
Get indexable columns of index scan.
Definition at line 23 of file RamIndexKeys.cpp.
References souffle::RamIndexRelationSearch::getRangePattern(), and i.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), and run().
{
     SearchColumns keys = 0;
     std::vector<RamExpression*> rangePattern = search->getRangePattern();
     for (std::size_t i = 0; i < rangePattern.size(); i++) {
         if (rangePattern[i] != nullptr) {
             keys |= (1 << i);
         }
     }
     return keys;
 }
void souffle::RamIndexKeysAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
Run keys analysis for a RAM translation unit.
Implements souffle::RamAnalysis.
Definition at line 33 of file RamIndexKeys.h.
References getRangeQueryColumns().
 {}
Field Documentation
constexpr const char* souffle::RamIndexKeysAnalysis::name = "index-scan-keys-analysis" static
Name of analysis.
Definition at line 30 of file RamIndexKeys.h.
The documentation for this class was generated from the following files:
RamIndexKeys.h
RamIndexKeys.cpp