souffle: souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > Class Template Reference
souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > Class Template Reference
The actual implementation of a b-tree data structure.
#include <BTree.h>
Data Structures
struct base
The base type of all node types containing essential book-keeping information.
struct btree_operation_hints
A collection of operation hints speeding up some of the involved operations by exploiting temporal locality.
struct hint_statistics
struct inner_node
The data type representing inner nodes of the b-tree.
class iterator
The iterator type to be utilized for scanning through btree instances.
struct leaf_node
The data type representing leaf nodes of the b-tree.
struct node
The actual, generic node implementation covering the operations for both, inner and leaf nodes.
Public Types
enum { max_keys_per_node = node::maxKeys }
using chunk = range< iterator >
using const_iterator = iterator
using key_type = Key
using operation_hints = btree_operation_hints< 1 >
Public Member Functions
iterator begin () const
btree (const Comparator &comp=Comparator(), const WeakComparator &weak_comp=WeakComparator())
template<typename Iter >
btree (const Iter &a, const Iter &b)
btree (btree &&other)
btree (const btree &set)
bool check ()
Checks the consistency of this tree.
void clear ()
Clears this tree.
bool contains (const Key &k) const
Determines whether the given element is a member of this tree.
bool contains (const Key &k, operation_hints &hints) const
Determines whether the given element is a member of this tree.
bool empty () const
iterator end () const
iterator find (const Key &k) const
Locates the given key within this tree and returns an iterator referencing its position.
iterator find (const Key &k, operation_hints &hints) const
Locates the given key within this tree and returns an iterator referencing its position.
std::vector< chunk > getChunks (size_type num) const
Partitions the full range of this set into up to a given number of chunks.
size_type getDepth () const
const hint_statistics & getHintStatistics () const
size_type getMemoryUsage () const
size_type getNumNodes () const
bool insert (const Key &k)
Inserts the given key into this tree.
bool insert (const Key &k, operation_hints &hints)
Inserts the given key into this tree.
template<typename Iter >
void insert (const Iter &a, const Iter &b)
Inserts the given range of elements into this tree.
void insertAll (const btree &other)
Inserts all elements of the given b-tree into this tree.
iterator lower_bound (const Key &k) const
Obtains a lower boundary for the given key – hence an iterator referencing the smallest value that is not less the given key.
iterator lower_bound (const Key &k, operation_hints &hints) const
Obtains a lower boundary for the given key – hence an iterator referencing the smallest value that is not less the given key.
bool operator!= (const btree &other) const
btree & operator= (const btree &other)
bool operator== (const btree &other) const
void printStats (std::ostream &out=std::cout) const
Prints a textual summary of statistical properties of this tree to the given output stream (for debugging and tuning).
void printTree (std::ostream &out=std::cout) const
size_type size () const
void swap (btree &other)
Swaps the content of this tree with the given tree.
iterator upper_bound (const Key &k) const
Obtains an upper boundary for the given key – hence an iterator referencing the first element that the given key is less than the referenced value.
iterator upper_bound (const Key &k, operation_hints &hints) const
Obtains an upper boundary for the given key – hence an iterator referencing the first element that the given key is less than the referenced value.
~btree ()
Static Public Member Functions
template<typename R , typename Iter >
static std::enable_if< std::is_same< typename std::iterator_traits< Iter >::iterator_category, std::random_access_iterator_tag >::value, R >::type load (const Iter &a, const Iter &b)
A static member enabling the bulk-load of ordered data into an empty tree.
Protected Types
using field_index_type = uint8_t
using lock_type = OptimisticReadWriteLock
using size_type = std::size_t
Protected Member Functions
btree (size_type size, node *root, leaf_node *leftmost)
An internal constructor enabling the specific creation of a tree based on internal parameters.
bool covers (const node *node, const Key &k) const
Determines whether the range covered by the given node is also covering the given key value.
bool equal (const Key &a, const Key &b) const
bool less (const Key &a, const Key &b) const
void update (Key &old_k, const Key &new_k)
bool weak_covers (const node *node, const Key &k) const
Determines whether the range covered by the given node is also covering the given key value.
bool weak_equal (const Key &a, const Key &b) const
bool weak_less (const Key &a, const Key &b) const
Protected Attributes
Comparator comp
hint_statistics hint_stats
leaf_node * leftmost
node * root
lock_type root_lock
Updater upd
WeakComparator weak_comp
Static Protected Attributes
static const SearchStrategy search
Private Member Functions
bool coversUpperBound (const node *node, const Key &k) const
Determines whether the range covered by this node covers the upper bound of the given key.
Static Private Member Functions
template<typename Iter >
static node * buildSubTree (const Iter &a, const Iter &b)
Detailed Description
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>>
class souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >
The actual implementation of a b-tree data structure.
Template Parameters
Key .. the element type to be stored in this tree
Comparator .. a class defining an order on the stored elements
Allocator .. utilized for allocating memory for required nodes
blockSize .. determines the number of bytes/block utilized by leaf nodes
SearchStrategy .. enables switching between linear, binary or any other search strategy
isSet .. true = set, false = multiset
Definition at line 245 of file BTree.h.
Member Typedef Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::chunk = range<iterator>
Definition at line 251 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::const_iterator = iterator
Definition at line 248 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::field_index_type = uint8_t protected
Definition at line 290 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::key_type = Key
Definition at line 250 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::lock_type = OptimisticReadWriteLock protected
Definition at line 291 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::operation_hints = btree_operation_hints<1>
Definition at line 1198 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> using souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::size_type = std::size_t protected
Definition at line 289 of file BTree.h.
Member Enumeration Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> anonymous enum
Enumerator
max_keys_per_node
Definition at line 1239 of file BTree.h.
          {
         // the maximum number of keys stored per node
         max_keys_per_node = node::maxKeys
     };
Constructor & Destructor Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::btree (const Comparator & comp = Comparator(), const WeakComparator & weak_comp = WeakComparator()) inline
Definition at line 1247 of file BTree.h.
             : comp(comp), weak_comp(weak_comp), root(nullptr), leftmost(nullptr) {}
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> template<typename Iter > souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::btree (const Iter & a, const Iter & b) inline
Definition at line 1252 of file BTree.h.
                                         : root(nullptr), leftmost(nullptr) {
         insert(a, b);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::btree (btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > && other) inline
Definition at line 1257 of file BTree.h.
             : comp(other.comp), weak_comp(other.weak_comp), root(other.root), leftmost(other.leftmost) {
         other.root = nullptr;
         other.leftmost = nullptr;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::btree (const btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > & set) inline
Definition at line 1264 of file BTree.h.
                             : comp(set.comp), weak_comp(set.weak_comp), root(nullptr), leftmost(nullptr) {
         // use assignment operator for a deep copy
         *this = set;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::btree (size_type size, node * root, leaf_node * leftmost) inline protected
An internal constructor enabling the specific creation of a tree based on internal parameters.
Definition at line 1274 of file BTree.h.
 : root(root), leftmost(leftmost) {}
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::~btree () inline
Definition at line 1278 of file BTree.h.
              {
         clear();
     }
Member Function Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::begin () const inline
Definition at line 1711 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::begin(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insertAll(), and souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::insertAll().
{
         return iterator(leftmost, 0);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> template<typename Iter > static node* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::buildSubTree (const Iter & a, const Iter & b) inline static private
Definition at line 2157 of file BTree.h.
{
         const int N = node::maxKeys;
         // divide range in N+1 sub-ranges
         int length = (b - a) + 1;
         // terminal case: length is less then maxKeys
         if (length <= N) {
             // create a leaf node
             node* res = new leaf_node();
             res->numElements = length;
             for (int i = 0; i < length; ++i) {
                 res->keys[i] = a[i];
             }
             return res;
         }
         // recursive case - compute step size
         int numKeys = N;
         int step = ((length - numKeys) / (numKeys + 1));
         while (numKeys > 1 && (step < N / 2)) {
             numKeys--;
             step = ((length - numKeys) / (numKeys + 1));
         }
         // create inner node
         node* res = new inner_node();
         res->numElements = numKeys;
         Iter c = a;
         for (int i = 0; i < numKeys; i++) {
             // get dividing key
             res->keys[i] = c[step];
             // get sub-tree
             auto child = buildSubTree(c, c + (step - 1));
             child->parent = res;
             child->position = i;
             res->getChildren()[i] = child;
             c = c + (step + 1);
         }
         // and the remaining part
         auto child = buildSubTree(c, b);
         child->parent = res;
         child->position = numKeys;
         res->getChildren()[numKeys] = child;
         // done
         return res;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::check () inline
Checks the consistency of this tree.
Definition at line 2077 of file BTree.h.
                  {
         auto ok = empty() || root->check(comp, root);
         if (!ok) {
             printTree();
         }
         return ok;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::clear () inline
Clears this tree.
Definition at line 1931 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::clear().
                  {
         delete root;
         root = nullptr;
         leftmost = nullptr;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::contains (const Key & k) const inline
Determines whether the given element is a member of this tree.
Definition at line 1739 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::contains(), and souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::operator==().
{
         operation_hints hints;
         return contains(k, hints);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::contains (const Key & k, operation_hints & hints) const inline
Determines whether the given element is a member of this tree.
Definition at line 1747 of file BTree.h.
{
         return find(k, hints) != end();
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::covers (const node * node, const Key & k) const inline protected
Determines whether the range covered by the given node is also covering the given key value.
Definition at line 2121 of file BTree.h.
{
         if (isSet) {
             // in sets we can include the ends as covered elements
             return !node->isEmpty() && !less(k, node->keys[0]) && !less(node->keys[node->numElements - 1], k);
         }
         // in multi-sets the ends may not be completely covered
         return !node->isEmpty() && less(node->keys[0], k) && less(k, node->keys[node->numElements - 1]);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::coversUpperBound (const node * node, const Key & k) const inline private
Determines whether the range covered by this node covers the upper bound of the given key.
Definition at line 2150 of file BTree.h.
{
         // ignore edges
         return !node->isEmpty() && !less(k, node->keys[0]) && less(k, node->keys[node->numElements - 1]);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::empty () const inline
Definition at line 1285 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::empty(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::operator=(), and souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::operator=().
{
         return root == nullptr;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::end () const inline
Definition at line 1716 of file BTree.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::anteriorIt(), souffle::EquivalenceRelation< tuple_type >::antpostit(), souffle::ram::index_utils::DirectIndex< Tuple, Index >::end(), souffle::ram::index_utils::DirectIndex< Tuple, Index >::equalRange(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insertAll(), and souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::insertAll().
{
         return iterator();
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::equal (const Key & a, const Key & b) const inline protected
Definition at line 266 of file BTree.h.
{
         return comp.equal(a, b);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::find (const Key & k) const inline
Locates the given key within this tree and returns an iterator referencing its position.
If not found, an end-iterator will be returned.
Definition at line 1755 of file BTree.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::anteriorIt(), souffle::EquivalenceRelation< tuple_type >::antpostit(), souffle::EquivalenceRelation< tuple_type >::closure(), and souffle::ram::index_utils::DirectIndex< Tuple, Index >::find().
{
         operation_hints hints;
         return find(k, hints);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::find (const Key & k, operation_hints & hints) const inline
Locates the given key within this tree and returns an iterator referencing its position.
If not found, an end-iterator will be returned.
Definition at line 1764 of file BTree.h.
{
         if (empty()) {
             return end();
         }
         node* cur = root;
         auto checkHints = [&](node* last_find_end) {
             if (!last_find_end) return false;
             if (!covers(last_find_end, k)) return false;
             cur = last_find_end;
             return true;
         };
         // test last location searched (temporal locality)
         if (hints.last_find_end.any(checkHints)) {
             // register it as a hit
             hint_stats.contains.addHit();
         } else {
             // register it as a miss
             hint_stats.contains.addMiss();
         }
         // an iterative implementation (since 2/7 faster than recursive)
         while (true) {
             auto a = &(cur->keys[0]);
             auto b = &(cur->keys[cur->numElements]);
             auto pos = search(k, a, b, comp);
             if (pos < b && equal(*pos, k)) {
                 hints.last_find_end.access(cur);
                 return iterator(cur, pos - a);
             }
             if (!cur->inner) {
                 hints.last_find_end.access(cur);
                 return end();
             }
             // continue search in child node
             cur = cur->getChild(pos - a);
         }
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> std::vector<chunk> souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getChunks (size_type num) const inline
Partitions the full range of this set into up to a given number of chunks.
The chunks will cover approximately the same number of elements. Also, the number of chunks will only approximate the desired number of chunks.
Parameters
num .. the number of chunks requested
Returns
a list of chunks partitioning this tree
Definition at line 1728 of file BTree.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::insertAll(), and souffle::ram::index_utils::DirectIndex< Tuple, Index >::partition().
{
         std::vector<chunk> res;
         if (empty()) {
             return res;
         }
         return root->collectChunks(res, num, begin(), end());
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getDepth () const inline
Definition at line 2007 of file BTree.h.
{
         return (empty()) ? 0 : root->getDepth();
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> const hint_statistics& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getHintStatistics () const inline
Definition at line 2022 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::printHintStatistics().
{
         return hint_stats;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getMemoryUsage () const inline
Definition at line 2017 of file BTree.h.
{
         return sizeof(*this) + (empty() ? 0 : root->getMemoryUsage());
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getNumNodes () const inline
Definition at line 2012 of file BTree.h.
{
         return (empty()) ? 0 : root->countNodes();
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert (const Key & k) inline
Inserts the given key into this tree.
Definition at line 1297 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::insert().
{
         operation_hints hints;
         return insert(k, hints);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert (const Key & k, operation_hints & hints) inline
Inserts the given key into this tree.
Definition at line 1305 of file BTree.h.
{
 #ifdef IS_PARALLEL
         // special handling for inserting first element
         while (root == nullptr) {
             // try obtaining root-lock
             if (!root_lock.try_start_write()) {
                 // somebody else was faster => re-check
                 continue;
             }
             // check loop condition again
             if (root != nullptr) {
                 // somebody else was faster => normal insert
                 root_lock.end_write();
                 break;
             }
             // create new node
             leftmost = new leaf_node();
             leftmost->numElements = 1;
             leftmost->keys[0] = k;
             root = leftmost;
             // operation complete => we can release the root lock
             root_lock.end_write();
             hints.last_insert.access(leftmost);
             return true;
         }
         // insert using iterative implementation
         node* cur = nullptr;
         // test last insert hints
         lock_type::Lease cur_lease;
         auto checkHint = [&](node* last_insert) {
             // ignore null pointer
             if (!last_insert) return false;
             // get a read lease on indicated node
             auto hint_lease = last_insert->lock.start_read();
             // check whether it covers the key
             if (!weak_covers(last_insert, k)) return false;
             // and if there was no concurrent modification
             if (!last_insert->lock.validate(hint_lease)) return false;
             // use hinted location
             cur = last_insert;
             // and keep lease
             cur_lease = hint_lease;
             // we found a hit
             return true;
         };
         if (hints.last_insert.any(checkHint)) {
             // register this as a hit
             hint_stats.inserts.addHit();
         } else {
             // register this as a miss
             hint_stats.inserts.addMiss();
         }
         // if there is no valid hint ..
         if (!cur) {
             do {
                 // get root - access lock
                 auto root_lease = root_lock.start_read();
                 // start with root
                 cur = root;
                 // get lease of the next node to be accessed
                 cur_lease = cur->lock.start_read();
                 // check validity of root pointer
                 if (root_lock.end_read(root_lease)) break;
             } while (true);
         }
         while (true) {
             // handle inner nodes
             if (cur->inner) {
                 auto a = &(cur->keys[0]);
                 auto b = &(cur->keys[cur->numElements]);
                 auto pos = search.lower_bound(k, a, b, weak_comp);
                 auto idx = pos - a;
                 // early exit for sets
                 if (isSet && pos != b && weak_equal(*pos, k)) {
                     // validate results
                     if (!cur->lock.validate(cur_lease)) {
                         // start over again
                         return insert(k, hints);
                     }
                     // update provenance information
                     if (typeid(Comparator) != typeid(WeakComparator) && less(k, *pos)) {
                         if (!cur->lock.try_upgrade_to_write(cur_lease)) {
                             // start again
                             return insert(k, hints);
                         }
                         update(*pos, k);
                         cur->lock.end_write();
                         return true;
                     }
                     // we found the element => no check of lock necessary
                     return false;
                 }
                 // get next pointer
                 auto next = cur->getChild(idx);
                 // get lease on next level
                 auto next_lease = next->lock.start_read();
                 // check whether there was a write
                 if (!cur->lock.end_read(cur_lease)) {
                     // start over
                     return insert(k, hints);
                 }
                 // go to next
                 cur = next;
                 // move on lease
                 cur_lease = next_lease;
                 continue;
             }
             // the rest is for leaf nodes
             assert(!cur->inner);
             // -- insert node in leaf node --
             auto a = &(cur->keys[0]);
             auto b = &(cur->keys[cur->numElements]);
             auto pos = search.upper_bound(k, a, b, weak_comp);
             auto idx = pos - a;
             // early exit for sets
             if (isSet && pos != a && weak_equal(*(pos - 1), k)) {
                 // validate result
                 if (!cur->lock.validate(cur_lease)) {
                     // start over again
                     return insert(k, hints);
                 }
                 // update provenance information
                 if (typeid(Comparator) != typeid(WeakComparator) && less(k, *(pos - 1))) {
                     if (!cur->lock.try_upgrade_to_write(cur_lease)) {
                         // start again
                         return insert(k, hints);
                     }
                     update(*(pos - 1), k);
                     cur->lock.end_write();
                     return true;
                 }
                 // we found the element => done
                 return false;
             }
             // upgrade to write-permission
             if (!cur->lock.try_upgrade_to_write(cur_lease)) {
                 // something has changed => restart
                 hints.last_insert.access(cur);
                 return insert(k, hints);
             }
             if (cur->numElements >= node::maxKeys) {
                 // -- lock parents --
                 auto priv = cur;
                 auto parent = priv->parent;
                 std::vector<node*> parents;
                 do {
                     if (parent) {
                         parent->lock.start_write();
                         while (true) {
                             // check whether parent is correct
                             if (parent == priv->parent) break;
                             // switch parent
                             parent->lock.abort_write();
                             parent = priv->parent;
                             parent->lock.start_write();
                         }
                     } else {
                         // lock root lock => since cur is root
                         root_lock.start_write();
                     }
                     // record locked node
                     parents.push_back(parent);
                     // stop at "sphere of influence"
                     if (!parent || !parent->isFull()) break;
                     // go one step higher
                     priv = parent;
                     parent = parent->parent;
                 } while (true);
                 // split this node
                 auto old_root = root;
                 idx -= cur->rebalance_or_split(const_cast<node**>(&root), root_lock, idx, parents);
                 // release parent lock
                 for (auto it = parents.rbegin(); it != parents.rend(); ++it) {
                     auto parent = *it;
                     // release this lock
                     if (parent) {
                         parent->lock.end_write();
                     } else {
                         if (old_root != root) {
                             root_lock.end_write();
                         } else {
                             root_lock.abort_write();
                         }
                     }
                 }
                 // insert element in right fragment
                 if (((size_type)idx) > cur->numElements) {
                     // release current lock
                     cur->lock.end_write();
                     // insert in sibling
                     return insert(k, hints);
                 }
             }
             // ok - no split necessary
             assert(cur->numElements < node::maxKeys && "Split required!");
             // move keys
             for (int j = cur->numElements; j > idx; --j) {
                 cur->keys[j] = cur->keys[j - 1];
             }
             // insert new element
             cur->keys[idx] = k;
             cur->numElements++;
             // release lock on current node
             cur->lock.end_write();
             // remember last insertion position
             hints.last_insert.access(cur);
             return true;
         }
 #else
         // special handling for inserting first element
         if (empty()) {
             // create new node
             leftmost = new leaf_node();
             leftmost->numElements = 1;
             leftmost->keys[0] = k;
             root = leftmost;
             hints.last_insert.access(leftmost);
             return true;
         }
         // insert using iterative implementation
         node* cur = root;
         auto checkHints = [&](node* last_insert) {
             if (!last_insert) return false;
             if (!weak_covers(last_insert, k)) return false;
             cur = last_insert;
             return true;
         };
         // test last insert
         if (hints.last_insert.any(checkHints)) {
             hint_stats.inserts.addHit();
         } else {
             hint_stats.inserts.addMiss();
         }
         while (true) {
             // handle inner nodes
             if (cur->inner) {
                 auto a = &(cur->keys[0]);
                 auto b = &(cur->keys[cur->numElements]);
                 auto pos = search.lower_bound(k, a, b, weak_comp);
                 auto idx = pos - a;
                 // early exit for sets
                 if (isSet && pos != b && weak_equal(*pos, k)) {
                     // update provenance information
                     if (typeid(Comparator) != typeid(WeakComparator) && less(k, *pos)) {
                         update(*pos, k);
                         return true;
                     }
                     return false;
                 }
                 cur = cur->getChild(idx);
                 continue;
             }
             // the rest is for leaf nodes
             assert(!cur->inner);
             // -- insert node in leaf node --
             auto a = &(cur->keys[0]);
             auto b = &(cur->keys[cur->numElements]);
             auto pos = search.upper_bound(k, a, b, weak_comp);
             auto idx = pos - a;
             // early exit for sets
             if (isSet && pos != a && weak_equal(*(pos - 1), k)) {
                 // update provenance information
                 if (typeid(Comparator) != typeid(WeakComparator) && less(k, *(pos - 1))) {
                     update(*(pos - 1), k);
                     return true;
                 }
                 return false;
             }
             if (cur->numElements >= node::maxKeys) {
                 // split this node
                 idx -= cur->rebalance_or_split(&root, root_lock, idx);
                 // insert element in right fragment
                 if (((size_type)idx) > cur->numElements) {
                     idx -= cur->numElements + 1;
                     cur = cur->parent->getChild(cur->position + 1);
                 }
             }
             // ok - no split necessary
             assert(cur->numElements < node::maxKeys && "Split required!");
             // move keys
             for (int j = cur->numElements; j > idx; --j) {
                 cur->keys[j] = cur->keys[j - 1];
             }
             // insert new element
             cur->keys[idx] = k;
             cur->numElements++;
             // remember last insertion position
             hints.last_insert.access(cur);
             return true;
         }
 #endif
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> template<typename Iter > void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert (const Iter & a, const Iter & b) inline
Inserts the given range of elements into this tree.
Definition at line 1676 of file BTree.h.
{
         // TODO: improve this beyond a naive insert
         operation_hints hints;
         // a naive insert so far .. seems to work fine
         for (auto it = a; it != b; ++it) {
             // use insert with hint
             insert(*it, hints);
         }
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insertAll (const btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > & other) inline
Inserts all elements of the given b-tree into this tree.
This can be a more effective alternative to the ordered insertion of elements utilizing iterators.
Definition at line 1691 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::insertAll(), and souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::insertAll().
{
         // shortcut for non-sense operation
         if (this == &other) {
             return;
         }
         // make sure bigger tree is inserted in smaller tree
         if ((size() + 10000) < other.size()) {
             // switch sides
             btree tmp = other;
             tmp.insertAll(*this);
             swap(tmp);
             return;
         }
         // by default use the iterator based insertion
         insert(other.begin(), other.end());
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::less (const Key & a, const Key & b) const inline protected
Definition at line 262 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
{
         return comp.less(a, b);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> template<typename R , typename Iter > static std::enable_if<std::is_same<typename std::iterator_traits<Iter>::iterator_category, std::random_access_iterator_tag>::value, R>::type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::load (const Iter & a, const Iter & b) inline static
A static member enabling the bulk-load of ordered data into an empty tree.
This function is much more efficient in creating a index over an ordered set of elements than an iterative insertion of values.
Template Parameters
Iter .. the type of iterator specifying the range it must be a random-access iterator
Definition at line 2097 of file BTree.h.
{
         // quick exit - empty range
         if (a == b) {
             return R();
         }
         // resolve tree recursively
         auto root = buildSubTree(a, b - 1);
         // find leftmost node
         node* leftmost = root;
         while (!leftmost->isLeaf()) {
             leftmost = leftmost->getChild(0);
         }
         // build result
         return R(b - a, root, static_cast<leaf_node*>(leftmost));
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::lower_bound (const Key & k) const inline
Obtains a lower boundary for the given key – hence an iterator referencing the smallest value that is not less the given key.
If there is no such element, an end-iterator will be returned.
Definition at line 1815 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::equalRange().
{
         operation_hints hints;
         return lower_bound(k, hints);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::lower_bound (const Key & k, operation_hints & hints) const inline
Obtains a lower boundary for the given key – hence an iterator referencing the smallest value that is not less the given key.
If there is no such element, an end-iterator will be returned.
Definition at line 1825 of file BTree.h.
{
         if (empty()) {
             return end();
         }
         node* cur = root;
         auto checkHints = [&](node* last_lower_bound_end) {
             if (!last_lower_bound_end) return false;
             if (!covers(last_lower_bound_end, k)) return false;
             cur = last_lower_bound_end;
             return true;
         };
         // test last searched node
         if (hints.last_lower_bound_end.any(checkHints)) {
             hint_stats.lower_bound.addHit();
         } else {
             hint_stats.lower_bound.addMiss();
         }
         iterator res = end();
         while (true) {
             auto a = &(cur->keys[0]);
             auto b = &(cur->keys[cur->numElements]);
             auto pos = search.lower_bound(k, a, b, comp);
             auto idx = pos - a;
             if (!cur->inner) {
                 hints.last_lower_bound_end.access(cur);
                 return (pos != b) ? iterator(cur, idx) : res;
             }
             if (isSet && pos != b && equal(*pos, k)) {
                 return iterator(cur, idx);
             }
             if (pos != b) {
                 res = iterator(cur, idx);
             }
             cur = cur->getChild(idx);
         }
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::operator!= (const btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > & other) const inline
Definition at line 2000 of file BTree.h.
{
         return !(*this == other);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> btree& souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::operator= (const btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > & other) inline
Definition at line 1949 of file BTree.h.
{
         // check identity
         if (this == &other) {
             return *this;
         }
         // create a deep-copy of the content of the other tree
         // shortcut for empty sets
         if (other.empty()) {
             return *this;
         }
         // clone content (deep copy)
         root = other.root->clone();
         // update leftmost reference
         auto tmp = root;
         while (!tmp->isLeaf()) {
             tmp = tmp->getChild(0);
         }
         leftmost = static_cast<leaf_node*>(tmp);
         // done
         return *this;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::operator== (const btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > & other) const inline
Definition at line 1976 of file BTree.h.
{
         // check identity
         if (this == &other) {
             return true;
         }
         // check size
         if (size() != other.size()) {
             return false;
         }
         if (size() < other.size()) {
             return other == *this;
         }
         // check content
         for (const auto& key : other) {
             if (!contains(key)) {
                 return false;
             }
         }
         return true;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::printStats (std::ostream & out = std::cout) const inline
Prints a textual summary of statistical properties of this tree to the given output stream (for debugging and tuning).
Definition at line 2043 of file BTree.h.
{
         auto nodes = getNumNodes();
         out << "\n";
         out << "---------------------------------\n";
         out << "Table Statistics:\n";
         out << "---------------------------------\n";
         out << "  Elements: " << size() << "\n";
         out << "  Depth:    " << (empty() ? 0 : root->getDepth()) << "\n";
         out << "  Nodes:    " << nodes << "\n";
         out << "---------------------------------\n";
         out << "  Size of inner node: " << sizeof(inner_node) << "\n";
         out << "  Size of leaf node:  " << sizeof(leaf_node) << "\n";
         out << "  Size of Key:        " << sizeof(Key) << "\n";
         out << "  max keys / node:  " << node::maxKeys << "\n";
         out << "  avg keys / node:  " << (size() / (double)nodes) << "\n";
         out << "  avg filling rate: " << ((size() / (double)nodes) / node::maxKeys) << "\n";
         out << "---------------------------------\n";
         if (isHintsProfilingEnabled()) {
             out << "         insert hint hits: " << hint_stats.inserts.getHits() << "\n";
             out << "       insert hint misses: " << hint_stats.inserts.getMisses() << "\n";
             out << "       contains hint hits: " << hint_stats.contains.getHits() << "\n";
             out << "     contains hint misses: " << hint_stats.contains.getMisses() << "\n";
             out << "    lower_bound hint hits: " << hint_stats.lower_bound.getHits() << "\n";
             out << "  lower_bound hint misses: " << hint_stats.lower_bound.getMisses() << "\n";
             out << "    upper_bound hint hits: " << hint_stats.upper_bound.getHits() << "\n";
             out << "  upper_bound hint misses: " << hint_stats.upper_bound.getMisses() << "\n";
             out << "---------------------------------\n";
         }
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::printTree (std::ostream & out = std::cout) const inline
Definition at line 2030 of file BTree.h.
{
         out << "B-Tree with " << size() << " elements:\n";
         if (empty()) {
             out << " - empty - \n";
         } else {
             root->printTree(out, "");
         }
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> size_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::size () const inline
Definition at line 1290 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insertAll(), souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::insertAll(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::operator==(), souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::operator==(), souffle::EquivalenceRelation< tuple_type >::partition(), and souffle::ram::index_utils::DirectIndex< Tuple, Index >::size().
{
         return (root) ? root->countEntries() : 0;
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::swap (btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater > & other) inline
Swaps the content of this tree with the given tree.
This is a much more efficient operation than creating a copy and realizing the swap utilizing assignment operations.
Definition at line 1942 of file BTree.h.
{
         // swap the content
         std::swap(root, other.root);
         std::swap(leftmost, other.leftmost);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> void souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::update (Key & old_k, const Key & new_k) inline protected
Definition at line 283 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
{
         upd.update(old_k, new_k);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::upper_bound (const Key & k) const inline
Obtains an upper boundary for the given key – hence an iterator referencing the first element that the given key is less than the referenced value.
If there is no such element, an end-iterator will be returned.
Definition at line 1876 of file BTree.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::equalRange().
{
         operation_hints hints;
         return upper_bound(k, hints);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> iterator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::upper_bound (const Key & k, operation_hints & hints) const inline
Obtains an upper boundary for the given key – hence an iterator referencing the first element that the given key is less than the referenced value.
If there is no such element, an end-iterator will be returned.
Definition at line 1886 of file BTree.h.
{
         if (empty()) {
             return end();
         }
         node* cur = root;
         auto checkHints = [&](node* last_upper_bound_end) {
             if (!last_upper_bound_end) return false;
             if (!coversUpperBound(last_upper_bound_end, k)) return false;
             cur = last_upper_bound_end;
             return true;
         };
         // test last search node
         if (hints.last_upper_bound_end.any(checkHints)) {
             hint_stats.upper_bound.addHit();
         } else {
             hint_stats.upper_bound.addMiss();
         }
         iterator res = end();
         while (true) {
             auto a = &(cur->keys[0]);
             auto b = &(cur->keys[cur->numElements]);
             auto pos = search.upper_bound(k, a, b, comp);
             auto idx = pos - a;
             if (!cur->inner) {
                 hints.last_upper_bound_end.access(cur);
                 return (pos != b) ? iterator(cur, idx) : res;
             }
             if (pos != b) {
                 res = iterator(cur, idx);
             }
             cur = cur->getChild(idx);
         }
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::weak_covers (const node * node, const Key & k) const inline protected
Determines whether the range covered by the given node is also covering the given key value.
Definition at line 2134 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
{
         if (isSet) {
             // in sets we can include the ends as covered elements
             return !node->isEmpty() && !weak_less(k, node->keys[0]) &&
                    !weak_less(node->keys[node->numElements - 1], k);
         }
         // in multi-sets the ends may not be completely covered
         return !node->isEmpty() && weak_less(node->keys[0], k) &&
                weak_less(k, node->keys[node->numElements - 1]);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::weak_equal (const Key & a, const Key & b) const inline protected
Definition at line 276 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
{
         return weak_comp.equal(a, b);
     }
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> bool souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::weak_less (const Key & a, const Key & b) const inline protected
Definition at line 272 of file BTree.h.
{
         return weak_comp.less(a, b);
     }
Field Documentation
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> Comparator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::comp mutable protected
Definition at line 260 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> hint_statistics souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::hint_stats mutable protected
Definition at line 1236 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> leaf_node* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::leftmost protected
Definition at line 1216 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::operator=(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::swap(), and souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::swap().
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> node* souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::root protected
Definition at line 1209 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::operator=(), souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::operator=(), souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::swap(), and souffle::detail::btree< const RamDomain *, comparator, std::allocator< const RamDomain * >, blockSize, typename detail::default_strategy< const RamDomain * >::type, false, comparator, detail::updater< const RamDomain * > >::swap().
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> lock_type souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::root_lock protected
Definition at line 1212 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> const SearchStrategy souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::search static protected
Definition at line 256 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> Updater souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::upd mutable protected
Definition at line 282 of file BTree.h.
template<typename Key, typename Comparator, typename Allocator, unsigned blockSize, typename SearchStrategy, bool isSet, typename WeakComparator = Comparator, typename Updater = detail::updater<Key>> WeakComparator souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::weak_comp mutable protected
Definition at line 270 of file BTree.h.
Referenced by souffle::detail::LambdaBTree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, Functor >::insert().
The documentation for this class was generated from the following file:
BTree.h