souffle: souffle::ProfileEventSingleton Class Reference
souffle::ProfileEventSingleton Class Reference
Profile Event Singleton.
#include <ProfileEvent.h>
Data Structures
class ProfileTimer
Profile Timer.
Public Member Functions
void dump ()
Dump all events.
const profile::ProfileDatabase & getDB () const
void makeConfigRecord (const std::string &key, const std::string &value)
create config record
void makeQuantityEvent (const std::string &txt, size_t number, int iteration)
create quantity event
void makeStratumRecord (size_t index, const std::string &type, const std::string &relName, const std::string &key, const std::string &value)
create stratum record
void makeTimeEvent (const std::string &txt)
create time event
void makeTimingEvent (const std::string &txt, time_point start, time_point end, size_t startMaxRSS, size_t endMaxRSS, size_t size, size_t iteration)
create an event for recording start and end times
void makeUtilisationEvent (const std::string &txt)
create utilisation event
void resetTimerInterval (uint32_t interval=1)
void setDBFromFile (const std::string &filename)
void setOutputFile (std::string filename)
void startTimer ()
Start timer.
void stopTimer ()
Stop timer.
~ProfileEventSingleton ()
Static Public Member Functions
static ProfileEventSingleton & instance ()
get instance
Private Member Functions
ProfileEventSingleton ()=default
Private Attributes
profile::ProfileDatabase database
profile database
std::string filename {""}
ProfileTimer timer
Detailed Description
Profile Event Singleton.
Definition at line 44 of file ProfileEvent.h.
Constructor & Destructor Documentation
souffle::ProfileEventSingleton::ProfileEventSingleton () private default
souffle::ProfileEventSingleton::~ProfileEventSingleton () inline
Definition at line 52 of file ProfileEvent.h.
References dump(), instance(), and stopTimer().
{
         stopTimer();
         ProfileEventSingleton::instance().dump();
     }
Member Function Documentation
void souffle::ProfileEventSingleton::dump () inline
Dump all events.
Definition at line 118 of file ProfileEvent.h.
References filename.
Referenced by ~ProfileEventSingleton().
                 {
         if (!filename.empty()) {
             std::ofstream os(filename);
             if (!os.is_open()) {
                 std::cerr << "Cannot open profile log file <" + filename + ">";
             } else {
                 database.print(os);
             }
         }
     }
const profile::ProfileDatabase& souffle::ProfileEventSingleton::getDB () const inline
Definition at line 142 of file ProfileEvent.h.
References database.
Referenced by genJsonAtoms(), and genJsonConfiguration().
{
         return database;
     }
static ProfileEventSingleton& souffle::ProfileEventSingleton::instance () inline static
get instance
Definition at line 58 of file ProfileEvent.h.
Referenced by souffle::RAMI::evalStmt(), souffle::LVM::execute(), souffle::RAMI::executeMain(), souffle::LVM::executeMain(), genJsonAtoms(), genJsonConfiguration(), souffle::Logger::Logger(), souffle::profile::Reader::Reader(), souffle::ProfileEventSingleton::ProfileTimer::run(), souffle::Logger::~Logger(), and ~ProfileEventSingleton().
{
         static ProfileEventSingleton singleton;
         return singleton;
     }
void souffle::ProfileEventSingleton::makeConfigRecord (const std::string & key, const std::string & value) inline
create config record
Definition at line 64 of file ProfileEvent.h.
References souffle::profile::EventProcessorSingleton::instance(), and souffle::profile::EventProcessorSingleton::process().
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
{
         profile::EventProcessorSingleton::instance().process(database, "@config", key.c_str(), value.c_str());
     }
void souffle::ProfileEventSingleton::makeQuantityEvent (const std::string & txt, size_t number, int iteration) inline
create quantity event
Definition at line 92 of file ProfileEvent.h.
References souffle::profile::EventProcessorSingleton::instance(), iteration, and souffle::profile::EventProcessorSingleton::process().
Referenced by souffle::RAMI::evalStmt(), souffle::LVM::execute(), souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
{
         profile::EventProcessorSingleton::instance().process(database, txt.c_str(), number, iteration);
     }
void souffle::ProfileEventSingleton::makeStratumRecord (size_t index, const std::string & type, const std::string & relName, const std::string & key, const std::string & value) inline
create stratum record
Definition at line 69 of file ProfileEvent.h.
References souffle::profile::EventProcessorSingleton::instance(), souffle::profile::EventProcessorSingleton::process(), and souffle::profile::ss.
Referenced by souffle::RAMI::evalStmt(), and souffle::LVM::execute().
{
         std::stringstream ss;
         ss << "@text;stratum;" << index << ';' << type << ';' << relName << ';' << key;
         profile::EventProcessorSingleton::instance().process(database, ss.str().c_str(), value.c_str());
     }
void souffle::ProfileEventSingleton::makeTimeEvent (const std::string & txt) inline
create time event
Definition at line 77 of file ProfileEvent.h.
References souffle::profile::EventProcessorSingleton::instance(), souffle::now(), and souffle::profile::EventProcessorSingleton::process().
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
{
         profile::EventProcessorSingleton::instance().process(
                 database, txt.c_str(), std::chrono::duration_cast<microseconds>(now().time_since_epoch()));
     }
void souffle::ProfileEventSingleton::makeTimingEvent (const std::string & txt, time_point start, time_point end, size_t startMaxRSS, size_t endMaxRSS, size_t size, size_t iteration) inline
create an event for recording start and end times
Definition at line 83 of file ProfileEvent.h.
References souffle::profile::EventProcessorSingleton::instance(), iteration, and souffle::profile::EventProcessorSingleton::process().
Referenced by souffle::Logger::~Logger().
{
         microseconds start_ms = std::chrono::duration_cast<microseconds>(start.time_since_epoch());
         microseconds end_ms = std::chrono::duration_cast<microseconds>(end.time_since_epoch());
         profile::EventProcessorSingleton::instance().process(
                 database, txt.c_str(), start_ms, end_ms, startMaxRSS, endMaxRSS, size, iteration);
     }
void souffle::ProfileEventSingleton::makeUtilisationEvent (const std::string & txt) inline
create utilisation event
Definition at line 97 of file ProfileEvent.h.
References souffle::profile::EventProcessorSingleton::instance(), souffle::now(), and souffle::profile::EventProcessorSingleton::process().
Referenced by souffle::ProfileEventSingleton::ProfileTimer::run().
{
         /* current time */
         microseconds time = std::chrono::duration_cast<microseconds>(now().time_since_epoch());
         /* system CPU time used */
         struct rusage ru {};
         getrusage(RUSAGE_SELF, &ru);
         /* system CPU time used */
         uint64_t systemTime = ru.ru_stime.tv_sec * 1000000 + ru.ru_stime.tv_usec;
         /* user CPU time used */
         uint64_t userTime = ru.ru_utime.tv_sec * 1000000 + ru.ru_utime.tv_usec;
         /* Maximum resident set size (kb) */
         size_t maxRSS = ru.ru_maxrss;
         profile::EventProcessorSingleton::instance().process(
                 database, txt.c_str(), time, systemTime, userTime, maxRSS);
     }
void souffle::ProfileEventSingleton::resetTimerInterval (uint32_t interval = 1) inline
Definition at line 139 of file ProfileEvent.h.
References souffle::ProfileEventSingleton::ProfileTimer::resetTimerInterval(), and timer.
Referenced by souffle::Logger::Logger().
{
         timer.resetTimerInterval(interval);
     }
void souffle::ProfileEventSingleton::setDBFromFile (const std::string & filename) inline
Definition at line 146 of file ProfileEvent.h.
Referenced by souffle::profile::Reader::Reader().
{
         database = profile::ProfileDatabase(filename);
     }
void souffle::ProfileEventSingleton::setOutputFile (std::string filename) inline
Definition at line 114 of file ProfileEvent.h.
References filename.
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
{
         this->filename = filename;
     }
void souffle::ProfileEventSingleton::startTimer () inline
Start timer.
Definition at line 130 of file ProfileEvent.h.
References souffle::ProfileEventSingleton::ProfileTimer::start(), and timer.
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
                       {
         timer.start();
     }
void souffle::ProfileEventSingleton::stopTimer () inline
Stop timer.
Definition at line 135 of file ProfileEvent.h.
References souffle::ProfileEventSingleton::ProfileTimer::stop(), and timer.
Referenced by souffle::RAMI::executeMain(), souffle::LVM::executeMain(), and ~ProfileEventSingleton().
                      {
         timer.stop();
     }
Field Documentation
profile::ProfileDatabase souffle::ProfileEventSingleton::database private
profile database
Definition at line 46 of file ProfileEvent.h.
Referenced by getDB().
std::string souffle::ProfileEventSingleton::filename {""} private
Definition at line 47 of file ProfileEvent.h.
Referenced by dump(), and setOutputFile().
ProfileTimer souffle::ProfileEventSingleton::timer private
Definition at line 235 of file ProfileEvent.h.
Referenced by resetTimerInterval(), startTimer(), and stopTimer().
The documentation for this class was generated from the following file:
ProfileEvent.h