souffle: souffle::SparseDisjointSet< SparseDomain > Class Template Reference
souffle::SparseDisjointSet< SparseDomain > Class Template Reference
#include <UnionFind.h>
Public Member Functions
void clear ()
Remove all elements from this disjoint set.
bool contains (SparseDomain v1, SparseDomain v2)
SparseDomain findNode (SparseDomain x)
void makeNode (SparseDomain val)
bool nodeExists (const SparseDomain val) const
SparseDisjointSet & operator= (SparseDisjointSet &other)=delete
SparseDisjointSet & operator= (SparseDisjointSet &&other)=delete
bool sameSet (SparseDomain x, SparseDomain y)
std::size_t size ()
SparseDisjointSet ()=default
SparseDisjointSet (SparseDisjointSet &other)=delete
SparseDisjointSet (SparseDisjointSet &&other)=delete
parent_t toDense (const SparseDomain in)
Retrieve dense encoding, adding it in if non-existent.
const SparseDomain toSparse (const parent_t in) const
For the given dense value, return the associated sparse value Undefined behaviour if dense value not in set.
void unionNodes (SparseDomain x, SparseDomain y)
Private Types
using DenseMap = RandomInsertPiggyList< SparseDomain >
using PairStore = std::pair< SparseDomain, parent_t >
using SparseMap = LambdaBTreeSet< PairStore, std::function< parent_t(PairStore &)>, EqrelMapComparator< PairStore >>
Private Attributes
DenseMap denseToSparseMap
DisjointSet ds
SparseMap::operation_hints last_ins
SparseMap sparseToDenseMap
Friends
template<typename TupleType >
class EquivalenceRelation
Detailed Description
template<typename SparseDomain>
class souffle::SparseDisjointSet< SparseDomain >
Definition at line 251 of file UnionFind.h.
Member Typedef Documentation
template<typename SparseDomain> using souffle::SparseDisjointSet< SparseDomain >::DenseMap = RandomInsertPiggyList<SparseDomain> private
Definition at line 260 of file UnionFind.h.
template<typename SparseDomain> using souffle::SparseDisjointSet< SparseDomain >::PairStore = std::pair<SparseDomain, parent_t> private
Definition at line 257 of file UnionFind.h.
template<typename SparseDomain> using souffle::SparseDisjointSet< SparseDomain >::SparseMap = LambdaBTreeSet<PairStore, std::function<parent_t(PairStore&)>, EqrelMapComparator<PairStore>> private
Definition at line 259 of file UnionFind.h.
Constructor & Destructor Documentation
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::SparseDisjointSet () default
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::SparseDisjointSet (SparseDisjointSet< SparseDomain > & other) delete
template<typename SparseDomain> souffle::SparseDisjointSet< SparseDomain >::SparseDisjointSet (SparseDisjointSet< SparseDomain > && other) delete
Member Function Documentation
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::clear () inline
Remove all elements from this disjoint set.
Definition at line 331 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::clear().
                  {
         ds.clear();
         sparseToDenseMap.clear();
         denseToSparseMap.clear();
     }
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::contains (SparseDomain v1, SparseDomain v2) inline
Definition at line 348 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::contains(), and souffle::EquivalenceRelation< tuple_type >::getBoundaries().
{
         if (nodeExists(v1) && nodeExists(v2)) {
             return sameSet(v1, v2);
         }
         return false;
     }
template<typename SparseDomain> SparseDomain souffle::SparseDisjointSet< SparseDomain >::findNode (SparseDomain x) inline
Definition at line 316 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::anteriorIt(), souffle::EquivalenceRelation< tuple_type >::antpostit(), souffle::EquivalenceRelation< tuple_type >::closure(), souffle::EquivalenceRelation< tuple_type >::extend(), and souffle::EquivalenceRelation< tuple_type >::genAllDisjointSetLists().
{
         return toSparse(ds.findNode(toDense(x)));
     };
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::makeNode (SparseDomain val) inline
Definition at line 338 of file UnionFind.h.
{
         // dense has the behaviour of creating if not exists.
         toDense(val);
     };
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::nodeExists (const SparseDomain val) const inline
Definition at line 344 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::containsElement(), and souffle::EquivalenceRelation< tuple_type >::getBoundaries().
{
         return sparseToDenseMap.contains({val, -1});
     };
template<typename SparseDomain> SparseDisjointSet& souffle::SparseDisjointSet< SparseDomain >::operator= (SparseDisjointSet< SparseDomain > & other) delete
template<typename SparseDomain> SparseDisjointSet& souffle::SparseDisjointSet< SparseDomain >::operator= (SparseDisjointSet< SparseDomain > && other) delete
template<typename SparseDomain> bool souffle::SparseDisjointSet< SparseDomain >::sameSet (SparseDomain x, SparseDomain y) inline
Definition at line 312 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::antpostit().
{
         return ds.sameSet(toDense(x), toDense(y));
     };
template<typename SparseDomain> std::size_t souffle::SparseDisjointSet< SparseDomain >::size () inline
Definition at line 324 of file UnionFind.h.
{
         return ds.size();
     };
template<typename SparseDomain> parent_t souffle::SparseDisjointSet< SparseDomain >::toDense (const SparseDomain in) inline
Retrieve dense encoding, adding it in if non-existent.
Parameters
in the sparse value
Returns
the corresponding dense value
Definition at line 274 of file UnionFind.h.
{
         // insert into the mapping - if the key doesn't exist (in), the function will be called
         // and a dense value will be created for it
         PairStore p = {in, -1};
         return sparseToDenseMap.insert(p, [&](PairStore& p) {
             parent_t c2 = DisjointSet::b2p(this->ds.makeNode());
             this->denseToSparseMap.insertAt(c2, p.first);
             p.second = c2;
             return c2;
         });
     }
template<typename SparseDomain> const SparseDomain souffle::SparseDisjointSet< SparseDomain >::toSparse (const parent_t in) const inline
For the given dense value, return the associated sparse value Undefined behaviour if dense value not in set.
Parameters
in the supplied dense value
Returns
the sparse value from the denseToSparseMap
Definition at line 307 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::genAllDisjointSetLists().
{
         return denseToSparseMap.get(in);
     };
template<typename SparseDomain> void souffle::SparseDisjointSet< SparseDomain >::unionNodes (SparseDomain x, SparseDomain y) inline
Definition at line 320 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::insert(), and souffle::EquivalenceRelation< tuple_type >::insertAll().
{
         ds.unionNodes(toDense(x), toDense(y));
     };
Friends And Related Function Documentation
template<typename SparseDomain> template<typename TupleType > friend class EquivalenceRelation friend
Definition at line 255 of file UnionFind.h.
Field Documentation
template<typename SparseDomain> DenseMap souffle::SparseDisjointSet< SparseDomain >::denseToSparseMap private
Definition at line 266 of file UnionFind.h.
template<typename SparseDomain> DisjointSet souffle::SparseDisjointSet< SparseDomain >::ds private
Definition at line 252 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::genAllDisjointSetLists().
template<typename SparseDomain> SparseMap::operation_hints souffle::SparseDisjointSet< SparseDomain >::last_ins private
Definition at line 262 of file UnionFind.h.
template<typename SparseDomain> SparseMap souffle::SparseDisjointSet< SparseDomain >::sparseToDenseMap private
Definition at line 264 of file UnionFind.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::extend().
The documentation for this class was generated from the following file:
UnionFind.h