souffle: souffle::InterpreterContext Class Reference
souffle::InterpreterContext Class Reference
Evaluation context for Interpreter operations.
#include <InterpreterContext.h>
Public Member Functions
void addReturnValue (RamDomain val, bool err=false)
RamDomain * allocateNewTuple (size_t size)
Allocate a tuple.
RamDomain getArgument (size_t i) const
const std::vector< RamDomain > & getArguments () const
std::vector< bool > & getReturnErrors () const
std::vector< RamDomain > & getReturnValues () const
InterpreterContext (size_t size=0)
const RamDomain *& operator[] (size_t index)
const RamDomain *const & operator[] (size_t index) const
void setArguments (const std::vector< RamDomain > &a)
void setReturnErrors (std::vector< bool > &retErrs)
void setReturnValues (std::vector< RamDomain > &retVals)
virtual ~InterpreterContext ()=default
Private Attributes
std::vector< std::unique_ptr< RamDomain[]> > allocatedDataContainer
const std::vector< RamDomain > * args = nullptr
std::vector< const RamDomain * > data
std::vector< bool > * returnErrors = nullptr
std::vector< RamDomain > * returnValues = nullptr
Detailed Description
Evaluation context for Interpreter operations.
Definition at line 29 of file InterpreterContext.h.
Constructor & Destructor Documentation
souffle::InterpreterContext::InterpreterContext (size_t size = 0) inline
Definition at line 37 of file InterpreterContext.h.
References ~InterpreterContext().
 : data(size) {}
virtual souffle::InterpreterContext::~InterpreterContext () virtual default
Referenced by InterpreterContext().
Member Function Documentation
void souffle::InterpreterContext::addReturnValue (RamDomain val, bool err = false) inline
Definition at line 69 of file InterpreterContext.h.
References err.
Referenced by souffle::RAMI::evalOp(), and souffle::LVM::execute().
{
         assert(returnValues != nullptr && returnErrors != nullptr);
         returnValues->push_back(val);
         returnErrors->push_back(err);
     }
RamDomain* souffle::InterpreterContext::allocateNewTuple (size_t size) inline
Allocate a tuple.
allocatedDataContainer has the ownership of those tuples.
Definition at line 53 of file InterpreterContext.h.
Referenced by souffle::LVM::execute().
{
         std::unique_ptr<RamDomain[]> newTuple(new RamDomain[size]);
         allocatedDataContainer.push_back(std::move(newTuple));
         // Return the reference as raw pointer.
         return allocatedDataContainer.back().get();
     }
RamDomain souffle::InterpreterContext::getArgument (size_t i) const inline
Definition at line 91 of file InterpreterContext.h.
References i.
Referenced by souffle::RAMI::evalExpr(), and souffle::LVM::execute().
{
         assert(args != nullptr && i < args->size() && "argument out of range");
         return (*args)[i];
     }
const std::vector<RamDomain>& souffle::InterpreterContext::getArguments () const inline
Definition at line 83 of file InterpreterContext.h.
References args.
Referenced by souffle::RAMI::evalOp().
{
         return *args;
     }
std::vector<bool>& souffle::InterpreterContext::getReturnErrors () const inline
Definition at line 75 of file InterpreterContext.h.
References returnErrors.
Referenced by souffle::RAMI::evalOp().
{
         return *returnErrors;
     }
std::vector<RamDomain>& souffle::InterpreterContext::getReturnValues () const inline
Definition at line 61 of file InterpreterContext.h.
References returnValues.
Referenced by souffle::RAMI::evalOp().
{
         return *returnValues;
     }
const RamDomain*& souffle::InterpreterContext::operator[] (size_t index) inline
Definition at line 40 of file InterpreterContext.h.
{
         if (index >= data.size()) {
             data.resize((index + 1));
         }
         return data[index];
     }
const RamDomain* const& souffle::InterpreterContext::operator[] (size_t index) const inline
Definition at line 47 of file InterpreterContext.h.
{
         return data[index];
     }
void souffle::InterpreterContext::setArguments (const std::vector< RamDomain > & a) inline
Definition at line 87 of file InterpreterContext.h.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::executeSubroutine(), and souffle::LVM::executeSubroutine().
{
         args = &a;
     }
void souffle::InterpreterContext::setReturnErrors (std::vector< bool > & retErrs) inline
Definition at line 79 of file InterpreterContext.h.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::executeSubroutine(), and souffle::LVM::executeSubroutine().
{
         returnErrors = &retErrs;
     }
void souffle::InterpreterContext::setReturnValues (std::vector< RamDomain > & retVals) inline
Definition at line 65 of file InterpreterContext.h.
Referenced by souffle::RAMI::evalOp(), souffle::RAMI::executeSubroutine(), and souffle::LVM::executeSubroutine().
{
         returnValues = &retVals;
     }
Field Documentation
std::vector<std::unique_ptr<RamDomain[]> > souffle::InterpreterContext::allocatedDataContainer private
Definition at line 34 of file InterpreterContext.h.
const std::vector<RamDomain>* souffle::InterpreterContext::args = nullptr private
Definition at line 33 of file InterpreterContext.h.
Referenced by getArguments().
std::vector<const RamDomain*> souffle::InterpreterContext::data private
Definition at line 30 of file InterpreterContext.h.
std::vector<bool>* souffle::InterpreterContext::returnErrors = nullptr private
Definition at line 32 of file InterpreterContext.h.
Referenced by getReturnErrors().
std::vector<RamDomain>* souffle::InterpreterContext::returnValues = nullptr private
Definition at line 31 of file InterpreterContext.h.
Referenced by getReturnValues().
The documentation for this class was generated from the following file:
InterpreterContext.h