souffle: souffle::Explain Class Reference
souffle::Explain Class Reference
#include <Explain.h>
Public Member Functions
Explain (ExplainProvenance &p, bool ncurses, int d=4)
void explain ()
~Explain ()
Private Member Functions
std::pair< std::string, std::vector< std::string > > parseTuple (const std::string &str)
Private Attributes
int depthLimit
bool json
flag for outputting in JSON format
int maxx = 0
int maxy = 0
bool ncurses
std::ostream * output
output stream
ExplainProvenance & prov
WINDOW * queryWindow = nullptr
WINDOW * treePad = nullptr
Detailed Description
Definition at line 35 of file Explain.h.
Constructor & Destructor Documentation
souffle::Explain::Explain (ExplainProvenance & p, bool ncurses, int d = 4) inline
Definition at line 37 of file Explain.h.
Referenced by explain().
             : prov(p), ncurses(ncurses), depthLimit(d), output(nullptr), json(false) {}
souffle::Explain::~Explain () inline
Definition at line 39 of file Explain.h.
References output.
                {
         delete output;
     }
Member Function Documentation
void souffle::Explain::explain () inline
Definition at line 43 of file Explain.h.
References clearDisplay(), depthLimit, e, souffle::ExplainProvenance::explain(), souffle::ExplainProvenance::explainNegation(), souffle::ExplainProvenance::explainNegationGetVariables(), souffle::ExplainProvenance::explainSubproof(), getInput(), souffle::ExplainProvenance::getRule(), souffle::ExplainProvenance::getRules(), i, initialiseWindow(), json, maxx, maxy, souffle::ExplainProvenance::measureRelation(), ncurses, output, parseTuple(), printPrompt(), printStr(), prov, rule, scrollTree(), souffle::split(), treePad, and variables.
                    {
         if (ncurses && !output) {
             initialiseWindow();
             std::signal(SIGWINCH, nullptr);
         }
         while (true) {
             clearDisplay();
             printPrompt("Enter command > ");
             std::string line = getInput();
             std::vector<std::string> command = split(line, ' ', 1);
             if (command.empty()) {
                 continue;
             }
             if (command[0] == "setdepth") {
                 if (command.size() != 2) {
                     printStr("Usage: setdepth <depth>\n");
                     continue;
                 }
                 try {
                     depthLimit = std::stoi(command[1]);
                 } catch (std::exception& e) {
                     printStr("<" + command[1] + "> is not a valid depth\n");
                     continue;
                 }
                 printStr("Depth is now " + std::to_string(depthLimit) + "\n");
             } else if (command[0] == "explain") {
                 std::pair<std::string, std::vector<std::string>> query;
                 if (command.size() == 2) {
                     query = parseTuple(command[1]);
                 } else {
                     printStr("Usage: explain relation_name(\"<string element1>\", <number element2>, ...)\n");
                     continue;
                 }
                 std::unique_ptr<TreeNode> t = prov.explain(query.first, query.second, depthLimit);
                 printTree(std::move(t));
             } else if (command[0] == "subproof") {
                 std::pair<std::string, std::vector<std::string>> query;
                 int label = -1;
                 if (command.size() > 1) {
                     query = parseTuple(command[1]);
                     label = std::stoi(query.second[0]);
                 } else {
                     printStr("Usage: subproof relation_name(<label>)\n");
                     continue;
                 }
                 std::unique_ptr<TreeNode> t = prov.explainSubproof(query.first, label, depthLimit);
                 printTree(std::move(t));
             } else if (command[0] == "explainnegation") {
                 std::pair<std::string, std::vector<std::string>> query;
                 if (command.size() == 2) {
                     query = parseTuple(command[1]);
                 } else {
                     printStr(
                             "Usage: explainnegation relation_name(\"<string element1>\", <number element2>, "
                             "...)\n");
                     continue;
                 }
                 size_t i = 1;
                 std::string rules;
                 for (auto rule : prov.getRules(query.first)) {
                     rules += std::to_string(i) + ": ";
                     rules += rule;
                     rules += "\n\n";
                     i++;
                 }
                 printStr(rules);
                 if (ncurses && !output) {
                     prefresh(treePad, 0, 0, 0, 0, maxy - 3, maxx - 1);
                 }
                 printPrompt("Pick a rule number: ");
                 std::string ruleNum = getInput();
                 auto variables =
                         prov.explainNegationGetVariables(query.first, query.second, std::stoi(ruleNum));
                 if (variables.size() == 1 && variables[0] == "@") {
                     printPrompt("The tuple exists, cannot explain negation of it!\n");
                     continue;
                 } else if (variables.size() == 1 && variables[0] == "@non_matching") {
                     printPrompt("The variable bindings don't match, cannot explain!\n");
                     continue;
                 }
                 // this doesn't work with ncurses yet!!
                 std::map<std::string, std::string> varValues;
                 for (auto var : variables) {
                     printPrompt("Pick a value for " + var + ": ");
                     std::string varValue = getInput();
                     varValues[var] = varValue;
                 }
                 printTree(prov.explainNegation(query.first, std::stoi(ruleNum), query.second, varValues));
             } else if (command[0] == "rule" && command.size() == 2) {
                 auto query = split(command[1], ' ');
                 if (query.size() != 2) {
                     printStr("Usage: rule <relation name> <rule number>\n");
                     continue;
                 }
                 try {
                     printStr(prov.getRule(query[0], std::stoi(query[1])) + "\n");
                 } catch (std::exception& e) {
                     printStr("Usage: rule <relation name> <rule number>\n");
                     continue;
                 }
             } else if (command[0] == "measure") {
                 try {
                     printStr(prov.measureRelation(command[1]));
                 } catch (std::exception& e) {
                     printStr("Usage: printrel <relation name>\n");
                     continue;
                 }
             } else if (command[0] == "output") {
                 if (command.size() == 2) {
                     output = new std::ofstream(command[1]);
                 } else if (command.size() == 1) {
                     delete output;
                     output = nullptr;
                 } else {
                     printStr("Usage: output  [<filename>]\n");
                 }
             } else if (command[0] == "format") {
                 if (command.size() == 2 && command[1] == "json") {
                     json = true;
                 } else if (command.size() == 2 && command[1] == "proof") {
                     json = false;
                 } else {
                     printStr("Usage: format <json|proof>\n");
                 }
             } else if (command[0] == "exit" || command[0] == "q" || command[0] == "quit") {
                 printStr("Exiting explain\n");
                 break;
             } else {
                 printStr(
                         "\n----------\n"
                         "Commands:\n"
                         "----------\n"
                         "setdepth <depth>: Set a limit for printed derivation tree height\n"
                         "explain <relation>(<element1>, <element2>, ...): Prints derivation tree\n"
                         "subproof <relation>(<label>): Prints derivation tree for a subproof, label is "
                         "generated if a derivation tree exceeds height limit\n"
                         "rule <relation name> <rule number>: Prints a rule\n"
                         "output <filename>: Write output into a file/disable output\n"
                         "format <json|proof>: switch format between json and proof-trees\n"
                         "exit: Exits this interface\n\n");
             }
             // refresh treePad and allow scrolling
             if (ncurses && !output) {
                 prefresh(treePad, 0, 0, 0, 0, maxy - 3, maxx - 1);
                 scrollTree(maxx, maxy);
             }
         }
         if (ncurses && !output) {
             endwin();
         }
     }
std::pair<std::string, std::vector<std::string> > souffle::Explain::parseTuple (const std::string & str) inline private
Definition at line 224 of file Explain.h.
References souffle::ScreenBuffer::getString(), maxy, and souffle::ExplainProvenance::printRulesJSON().
Referenced by explain().
{
         std::string relName;
         std::vector<std::string> args;
         // regex for matching tuples
         // values matches numbers or strings enclosed in quotation marks
         std::regex relRegex(
                 "([a-zA-Z0-9_.-]*)[[:blank:]]*\\(([[:blank:]]*([0-9]+|\"[^\"]*\")([[:blank:]]*,[[:blank:]]*(["
                 "0-"
                 "9]+|\"[^\"]*\"))*)?\\)",
                 std::regex_constants::extended);
         std::smatch relMatch;
         // first check that format matches correctly
         // and extract relation name
         if (!std::regex_match(str, relMatch, relRegex) || relMatch.size() < 3) {
             return std::make_pair(relName, args);
         }
         // set relation name
         relName = relMatch[1];
         // extract each argument
         std::string argsList = relMatch[2];
         std::smatch argsMatcher;
         std::regex argRegex(R"([0-9]+|"[^"]*")", std::regex_constants::extended);
         while (std::regex_search(argsList, argsMatcher, argRegex)) {
             // match the start of the arguments
             std::string currentArg = argsMatcher[0];
             args.push_back(currentArg);
             // use the rest of the arguments
             argsList = argsMatcher.suffix().str();
         }
         return std::make_pair(relName, args);
     }
     // initialise ncurses window
     WINDOW* makeQueryWindow() {
         WINDOW* w = newwin(3, maxx, maxy - 2, 0);
         wrefresh(w);
         return w;
     }
     // print provenance tree
     void printTree(std::unique_ptr<TreeNode> tree) {
         if (tree) {
             if (!json) {
                 tree->place(0, 0);
                 ScreenBuffer screenBuffer(tree->getWidth(), tree->getHeight());
                 tree->render(screenBuffer);
                 if (ncurses && !output) {
                     wprintw(treePad, screenBuffer.getString().c_str());
                 } else {
                     if (output) {
                         *output << screenBuffer.getString();
                     } else {
                         std::cout << screenBuffer.getString();
                     }
                 }
             } else {
                 if (!output) {
                     std::cout << "{ \"proof\":\n";
                     tree->printJSON(std::cout, 1);
                     std::cout << ",";
                     prov.printRulesJSON(std::cout);
                     std::cout << "}\n";
                 } else {
                     *output << "{ \"proof\":\n";
                     tree->printJSON(*output, 1);
                     *output << ",";
                     prov.printRulesJSON(*output);
                     *output << "}\n";
                 }
             }
Field Documentation
int souffle::Explain::depthLimit private
Definition at line 215 of file Explain.h.
Referenced by explain().
bool souffle::Explain::json private
flag for outputting in JSON format
Definition at line 221 of file Explain.h.
Referenced by explain().
int souffle::Explain::maxx = 0 private
Definition at line 213 of file Explain.h.
Referenced by explain().
int souffle::Explain::maxy = 0 private
Definition at line 213 of file Explain.h.
Referenced by clearDisplay(), explain(), initialiseWindow(), and parseTuple().
bool souffle::Explain::ncurses private
Definition at line 210 of file Explain.h.
Referenced by explain(), and explain().
std::ostream* souffle::Explain::output private
output stream
Definition at line 218 of file Explain.h.
Referenced by explain(), and ~Explain().
ExplainProvenance& souffle::Explain::prov private
Definition at line 208 of file Explain.h.
Referenced by explain(), and explain().
WINDOW* souffle::Explain::queryWindow = nullptr private
Definition at line 212 of file Explain.h.
WINDOW* souffle::Explain::treePad = nullptr private
Definition at line 211 of file Explain.h.
Referenced by explain().
The documentation for this class was generated from the following file:
Explain.h