souffle: souffle::LVM Class Reference
souffle::LVM Class Reference
Bytecode Interpreter executing a RAM translation unit.
#include <LVM.h>
Public Member Functions
virtual void executeMain ()
Execute the main program.
void executeSubroutine (const std::string &name, const std::vector< RamDomain > &arguments, std::vector< RamDomain > &returnValues, std::vector< bool > &returnErrors)
Execute the subroutine.
LVM (RamTranslationUnit &tUnit)
void printMain ()
Print out the instruction stream.
void resetMainProgram ()
Clean the cache of main Program.
void resetSubroutine (const std::string &name)
Clean the cache of subroutine.
virtual ~LVM ()
Public Member Functions inherited from souffle::Interpreter
RamTranslationUnit & getTranslationUnit ()
Get translation unit.
Interpreter (RamTranslationUnit &tUnit)
virtual ~Interpreter ()
Protected Types
using index_set = btree_multiset< const RamDomain *, InterpreterIndex::comparator, std::allocator< const RamDomain * >, 512 >
Protected Types inherited from souffle::Interpreter
using relation_map = std::map< std::string, InterpreterRelation * >
relation environment type
Protected Member Functions
void dropRelation (const std::string &relName)
Drop relation.
int getCounter ()
Get Counter.
size_t getIterationNumber () const
Get Iteration Number.
InterpreterRelation & getRelation (const std::string &name)
Get relation.
SearchColumns getSearchColumns (const std::string &patterns, size_t arity)
Obtain the search columns.
SymbolTable & getSymbolTable ()
Get symbol table.
int incCounter ()
Increment counter.
void incIterationNumber ()
Increment iteration number.
void insertTimerAt (size_t index, Logger *timer)
Insert Logger.
void * loadDLL ()
load dll
std::pair< InterpreterRelation::iterator, InterpreterRelation::iterator > & lookUpChoiceIterator (size_t idx)
Lookup Choice iterator, resize the iterator pool if necessary.
std::pair< index_set::iterator, index_set::iterator > & lookUpIndexChoiceIterator (size_t idx)
Lookup IndexChoice iterator, resize the iterator pool if necessary.
std::pair< index_set::iterator, index_set::iterator > & lookUpIndexScanIterator (size_t idx)
Lookup IndexScan iterator, resize the iterator pool if necessary.
std::pair< InterpreterRelation::iterator, InterpreterRelation::iterator > & lookUpScanIterator (size_t idx)
Lookup Scan iterator, resize the iterator pool if necessary.
void resetIterationNumber ()
Reset iteration number.
void stopTimerAt (size_t index)
Stop and destroy logger.
void swapRelation (const std::string &ramRel1, const std::string &ramRel2)
Swap relation.
Protected Member Functions inherited from souffle::Interpreter
relation_map & getRelationMap () const
Get relation map.
SymbolTable & getSymbolTable ()
Get symbol table.
Private Member Functions
void execute (std::unique_ptr< LVMCode > &codeStream, InterpreterContext &ctxt, size_t ip=0)
Execute given program.
Private Attributes
std::vector< std::pair< InterpreterRelation::iterator, InterpreterRelation::iterator > > choiceIteratorPool
List of iters for Choice operation.
int counter = 0
counter for $ operator
void * dll = nullptr
Dynamic library for user-defined functors.
std::map< std::string, std::map< size_t, size_t > > frequencies
counters for atom profiling
std::vector< std::pair< index_set::iterator, index_set::iterator > > indexChoiceIteratorPool
List of iters for indexChoice operation.
std::vector< std::pair< index_set::iterator, index_set::iterator > > indexScanIteratorPool
List of iters for indexScan operation.
friend InterpreterProgInterface
size_t iteration = 0
iteration number (in a fix-point calculation)
size_t level = 0
stratum
std::unique_ptr< LVMCode > mainProgram = nullptr
Main program.
std::map< std::string, std::atomic< size_t > > reads
counters for non-existence check
std::vector< std::pair< InterpreterRelation::iterator, InterpreterRelation::iterator > > scanIteratorPool
List of iters for Scan operation.
std::map< std::string, std::unique_ptr< LVMCode > > subroutines
subroutines
std::vector< Logger * > timers
List of loggers for logtimer.
Additional Inherited Members
Protected Attributes inherited from souffle::Interpreter
relation_map environment
Relation Environment.
friend InterpreterProgInterface
RamTranslationUnit & translationUnit
RAM translation Unit.
Detailed Description
Bytecode Interpreter executing a RAM translation unit.
RAM is transferred into an equivalent Bytecode Representation (LVMCode) by LVMGenerator. LVM then directly execute the program by interpreting the LVMCode. The LVMCode will be cached in the memory to save time when repeatedly execution is needed.
Definition at line 53 of file LVM.h.
Member Typedef Documentation
using souffle::LVM::index_set = btree_multiset<const RamDomain*, InterpreterIndex::comparator, std::allocator<const RamDomain*>, 512> protected
Definition at line 103 of file LVM.h.
Constructor & Destructor Documentation
souffle::LVM::LVM (RamTranslationUnit & tUnit) inline
Definition at line 55 of file LVM.h.
 : Interpreter(tUnit) {}
virtual souffle::LVM::~LVM () inline virtual
Definition at line 57 of file LVM.h.
References executeMain().
 {}
Member Function Documentation
void souffle::LVM::dropRelation (const std::string & relName) inline protected
Drop relation.
Definition at line 157 of file LVM.h.
References souffle::Interpreter::environment, and getRelation().
Referenced by execute().
{
         InterpreterRelation& rel = getRelation(relName);
         environment.erase(relName);
         delete &rel;
     }
void souffle::LVM::execute (std::unique_ptr< LVMCode > & codeStream, InterpreterContext & ctxt, size_t ip = 0) private
Execute given program.
Parameters
ip the instruction pointer start position, default is 0.
Does nothing, just a label
Does nothing, just a label
Does nothing, just a label
Does nothing, just a label
Does nothing, just a label
Does nothing, jus a label
Does nothing, just a label
Definition at line 119 of file LVM.cpp.
References souffle::InterpreterContext::addReturnValue(), souffle::InterpreterContext::allocateNewTuple(), arity, souffle::InterpreterRelation::begin(), choiceIteratorPool, souffle::Global::config(), counter, dropRelation(), e, souffle::InterpreterRelation::empty(), souffle::InterpreterRelation::end(), souffle::Interpreter::environment, souffle::InterpreterRelation::exists(), souffle::InterpreterRelation::extend(), frequencies, souffle::InterpreterContext::getArgument(), souffle::InterpreterRelation::getArity(), souffle::InterpreterRelation::getAttributeTypeQualifiers(), souffle::InterpreterRelation::getIndex(), souffle::IOSystem::getInstance(), getIterationNumber(), souffle::IOSystem::getReader(), getRelation(), getSearchColumns(), souffle::IOSystem::getWriter(), high, i, incCounter(), incIterationNumber(), indexChoiceIteratorPool, indexScanIteratorPool, souffle::InterpreterRelation::insert(), insertTimerAt(), souffle::SignalHandler::instance(), souffle::ProfileEventSingleton::instance(), souffle::isNull(), level, lhs, loadDLL(), lookUpChoiceIterator(), lookUpIndexChoiceIterator(), lookUpIndexScanIterator(), lookUpScanIterator(), low, souffle::LVM_Aggregate, souffle::LVM_Aggregate_COUNT, souffle::LVM_Aggregate_Return, souffle::LVM_Argument, souffle::LVM_AutoIncrement, souffle::LVM_Choice, souffle::LVM_Clear, souffle::LVM_Conjunction, souffle::LVM_Constraint, souffle::LVM_Create, souffle::LVM_DebugInfo, souffle::LVM_Drop, souffle::LVM_ElementAccess, souffle::LVM_EmptinessCheck, souffle::LVM_EQREL, souffle::LVM_ExistenceCheck, souffle::LVM_Exit, souffle::LVM_Fact, souffle::LVM_Filter, souffle::LVM_Goto, souffle::LVM_IncIterationNumber, souffle::LVM_IndexAggregate, souffle::LVM_IndexChoice, souffle::LVM_IndexScan, souffle::LVM_ITER_Inc, souffle::LVM_ITER_NotAtEnd, souffle::LVM_ITER_Select, souffle::LVM_ITER_TypeChoice, souffle::LVM_ITER_TypeIndexChoice, souffle::LVM_ITER_TypeIndexScan, souffle::LVM_ITER_TypeScan, souffle::LVM_Jmpez, souffle::LVM_Jmpnz, souffle::LVM_Load, souffle::LVM_LogSize, souffle::LVM_LogTimer, souffle::LVM_Loop, souffle::LVM_Merge, souffle::LVM_Negation, souffle::LVM_Number, souffle::LVM_OP_ADD, souffle::LVM_OP_BAND, souffle::LVM_OP_BNOT, souffle::LVM_OP_BOR, souffle::LVM_OP_BXOR, souffle::LVM_OP_CAT, souffle::LVM_OP_CONTAINS, souffle::LVM_OP_DIV, souffle::LVM_OP_EQ, souffle::LVM_OP_EXP, souffle::LVM_OP_GE, souffle::LVM_OP_GT, souffle::LVM_OP_LAND, souffle::LVM_OP_LE, souffle::LVM_OP_LNOT, souffle::LVM_OP_LOR, souffle::LVM_OP_LT, souffle::LVM_OP_MATCH, souffle::LVM_OP_MAX, souffle::LVM_OP_MIN, souffle::LVM_OP_MOD, souffle::LVM_OP_MUL, souffle::LVM_OP_NE, souffle::LVM_OP_NEG, souffle::LVM_OP_NOT_CONTAINS, souffle::LVM_OP_NOT_MATCH, souffle::LVM_OP_ORD, souffle::LVM_OP_STRLEN, souffle::LVM_OP_SUB, souffle::LVM_OP_SUBSTR, souffle::LVM_OP_TONUMBER, souffle::LVM_OP_TOSTRING, souffle::LVM_PackRecord, souffle::LVM_Parallel, souffle::LVM_Project, souffle::LVM_ProvenanceExistenceCheck, souffle::LVM_Query, souffle::LVM_ResetIterationNumber, souffle::LVM_ReturnValue, souffle::LVM_Scan, souffle::LVM_Search, souffle::LVM_Sequence, souffle::LVM_STOP, souffle::LVM_Stop_Parallel, souffle::LVM_StopLogTimer, souffle::LVM_Store, souffle::LVM_Stratum, souffle::LVM_Swap, souffle::LVM_UnpackRecord, souffle::LVM_UserDefinedOperator, souffle::ProfileEventSingleton::makeQuantityEvent(), souffle::ProfileEventSingleton::makeStratumRecord(), MAX_RAM_DOMAIN, MIN_RAM_DOMAIN, souffle::pack(), reads, relation, resetIterationNumber(), rhs, scanIteratorPool, souffle::InterpreterRelation::setAttributes(), souffle::InterpreterRelation::setLevel(), souffle::SignalHandler::setMsg(), souffle::InterpreterRelation::size(), SOUFFLE_DLL, stopTimerAt(), stord, str, swapRelation(), types, and souffle::unpack().
Referenced by executeMain(), and executeSubroutine().
{
     std::stack<RamDomain> stack;
     const auto& code = codeStream->getCode();
     auto& symbolTable = codeStream->getSymbolTable();
     while (true) {
         switch (code[ip]) {
             case LVM_Number:
                 stack.push(code[ip + 1]);
                 ip += 2;
                 break;
             case LVM_ElementAccess:
                 stack.push(ctxt[code[ip + 1]][code[ip + 2]]);
                 ip += 3;
                 break;
             case LVM_AutoIncrement:
                 stack.push(this->counter);
                 incCounter();
                 ip += 1;
                 break;
             case LVM_OP_ORD:
                 // Does nothing
                 ip += 1;
                 break;
             case LVM_OP_STRLEN: {
                 RamDomain relNameId = stack.top();
                 stack.pop();
                 stack.push(symbolTable.resolve(relNameId).size());
                 ip += 1;
                 break;
             }
             case LVM_OP_NEG: {
                 RamDomain val = stack.top();
                 stack.pop();
                 stack.push(-val);
                 ip += 1;
                 break;
             }
             case LVM_OP_BNOT: {
                 RamDomain val = stack.top();
                 stack.pop();
                 stack.push(~val);
                 ip += 1;
                 break;
             }
             case LVM_OP_LNOT: {
                 RamDomain val = stack.top();
                 stack.pop();
                 stack.push(!val);
                 ip += 1;
                 break;
             }
             case LVM_OP_TONUMBER: {
                 RamDomain val = stack.top();
                 stack.pop();
                 RamDomain result = 0;
                 try {
                     result = stord(symbolTable.resolve(val));
                 } catch (...) {
                     std::cerr << "error: wrong string provided by to_number(\"";
                     std::cerr << symbolTable.resolve(val);
                     std::cerr << "\") functor.\n";
                     raise(SIGFPE);
                 }
                 stack.push(result);
                 ip += 1;
                 break;
             }
             case LVM_OP_TOSTRING: {
                 RamDomain val = stack.top();
                 RamDomain result = symbolTable.lookup(std::to_string(val));
                 stack.pop();
                 stack.push(result);
                 ip += 1;
                 break;
             }
             case LVM_OP_ADD: {
                 RamDomain x = stack.top();
                 stack.pop();
                 RamDomain y = stack.top();
                 stack.pop();
                 stack.push(x + y);
                 ip += 1;
                 break;
             }
             case LVM_OP_SUB: {
                 // Rhs was pushed last in the generator, so it should be on top.
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs - rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_MUL: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs * rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_DIV: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs / rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_EXP: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(std::pow(lhs, rhs));
                 ip += 1;
                 break;
             }
             case LVM_OP_MOD: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs % rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_BAND: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs & rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_BOR: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs | rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_BXOR: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs ^ rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_LAND: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs && rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_LOR: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs || rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_MAX: {
                 size_t size = code[ip + 1];
                 RamDomain val = MIN_RAM_DOMAIN;
                 for (size_t i = 0; i < size; ++i) {
                     val = std::max(val, stack.top());
                     stack.pop();
                 }
                 stack.push(val);
                 ip += 2;
                 break;
             }
             case LVM_OP_MIN: {
                 size_t size = code[ip + 1];
                 RamDomain val = MAX_RAM_DOMAIN;
                 for (size_t i = 0; i < size; ++i) {
                     val = std::min(val, stack.top());
                     stack.pop();
                 }
                 stack.push(val);
                 ip += 2;
                 break;
             }
             case LVM_OP_CAT: {
                 size_t size = code[ip + 1];
                 std::string cat;
                 for (size_t i = 0; i < size; ++i) {
                     cat += symbolTable.resolve(stack.top());
                     stack.pop();
                 }
                 stack.push(symbolTable.lookup(cat));
                 ip += 2;
                 break;
             }
             case LVM_OP_SUBSTR: {
                 RamDomain len = stack.top();
                 stack.pop();
                 RamDomain idx = stack.top();
                 stack.pop();
                 RamDomain symbol = stack.top();
                 stack.pop();
                 std::string str = symbolTable.resolve(symbol);
                 std::string sub_str;
                 try {
                     sub_str = str.substr(idx, len);
                 } catch (...) {
                     std::cerr << "warning: wrong index position provided by substr(\"";
                     std::cerr << str << "\"," << (int32_t)idx << "," << (int32_t)len << ") functor.\n";
                 }
                 stack.push(symbolTable.lookup(sub_str));
                 ip += 1;
                 break;
             }
             case LVM_OP_EQ: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs == rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_NE: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs != rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_LT: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs < rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_LE: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs <= rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_GT: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs > rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_GE: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs >= rhs);
                 ip += 1;
                 break;
             }
             case LVM_OP_MATCH: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 const std::string& pattern = symbolTable.resolve(lhs);
                 const std::string& text = symbolTable.resolve(rhs);
                 bool result = false;
                 try {
                     result = std::regex_match(text, std::regex(pattern));
                 } catch (...) {
                     std::cerr << "warning: wrong pattern provided for match(\"" << pattern << "\",\"" << text
                               << "\").\n";
                 }
                 stack.push(result);
                 ip += 1;
                 break;
             }
             case LVM_OP_NOT_MATCH: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 const std::string& pattern = symbolTable.resolve(lhs);
                 const std::string& text = symbolTable.resolve(rhs);
                 bool result = false;
                 try {
                     result = !std::regex_match(text, std::regex(pattern));
                 } catch (...) {
                     std::cerr << "warning: wrong pattern provided for match(\"" << pattern << "\",\"" << text
                               << "\").\n";
                 }
                 stack.push(result);
                 ip += 1;
                 break;
             }
             case LVM_OP_CONTAINS: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 const std::string& pattern = symbolTable.resolve(lhs);
                 const std::string& text = symbolTable.resolve(rhs);
                 stack.push(text.find(pattern) != std::string::npos);
                 ip += 1;
                 break;
             }
             case LVM_OP_NOT_CONTAINS: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 const std::string& pattern = symbolTable.resolve(lhs);
                 const std::string& text = symbolTable.resolve(rhs);
                 stack.push(text.find(pattern) == std::string::npos);
                 ip += 1;
                 break;
             }
             case LVM_UserDefinedOperator: {
                 // get name and type
                 const std::string name = symbolTable.resolve(code[ip + 1]);
                 const std::string type = symbolTable.resolve(code[ip + 2]);
                 // load DLL (if not done yet)
                 void* handle = this->loadDLL();
                 void (*fn)() = (void (*)())dlsym(handle, name.c_str());
                 if (fn == nullptr) {
                     std::cerr << "Cannot find user-defined operator " << name << " in " << SOUFFLE_DLL
                               << std::endl;
                     exit(1);
                 }
                 size_t arity = type.length();
                 ffi_cif cif;
                 ffi_type* args[arity];
                 void* values[arity];
                 RamDomain intVal[arity];
                 const char* strVal[arity];
                 ffi_arg rc;
                 /* Initialize arguments for ffi-call */
                 for (size_t i = 0; i < arity; i++) {
                     RamDomain arg = stack.top();
                     stack.pop();
                     if (type[arity - i - 1] == 'S') {
                         args[arity - i - 1] = &ffi_type_pointer;
                         strVal[arity - i - 1] = symbolTable.resolve(arg).c_str();
                         values[arity - i - 1] = &strVal[arity - i - 1];
                     } else {
                         args[arity - i - 1] = &ffi_type_uint32;
                         intVal[arity - i - 1] = arg;
                         values[arity - i - 1] = &intVal[arity - i - 1];
                     }
                 }
                 // call external function
                 if (type[arity] == 'N') {
                     // Initialize for numerical return value
                     if (ffi_prep_cif(&cif, FFI_DEFAULT_ABI, arity, &ffi_type_uint32, args) != FFI_OK) {
                         std::cerr << "Failed to prepare CIF for user-defined operator ";
                         std::cerr << name << std::endl;
                         exit(1);
                     }
                 } else {
                     // Initialize for string return value
                     if (ffi_prep_cif(&cif, FFI_DEFAULT_ABI, arity, &ffi_type_pointer, args) != FFI_OK) {
                         std::cerr << "Failed to prepare CIF for user-defined operator ";
                         std::cerr << name << std::endl;
                         exit(1);
                     }
                 }
                 ffi_call(&cif, fn, &rc, values);
                 RamDomain result;
                 if (type[arity] == 'N') {
                     result = ((RamDomain)rc);
                 } else {
                     result = symbolTable.lookup(((const char*)rc));
                 }
                 stack.push(result);
                 ip += 3;
                 break;
             }
             case LVM_PackRecord: {
                 RamDomain arity = code[ip + 1];
                 RamDomain data[arity];
                 for (auto i = 0; i < arity; ++i) {
                     data[arity - i - 1] = stack.top();
                     stack.pop();
                 }
                 stack.push(pack(data, arity));
                 ip += 2;
                 break;
             }
             case LVM_Argument: {
                 stack.push(ctxt.getArgument(code[ip + 1]));
                 ip += 2;
                 break;
             }
             case LVM_Conjunction: {
                 RamDomain rhs = stack.top();
                 stack.pop();
                 RamDomain lhs = stack.top();
                 stack.pop();
                 stack.push(lhs && rhs);
                 ip += 1;
                 break;
             }
             case LVM_Negation: {
                 RamDomain val = stack.top();
                 stack.pop();
                 stack.push(!val);
                 ip += 1;
                 break;
             }
             case LVM_EmptinessCheck: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 stack.push(getRelation(relName).empty());
                 ip += 2;
                 break;
             }
             case LVM_ExistenceCheck: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 std::string patterns = symbolTable.resolve(code[ip + 2]);
                 const InterpreterRelation& rel = getRelation(relName);
                 size_t arity = rel.getArity();
                 if (Global::config().has("profile") && !(relName[0] == '@')) {
                     this->reads[relName]++;
                 }
                 // for total we use the exists test
                 if (patterns.find("_") == std::string::npos) {
                     RamDomain tuple[arity];
                     for (size_t i = 0; i < arity; i++) {
                         tuple[arity - i - 1] = stack.top();
                         stack.pop();
                     }
                     stack.push(rel.exists(tuple));
                     ip += 3;
                     break;
                 } else {  // for partial we search for lower and upper boundaries
                     RamDomain low[arity];
                     RamDomain high[arity];
                     for (size_t i = 0; i < arity; i++) {
                         if (patterns[arity - i - 1] == 'V') {
                             low[arity - i - 1] = stack.top();
                             stack.pop();
                             high[arity - i - 1] = low[arity - i - 1];
                         } else {
                             low[arity - i - 1] = MIN_RAM_DOMAIN;
                             high[arity - i - 1] = MAX_RAM_DOMAIN;
                         }
                     }
                     SearchColumns res = getSearchColumns(patterns, arity);
                     auto idx = rel.getIndex(res);
                     auto range = idx->lowerUpperBound(low, high);
                     stack.push(range.first != range.second);
                     ip += 3;
                     break;
                 }
                 break;
             }
             case LVM_ProvenanceExistenceCheck: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 std::string patterns = symbolTable.resolve(code[ip + 2]);
                 const InterpreterRelation& rel = getRelation(relName);
                 auto arity = rel.getArity();
                 RamDomain low[arity];
                 RamDomain high[arity];
                 for (size_t i = 2; i < arity; i++) {
                     if (patterns[arity - i - 1] == 'V') {
                         low[arity - i - 1] = stack.top();
                         stack.pop();
                         high[arity - i - 1] = low[arity - i - 1];
                     } else {
                         low[arity - i - 1] = MIN_RAM_DOMAIN;
                         low[arity - i - 1] = MAX_RAM_DOMAIN;
                     }
                 }
                 low[arity - 2] = MIN_RAM_DOMAIN;
                 low[arity - 1] = MIN_RAM_DOMAIN;
                 high[arity - 2] = MAX_RAM_DOMAIN;
                 high[arity - 1] = MAX_RAM_DOMAIN;
                 // obtain index
                 SearchColumns res = 0;
                 // values.size() - 1 because we discard the height annotation
                 for (std::size_t i = 0; i < arity - 1; i++) {
                     if (patterns[i] == 'V') {
                         res |= (1 << i);
                     }
                 }
                 auto idx = rel.getIndex(res);
                 auto range = idx->lowerUpperBound(low, high);
                 stack.push(range.first != range.second);
                 ip += 3;
                 break;
             }
             case LVM_Constraint:
                 /** Does nothing, just a label */
                 ip += 1;
                 break;
             case LVM_Scan:
                 /** Does nothing, just a label */
                 ip += 1;
                 break;
             case LVM_IndexScan:
                 /** Does nothing, just a label */
                 ip += 1;
                 break;
             case LVM_Choice:
                 /** Does nothing, just a label */
                 ip += 1;
                 break;
             case LVM_IndexChoice:
                 /** Does nothing, just a label */
                 ip += 1;
                 break;
             case LVM_Search: {
                 if (Global::config().has("profile") && code[ip + 1] != 0) {
                     std::string msg = symbolTable.resolve(code[ip + 2]);
                     this->frequencies[msg][this->getIterationNumber()]++;
                 }
                 ip += 3;
                 break;
             }
             case LVM_UnpackRecord: {
                 RamDomain referenceLevel = code[ip + 1];
                 RamDomain position = code[ip + 2];
                 RamDomain arity = code[ip + 3];
                 RamDomain id = code[ip + 4];
                 RamDomain exitAddress = code[ip + 5];
                 RamDomain ref = ctxt[referenceLevel][position];
                 if (isNull(ref)) {
                     ip = exitAddress;
                     break;
                 }
                 RamDomain* tuple = unpack(ref, arity);
                 ctxt[id] = tuple;
                 ip += 6;
                 break;
             }
             case LVM_Filter:
                 if (Global::config().has("profile")) {
                     std::string msg = symbolTable.resolve(code[ip + 1]);
                     if (!msg.empty()) {
                         this->frequencies[msg][this->getIterationNumber()]++;
                     }
                 }
                 ip += 2;
                 break;
             case LVM_Project: {
                 RamDomain arity = code[ip + 1];
                 std::string relName = symbolTable.resolve(code[ip + 2]);
                 RamDomain tuple[arity];
                 for (auto i = 0; i < arity; ++i) {
                     tuple[arity - i - 1] = stack.top();
                     stack.pop();
                 }
                 InterpreterRelation& rel = getRelation(relName);
                 rel.insert(tuple);
                 ip += 3;
                 break;
             }
             case LVM_ReturnValue: {
                 RamDomain size = code[ip + 1];
                 std::string types = symbolTable.resolve(code[ip + 2]);
                 for (auto i = 0; i < size; ++i) {
                     if (types[size - i - 1] == '_') {
                         ctxt.addReturnValue(0, true);
                     } else {
                         ctxt.addReturnValue(stack.top(), false);
                         stack.pop();
                     }
                 }
                 ip += 3;
                 break;
             }
             case LVM_Sequence: {
                 ip += 1;
                 break;
             }
             case LVM_Parallel: {
                 size_t size = code[ip + 1];
                 size_t end = code[ip + 2];
                 size_t startAddresses[size];
                 for (size_t i = 0; i < size; ++i) {
                     startAddresses[i] = code[ip + 3 + i];
                 }
 #pragma omp parallel for
                 for (size_t i = 0; i < size; ++i) {
                     this->execute(codeStream, ctxt, startAddresses[i]);
                 }
                 ip = end;
                 break;
             }
             case LVM_Stop_Parallel: {
                 ip += 2;
                 break;
             }
             case LVM_Loop: {
                 /** Does nothing, jus a label */
                 ip += 1;
                 break;
             }
             case LVM_IncIterationNumber: {
                 incIterationNumber();
                 ip += 1;
                 break;
             };
             case LVM_ResetIterationNumber: {
                 resetIterationNumber();
                 ip += 1;
                 break;
             };
             case LVM_Exit: {
                 RamDomain val = stack.top();
                 stack.pop();
                 if (val) {
                     ip = code[ip + 1];
                     break;
                 }
                 ip += 2;
                 break;
             }
             case LVM_LogTimer: {
                 std::string msg = symbolTable.resolve(code[ip + 1]);
                 size_t timerIndex = code[ip + 4];
                 Logger* logger;
                 if (code[ip + 2] == 0) {
                     logger = new Logger(msg.c_str(), this->getIterationNumber());
                 } else {
                     std::string relName = symbolTable.resolve(code[ip + 3]);
                     const InterpreterRelation& rel = getRelation(relName);
                     logger = new Logger(msg.c_str(), this->getIterationNumber(),
                             std::bind(&InterpreterRelation::size, &rel));
                 }
                 insertTimerAt(timerIndex, logger);
                 ip += 5;
                 break;
             }
             case LVM_StopLogTimer: {
                 size_t timerIndex = code[ip + 1];
                 stopTimerAt(timerIndex);
                 ip += 2;
                 break;
             }
             case LVM_DebugInfo: {
                 std::string msg = symbolTable.resolve(code[ip + 1]);
                 SignalHandler::instance()->setMsg(msg.c_str());
                 ip += 2;
                 break;
             }
             case LVM_Stratum: {
                 this->level++;
                 // Record all the rleation that is created in the previous level
                 if (Global::config().has("profile") || this->level != 0) {
                     for (const auto& rel : environment) {
                         // Skip if it is a temp rel and select only the relation in the same level
                         if (rel.first[0] == '@' || rel.second->getLevel() != this->level - 1) continue;
                         ProfileEventSingleton::instance().makeStratumRecord(rel.second->getLevel(),
                                 "relation", rel.first, "arity", std::to_string(rel.second->getArity()));
                     }
                 }
                 ip += 1;
                 break;
             }
             case LVM_Create: {
                 InterpreterRelation* res = nullptr;
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 auto arity = code[ip + 2];
                 assert(environment.find(relName) == environment.end());
                 if (code[ip + 3] == LVM_EQREL) {
                     res = new InterpreterEqRelation(arity);
                 } else {
                     res = new InterpreterRelation(arity);
                 }
                 std::vector<std::string> attributeTypes;
                 for (int i = 0; i < code[ip + 2]; ++i) {
                     attributeTypes.push_back(symbolTable.resolve(code[ip + 4 + i]));
                 }
                 attributeTypes.reserve(attributeTypes.size());
                 res->setAttributes(attributeTypes);
                 res->setLevel(level);
                 environment[relName] = res;
                 ip += 3 + code[ip + 2] + 1;
                 break;
             }
             case LVM_Clear: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 auto& rel = getRelation(relName);
                 rel.purge();
                 ip += 2;
                 break;
             }
             case LVM_Drop: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 dropRelation(relName);
                 ip += 2;
                 break;
             }
             case LVM_LogSize: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 const InterpreterRelation& rel = getRelation(relName);
                 std::string msg = symbolTable.resolve(code[ip + 2]);
                 ProfileEventSingleton::instance().makeQuantityEvent(
                         msg, rel.size(), this->getIterationNumber());
                 ip += 3;
                 break;
             }
             case LVM_Load: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 auto IOs = codeStream->getIODirectives()[code[ip + 2]];
                 for (auto& io : IOs) {
                     try {
                         InterpreterRelation& relation = getRelation(relName);
                         std::vector<bool> symbolMask;
                         for (auto& cur : relation.getAttributeTypeQualifiers()) {
                             symbolMask.push_back(cur[0] == 's');
                         }
                         IOSystem::getInstance()
                                 .getReader(symbolMask, symbolTable, io, Global::config().has("provenance"))
                                 ->readAll(relation);
                     } catch (std::exception& e) {
                         std::cerr << "Error loading data: " << e.what() << "\n";
                     }
                 }
                 ip += 3;
                 break;
             }
             case LVM_Store: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 auto IOs = codeStream->getIODirectives()[code[ip + 2]];
                 for (auto& io : IOs) {
                     try {
                         InterpreterRelation& relation = getRelation(relName);
                         std::vector<bool> symbolMask;
                         for (auto& cur : relation.getAttributeTypeQualifiers()) {
                             symbolMask.push_back(cur[0] == 's');
                         }
                         IOSystem::getInstance()
                                 .getWriter(symbolMask, symbolTable, io, Global::config().has("provenance"))
                                 ->writeAll(relation);
                     } catch (std::exception& e) {
                         std::cerr << "Error Storing data: " << e.what() << "\n";
                     }
                 }
                 ip += 3;
                 break;
             }
             case LVM_Fact: {
                 std::string relName = symbolTable.resolve(code[ip + 1]);
                 auto arity = code[ip + 2];
                 RamDomain tuple[arity];
                 for (auto i = 0; i < arity; ++i) {
                     tuple[arity - i - 1] = stack.top();
                     stack.pop();
                 }
                 getRelation(relName).insert(tuple);
                 ip += 3;
                 break;
             }
             case LVM_Merge: {
                 std::string source = symbolTable.resolve(code[ip + 1]);
                 std::string target = symbolTable.resolve(code[ip + 2]);
                 // get involved relation
                 InterpreterRelation& src = getRelation(source);
                 InterpreterRelation& trg = getRelation(target);
                 if (dynamic_cast<InterpreterEqRelation*>(&trg)) {
                     // expand src with the new knowledge generated by insertion.
                     src.extend(trg);
                 }
                 // merge in all elements
                 trg.insert(src);
                 ip += 3;
                 break;
             }
             case LVM_Swap: {
                 std::string firstRel = symbolTable.resolve(code[ip + 1]);
                 std::string secondRel = symbolTable.resolve(code[ip + 2]);
                 swapRelation(firstRel, secondRel);
                 ip += 3;
                 break;
             }
             case LVM_Query:
                 /** Does nothing, just a label */
                 ip += 1;
                 break;
             case LVM_Goto:
                 ip = code[ip + 1];
                 break;
             case LVM_Jmpnz: {
                 RamDomain val = stack.top();
                 stack.pop();
                 ip = (val != 0 ? code[ip + 1] : ip + 2);
                 break;
             }
             case LVM_Jmpez: {
                 RamDomain val = stack.top();
                 stack.pop();
                 ip = (val == 0 ? code[ip + 1] : ip + 2);
                 break;
             }
             case LVM_Aggregate: {
                 ip += 1;
                 break;
             };
             case LVM_IndexAggregate: {
                 ip += 1;
                 break;
             };
             case LVM_Aggregate_COUNT: {
                 RamDomain res = 0;
                 RamDomain idx = code[ip + 2];
                 if (code[ip + 1] == LVM_ITER_TypeScan) {
                     auto& iters = scanIteratorPool[idx];
                     for (auto i = iters.first; i != iters.second; ++i) {
                         res++;
                     }
                     stack.push(res);
                 } else {
                     auto& iters = indexScanIteratorPool[idx];
                     for (auto i = iters.first; i != iters.second; ++i) {
                         res++;
                     }
                     stack.push(res);
                 }
                 ip += 3;
                 break;
             };
             case LVM_Aggregate_Return: {
                 RamDomain id = code[ip + 1];
                 RamDomain res = stack.top();
                 stack.pop();
                 RamDomain* tuple = ctxt.allocateNewTuple(1);
                 tuple[0] = res;
                 ctxt[id] = tuple;
                 ip += 2;
                 break;
             };
             case LVM_ITER_TypeScan: {
                 RamDomain idx = code[ip + 1];
                 std::string relName = symbolTable.resolve(code[ip + 2]);
                 InterpreterRelation& rel = getRelation(relName);
                 lookUpScanIterator(idx) =
                         std::pair<InterpreterRelation::iterator, InterpreterRelation::iterator>(
                                 rel.begin(), rel.end());
                 assert(rel.begin() != rel.end() || rel.empty());
                 ip += 3;
                 break;
             }
             case LVM_ITER_TypeChoice: {
                 RamDomain idx = code[ip + 1];
                 std::string relName = symbolTable.resolve(code[ip + 2]);
                 InterpreterRelation& rel = getRelation(relName);
                 lookUpChoiceIterator(idx) =
                         std::pair<InterpreterRelation::iterator, InterpreterRelation::iterator>(
                                 rel.begin(), rel.end());
                 assert(rel.begin() != rel.end() || rel.empty());
                 ip += 3;
                 break;
             }
             case LVM_ITER_TypeIndexScan: {
                 RamDomain idx = code[ip + 1];
                 std::string relName = symbolTable.resolve(code[ip + 2]);
                 InterpreterRelation& rel = getRelation(relName);
                 std::string pattern = symbolTable.resolve(code[ip + 3]);
                 // create pattern tuple for range query
                 auto arity = rel.getArity();
                 RamDomain low[arity];
                 RamDomain hig[arity];
                 for (size_t i = 0; i < arity; i++) {
                     if (pattern[arity - i - 1] == 'V') {
                         low[arity - i - 1] = stack.top();
                         stack.pop();
                         hig[arity - i - 1] = low[arity - i - 1];
                     } else {
                         low[arity - i - 1] = MIN_RAM_DOMAIN;
                         hig[arity - i - 1] = MAX_RAM_DOMAIN;
                     }
                 }
                 SearchColumns keys = getSearchColumns(pattern, arity);
                 auto index = rel.getIndex(keys);
                 // get iterator range
                 lookUpIndexScanIterator(idx) = index->lowerUpperBound(low, hig);
                 ip += 4;
                 break;
             }
             case LVM_ITER_TypeIndexChoice: {
                 RamDomain idx = code[ip + 1];
                 std::string relName = symbolTable.resolve(code[ip + 2]);
                 InterpreterRelation& rel = getRelation(relName);
                 std::string pattern = symbolTable.resolve(code[ip + 3]);
                 // create pattern tuple for range query
                 auto arity = rel.getArity();
                 RamDomain low[arity];
                 RamDomain hig[arity];
                 for (size_t i = 0; i < arity; i++) {
                     if (pattern[arity - i - 1] == 'V') {
                         low[arity - i - 1] = stack.top();
                         stack.pop();
                         hig[arity - i - 1] = low[arity - i - 1];
                     } else {
                         low[arity - i - 1] = MIN_RAM_DOMAIN;
                         hig[arity - i - 1] = MAX_RAM_DOMAIN;
                     }
                 }
                 SearchColumns keys = getSearchColumns(pattern, arity);
                 auto index = rel.getIndex(keys);
                 // get iterator range
                 lookUpIndexChoiceIterator(idx) = index->lowerUpperBound(low, hig);
                 ip += 4;
                 break;
             }
             case LVM_ITER_NotAtEnd: {
                 RamDomain idx = code[ip + 1];
                 switch (code[ip + 2]) {
                     case LVM_ITER_TypeScan: {
                         auto iter = scanIteratorPool[idx];
                         stack.push(iter.first != iter.second);
                         break;
                     }
                     case LVM_ITER_TypeIndexScan: {
                         auto iter = indexScanIteratorPool[idx];
                         stack.push(iter.first != iter.second);
                         break;
                     }
                     case LVM_ITER_TypeChoice: {
                         auto iter = choiceIteratorPool[idx];
                         stack.push(iter.first != iter.second);
                         break;
                     }
                     case LVM_ITER_TypeIndexChoice: {
                         auto iter = indexChoiceIteratorPool[idx];
                         stack.push(iter.first != iter.second);
                         break;
                     }
                     default:
                         printf("Unknown iter type at LVM_ITER_NotAtEnd\n");
                         break;
                 }
                 ip += 3;
                 break;
             }
             case LVM_ITER_Select: {
                 RamDomain idx = code[ip + 1];
                 RamDomain id = code[ip + 3];
                 switch (code[ip + 2]) {
                     case LVM_ITER_TypeScan: {
                         auto iter = scanIteratorPool[idx];
                         ctxt[id] = *iter.first;
                         break;
                     }
                     case LVM_ITER_TypeIndexScan: {
                         auto iter = indexScanIteratorPool[idx];
                         ctxt[id] = *iter.first;
                         break;
                     }
                     case LVM_ITER_TypeChoice: {
                         auto iter = choiceIteratorPool[idx];
                         ctxt[id] = *iter.first;
                         break;
                     }
                     case LVM_ITER_TypeIndexChoice: {
                         auto iter = indexChoiceIteratorPool[idx];
                         ctxt[id] = *iter.first;
                         break;
                     }
                     default:
                         printf("Unknown iter type at LVM_ITER_Select\n");
                         break;
                 }
                 ip += 4;
                 break;
             }
             case LVM_ITER_Inc: {
                 RamDomain idx = code[ip + 1];
                 switch (code[ip + 2]) {
                     case LVM_ITER_TypeScan: {
                         ++scanIteratorPool[idx].first;
                         break;
                     }
                     case LVM_ITER_TypeIndexScan: {
                         ++indexScanIteratorPool[idx].first;
                         break;
                     }
                     case LVM_ITER_TypeChoice: {
                         ++choiceIteratorPool[idx].first;
                         break;
                     }
                     case LVM_ITER_TypeIndexChoice: {
                         ++indexChoiceIteratorPool[idx].first;
                         break;
                     }
                     default:
                         printf("Unknown iter\n");
                         break;
                 }
                 ip += 3;
                 break;
             }
             case LVM_STOP:
                 assert(stack.size() == 0);
                 return;
             default:
                 printf("Unknown. eval()\n");
                 break;
         }
     }
 }
void souffle::LVM::executeMain () virtual
Execute the main program.
Implements souffle::Interpreter.
Definition at line 60 of file LVM.cpp.
References souffle::Global::config(), souffle::SignalHandler::enableLogging(), execute(), frequencies, souffle::RamProgram::getMain(), souffle::RamRelation::getName(), souffle::RamNestedOperation::getProfileText(), souffle::RamTranslationUnit::getProgram(), souffle::RamRelationStatement::getRelation(), souffle::RamTranslationUnit::getSymbolTable(), souffle::SignalHandler::instance(), souffle::ProfileEventSingleton::instance(), souffle::main(), mainProgram, souffle::ProfileEventSingleton::makeConfigRecord(), souffle::ProfileEventSingleton::makeQuantityEvent(), souffle::ProfileEventSingleton::makeTimeEvent(), reads, souffle::SignalHandler::reset(), rule, souffle::SignalHandler::set(), souffle::ProfileEventSingleton::setOutputFile(), souffle::ProfileEventSingleton::startTimer(), souffle::ProfileEventSingleton::stopTimer(), souffle::Interpreter::translationUnit, and souffle::visitDepthFirst().
Referenced by ~LVM().
                       {
     const RamStatement& main = *translationUnit.getProgram()->getMain();
     if (mainProgram.get() == nullptr) {
         LVMGenerator generator(translationUnit.getSymbolTable(), main);
         mainProgram = generator.getCodeStream();
     }
     InterpreterContext ctxt;
     SignalHandler::instance()->set();
     if (Global::config().has("verbose")) {
         SignalHandler::instance()->enableLogging();
     }
     if (!Global::config().has("profile")) {
         execute(mainProgram, ctxt);
     } else {
         ProfileEventSingleton::instance().setOutputFile(Global::config().get("profile"));
         // Prepare the frequency table for threaded use
         visitDepthFirst(main, [&](const RamSearch& node) {
             if (!node.getProfileText().empty()) {
                 frequencies.emplace(node.getProfileText(), std::map<size_t, size_t>());
             }
         });
         // Enable profiling for execution of main
         ProfileEventSingleton::instance().startTimer();
         ProfileEventSingleton::instance().makeTimeEvent("@time;starttime");
         // Store configuration
         for (const auto& cur : Global::config().data()) {
             ProfileEventSingleton::instance().makeConfigRecord(cur.first, cur.second);
         }
         // Store count of relations
         size_t relationCount = 0;
         visitDepthFirst(main, [&](const RamCreate& create) {
             if (create.getRelation().getName()[0] != '@') {
                 ++relationCount;
                 reads[create.getRelation().getName()] = 0;
             }
         });
         ProfileEventSingleton::instance().makeConfigRecord("relationCount", std::to_string(relationCount));
         // Store count of rules
         size_t ruleCount = 0;
         visitDepthFirst(main, [&](const RamQuery& rule) { ++ruleCount; });
         ProfileEventSingleton::instance().makeConfigRecord("ruleCount", std::to_string(ruleCount));
         execute(mainProgram, ctxt);
         ProfileEventSingleton::instance().stopTimer();
         for (auto const& cur : frequencies) {
             for (auto const& iter : cur.second) {
                 ProfileEventSingleton::instance().makeQuantityEvent(cur.first, iter.second, iter.first);
             }
         }
         for (auto const& cur : reads) {
             ProfileEventSingleton::instance().makeQuantityEvent(
                     "@relation-reads;" + cur.first, cur.second, 0);
         }
     }
     SignalHandler::instance()->reset();
 }
void souffle::LVM::executeSubroutine (const std::string & name, const std::vector< RamDomain > & arguments, std::vector< RamDomain > & returnValues, std::vector< bool > & returnErrors) inline virtual
Execute the subroutine.
Implements souffle::Interpreter.
Definition at line 73 of file LVM.h.
References execute(), souffle::RamTranslationUnit::getProgram(), souffle::RamProgram::getSubroutine(), souffle::RamTranslationUnit::getSymbolTable(), souffle::InterpreterContext::setArguments(), souffle::InterpreterContext::setReturnErrors(), souffle::InterpreterContext::setReturnValues(), subroutines, and souffle::Interpreter::translationUnit.
{
         InterpreterContext ctxt;
         ctxt.setReturnValues(returnValues);
         ctxt.setReturnErrors(returnErrors);
         ctxt.setArguments(arguments);
         if (subroutines.find(name) != subroutines.cend()) {
             execute(subroutines.at(name), ctxt);
         } else {
             // Parse and cache the program
             LVMGenerator generator(
                     translationUnit.getSymbolTable(), translationUnit.getProgram()->getSubroutine(name));
             subroutines.emplace(std::make_pair(name, generator.getCodeStream()));
             execute(subroutines.at(name), ctxt);
         }
     }
int souffle::LVM::getCounter () inline protected
Get Counter.
Definition at line 125 of file LVM.h.
References counter.
                      {
         return counter;
     }
size_t souffle::LVM::getIterationNumber () const inline protected
Get Iteration Number.
Definition at line 140 of file LVM.h.
References iteration.
Referenced by execute().
{
         return iteration;
     }
InterpreterRelation& souffle::LVM::getRelation (const std::string & name) inline protected
Get relation.
Definition at line 149 of file LVM.h.
References souffle::Interpreter::environment.
Referenced by dropRelation(), execute(), and swapRelation().
{
         // look up relation
         auto pos = environment.find(name);
         assert(pos != environment.end());
         return *pos->second;
     }
SearchColumns souffle::LVM::getSearchColumns (const std::string & patterns, size_t arity) inline protected
Obtain the search columns.
Definition at line 219 of file LVM.h.
References arity, and i.
Referenced by execute().
{
         SearchColumns res = 0;
         for (size_t i = 0; i < arity; ++i) {
             if (patterns[i] == 'V') {
                 res |= (1 << i);
             }
         }
         return res;
     }
SymbolTable& souffle::LVM::getSymbolTable () inline protected
Get symbol table.
Definition at line 120 of file LVM.h.
References souffle::RamTranslationUnit::getSymbolTable(), and souffle::Interpreter::translationUnit.
{
         return translationUnit.getSymbolTable();
     }
int souffle::LVM::incCounter () inline protected
Increment counter.
Definition at line 130 of file LVM.h.
References counter.
Referenced by execute().
                      {
         return counter++;
     }
void souffle::LVM::incIterationNumber () inline protected
Increment iteration number.
Definition at line 135 of file LVM.h.
References iteration.
Referenced by execute().
{
         iteration++;
     }
void souffle::LVM::insertTimerAt (size_t index, Logger * timer) inline protected
Insert Logger.
Definition at line 106 of file LVM.h.
References timers.
Referenced by execute().
{
         if (index >= timers.size()) {
             timers.resize((index + 1), nullptr);
         }
         timers[index] = timer;
     }
void* souffle::LVM::loadDLL () inline protected
load dll
Definition at line 172 of file LVM.h.
References dll, and SOUFFLE_DLL.
Referenced by execute().
                     {
         if (dll == nullptr) {
             // check environment variable
             std::string fname = SOUFFLE_DLL;
             dll = dlopen(SOUFFLE_DLL, RTLD_LAZY);
             if (dll == nullptr) {
                 std::cerr << "Cannot find Souffle's DLL" << std::endl;
                 exit(1);
             }
         }
         return dll;
     }
std::pair<InterpreterRelation::iterator, InterpreterRelation::iterator>& souffle::LVM::lookUpChoiceIterator (size_t idx) inline protected
Lookup Choice iterator, resize the iterator pool if necessary.
Definition at line 202 of file LVM.h.
References choiceIteratorPool.
Referenced by execute().
{
         if (idx >= choiceIteratorPool.size()) {
             choiceIteratorPool.resize(idx + 1);
         }
         return choiceIteratorPool[idx];
     }
std::pair<index_set::iterator, index_set::iterator>& souffle::LVM::lookUpIndexChoiceIterator (size_t idx) inline protected
Lookup IndexChoice iterator, resize the iterator pool if necessary.
Definition at line 211 of file LVM.h.
References indexChoiceIteratorPool.
Referenced by execute().
{
         if (idx >= indexChoiceIteratorPool.size()) {
             indexChoiceIteratorPool.resize(idx + 1);
         }
         return indexChoiceIteratorPool[idx];
     }
std::pair<index_set::iterator, index_set::iterator>& souffle::LVM::lookUpIndexScanIterator (size_t idx) inline protected
Lookup IndexScan iterator, resize the iterator pool if necessary.
Definition at line 186 of file LVM.h.
References indexScanIteratorPool.
Referenced by execute().
{
         if (idx >= indexScanIteratorPool.size()) {
             indexScanIteratorPool.resize(idx + 1);
         }
         return indexScanIteratorPool[idx];
     }
std::pair<InterpreterRelation::iterator, InterpreterRelation::iterator>& souffle::LVM::lookUpScanIterator (size_t idx) inline protected
Lookup Scan iterator, resize the iterator pool if necessary.
Definition at line 194 of file LVM.h.
References scanIteratorPool.
Referenced by execute().
{
         if (idx >= scanIteratorPool.size()) {
             scanIteratorPool.resize(idx + 1);
         }
         return scanIteratorPool[idx];
     }
void souffle::LVM::printMain () inline
Print out the instruction stream.
Definition at line 92 of file LVM.h.
References souffle::RamProgram::getMain(), souffle::RamTranslationUnit::getProgram(), souffle::RamTranslationUnit::getSymbolTable(), mainProgram, and souffle::Interpreter::translationUnit.
                      {
         if (mainProgram.get() == nullptr) {
             LVMGenerator generator(
                     translationUnit.getSymbolTable(), *translationUnit.getProgram()->getMain());
             mainProgram = generator.getCodeStream();
         }
         mainProgram->print();
     }
void souffle::LVM::resetIterationNumber () inline protected
Reset iteration number.
Definition at line 144 of file LVM.h.
References iteration.
Referenced by execute().
{
         iteration = 0;
     }
void souffle::LVM::resetMainProgram () inline
Clean the cache of main Program.
Definition at line 63 of file LVM.h.
References mainProgram.
{
         mainProgram.reset();
     }
void souffle::LVM::resetSubroutine (const std::string & name) inline
Clean the cache of subroutine.
Definition at line 68 of file LVM.h.
References subroutines.
{
         subroutines.erase(name);
     }
void souffle::LVM::stopTimerAt (size_t index) inline protected
Stop and destroy logger.
Definition at line 114 of file LVM.h.
References timers.
Referenced by execute().
{
         assert(index < timers.size());
         timers[index]->~Logger();
     }
void souffle::LVM::swapRelation (const std::string & ramRel1, const std::string & ramRel2) inline protected
Swap relation.
Definition at line 164 of file LVM.h.
References souffle::Interpreter::environment, and getRelation().
Referenced by execute().
{
         InterpreterRelation* rel1 = &getRelation(ramRel1);
         InterpreterRelation* rel2 = &getRelation(ramRel2);
         environment[ramRel1] = rel2;
         environment[ramRel2] = rel1;
     }
Field Documentation
std::vector<std::pair<InterpreterRelation::iterator, InterpreterRelation::iterator> > souffle::LVM::choiceIteratorPool private
List of iters for Choice operation.
Definition at line 260 of file LVM.h.
Referenced by execute(), and lookUpChoiceIterator().
int souffle::LVM::counter = 0 private
counter for $ operator
Definition at line 269 of file LVM.h.
Referenced by execute(), getCounter(), and incCounter().
void* souffle::LVM::dll = nullptr private
Dynamic library for user-defined functors.
Definition at line 275 of file LVM.h.
Referenced by loadDLL().
std::map<std::string, std::map<size_t, size_t> > souffle::LVM::frequencies private
counters for atom profiling
Definition at line 245 of file LVM.h.
Referenced by execute(), and executeMain().
std::vector<std::pair<index_set::iterator, index_set::iterator> > souffle::LVM::indexChoiceIteratorPool private
List of iters for indexChoice operation.
Definition at line 257 of file LVM.h.
Referenced by execute(), and lookUpIndexChoiceIterator().
std::vector<std::pair<index_set::iterator, index_set::iterator> > souffle::LVM::indexScanIteratorPool private
List of iters for indexScan operation.
Definition at line 251 of file LVM.h.
Referenced by execute(), and lookUpIndexScanIterator().
friend souffle::LVM::InterpreterProgInterface private
Definition at line 230 of file LVM.h.
size_t souffle::LVM::iteration = 0 private
iteration number (in a fix-point calculation)
Definition at line 272 of file LVM.h.
Referenced by getIterationNumber(), incIterationNumber(), and resetIterationNumber().
size_t souffle::LVM::level = 0 private
stratum
Definition at line 263 of file LVM.h.
Referenced by execute().
std::unique_ptr<LVMCode> souffle::LVM::mainProgram = nullptr private
Main program.
Definition at line 242 of file LVM.h.
Referenced by executeMain(), printMain(), and resetMainProgram().
std::map<std::string, std::atomic<size_t> > souffle::LVM::reads private
counters for non-existence check
Definition at line 248 of file LVM.h.
Referenced by execute(), and executeMain().
std::vector<std::pair<InterpreterRelation::iterator, InterpreterRelation::iterator> > souffle::LVM::scanIteratorPool private
List of iters for Scan operation.
Definition at line 254 of file LVM.h.
Referenced by execute(), and lookUpScanIterator().
std::map<std::string, std::unique_ptr<LVMCode> > souffle::LVM::subroutines private
subroutines
Definition at line 239 of file LVM.h.
Referenced by executeSubroutine(), and resetSubroutine().
std::vector<Logger*> souffle::LVM::timers private
List of loggers for logtimer.
Definition at line 266 of file LVM.h.
Referenced by insertTimerAt(), and stopTimerAt().
The documentation for this class was generated from the following files:
LVM.h
LVM.cpp