souffle: souffle::DebugReporter Class Reference
souffle::DebugReporter Class Reference
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
#include <DebugReport.h>
Public Member Functions
DebugReporter (std::unique_ptr< AstTransformer > wrappedTransformer)
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::MetaTransformer
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static void generateDebugReport (AstTranslationUnit &translationUnit, const std::string &id, std::string title)
Generate a debug report section for the current state of the given translation unit with the given id and title, and add the section to the translation unit's debug report.
static DebugReportSection getCodeSection (const std::string &id, std::string title, std::string code)
Generate a debug report section for code (preserving formatting), with the given id and title.
static DebugReportSection getDotGraphSection (const std::string &id, std::string title, const std::string &dotSpec)
Generated a debug report section for a dot graph specification, with the given id and title.
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Private Attributes
std::unique_ptr< AstTransformer > wrappedTransformer
Additional Inherited Members
Protected Attributes inherited from souffle::MetaTransformer
bool verbose = false
Detailed Description
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
Definition at line 121 of file DebugReport.h.
Constructor & Destructor Documentation
souffle::DebugReporter::DebugReporter (std::unique_ptr< AstTransformer > wrappedTransformer) inline
Definition at line 123 of file DebugReport.h.
             : wrappedTransformer(std::move(wrappedTransformer)) {}
Member Function Documentation
void souffle::DebugReporter::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 135 of file DebugReport.h.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(wrappedTransformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(wrappedTransformer->getName()) != transforms.end()) {
             wrappedTransformer = std::unique_ptr<AstTransformer>(new NullTransformer());
         }
     }
void souffle::DebugReporter::generateDebugReport (AstTranslationUnit & translationUnit, const std::string & id, std::string title) static
Generate a debug report section for the current state of the given translation unit with the given id and title, and add the section to the translation unit's debug report.
Parameters
translationUnit translation unit to generate and add debug report section
id the unique id of the generated section
title the text to display as the heading of the section
Definition at line 214 of file DebugReport.cpp.
References souffle::DebugReport::addSection(), souffle::DebugReportSection::DebugReportSection(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getDebugReport(), souffle::AstTranslationUnit::getProgram(), and souffle::AstProgram::print().
Referenced by souffle::main(), souffle::toBddbddb(), and souffle::toLogicblox().
{
     std::stringstream datalogSpec;
     translationUnit.getProgram()->print(datalogSpec);
     DebugReportSection datalogSection = getCodeSection(id + "-dl", "Datalog", datalogSpec.str());
     std::stringstream typeAnalysis;
     translationUnit.getAnalysis<TypeAnalysis>()->print(typeAnalysis);
     DebugReportSection typeAnalysisSection = getCodeSection(id + "-ta", "Type Analysis", typeAnalysis.str());
     std::stringstream typeEnvironmentAnalysis;
     translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->print(typeEnvironmentAnalysis);
     DebugReportSection typeEnvironmentAnalysisSection =
             getCodeSection(id + "-tea", "Type Environment Analysis", typeEnvironmentAnalysis.str());
     std::stringstream precGraphDot;
     translationUnit.getAnalysis<PrecedenceGraph>()->print(precGraphDot);
     DebugReportSection precedenceGraphSection =
             getDotGraphSection(id + "-prec-graph", "Precedence Graph", precGraphDot.str());
     std::stringstream sccGraphDot;
     translationUnit.getAnalysis<SCCGraph>()->print(sccGraphDot);
     DebugReportSection sccGraphSection =
             getDotGraphSection(id + "-scc-graph", "SCC Graph", sccGraphDot.str());
     std::stringstream topsortSCCGraph;
     translationUnit.getAnalysis<TopologicallySortedSCCGraph>()->print(topsortSCCGraph);
     DebugReportSection topsortSCCGraphSection =
             getCodeSection(id + "-topsort-scc-graph", "SCC Topological Sort Order", topsortSCCGraph.str());
     translationUnit.getDebugReport().addSection(DebugReportSection(id, std::move(title),
             {datalogSection, typeAnalysisSection, typeEnvironmentAnalysisSection, precedenceGraphSection,
                     sccGraphSection, topsortSCCGraphSection},
             ""));
 }
DebugReportSection souffle::DebugReporter::getCodeSection (const std::string & id, std::string title, std::string code) static
Generate a debug report section for code (preserving formatting), with the given id and title.
Definition at line 153 of file DebugReport.cpp.
References souffle::DebugReportSection::DebugReportSection(), and i.
Referenced by souffle::main(), and souffle::AstTranslator::translateUnit().
{
     std::stringstream codeHTML;
     std::string escapedCode = std::move(code);
     while (true) {
         size_t i = escapedCode.find("<");
         if (i == std::string::npos) {
             break;
         }
         escapedCode.replace(i, 1, "&lt;");
     }
     codeHTML << "<pre>" << escapedCode << "</pre>\n";
     return DebugReportSection(id, std::move(title), {}, codeHTML.str());
 }
DebugReportSection souffle::DebugReporter::getDotGraphSection (const std::string & id, std::string title, const std::string & dotSpec) static
Generated a debug report section for a dot graph specification, with the given id and title.
Definition at line 167 of file DebugReport.cpp.
References souffle::DebugReportSection::DebugReportSection(), and souffle::toBase64().
{
     std::stringstream cmd;
     cmd << "dot -Tsvg <<END_DOT_FILE\n";
     cmd << dotSpec << "\n";
     cmd << "END_DOT_FILE\n";
     FILE* in = popen(cmd.str().c_str(), "r");
     std::stringstream data;
     while (true) {
         char c = fgetc(in);
         if (feof(in)) {
             break;
         }
         data << c;
     }
     pclose(in);
     std::stringstream graphHTML;
     if (data.str().find("<svg") != std::string::npos) {
         graphHTML << "<img alt='graph image' src='data:image/svg+xml;base64," << toBase64(data.str())
                   << "'><br/>\n";
     } else {
         graphHTML << "<p>(error: unable to generate dot graph image)</p>";
     }
     graphHTML << "<a href=\"javascript:toggleVisibility('" << id << "-source"
               << "')\">(show dot source)</a>\n";
     graphHTML << "<div id='" << id << "-source"
               << "' style='display:none'>\n";
     graphHTML << "<pre>" << dotSpec << "</pre>\n";
     graphHTML << "</div>\n";
     return DebugReportSection(id, std::move(title), {}, graphHTML.str());
 }
std::string souffle::DebugReporter::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 143 of file DebugReport.h.
References souffle::DebugReportSection::title.
{
         return "DebugReporter";
     }
void souffle::DebugReporter::setDebugReport () inline override virtual
Implements souffle::MetaTransformer.
Definition at line 126 of file DebugReport.h.
 {}
void souffle::DebugReporter::setVerbosity (bool verbose) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 128 of file DebugReport.h.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(wrappedTransformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
bool souffle::DebugReporter::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 199 of file DebugReport.cpp.
References souffle::DebugReport::addSection(), souffle::DebugReportSection::DebugReportSection(), souffle::AstTranslationUnit::getDebugReport(), and souffle::now().
{
     auto start = std::chrono::high_resolution_clock::now();
     bool changed = applySubtransformer(translationUnit, wrappedTransformer.get());
     auto end = std::chrono::high_resolution_clock::now();
     std::string runtimeStr = "(" + std::to_string(std::chrono::duration<double>(end - start).count()) + "s)";
     if (changed) {
         generateDebugReport(translationUnit, wrappedTransformer->getName(),
                 "After " + wrappedTransformer->getName() + " " + runtimeStr);
     } else {
         translationUnit.getDebugReport().addSection(DebugReportSection(wrappedTransformer->getName(),
                 "After " + wrappedTransformer->getName() + " " + runtimeStr + " (unchanged)", {}, ""));
     }
     return changed;
 }
Field Documentation
std::unique_ptr<AstTransformer> souffle::DebugReporter::wrappedTransformer private
Definition at line 169 of file DebugReport.h.
The documentation for this class was generated from the following files:
DebugReport.h
DebugReport.cpp