souffle: souffle::SynthesiserBrieRelation Class Reference
souffle::SynthesiserBrieRelation Class Reference
#include <SynthesiserRelation.h>
Public Member Functions
void computeIndices () override
Generate index set for a brie relation.
void generateTypeStruct (std::ostream &out) override
Generate type struct of a brie relation.
std::string getTypeName () override
Generate type name of a brie relation.
SynthesiserBrieRelation (const RamRelation &ramRel, const IndexSet &indexSet, bool isProvenance)
Public Member Functions inherited from souffle::SynthesiserRelation
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
const IndexSet & getIndexSet () const
Get stored IndexSet.
std::vector< std::vector< int > > getIndices () const
Get list of indices used for relation, guaranteed that original indices in IndexSet come before any generated indices.
const RamRelation & getRamRelation () const
Get stored RamRelation.
SynthesiserRelation (const RamRelation &rel, const IndexSet &indices, const bool isProvenance=false)
virtual ~SynthesiserRelation ()=default
Additional Inherited Members
Static Public Member Functions inherited from souffle::SynthesiserRelation
static std::unique_ptr< SynthesiserRelation > getSynthesiserRelation (const RamRelation &ramRel, const IndexSet &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes inherited from souffle::SynthesiserRelation
std::vector< IndexSet::LexicographicalOrder > computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const IndexSet & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
const RamRelation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 118 of file SynthesiserRelation.h.
Constructor & Destructor Documentation
souffle::SynthesiserBrieRelation::SynthesiserBrieRelation (const RamRelation & ramRel, const IndexSet & indexSet, bool isProvenance) inline
Definition at line 120 of file SynthesiserRelation.h.
References souffle::SynthesiserRelation::computeIndices(), souffle::SynthesiserRelation::generateTypeStruct(), and souffle::SynthesiserRelation::getTypeName().
             : SynthesiserRelation(ramRel, indexSet, isProvenance) {}
Member Function Documentation
void souffle::SynthesiserBrieRelation::computeIndices () override virtual
Generate index set for a brie relation.
Implements souffle::SynthesiserRelation.
Definition at line 689 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::computedIndices, souffle::IndexSet::getAllOrders(), souffle::SynthesiserRelation::getArity(), i, souffle::SynthesiserRelation::indices, souffle::SynthesiserRelation::isProvenance, and souffle::SynthesiserRelation::masterIndex.
{
     assert(!isProvenance && "bries cannot be used with provenance");
     // Generate and set indices
     std::vector<std::vector<int>> inds = indices.getAllOrders();
     // generate a full index if no indices exist
     if (inds.empty()) {
         std::vector<int> fullInd(getArity());
         std::iota(fullInd.begin(), fullInd.end(), 0);
         inds.push_back(fullInd);
     }
     // expand all indexes to be full
     for (auto& ind : inds) {
         if (ind.size() != getArity()) {
             // use a set as a cache for fast lookup
             std::set<int> curIndexElems(ind.begin(), ind.end());
             // expand index to be full
             for (size_t i = 0; i < getArity(); i++) {
                 if (curIndexElems.find(i) == curIndexElems.end()) {
                     ind.push_back(i);
                 }
             }
         }
         assert(ind.size() == getArity());
     }
     masterIndex = 0;
     computedIndices = inds;
 }
void souffle::SynthesiserBrieRelation::generateTypeStruct (std::ostream & out) override virtual
Generate type struct of a brie relation.
Implements souffle::SynthesiserRelation.
Definition at line 740 of file SynthesiserRelation.cpp.
References arity, souffle::IndexSet::getAllOrders(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndexSet(), souffle::SynthesiserRelation::getIndices(), souffle::IndexSet::getLexOrder(), souffle::SynthesiserRelation::getTypeName(), i, j, souffle::join(), and souffle::SynthesiserRelation::masterIndex.
{
     size_t arity = getArity();
     const auto& inds = getIndices();
     size_t numIndexes = inds.size();
     std::map<std::vector<int>, int> indexToNumMap;
     // struct definition
     out << "struct " << getTypeName() << " {\n";
     // define trie structures
     for (size_t i = 0; i < inds.size(); i++) {
         if (i < getIndexSet().getAllOrders().size()) {
             indexToNumMap[getIndexSet().getAllOrders()[i]] = i;
         }
         out << "using t_ind_" << i << " = Trie<" << inds[i].size() << ">;\n";
         out << "t_ind_" << i << " ind_" << i << ";\n";
     }
     out << "using t_tuple = t_ind_" << masterIndex << "::entry_type;\n";
     // generate auxiliary iterators that use orderOut
     for (size_t i = 0; i < numIndexes; i++) {
         // generate auxiliary iterators which orderOut
         out << "class iterator_" << i << " : public std::iterator<std::forward_iterator_tag, t_tuple> {\n";
         out << "    using nested_iterator = typename t_ind_" << i << "::iterator;\n";
         out << "    nested_iterator nested;\n";
         out << "    t_tuple value;\n";
         out << "public:\n";
         out << "    iterator_" << i << "() = default;\n";
         out << "    iterator_" << i << "(const nested_iterator& iter) : nested(iter), value(orderOut_" << i
             << "(*iter)) {}\n";
         out << "    iterator_" << i << "(const iterator_" << i << "& other) = default;\n";
         out << "    iterator_" << i << "& operator=(const iterator_" << i << "& other) = default;\n";
         out << "    bool operator==(const iterator_" << i << "& other) const {\n";
         out << "        return nested == other.nested;\n";
         out << "    }\n";
         out << "    bool operator!=(const iterator_" << i << "& other) const {\n";
         out << "        return !(*this == other);\n";
         out << "    }\n";
         out << "    const t_tuple& operator*() const {\n";
         out << "        return value;\n";
         out << "    }\n";
         out << "    const t_tuple* operator->() const {\n";
         out << "        return &value;\n";
         out << "    }\n";
         out << "    iterator_" << i << "& operator++() {\n";
         out << "        ++nested;\n";
         out << "        value = orderOut_" << i << "(*nested);\n";
         out << "        return *this;\n";
         out << "    }\n";
         out << "};\n";
     }
     out << "using iterator = iterator_" << masterIndex << ";\n";
     // hints struct
     out << "struct context {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "t_ind_" << i << "::op_context hints_" << i << ";\n";
     }
     out << "};\n";
     out << "context createContext() { return context(); }\n";
     // insert methods
     out << "bool insert(const t_tuple& t) {\n";
     out << "context h;\n";
     out << "return insert(t, h);\n";
     out << "}\n";
     out << "bool insert(const t_tuple& t, context& h) {\n";
     out << "if (ind_" << masterIndex << ".insert(orderIn_" << masterIndex << "(t), h.hints_" << masterIndex
         << ")) {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         if (i != masterIndex) {
             out << "ind_" << i << ".insert(orderIn_" << i << "(t), h.hints_" << i << ");\n";
         }
     }
     out << "return true;\n";
     out << "} else return false;\n";
     out << "}\n";
     out << "bool insert(const RamDomain* ramDomain) {\n";
     out << "RamDomain data[" << arity << "];\n";
     out << "std::copy(ramDomain, ramDomain + " << arity << ", data);\n";
     out << "const t_tuple& tuple = reinterpret_cast<const t_tuple&>(data);\n";
     out << "context h;\n";
     out << "return insert(tuple, h);\n";
     out << "}\n";
     // insertAll method
     out << "template <typename T>\n";
     out << "void insertAll(T& other) {\n";
     out << "for (auto const& cur : other) {\n";
     out << "insert(cur);\n";
     out << "}\n";
     out << "}\n";
     // insertAll using the index method
     out << "void insertAll(" << getTypeName() << "& other) {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "ind_" << i << ".insertAll(other.ind_" << i << ");\n";
     }
     out << "}\n";
     // insert method
     std::vector<std::string> decls, params;
     for (size_t i = 0; i < arity; i++) {
         decls.push_back("RamDomain a" + std::to_string(i));
         params.push_back("a" + std::to_string(i));
     }
     out << "bool insert(" << join(decls, ",") << ") {\nRamDomain data[";
     out << arity << "] = {" << join(params, ",") << "};\n";
     out << "return insert(data);\n";
     out << "}\n";
     // contains methods
     out << "bool contains(const t_tuple& t, context& h) const {\n";
     out << "return ind_" << masterIndex << ".contains(orderIn_" << masterIndex << "(t), h.hints_"
         << masterIndex << ");\n";
     out << "}\n";
     out << "bool contains(const t_tuple& t) const {\n";
     out << "context h;\n";
     out << "return contains(t, h);\n";
     out << "}\n";
     // size method
     out << "std::size_t size() const {\n";
     out << "return ind_" << masterIndex << ".size();\n";
     out << "}\n";
     // find methods
     if (arity > 1) {
         out << "iterator find(const t_tuple& t, context& h) const {\n";
         out << "return ind_" << masterIndex << ".find(orderIn_" << masterIndex << "(t), h.hints_"
             << masterIndex << ");\n";
         out << "}\n";
         out << "iterator find(const t_tuple& t) const {\n";
         out << "context h;\n";
         out << "return find(t, h);\n";
         out << "}\n";
     }
     // empty equalRange method
     out << "range<iterator> equalRange_0(const t_tuple& t, context& h) const {\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     out << "range<iterator> equalRange_0(const t_tuple& t) const {\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     // equalRange methods
     for (int64_t search : getIndexSet().getSearches()) {
         auto lexOrder = getIndexSet().getLexOrder(search);
         size_t indNum = indexToNumMap[lexOrder];
         out << "range<iterator_" << indNum << "> equalRange_" << search;
         out << "(const t_tuple& t, context& h) const {\n";
         // compute size of sub-index
         size_t indSize = 0;
         for (size_t i = 0; i < arity; i++) {
             if ((search >> i) & 1) {
                 indSize++;
             }
         }
         out << "auto r = ind_" << indNum << ".template getBoundaries<" << indSize << ">(orderIn_" << indNum
             << "(t), h.hints_" << indNum << ");\n";
         out << "return make_range(iterator_" << indNum << "(r.begin()), iterator_" << indNum
             << "(r.end()));\n";
         out << "}\n";
         out << "range<iterator_" << indNum << "> equalRange_" << search;
         out << "(const t_tuple& t) const {\n";
         out << "context h; return equalRange_" << search << "(t, h);\n";
         out << "}\n";
     }
     // empty method
     out << "bool empty() const {\n";
     out << "return ind_" << masterIndex << ".empty();\n";
     out << "}\n";
     // partition method
     out << "std::vector<range<iterator>> partition() const {\n";
     out << "std::vector<range<iterator>> res;\n";
     out << "for (const auto& cur : ind_" << masterIndex << ".partition(10000)) {\n";
     out << "    res.push_back(make_range(iterator(cur.begin()), iterator(cur.end())));\n";
     out << "}\n";
     out << "return res;\n";
     out << "}\n";
     // purge method
     out << "void purge() {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "ind_" << i << ".clear();\n";
     }
     out << "}\n";
     // begin and end iterators
     out << "iterator begin() const {\n";
     out << "return iterator_" << masterIndex << "(ind_" << masterIndex << ".begin());\n";
     out << "}\n";
     out << "iterator end() const {\n";
     out << "return iterator_" << masterIndex << "(ind_" << masterIndex << ".end());\n";
     out << "}\n";
     // TODO: finish printHintStatistics method
     out << "void printHintStatistics(std::ostream& o, const std::string prefix) const {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "const auto& stats_" << i << " = ind_" << i << ".getHintStatistics();\n";
         out << "o << prefix << \"arity " << arity << " brie index " << inds[i]
             << ": (hits/misses/total)\\n\";\n";
         out << "o << prefix << \"Insert: \" << stats_" << i << ".inserts.getHits() << \"/\" << stats_" << i
             << ".inserts.getMisses() << \"/\" << stats_" << i << ".inserts.getAccesses() << \"\\n\";\n";
         out << "o << prefix << \"Contains: \" << stats_" << i << ".contains.getHits() << \"/\" << stats_" << i
             << ".contains.getMisses() << \"/\" << stats_" << i << ".contains.getAccesses() << \"\\n\";\n";
         out << "o << prefix << \"Range-query: \" << stats_" << i
             << ".get_boundaries.getHits() << \"/\" << stats_" << i
             << ".get_boundaries.getMisses() << \"/\" << stats_" << i
             << ".get_boundaries.getAccesses() << \"\\n\";\n";
     }
     out << "}\n";
     // orderOut and orderIn methods for reordering tuples according to index orders
     for (size_t i = 0; i < numIndexes; i++) {
         auto ind = inds[i];
         out << "static t_tuple orderIn_" << i << "(const t_tuple& t) {\n";
         out << "t_tuple res;\n";
         for (size_t j = 0; j < ind.size(); j++) {
             out << "res[" << j << "] = t[" << ind[j] << "];\n";
         }
         out << "return res;\n";
         out << "}\n";
         out << "static t_tuple orderOut_" << i << "(const t_tuple& t) {\n";
         out << "t_tuple res;\n";
         for (size_t j = 0; j < ind.size(); j++) {
             out << "res[" << ind[j] << "] = t[" << j << "];\n";
         }
         out << "return res;\n";
         out << "}\n";
     }
     // end class
     out << "};\n";
 }
std::string souffle::SynthesiserBrieRelation::getTypeName () override virtual
Generate type name of a brie relation.
Implements souffle::SynthesiserRelation.
Definition at line 724 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndexSet(), souffle::SynthesiserRelation::getIndices(), and souffle::join().
{
     std::stringstream res;
     res << "t_brie_" << getArity();
     for (auto& ind : getIndices()) {
         res << "__" << join(ind, "_");
     }
     for (auto& search : getIndexSet().getSearches()) {
         res << "__" << search;
     }
     return res.str();
 }
The documentation for this class was generated from the following files:
SynthesiserRelation.h
SynthesiserRelation.cpp