souffle: souffle::RamOperation Class Reference
souffle::RamOperation Class Reference abstract
Abstract class for a relational algebra operation.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override=0
Apply the mapper to all child nodes.
RamOperation * clone () const override=0
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override=0
Obtain list of all embedded child nodes.
virtual void print (std::ostream &os, int tabpos) const =0
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override=0
Abstract equality check for two RAM nodes.
Detailed Description
Abstract class for a relational algebra operation.
Definition at line 37 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamOperation::RamOperation () default
Member Function Documentation
void souffle::RamOperation::apply (const RamNodeMapper & mapper) override pure virtual
Apply the mapper to all child nodes.
Implements souffle::RamNode.
Implemented in souffle::RamReturnValue, souffle::RamProject, souffle::RamBreak, souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexRelationSearch, souffle::RamRelationSearch, and souffle::RamNestedOperation.
Referenced by souffle::HoistConditionsTransformer::hoistConditions(), and print().
RamOperation* souffle::RamOperation::clone () const override pure virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamNode.
Implemented in souffle::RamReturnValue, souffle::RamProject, souffle::RamBreak, souffle::RamFilter, souffle::RamUnpackRecord, souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexScan, and souffle::RamScan.
Referenced by souffle::RamIndexAggregate::clone(), souffle::RamAggregate::clone(), souffle::RamUnpackRecord::clone(), print(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), and souffle::ChoiceConversionTransformer::rewriteScan().
bool souffle::RamOperation::equal (const RamNode & other) const override protected pure virtual
Abstract equality check for two RAM nodes.
Implements souffle::RamNode.
Implemented in souffle::RamReturnValue, souffle::RamProject, souffle::RamBreak, souffle::RamFilter, souffle::RamUnpackRecord, souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexRelationSearch, souffle::RamRelationSearch, souffle::RamSearch, and souffle::RamNestedOperation.
Referenced by print().
std::vector<const RamNode*> souffle::RamOperation::getChildNodes () const override pure virtual
Obtain list of all embedded child nodes.
Implements souffle::RamNode.
Implemented in souffle::RamReturnValue, souffle::RamProject, souffle::RamBreak, souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexRelationSearch, souffle::RamScan, souffle::RamRelationSearch, souffle::RamSearch, and souffle::RamNestedOperation.
Referenced by print().
virtual void souffle::RamOperation::print (std::ostream & os, int tabpos) const pure virtual
Implemented in souffle::RamReturnValue, souffle::RamProject, souffle::RamBreak, souffle::RamFilter, souffle::RamUnpackRecord, souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexScan, souffle::RamScan, and souffle::RamNestedOperation.
Referenced by print().
void souffle::RamOperation::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 43 of file RamOperation.h.
References apply(), clone(), equal(), getChildNodes(), and print().
{
         print(os, 0);
     }
The documentation for this class was generated from the following file:
RamOperation.h