souffle: souffle::UnsupportedConstructException Class Reference
souffle::UnsupportedConstructException Class Reference
Conversion Exception for translation.
Public Member Functions
UnsupportedConstructException (std::string msg)
UnsupportedConstructException (std::string msg)
const char * what () const noexceptoverride
const char * what () const noexceptoverride
Private Attributes
std::string msg
Detailed Description
Conversion Exception for translation.
Definition at line 68 of file souffle2bdd.cpp.
Constructor & Destructor Documentation
souffle::UnsupportedConstructException::UnsupportedConstructException (std::string msg) inline
Definition at line 72 of file souffle2bdd.cpp.
Referenced by souffle::BddBddBTranslator::visitClause(), souffle::LogicbloxConverter::visitClause(), souffle::BddBddBTranslator::visitFunctor(), souffle::LogicbloxConverter::visitFunctor(), souffle::BddBddBTranslator::visitNode(), and souffle::LogicbloxConverter::visitNode().
 : msg(std::move(msg)) {}
souffle::UnsupportedConstructException::UnsupportedConstructException (std::string msg) inline
Definition at line 70 of file souffle2lb.cpp.
 : msg(std::move(msg)) {}
Member Function Documentation
const char* souffle::UnsupportedConstructException::what () const inline override noexcept
Definition at line 71 of file souffle2lb.cpp.
{
         return msg.c_str();
     }
const char* souffle::UnsupportedConstructException::what () const inline override noexcept
Definition at line 73 of file souffle2bdd.cpp.
Referenced by souffle::toBddbddb().
{
         return msg.c_str();
     }
Field Documentation
std::string souffle::UnsupportedConstructException::msg private
Definition at line 69 of file souffle2bdd.cpp.
The documentation for this class was generated from the following files:
souffle2bdd.cpp
souffle2lb.cpp