souffle: souffle::Table< T, blockSize > Class Template Reference
souffle::Table< T, blockSize > Class Template Reference
#include <Table.h>
Data Structures
struct Block
class iterator
Public Member Functions
iterator begin () const
void clear ()
bool empty () const
iterator end () const
const T & insert (const T &element)
std::size_t size () const
Table ()
~Table ()
Private Attributes
std::size_t count = 0
Block * head
Block * tail
Detailed Description
template<typename T, unsigned blockSize = 4096>
class souffle::Table< T, blockSize >
Definition at line 25 of file Table.h.
Constructor & Destructor Documentation
template<typename T, unsigned blockSize = 4096> souffle::Table< T, blockSize >::Table () inline
Definition at line 90 of file Table.h.
 : head(nullptr), tail(nullptr) {}
template<typename T, unsigned blockSize = 4096> souffle::Table< T, blockSize >::~Table () inline
Definition at line 92 of file Table.h.
              {
         clear();
     }
Member Function Documentation
template<typename T, unsigned blockSize = 4096> iterator souffle::Table< T, blockSize >::begin () const inline
Definition at line 124 of file Table.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::begin().
{
         return iterator(head);
     }
template<typename T, unsigned blockSize = 4096> void souffle::Table< T, blockSize >::clear () inline
Definition at line 132 of file Table.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::purge(), and souffle::Table< tuple_type >::~Table().
                  {
         while (head != nullptr) {
             auto cur = head;
             head = head->next;
             delete cur;
         }
         count = 0;
         head = nullptr;
         tail = nullptr;
     }
template<typename T, unsigned blockSize = 4096> bool souffle::Table< T, blockSize >::empty () const inline
Definition at line 96 of file Table.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::empty().
{
         return (!head);
     }
template<typename T, unsigned blockSize = 4096> iterator souffle::Table< T, blockSize >::end () const inline
Definition at line 128 of file Table.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::end().
{
         return iterator();
     }
template<typename T, unsigned blockSize = 4096> const T& souffle::Table< T, blockSize >::insert (const T & element) inline
Definition at line 104 of file Table.h.
Referenced by souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insert().
{
         // check whether the head is initialized
         if (!head) {
             head = new Block();
             tail = head;
         }
         // check whether tail is full
         if (tail->isFull()) {
             tail->next = new Block();
             tail = tail->next;
         }
         // increment counter
         count++;
         // add another element
         return tail->append(element);
     }
template<typename T, unsigned blockSize = 4096> std::size_t souffle::Table< T, blockSize >::size () const inline
Definition at line 100 of file Table.h.
Referenced by souffle::genJsonRules(), and souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::size().
{
         return count;
     }
Field Documentation
template<typename T, unsigned blockSize = 4096> std::size_t souffle::Table< T, blockSize >::count = 0 private
Definition at line 48 of file Table.h.
Referenced by souffle::Table< tuple_type >::size().
template<typename T, unsigned blockSize = 4096> Block* souffle::Table< T, blockSize >::head private
Definition at line 45 of file Table.h.
Referenced by souffle::Table< tuple_type >::clear(), and souffle::Table< tuple_type >::insert().
template<typename T, unsigned blockSize = 4096> Block* souffle::Table< T, blockSize >::tail private
Definition at line 46 of file Table.h.
The documentation for this class was generated from the following file:
Table.h