souffle: souffle::BaseTable< K, V > Class Template Reference
souffle::BaseTable< K, V > Class Template Reference
#include <Global.h>
Public Member Functions
BaseTable ()
BaseTable (const BaseTable &other)
const std::map< K, V > & data () const
void data (const std::map< K, V > &otherData)
const V & get (const K &key) const
const V & get (const K &key, const V &value) const
bool has (const K &key) const
bool has (const K &key, const V &value) const
BaseTable & operator= (const BaseTable &other)
void print (std::ostream &os)
void set (const K &key)
void set (const K &key, const V &value)
void unset (const K &key)
Private Attributes
std::map< K, V > _data
const V _default
Detailed Description
template<typename K, typename V>
class souffle::BaseTable< K, V >
Definition at line 28 of file Global.h.
Constructor & Destructor Documentation
template<typename K, typename V> souffle::BaseTable< K, V >::BaseTable () inline
Definition at line 31 of file Global.h.
 : _default(V()), _data(std::map<K, V>()) {}
template<typename K, typename V> souffle::BaseTable< K, V >::BaseTable (const BaseTable< K, V > & other) inline
Definition at line 33 of file Global.h.
References souffle::BaseTable< K, V >::data().
{
         data(other.data());
     }
Member Function Documentation
template<typename K, typename V> const std::map<K, V>& souffle::BaseTable< K, V >::data () const inline
Definition at line 42 of file Global.h.
References souffle::BaseTable< K, V >::_data.
Referenced by souffle::BaseTable< K, V >::BaseTable(), and souffle::BaseTable< K, V >::operator=().
{
         return _data;
     }
template<typename K, typename V> void souffle::BaseTable< K, V >::data (const std::map< K, V > & otherData) inline
Definition at line 46 of file Global.h.
References souffle::BaseTable< K, V >::_data.
{
         _data = otherData;
     }
template<typename K, typename V> const V& souffle::BaseTable< K, V >::get (const K & key) const inline
Definition at line 51 of file Global.h.
References souffle::BaseTable< K, V >::_data, souffle::BaseTable< K, V >::_default, and souffle::BaseTable< K, V >::has().
{
         return (has(key)) ? _data.at(key) : _default;
     }
template<typename K, typename V> const V& souffle::BaseTable< K, V >::get (const K & key, const V & value) const inline
Definition at line 55 of file Global.h.
References souffle::BaseTable< K, V >::_data, and souffle::BaseTable< K, V >::has().
{
         return (has(key)) ? _data.at(key) : value;
     }
template<typename K, typename V> bool souffle::BaseTable< K, V >::has (const K & key) const inline
Definition at line 59 of file Global.h.
References souffle::BaseTable< K, V >::_data.
Referenced by souffle::BaseTable< K, V >::get(), and souffle::BaseTable< K, V >::has().
{
         return _data.find(key) != _data.end();
     }
template<typename K, typename V> bool souffle::BaseTable< K, V >::has (const K & key, const V & value) const inline
Definition at line 63 of file Global.h.
References souffle::BaseTable< K, V >::_data, and souffle::BaseTable< K, V >::has().
{
         return has(key) && _data.at(key) == value;
     }
template<typename K, typename V> BaseTable& souffle::BaseTable< K, V >::operator= (const BaseTable< K, V > & other) inline
Definition at line 37 of file Global.h.
References souffle::BaseTable< K, V >::data().
{
         data(other.data());
         return *this;
     }
template<typename K, typename V> void souffle::BaseTable< K, V >::print (std::ostream & os) inline
Definition at line 80 of file Global.h.
References souffle::BaseTable< K, V >::_data.
{
         os << _data << std::endl;
     }
template<typename K, typename V> void souffle::BaseTable< K, V >::set (const K & key) inline
Definition at line 68 of file Global.h.
References souffle::BaseTable< K, V >::_data, and souffle::BaseTable< K, V >::_default.
{
         _data[key] = _default;
     }
template<typename K, typename V> void souffle::BaseTable< K, V >::set (const K & key, const V & value) inline
Definition at line 72 of file Global.h.
References souffle::BaseTable< K, V >::_data.
{
         _data[key] = value;
     }
template<typename K, typename V> void souffle::BaseTable< K, V >::unset (const K & key) inline
Definition at line 76 of file Global.h.
References souffle::BaseTable< K, V >::_data.
{
         _data.erase(key);
     }
Field Documentation
template<typename K, typename V> std::map<K, V> souffle::BaseTable< K, V >::_data private
Definition at line 88 of file Global.h.
Referenced by souffle::BaseTable< K, V >::data(), souffle::BaseTable< K, V >::get(), souffle::BaseTable< K, V >::has(), souffle::BaseTable< K, V >::print(), souffle::BaseTable< K, V >::set(), and souffle::BaseTable< K, V >::unset().
template<typename K, typename V> const V souffle::BaseTable< K, V >::_default private
Definition at line 86 of file Global.h.
Referenced by souffle::BaseTable< K, V >::get(), and souffle::BaseTable< K, V >::set().
The documentation for this class was generated from the following file:
Global.h