souffle: souffle::AstVariable Class Reference
souffle::AstVariable Class Reference
Subclass of Argument that represents a named variable.
#include <AstArgument.h>
Public Member Functions
void apply (const AstNodeMapper &) override
Mutates this node.
AstVariable (std::string n)
AstVariable * clone () const override
Creates a clone of this AST sub-structure.
const std::string & getName () const
void print (std::ostream &os) const override
Print argument to the given output stream.
void setName (const std::string &name)
Updates this variable name.
Public Member Functions inherited from souffle::AstArgument
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::string name
Variable name.
Detailed Description
Subclass of Argument that represents a named variable.
Definition at line 59 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstVariable::AstVariable (std::string n) inline
Definition at line 61 of file AstArgument.h.
 : AstArgument(), name(std::move(n)) {}
Member Function Documentation
void souffle::AstVariable::apply (const AstNodeMapper &) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 86 of file AstArgument.h.
{
         // no sub-nodes to consider
     }
AstVariable* souffle::AstVariable::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstArgument.
Definition at line 79 of file AstArgument.h.
References souffle::AstNode::getSrcLoc(), and souffle::AstNode::setSrcLoc().
{
         AstVariable* res = new AstVariable(name);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstVariable::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 95 of file AstArgument.h.
References name.
{
         assert(nullptr != dynamic_cast<const AstVariable*>(&node));
         const auto& other = static_cast<const AstVariable&>(node);
         return name == other.name;
     }
const std::string& souffle::AstVariable::getName () const inline
Returns
Variable name
Definition at line 69 of file AstArgument.h.
Referenced by souffle::BindingStore::addBinding(), souffle::AstTranslator::ValueIndex::addVarReference(), souffle::AstSemanticChecker::checkClause(), souffle::AstSemanticChecker::checkProgram(), souffle::AstTranslator::ValueIndex::getDefinitionPoint(), souffle::getSipsFunction(), souffle::isBoundComposite(), souffle::AstTranslator::ValueIndex::isDefined(), souffle::isValidPermutation(), souffle::AstTranslator::makeNegationSubproofSubroutine(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), souffle::numBoundArguments(), souffle::UniqueAggregationVariablesTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::ReplaceSingletonVariablesTransformer::transform().
{
         return name;
     }
void souffle::AstVariable::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 74 of file AstArgument.h.
Referenced by souffle::makeInfoRelation().
{
         os << name;
     }
void souffle::AstVariable::setName (const std::string & name) inline
Updates this variable name.
Definition at line 64 of file AstArgument.h.
{
         this->name = name;
     }
Field Documentation
std::string souffle::AstVariable::name protected
Variable name.
Definition at line 92 of file AstArgument.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstArgument.h