souffle: souffle::RamSearch Class Reference
souffle::RamSearch Class Reference
Abstract class for relation searches and lookups.
#include <RamOperation.h>
Public Member Functions
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
int getTupleId () const
Get identifier.
RamSearch (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
void print (std::ostream &os, int tabpos) const override
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create a clone (i.e.
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Abstract equality check for two RAM nodes.
Protected Attributes
const int identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Abstract class for relation searches and lookups.
Definition at line 105 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamSearch::RamSearch (int ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 107 of file RamOperation.h.
             : RamNestedOperation(std::move(nested), std::move(profileText)), identifier(ident) {}
Member Function Documentation
bool souffle::RamSearch::equal (const RamNode & other) const inline override protected virtual
Abstract equality check for two RAM nodes.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamUnpackRecord, souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexRelationSearch, and souffle::RamRelationSearch.
Definition at line 123 of file RamOperation.h.
References souffle::RamNestedOperation::equal().
Referenced by souffle::RamRelationSearch::equal(), and souffle::RamUnpackRecord::equal().
{
         assert(nullptr != dynamic_cast<const RamSearch*>(&node));
         const auto& other = static_cast<const RamSearch&>(node);
         return RamNestedOperation::equal(other) && getTupleId() == other.getTupleId();
     }
std::vector<const RamNode*> souffle::RamSearch::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamAggregate, souffle::RamIndexAggregate, souffle::RamIndexChoice, souffle::RamChoice, souffle::RamIndexRelationSearch, souffle::RamScan, and souffle::RamRelationSearch.
Definition at line 115 of file RamOperation.h.
References souffle::RamNestedOperation::getChildNodes().
Referenced by souffle::RamRelationSearch::getChildNodes().
{
         return RamNestedOperation::getChildNodes();
     }
int souffle::RamSearch::getTupleId () const inline
Get identifier.
Definition at line 111 of file RamOperation.h.
References souffle::identifier().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::HoistConditionsTransformer::hoistConditions(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::LVMGenerator::visitAggregate(), souffle::LVMGenerator::visitChoice(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), souffle::LVMGenerator::visitScan(), and souffle::LVMGenerator::visitUnpackRecord().
{
         return identifier;
     }
Field Documentation
const int souffle::RamSearch::identifier protected
Identifier for the tuple.
Definition at line 121 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h