souffle: souffle::SynthesiserIndirectRelation Class Reference
souffle::SynthesiserIndirectRelation Class Reference
#include <SynthesiserRelation.h>
Public Member Functions
void computeIndices () override
Generate index set for a indirect indexed relation.
void generateTypeStruct (std::ostream &out) override
Generate type struct of a indirect indexed relation.
std::string getTypeName () override
Generate type name of a indirect indexed relation.
SynthesiserIndirectRelation (const RamRelation &ramRel, const IndexSet &indexSet, bool isProvenance)
Public Member Functions inherited from souffle::SynthesiserRelation
size_t getArity () const
Get arity of relation.
const std::string & getDataStructure () const
Get data structure of relation.
const IndexSet & getIndexSet () const
Get stored IndexSet.
std::vector< std::vector< int > > getIndices () const
Get list of indices used for relation, guaranteed that original indices in IndexSet come before any generated indices.
const RamRelation & getRamRelation () const
Get stored RamRelation.
SynthesiserRelation (const RamRelation &rel, const IndexSet &indices, const bool isProvenance=false)
virtual ~SynthesiserRelation ()=default
Additional Inherited Members
Static Public Member Functions inherited from souffle::SynthesiserRelation
static std::unique_ptr< SynthesiserRelation > getSynthesiserRelation (const RamRelation &ramRel, const IndexSet &indexSet, bool isProvenance)
Factory method to generate a SynthesiserRelation.
Protected Attributes inherited from souffle::SynthesiserRelation
std::vector< IndexSet::LexicographicalOrder > computedIndices
The final list of indices used.
std::string dataStructure
The data structure used for the relation.
const IndexSet & indices
Indices used for this relation.
const bool isProvenance
Is this relation used with provenance.
size_t masterIndex = -1
The number of the master index.
const RamRelation & relation
Ram relation referred to by this.
Detailed Description
Definition at line 108 of file SynthesiserRelation.h.
Constructor & Destructor Documentation
souffle::SynthesiserIndirectRelation::SynthesiserIndirectRelation (const RamRelation & ramRel, const IndexSet & indexSet, bool isProvenance) inline
Definition at line 110 of file SynthesiserRelation.h.
References souffle::SynthesiserRelation::computeIndices(), souffle::SynthesiserRelation::generateTypeStruct(), and souffle::SynthesiserRelation::getTypeName().
             : SynthesiserRelation(ramRel, indexSet, isProvenance) {}
Member Function Documentation
void souffle::SynthesiserIndirectRelation::computeIndices () override virtual
Generate index set for a indirect indexed relation.
Implements souffle::SynthesiserRelation.
Definition at line 391 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::computedIndices, souffle::IndexSet::getAllOrders(), souffle::SynthesiserRelation::getArity(), i, souffle::SynthesiserRelation::indices, souffle::SynthesiserRelation::isProvenance, and souffle::SynthesiserRelation::masterIndex.
{
     assert(!isProvenance);
     // Generate and set indices
     std::vector<std::vector<int>> inds = indices.getAllOrders();
     // generate a full index if no indices exist
     if (inds.empty()) {
         std::vector<int> fullInd(getArity());
         std::iota(fullInd.begin(), fullInd.end(), 0);
         inds.push_back(fullInd);
         masterIndex = 0;
     }
     // Expand the first index to be a full index if no full inds exist
     bool fullExists = false;
     // check for full index
     for (size_t i = 0; i < inds.size(); i++) {
         auto& ind = inds[i];
         if (ind.size() == getArity()) {
             fullExists = true;
             if (masterIndex == (size_t)-1) {
                 masterIndex = i;
             }
         }
     }
     // expand the first ind to be full, it is guaranteed that at least one index exists
     if (!fullExists) {
         std::set<int> curIndexElems(inds[0].begin(), inds[0].end());
         // expand index to be full
         for (size_t i = 0; i < getArity(); i++) {
             if (curIndexElems.find(i) == curIndexElems.end()) {
                 inds[0].push_back(i);
             }
         }
         masterIndex = 0;
     }
     computedIndices = inds;
 }
void souffle::SynthesiserIndirectRelation::generateTypeStruct (std::ostream & out) override virtual
Generate type struct of a indirect indexed relation.
Implements souffle::SynthesiserRelation.
Definition at line 452 of file SynthesiserRelation.cpp.
References arity, souffle::IndexSet::getAllOrders(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndexSet(), souffle::SynthesiserRelation::getIndices(), souffle::IndexSet::getLexOrder(), souffle::SynthesiserRelation::getTypeName(), i, souffle::join(), and souffle::SynthesiserRelation::masterIndex.
{
     size_t arity = getArity();
     const auto& inds = getIndices();
     size_t numIndexes = inds.size();
     std::map<std::vector<int>, int> indexToNumMap;
     // struct definition
     out << "struct " << getTypeName() << " {\n";
     // stored tuple type
     out << "using t_tuple = Tuple<RamDomain, " << arity << ">;\n";
     // table and lock required for storing actual data for indirect indices
     out << "Table<t_tuple> dataTable;\n";
     out << "Lock insert_lock;\n";
     // btree types
     for (size_t i = 0; i < inds.size(); i++) {
         auto ind = inds[i];
         if (i < getIndexSet().getAllOrders().size()) {
             indexToNumMap[getIndexSet().getAllOrders()[i]] = i;
         }
         if (ind.size() == arity) {
             out << "using t_ind_" << i
                 << " = btree_set<const t_tuple*, index_utils::deref_compare<typename "
                    "index_utils::comparator<"
                 << join(ind) << ">>>;\n";
         } else {
             out << "using t_ind_" << i
                 << " = btree_multiset<const t_tuple*, index_utils::deref_compare<typename "
                    "index_utils::comparator<"
                 << join(ind) << ">>>;\n";
         }
         out << "t_ind_" << i << " ind_" << i << ";\n";
     }
     // typedef deref iterators
     for (size_t i = 0; i < numIndexes; i++) {
         out << "using iterator_" << i << " = IterDerefWrapper<typename t_ind_" << i << "::iterator>;\n";
     }
     out << "using iterator = iterator_" << masterIndex << ";\n";
     // Create a struct storing the context hints for each index
     out << "struct context {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "t_ind_" << i << "::operation_hints hints_" << i << ";\n";
     }
     out << "};\n";
     out << "context createContext() { return context(); }\n";
     // insert methods
     out << "bool insert(const t_tuple& t) {\n";
     out << "context h;\n";
     out << "return insert(t, h);\n";
     out << "}\n";
     out << "bool insert(const t_tuple& t, context& h) {\n";
     out << "const t_tuple* masterCopy = nullptr;\n";
     out << "{\n";
     out << "auto lease = insert_lock.acquire();\n";
     out << "if (contains(t, h)) return false;\n";
     out << "masterCopy = &dataTable.insert(t);\n";
     out << "ind_" << masterIndex << ".insert(masterCopy, h.hints_" << masterIndex << ");\n";
     out << "}\n";
     for (size_t i = 0; i < numIndexes; i++) {
         if (i != masterIndex) {
             out << "ind_" << i << ".insert(masterCopy, h.hints_" << i << ");\n";
         }
     }
     out << "return true;\n";
     out << "}\n";
     out << "bool insert(const RamDomain* ramDomain) {\n";
     out << "RamDomain data[" << arity << "];\n";
     out << "std::copy(ramDomain, ramDomain + " << arity << ", data);\n";
     out << "const t_tuple& tuple = reinterpret_cast<const t_tuple&>(data);\n";
     out << "context h;\n";
     out << "return insert(tuple, h);\n";
     out << "}\n";  // end of insert(RamDomain*)
     std::vector<std::string> decls, params;
     for (size_t i = 0; i < arity; i++) {
         decls.push_back("RamDomain a" + std::to_string(i));
         params.push_back("a" + std::to_string(i));
     }
     out << "bool insert(" << join(decls, ",") << ") {\n";
     out << "RamDomain data[" << arity << "] = {" << join(params, ",") << "};\n";
     out << "return insert(data);\n";
     out << "}\n";  // end of insert(RamDomain x1, RamDomain x2, ...)
     // insertAll method
     // do not use the specialized insertAll as it will copy references rather than tuples
     out << "template <typename T>\n";
     out << "void insertAll(T& other) {\n";
     out << "for (auto const& cur : other) {\n";
     out << "insert(cur);\n";
     out << "}\n";
     out << "}\n";
     // contains methods
     out << "bool contains(const t_tuple& t, context& h) const {\n";
     out << "return ind_" << masterIndex << ".contains(&t, h.hints_" << masterIndex << ");\n";
     out << "}\n";
     out << "bool contains(const t_tuple& t) const {\n";
     out << "context h;\n";
     out << "return contains(t, h);\n";
     out << "}\n";
     // size method
     out << "std::size_t size() const {\n";
     out << "return ind_" << masterIndex << ".size();\n";
     out << "}\n";
     // find methods
     out << "iterator find(const t_tuple& t, context& h) const {\n";
     out << "return ind_" << masterIndex << ".find(&t, h.hints_" << masterIndex << ");\n";
     out << "}\n";
     out << "iterator find(const t_tuple& t) const {\n";
     out << "context h;\n";
     out << "return find(t, h);\n";
     out << "}\n";
     // empty equalRange method
     out << "range<iterator> equalRange_0(const t_tuple& t, context& h) const {\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     out << "range<iterator> equalRange_0(const t_tuple& t) const {\n";
     out << "return range<iterator>(ind_" << masterIndex << ".begin(),ind_" << masterIndex << ".end());\n";
     out << "}\n";
     for (int64_t search : getIndexSet().getSearches()) {
         auto lexOrder = getIndexSet().getLexOrder(search);
         size_t indNum = indexToNumMap[lexOrder];
         out << "range<iterator_" << indNum << "> equalRange_" << search;
         out << "(const t_tuple& t, context& h) const {\n";
         // count size of search pattern
         size_t indSize = 0;
         for (size_t column = 0; column < arity; column++) {
             if ((search >> column) & 1) {
                 indSize++;
             }
         }
         // use the more efficient find() method for full range search
         if (indSize == arity) {
             out << "auto pos = find(t, h);\n";
             out << "auto fin = end();\n";
             out << "if (pos != fin) {fin = pos; ++fin;}\n";
             out << "return make_range(pos, fin);\n";
         } else {
             out << "t_tuple low(t); t_tuple high(t);\n";
             // check which indices to pad out
             for (size_t column = 0; column < arity; column++) {
                 // if bit number column is set
                 if (!((search >> column) & 1)) {
                     out << "low[" << column << "] = MIN_RAM_DOMAIN;\n";
                     out << "high[" << column << "] = MAX_RAM_DOMAIN;\n";
                 }
             }
             out << "return range<iterator_" << indNum << ">(ind_" << indNum << ".lower_bound(&low, h.hints_"
                 << indNum << "), ind_" << indNum << ".upper_bound(&high, h.hints_" << indNum << "));\n";
         }
         out << "}\n";
         out << "range<iterator_" << indNum << "> equalRange_" << search;
         out << "(const t_tuple& t) const {\n";
         out << "context h; return equalRange_" << search << "(t, h);\n";
         out << "}\n";
     }
     // empty method
     out << "bool empty() const {\n";
     out << "return ind_" << masterIndex << ".empty();\n";
     out << "}\n";
     // partition method
     out << "std::vector<range<iterator>> partition() const {\n";
     out << "std::vector<range<iterator>> res;\n";
     out << "for (const auto& cur : ind_" << masterIndex << ".getChunks(400)) {\n";
     out << "    res.push_back(make_range(derefIter(cur.begin()), derefIter(cur.end())));\n";
     out << "}\n";
     out << "return res;\n";
     out << "}\n";
     // purge method
     out << "void purge() {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "ind_" << i << ".clear();\n";
     }
     out << "dataTable.clear();\n";
     out << "}\n";
     // begin and end iterators
     out << "iterator begin() const {\n";
     out << "return ind_" << masterIndex << ".begin();\n";
     out << "}\n";
     out << "iterator end() const {\n";
     out << "return ind_" << masterIndex << ".end();\n";
     out << "}\n";
     // printHintStatistics method
     out << "void printHintStatistics(std::ostream& o, const std::string prefix) const {\n";
     for (size_t i = 0; i < numIndexes; i++) {
         out << "const auto& stats_" << i << " = ind_" << i << ".getHintStatistics();\n";
         out << "o << prefix << \"arity " << arity << " indirect b-tree index " << inds[i]
             << ": (hits/misses/total)\\n\";\n";
         out << "o << prefix << \"Insert: \" << stats_" << i << ".inserts.getHits() << \"/\" << stats_" << i
             << ".inserts.getMisses() << \"/\" << stats_" << i << ".inserts.getAccesses() << \"\\n\";\n";
         out << "o << prefix << \"Contains: \" << stats_" << i << ".contains.getHits() << \"/\" << stats_" << i
             << ".contains.getMisses() << \"/\" << stats_" << i << ".contains.getAccesses() << \"\\n\";\n";
         out << "o << prefix << \"Lower-bound: \" << stats_" << i
             << ".lower_bound.getHits() << \"/\" << stats_" << i
             << ".lower_bound.getMisses() << \"/\" << stats_" << i
             << ".lower_bound.getAccesses() << \"\\n\";\n";
         out << "o << prefix << \"Upper-bound: \" << stats_" << i
             << ".upper_bound.getHits() << \"/\" << stats_" << i
             << ".upper_bound.getMisses() << \"/\" << stats_" << i
             << ".upper_bound.getAccesses() << \"\\n\";\n";
     }
     out << "}\n";
     // end struct
     out << "};\n";
 }
std::string souffle::SynthesiserIndirectRelation::getTypeName () override virtual
Generate type name of a indirect indexed relation.
Implements souffle::SynthesiserRelation.
Definition at line 436 of file SynthesiserRelation.cpp.
References souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getIndexSet(), souffle::SynthesiserRelation::getIndices(), and souffle::join().
{
     std::stringstream res;
     res << "t_btree_" << getArity();
     for (auto& ind : getIndices()) {
         res << "__" << join(ind, "_");
     }
     for (auto& search : getIndexSet().getSearches()) {
         res << "__" << search;
     }
     return res.str();
 }
The documentation for this class was generated from the following files:
SynthesiserRelation.h
SynthesiserRelation.cpp