souffle: souffle::IOType Class Reference
souffle::IOType Class Reference
#include <AstIOTypeAnalysis.h>
Public Member Functions
bool isInput (const AstRelation *relation) const
bool isIO (const AstRelation *relation) const
bool isOutput (const AstRelation *relation) const
bool isPrintSize (const AstRelation *relation) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a RAM translation unit
Public Member Functions inherited from souffle::AstAnalysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "IO=type-analysis"
Private Attributes
std::set< const AstRelation * > inputRelations
std::set< const AstRelation * > outputRelations
std::set< const AstRelation * > printSizeRelations
Detailed Description
Definition at line 27 of file AstIOTypeAnalysis.h.
Member Function Documentation
bool souffle::IOType::isInput (const AstRelation * relation) const inline
Definition at line 35 of file AstIOTypeAnalysis.h.
References inputRelations.
Referenced by souffle::AstSemanticChecker::checkRelation(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::SCCGraph::getInternalInputRelations(), isIO(), souffle::BddBddBTranslator::visitRelation(), and souffle::LogicbloxConverter::visitRelation().
{
         return inputRelations.count(relation) != 0;
     }
bool souffle::IOType::isIO (const AstRelation * relation) const inline
Definition at line 47 of file AstIOTypeAnalysis.h.
References isInput(), isOutput(), and isPrintSize().
Referenced by souffle::AstSemanticChecker::checkInlining(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), and souffle::ReduceExistentialsTransformer::transform().
{
         return isInput(relation) || isOutput(relation) || isPrintSize(relation);
     }
bool souffle::IOType::isOutput (const AstRelation * relation) const inline
Definition at line 39 of file AstIOTypeAnalysis.h.
References outputRelations.
Referenced by souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::SCCGraph::getExternalNonOutputPredecessorRelations(), souffle::SCCGraph::getExternalOutputPredecessorRelations(), souffle::SCCGraph::getInternalNonOutputRelationsWithExternalSuccessors(), souffle::SCCGraph::getInternalOutputRelations(), isIO(), souffle::RedundantRelations::run(), souffle::BddBddBTranslator::visitRelation(), and souffle::LogicbloxConverter::visitRelation().
{
         return outputRelations.count(relation) != 0;
     }
bool souffle::IOType::isPrintSize (const AstRelation * relation) const inline
Definition at line 43 of file AstIOTypeAnalysis.h.
References printSizeRelations.
Referenced by souffle::AstSemanticChecker::checkRelationDeclaration(), and isIO().
{
         return printSizeRelations.count(relation) != 0;
     }
void souffle::IOType::print (std::ostream & os) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 64 of file AstIOTypeAnalysis.cpp.
References inputRelations, outputRelations, and printSizeRelations.
{
     os << "input relations: " << inputRelations << std::endl;
     os << "output relations: " << outputRelations << std::endl;
     os << "printSize relations: " << printSizeRelations << std::endl;
 }
void souffle::IOType::run (const AstTranslationUnit & translationUnit) override virtual
run analysis for a RAM translation unit
Implements souffle::AstAnalysis.
Definition at line 25 of file AstIOTypeAnalysis.cpp.
References souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelation(), inputRelations, outputRelations, printSizeRelations, relation, and souffle::visitDepthFirst().
{
     visitDepthFirst(*translationUnit.getProgram(), [&](const AstLoad& directive) {
         if (directive.getNames().empty()) {
             return;
         }
         auto* relation = translationUnit.getProgram()->getRelation(directive.getName());
         if (relation == nullptr) {
             return;
         }
         inputRelations.insert(relation);
     });
     visitDepthFirst(*translationUnit.getProgram(), [&](const AstStore& directive) {
         if (directive.getNames().empty()) {
             return;
         }
         auto* relation = translationUnit.getProgram()->getRelation(directive.getName());
         if (relation == nullptr) {
             return;
         }
         outputRelations.insert(relation);
     });
     visitDepthFirst(*translationUnit.getProgram(), [&](const AstPrintSize& directive) {
         if (directive.getNames().empty()) {
             return;
         }
         auto* relation = translationUnit.getProgram()->getRelation(directive.getName());
         if (relation == nullptr) {
             return;
         }
         printSizeRelations.insert(relation);
     });
 }
Field Documentation
std::set<const AstRelation*> souffle::IOType::inputRelations private
Definition at line 52 of file AstIOTypeAnalysis.h.
Referenced by isInput(), print(), and run().
constexpr const char* souffle::IOType::name = "IO=type-analysis" static
Definition at line 29 of file AstIOTypeAnalysis.h.
std::set<const AstRelation*> souffle::IOType::outputRelations private
Definition at line 53 of file AstIOTypeAnalysis.h.
Referenced by isOutput(), print(), and run().
std::set<const AstRelation*> souffle::IOType::printSizeRelations private
Definition at line 54 of file AstIOTypeAnalysis.h.
Referenced by isPrintSize(), print(), and run().
The documentation for this class was generated from the following files:
AstIOTypeAnalysis.h
AstIOTypeAnalysis.cpp