souffle: souffle::Relation::iterator_base Class Reference
souffle::Relation::iterator_base Class Reference abstract
#include <SouffleInterface.h>
Public Member Functions
virtual iterator_base * clone () const =0
virtual uint32_t getId () const
iterator_base (uint32_t arg_id)
virtual tuple & operator* ()=0
virtual void operator++ ()=0
bool operator== (const iterator_base &o) const
virtual ~iterator_base ()=default
Protected Member Functions
virtual bool equal (const iterator_base &o) const =0
Protected Attributes
uint32_t id
Detailed Description
Definition at line 41 of file SouffleInterface.h.
Constructor & Destructor Documentation
souffle::Relation::iterator_base::iterator_base (uint32_t arg_id) inline
Definition at line 51 of file SouffleInterface.h.
References operator*(), operator++(), and ~iterator_base().
 : id(arg_id) {}
virtual souffle::Relation::iterator_base::~iterator_base () virtual default
Reimplemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by iterator_base().
Member Function Documentation
virtual iterator_base* souffle::Relation::iterator_base::clone () const pure virtual
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by souffle::Relation::iterator::operator=(), and operator==().
virtual bool souffle::Relation::iterator_base::equal (const iterator_base & o) const protected pure virtual
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by operator==().
virtual uint32_t souffle::Relation::iterator_base::getId () const inline virtual
Definition at line 48 of file SouffleInterface.h.
References id.
Referenced by souffle::InterpreterRelInterface::iterator_base::clone(), and operator==().
{
             return id;
         }
virtual tuple& souffle::Relation::iterator_base::operator* () pure virtual
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by iterator_base().
virtual void souffle::Relation::iterator_base::operator++ () pure virtual
Implemented in souffle::InterpreterRelInterface::iterator_base.
Referenced by iterator_base().
bool souffle::Relation::iterator_base::operator== (const iterator_base & o) const inline
Definition at line 55 of file SouffleInterface.h.
References clone(), equal(), getId(), o, and souffle::Relation::~Relation().
{
             return this->getId() == o.getId() && equal(o);
         }
Field Documentation
uint32_t souffle::Relation::iterator_base::id protected
Definition at line 45 of file SouffleInterface.h.
Referenced by getId().
The documentation for this class was generated from the following file:
SouffleInterface.h