souffle: souffle::AstTypeCast Class Reference
souffle::AstTypeCast Class Reference
An argument capable of casting a value of one type into another.
#include <AstArgument.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Mutates this node.
AstTypeCast (std::unique_ptr< AstArgument > value, const AstTypeIdentifier &type)
AstTypeCast * clone () const override
Creates a clone of this AST sub-structure.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const AstTypeIdentifier & getType () const
AstArgument * getValue () const
void print (std::ostream &os) const override
Output to a given output stream.
void setType (const AstTypeIdentifier &type)
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
AstTypeIdentifier type
The target type name.
std::unique_ptr< AstArgument > value
The value to be casted.
Detailed Description
An argument capable of casting a value of one type into another.
Definition at line 536 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstTypeCast::AstTypeCast (std::unique_ptr< AstArgument > value, const AstTypeIdentifier & type) inline
Definition at line 538 of file AstArgument.h.
             : value(std::move(value)), type(type) {}
Member Function Documentation
void souffle::AstTypeCast::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 572 of file AstArgument.h.
{
         value = map(std::move(value));
     }
AstTypeCast* souffle::AstTypeCast::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstArgument.
Definition at line 565 of file AstArgument.h.
References souffle::AstNode::getSrcLoc().
{
         auto res = new AstTypeCast(std::unique_ptr<AstArgument>(value->clone()), type);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstTypeCast::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 584 of file AstArgument.h.
{
         assert(nullptr != dynamic_cast<const AstTypeCast*>(&node));
         const auto& other = static_cast<const AstTypeCast&>(node);
         return type == other.type && *value == *other.value;
     }
std::vector<const AstNode*> souffle::AstTypeCast::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 558 of file AstArgument.h.
References souffle::AstArgument::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         res.push_back(value.get());
         return res;
     }
const AstTypeIdentifier& souffle::AstTypeCast::getType () const inline
Definition at line 549 of file AstArgument.h.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
         return type;
     }
AstArgument* souffle::AstTypeCast::getValue () const inline
Definition at line 545 of file AstArgument.h.
Referenced by souffle::getGroundedTerms(), souffle::BddBddBTranslator::visitTypeCast(), and souffle::LogicbloxConverter::visitTypeCast().
{
         return value.get();
     }
void souffle::AstTypeCast::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 541 of file AstArgument.h.
{
         os << "as(" << *value << "," << type << ")";
     }
void souffle::AstTypeCast::setType (const AstTypeIdentifier & type) inline
Definition at line 553 of file AstArgument.h.
{
         this->type = type;
     }
Field Documentation
AstTypeIdentifier souffle::AstTypeCast::type protected
The target type name.
Definition at line 581 of file AstArgument.h.
std::unique_ptr<AstArgument> souffle::AstTypeCast::value protected
The value to be casted.
Definition at line 578 of file AstArgument.h.
The documentation for this class was generated from the following file:
AstArgument.h