souffle: souffle::AstExecutionPlan Class Reference
souffle::AstExecutionPlan Class Reference
The class utilized to model user-defined execution plans for various versions of clauses.
#include <AstClause.h>
Public Types
using const_iterator = typename std::map< int, AstExecutionOrder >::const_iterator
Public Member Functions
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstExecutionPlan ()=default
AstExecutionPlan * clone () const override
Create a clone (i.e.
bool empty () const
Tests whether there has any order been defined.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const int getMaxVersion () const
get maximal version number
const AstExecutionOrder & getOrderFor (int version) const
Obtains the order defined for the given version.
std::map< int, const AstExecutionOrder * > getOrders () const
bool hasOrderFor (int version) const
Determines whether for the given version a plan has been specified.
void print (std::ostream &out) const override
Output to a given output stream.
void setOrderFor (int version, std::unique_ptr< AstExecutionOrder > plan)
Updates the execution order for a special version of a rule.
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Private Attributes
int maxVersion = -1
remember maximal version number
std::map< int, std::unique_ptr< AstExecutionOrder > > plans
Mapping versions of clauses to execution plans.
Detailed Description
The class utilized to model user-defined execution plans for various versions of clauses.
Definition at line 117 of file AstClause.h.
Member Typedef Documentation
using souffle::AstExecutionPlan::const_iterator = typename std::map<int, AstExecutionOrder>::const_iterator
Definition at line 119 of file AstClause.h.
Constructor & Destructor Documentation
souffle::AstExecutionPlan::AstExecutionPlan () default
Member Function Documentation
void souffle::AstExecutionPlan::apply (const AstNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Implements souffle::AstNode.
Definition at line 185 of file AstClause.h.
{
         for (auto& plan : plans) {
             plan.second = map(std::move(plan.second));
         }
     }
AstExecutionPlan* souffle::AstExecutionPlan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 176 of file AstClause.h.
References souffle::AstNode::getSrcLoc().
{
         auto res = new AstExecutionPlan();
         res->setSrcLoc(getSrcLoc());
         for (auto& plan : plans) {
             res->setOrderFor(plan.first, std::unique_ptr<AstExecutionOrder>(plan.second->clone()));
         }
         return res;
     }
bool souffle::AstExecutionPlan::empty () const inline
Tests whether there has any order been defined.
Definition at line 148 of file AstClause.h.
{
         return plans.empty();
     }
bool souffle::AstExecutionPlan::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 202 of file AstClause.h.
References plans.
{
         assert(nullptr != dynamic_cast<const AstExecutionPlan*>(&node));
         const auto& other = static_cast<const AstExecutionPlan&>(node);
         if (maxVersion != other.maxVersion) {
             return false;
         }
         if (plans.size() != other.plans.size()) {
             return false;
         }
         auto iter = plans.begin();
         auto otherIter = other.plans.begin();
         for (; iter != plans.end(); ++iter, ++otherIter) {
             if (iter->first != otherIter->first) {
                 return false;
             }
             if (*iter->second != *otherIter->second) {
                 return false;
             }
         }
         return true;
     }
std::vector<const AstNode*> souffle::AstExecutionPlan::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 192 of file AstClause.h.
{
         std::vector<const AstNode*> childNodes;
         for (auto& plan : plans) {
             childNodes.push_back(plan.second.get());
         }
         return childNodes;
     }
const int souffle::AstExecutionPlan::getMaxVersion () const inline
get maximal version number
Definition at line 137 of file AstClause.h.
Referenced by souffle::AstTranslator::translateRecursiveRelation().
{
         return maxVersion;
     }
const AstExecutionOrder& souffle::AstExecutionPlan::getOrderFor (int version) const inline
Obtains the order defined for the given version.
Definition at line 142 of file AstClause.h.
Referenced by souffle::AstTranslator::ClauseTranslator::getReorderedClause().
{
         assert(hasOrderFor(version));
         return *plans.find(version)->second;
     }
std::map<int, const AstExecutionOrder*> souffle::AstExecutionPlan::getOrders () const inline
Definition at line 152 of file AstClause.h.
Referenced by souffle::AstSemanticChecker::checkClause().
{
         std::map<int, const AstExecutionOrder*> result;
         for (auto& plan : plans) {
             result.insert(std::make_pair(plan.first, plan.second.get()));
         }
         return result;
     }
bool souffle::AstExecutionPlan::hasOrderFor (int version) const inline
Determines whether for the given version a plan has been specified.
Definition at line 132 of file AstClause.h.
{
         return plans.find(version) != plans.end();
     }
void souffle::AstExecutionPlan::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 160 of file AstClause.h.
Referenced by souffle::AstClause::print().
{
         if (!plans.empty()) {
             out << "\n\n   .plan ";
             bool first = true;
             for (const auto& plan : plans) {
                 if (first) {
                     first = false;
                 } else {
                     out << ",";
                 }
                 out << plan.first << ":";
                 plan.second->print(out);
             }
         }
     }
void souffle::AstExecutionPlan::setOrderFor (int version, std::unique_ptr< AstExecutionOrder > plan) inline
Updates the execution order for a special version of a rule.
Definition at line 124 of file AstClause.h.
{
         plans[version] = std::move(plan);
         if (version > maxVersion) {
             maxVersion = version;
         }
     }
Field Documentation
int souffle::AstExecutionPlan::maxVersion = -1 private
remember maximal version number
Definition at line 229 of file AstClause.h.
std::map<int, std::unique_ptr<AstExecutionOrder> > souffle::AstExecutionPlan::plans private
Mapping versions of clauses to execution plans.
Definition at line 226 of file AstClause.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstClause.h