souffle: souffle::RamIndexRelationSearch Class Reference
souffle::RamIndexRelationSearch Class Reference
Relation Scan with Index.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getRangePattern () const
Get range pattern.
RamIndexRelationSearch (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationSearch
const RamRelation & getRelation () const
Get search relation.
RamRelationSearch (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamSearch
int getTupleId () const
Get identifier.
RamSearch (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
void print (std::ostream &os, int tabpos) const override
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create a clone (i.e.
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Abstract equality check for two RAM nodes.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationSearch
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamSearch
const int identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Relation Scan with Index.
Search for tuples of a relation matching a criteria
Definition at line 199 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamIndexRelationSearch::RamIndexRelationSearch (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 201 of file RamOperation.h.
             : RamRelationSearch(std::move(r), ident, std::move(nested), std::move(profileText)),
               queryPattern(std::move(queryPattern)) {
         assert(getRangePattern().size() == getRelation().getArity());
     }
Member Function Documentation
void souffle::RamIndexRelationSearch::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamRelationSearch.
Reimplemented in souffle::RamIndexAggregate, and souffle::RamIndexChoice.
Definition at line 224 of file RamOperation.h.
References souffle::RamRelationSearch::apply().
Referenced by souffle::RamIndexAggregate::apply().
{
         RamRelationSearch::apply(map);
         for (auto& cur : queryPattern) {
             if (cur != nullptr) {
                 cur = map(std::move(cur));
             }
         }
     }
bool souffle::RamIndexRelationSearch::equal (const RamNode & other) const inline override protected virtual
Abstract equality check for two RAM nodes.
Reimplemented from souffle::RamRelationSearch.
Reimplemented in souffle::RamIndexAggregate, and souffle::RamIndexChoice.
Definition at line 237 of file RamOperation.h.
References souffle::RamRelationSearch::equal(), and souffle::equal_targets().
Referenced by souffle::RamIndexAggregate::equal().
{
         assert(nullptr != dynamic_cast<const RamIndexRelationSearch*>(&node));
         const auto& other = static_cast<const RamIndexRelationSearch&>(node);
         return RamRelationSearch::equal(other) && equal_targets(queryPattern, other.queryPattern);
     }
std::vector<const RamNode*> souffle::RamIndexRelationSearch::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamRelationSearch.
Reimplemented in souffle::RamIndexAggregate, and souffle::RamIndexChoice.
Definition at line 214 of file RamOperation.h.
References souffle::RamRelationSearch::getChildNodes().
Referenced by souffle::RamIndexChoice::getChildNodes(), and souffle::RamIndexAggregate::getChildNodes().
{
         auto res = RamRelationSearch::getChildNodes();
         for (auto& cur : queryPattern) {
             if (cur != nullptr) {
                 res.push_back(cur.get());
             }
         }
         return res;
     }
std::vector<RamExpression*> souffle::RamIndexRelationSearch::getRangePattern () const inline
Get range pattern.
Definition at line 210 of file RamOperation.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), souffle::RamIndexKeysAnalysis::getRangeQueryColumns(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), and souffle::LVMGenerator::visitIndexScan().
{
         return toPtrVector(queryPattern);
     }
Field Documentation
std::vector<std::unique_ptr<RamExpression> > souffle::RamIndexRelationSearch::queryPattern protected
Values of index per column of table (if indexable)
Definition at line 235 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h