souffle: souffle::SignalHandler Class Reference
souffle::SignalHandler Class Reference
Class SignalHandler captures signals and reports the context where the signal occurs.
#include <SignalHandler.h>
Public Member Functions
void enableLogging ()
void error (const std::string &error)
void reset ()
void set ()
void setMsg (const char *m)
Static Public Member Functions
static SignalHandler * instance ()
Private Member Functions
SignalHandler ()
Static Private Member Functions
static void handler (int signal)
Signal handler for various types of signals.
Private Attributes
bool isSet = false
bool logMessages = false
std::atomic< const char * > msg
void(* prevFpeHandler)(int) = nullptr
void(* prevIntHandler)(int) = nullptr
void(* prevSegVHandler)(int) = nullptr
Detailed Description
Class SignalHandler captures signals and reports the context where the signal occurs.
The signal handler is implemented as a singleton.
Definition at line 34 of file SignalHandler.h.
Constructor & Destructor Documentation
souffle::SignalHandler::SignalHandler () inline private
Definition at line 176 of file SignalHandler.h.
 : msg(nullptr) {}
Member Function Documentation
void souffle::SignalHandler::enableLogging () inline
Definition at line 43 of file SignalHandler.h.
References logMessages.
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
{
         logMessages = true;
     }
void souffle::SignalHandler::error (const std::string & error) inline
Definition at line 125 of file SignalHandler.h.
References msg.
Referenced by handler().
{
         if (msg != nullptr) {
             std::cerr << error << " in rule:\n" << msg << std::endl;
         } else {
             std::cerr << error << std::endl;
         }
         exit(1);
     }
static void souffle::SignalHandler::handler (int signal) inline static private
Signal handler for various types of signals.
Definition at line 151 of file SignalHandler.h.
References error(), instance(), and msg.
Referenced by set().
{
         const char* msg = instance()->msg;
         std::string error;
         switch (signal) {
             case SIGINT:
                 error = "Interrupt";
                 break;
             case SIGFPE:
                 error = "Floating-point arithmetic exception";
                 break;
             case SIGSEGV:
                 error = "Segmentation violation";
                 break;
             default:
                 error = "Unknown";
                 break;
         }
         if (msg != nullptr) {
             std::cerr << error << " signal in rule:\n" << msg << std::endl;
         } else {
             std::cerr << error << " signal." << std::endl;
         }
         exit(1);
     }
static SignalHandler* souffle::SignalHandler::instance () inline static
Definition at line 37 of file SignalHandler.h.
Referenced by souffle::RAMI::evalStmt(), souffle::LVM::execute(), souffle::RAMI::executeMain(), souffle::LVM::executeMain(), and handler().
{
         static SignalHandler singleton;
         return &singleton;
     }
void souffle::SignalHandler::reset () inline
Definition at line 100 of file SignalHandler.h.
References isSet, prevFpeHandler, prevIntHandler, and prevSegVHandler.
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
                  {
         if (isSet) {
             // reset floating point exception
             if (signal(SIGFPE, prevFpeHandler) == SIG_ERR) {
                 perror("Failed to reset SIGFPE signal handler.");
                 exit(1);
             }
             // user interrupts
             if (signal(SIGINT, prevIntHandler) == SIG_ERR) {
                 perror("Failed to reset SIGINT signal handler.");
                 exit(1);
             }
             // memory issues
             if (signal(SIGSEGV, prevSegVHandler) == SIG_ERR) {
                 perror("Failed to reset SIGSEGV signal handler.");
                 exit(1);
             }
             isSet = false;
         }
     }
void souffle::SignalHandler::set () inline
Definition at line 75 of file SignalHandler.h.
References handler(), isSet, prevFpeHandler, prevIntHandler, and prevSegVHandler.
Referenced by souffle::RAMI::executeMain(), and souffle::LVM::executeMain().
                {
         if (!isSet) {
             // register signals
             // floating point exception
             if ((prevFpeHandler = signal(SIGFPE, handler)) == SIG_ERR) {
                 perror("Failed to set SIGFPE signal handler.");
                 exit(1);
             }
             // user interrupts
             if ((prevIntHandler = signal(SIGINT, handler)) == SIG_ERR) {
                 perror("Failed to set SIGINT signal handler.");
                 exit(1);
             }
             // memory issues
             if ((prevSegVHandler = signal(SIGSEGV, handler)) == SIG_ERR) {
                 perror("Failed to set SIGSEGV signal handler.");
                 exit(1);
             }
             isSet = true;
         }
     }
void souffle::SignalHandler::setMsg (const char * m) inline
Definition at line 47 of file SignalHandler.h.
References logMessages, m, and msg.
Referenced by souffle::RAMI::evalStmt(), and souffle::LVM::execute().
{
         if (logMessages && m != nullptr) {
             static std::mutex outputMutex;
             static bool sameLine = false;
             std::lock_guard<std::mutex> guard(outputMutex);
             if (msg != nullptr && strcmp(m, msg) == 0) {
                 std::cout << ".";
                 sameLine = true;
             } else {
                 if (sameLine) {
                     sameLine = false;
                     std::cout << std::endl;
                 }
                 std::string outputMessage(m);
                 for (char& c : outputMessage) {
                     if (c == '\n' || c == '\t') {
                         c = ' ';
                     }
                 }
                 std::cout << "Starting work on " << outputMessage << std::endl;
             }
         }
         msg = m;
     }
Field Documentation
bool souffle::SignalHandler::isSet = false private
Definition at line 139 of file SignalHandler.h.
Referenced by reset(), and set().
bool souffle::SignalHandler::logMessages = false private
Definition at line 141 of file SignalHandler.h.
Referenced by enableLogging(), and setMsg().
std::atomic<const char*> souffle::SignalHandler::msg private
Definition at line 136 of file SignalHandler.h.
Referenced by error(), handler(), and setMsg().
void(* souffle::SignalHandler::prevFpeHandler) (int) = nullptr private
Definition at line 144 of file SignalHandler.h.
Referenced by reset(), and set().
void(* souffle::SignalHandler::prevIntHandler) (int) = nullptr private
Definition at line 145 of file SignalHandler.h.
Referenced by reset(), and set().
void(* souffle::SignalHandler::prevSegVHandler) (int) = nullptr private
Definition at line 146 of file SignalHandler.h.
Referenced by reset(), and set().
The documentation for this class was generated from the following file:
SignalHandler.h