souffle: souffle::UnionType Class Reference
souffle::UnionType Class Reference
A union type combining a list of types into a new, aggregated type.
#include <TypeSystem.h>
Public Member Functions
void add (const Type &type)
const std::vector< const Type * > & getElementTypes () const
void print (std::ostream &out) const override
Public Member Functions inherited from souffle::Type
const AstTypeIdentifier & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const TypeEnvironment &environment, AstTypeIdentifier name)
Type (const Type &other)=delete
virtual ~Type ()=default
Private Member Functions
UnionType (const TypeEnvironment &environment, const AstTypeIdentifier &name)
Private Attributes
std::vector< const Type * > elementTypes
The contained element types.
Friends
class TypeEnvironment
Additional Inherited Members
Protected Attributes inherited from souffle::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
Detailed Description
A union type combining a list of types into a new, aggregated type.
Definition at line 116 of file TypeSystem.h.
Constructor & Destructor Documentation
souffle::UnionType::UnionType (const TypeEnvironment & environment, const AstTypeIdentifier & name) inline private
Definition at line 133 of file TypeSystem.h.
 : Type(environment, name) {}
Member Function Documentation
void souffle::UnionType::add (const Type & type)
Definition at line 35 of file TypeSystem.cpp.
References souffle::Type::environment, and souffle::TypeEnvironment::isType().
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     assert(environment.isType(type));
     elementTypes.push_back(&type);
 }
const std::vector<const Type*>& souffle::UnionType::getElementTypes () const inline
Definition at line 120 of file TypeSystem.h.
References souffle::Type::print().
Referenced by souffle::getGreatestCommonSubtypes(), souffle::getTypeQualifier(), and souffle::isRecursiveType().
{
         return elementTypes;
     }
void souffle::UnionType::print (std::ostream & out) const override virtual
Reimplemented from souffle::Type.
Definition at line 40 of file TypeSystem.cpp.
References souffle::Type::getName(), and souffle::join().
{
     out << getName() << " = "
         << join(elementTypes, " | ", [](std::ostream& out, const Type* type) { out << type->getName(); });
 }
Friends And Related Function Documentation
friend class TypeEnvironment friend
Definition at line 128 of file TypeSystem.h.
Field Documentation
std::vector<const Type*> souffle::UnionType::elementTypes private
The contained element types.
Definition at line 131 of file TypeSystem.h.
The documentation for this class was generated from the following files:
TypeSystem.h
TypeSystem.cpp