souffle: souffle::RamIntrinsicOperator Class Reference
souffle::RamIntrinsicOperator Class Reference
Operator that represents an intrinsic (built-in) functor.
#include <RamExpression.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamIntrinsicOperator * clone () const override
Create clone.
size_t getArgCount () const
Get number of arguments.
const RamExpression * getArgument (size_t i) const
Get i-th argument value.
std::vector< RamExpression * > getArguments () const
Get argument values.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
FunctorOp getOperator () const
Get operator symbol.
void print (std::ostream &os) const override
Print.
template<typename... Args>
RamIntrinsicOperator (FunctorOp op, Args...args)
RamIntrinsicOperator (FunctorOp op, std::vector< std::unique_ptr< RamExpression >> args)
Public Member Functions inherited from souffle::RamExpression
RamExpression ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > arguments
Arguments of the function.
const FunctorOp operation
Operation symbol.
Detailed Description
Operator that represents an intrinsic (built-in) functor.
Definition at line 51 of file RamExpression.h.
Constructor & Destructor Documentation
template<typename... Args> souffle::RamIntrinsicOperator::RamIntrinsicOperator (FunctorOp op, Args... args) inline
Definition at line 54 of file RamExpression.h.
                                                      : RamExpression(), operation(op) {
         std::unique_ptr<RamExpression> tmp[] = {std::move(args)...};
         for (auto& cur : tmp) {
             arguments.push_back(std::move(cur));
         }
     }
souffle::RamIntrinsicOperator::RamIntrinsicOperator (FunctorOp op, std::vector< std::unique_ptr< RamExpression >> args) inline
Definition at line 61 of file RamExpression.h.
             : RamExpression(), operation(op), arguments(std::move(args)) {}
Member Function Documentation
void souffle::RamIntrinsicOperator::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 120 of file RamExpression.h.
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
RamIntrinsicOperator* souffle::RamIntrinsicOperator::clone () const inline override virtual
Create clone.
Implements souffle::RamExpression.
Definition at line 110 of file RamExpression.h.
{
         std::vector<std::unique_ptr<RamExpression>> argsCopy;
         for (auto& arg : arguments) {
             argsCopy.emplace_back(arg->clone());
         }
         auto res = new RamIntrinsicOperator(operation, std::move(argsCopy));
         return res;
     }
bool souffle::RamIntrinsicOperator::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 134 of file RamExpression.h.
References souffle::equal_targets(), and getOperator().
{
         assert(nullptr != dynamic_cast<const RamIntrinsicOperator*>(&node));
         const auto& other = static_cast<const RamIntrinsicOperator&>(node);
         return getOperator() == other.getOperator() && equal_targets(arguments, other.arguments);
     }
size_t souffle::RamIntrinsicOperator::getArgCount () const inline
Get number of arguments.
Definition at line 96 of file RamExpression.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return arguments.size();
     }
const RamExpression* souffle::RamIntrinsicOperator::getArgument (size_t i) const inline
Get i-th argument value.
Definition at line 90 of file RamExpression.h.
References i.
Referenced by souffle::Synthesiser::emitCode().
{
         assert(i >= 0 && i < arguments.size() && "argument index out of bounds");
         return arguments[i].get();
     }
std::vector<RamExpression*> souffle::RamIntrinsicOperator::getArguments () const inline
Get argument values.
Definition at line 85 of file RamExpression.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalExpr(), souffle::RamLevelAnalysis::getLevel(), and souffle::LVMGenerator::visitIntrinsicOperator().
{
         return toPtrVector(arguments);
     }
std::vector<const RamNode*> souffle::RamIntrinsicOperator::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 101 of file RamExpression.h.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
FunctorOp souffle::RamIntrinsicOperator::getOperator () const inline
Get operator symbol.
Definition at line 80 of file RamExpression.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalExpr(), and souffle::LVMGenerator::visitIntrinsicOperator().
{
         return operation;
     }
void souffle::RamIntrinsicOperator::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 65 of file RamExpression.h.
References souffle::getSymbolForFunctorOp(), souffle::isInfixFunctorOp(), and souffle::join().
{
         if (isInfixFunctorOp(operation)) {
             os << "(";
             os << join(arguments, getSymbolForFunctorOp(operation),
                     print_deref<std::unique_ptr<RamExpression>>());
             os << ")";
         } else {
             os << getSymbolForFunctorOp(operation);
             os << "(";
             os << join(arguments, ",", print_deref<std::unique_ptr<RamExpression>>());
             os << ")";
         }
     }
Field Documentation
std::vector<std::unique_ptr<RamExpression> > souffle::RamIntrinsicOperator::arguments protected
Arguments of the function.
Definition at line 131 of file RamExpression.h.
const FunctorOp souffle::RamIntrinsicOperator::operation protected
Operation symbol.
Definition at line 128 of file RamExpression.h.
The documentation for this class was generated from the following file:
RamExpression.h