souffle: souffle::AstIO Class Reference
souffle::AstIO Class Reference
Intermediate representation of IO operations.
#include <AstIO.h>
Public Member Functions
void addKVP (const std::string &key, const std::string &value)
void addName (const AstRelationIdentifier &name)
Set kvp map name.
void apply (const AstNodeMapper &) override
No nested nodes to apply to.
AstIO ()=default
AstIO * clone () const override
Creates a clone of this AST sub-structure.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
const std::map< std::string, std::string > & getIODirectiveMap () const
const AstRelationIdentifier & getName () const
Return the name of this kvp map.
const std::set< AstRelationIdentifier > & getNames () const
Return the names of this kvp map.
void print (std::ostream &os) const override
Output to a given output stream.
void setName (const AstRelationIdentifier &name)
Set kvp map name.
~AstIO () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
AstIO (const AstIO &io)
bool equal (const AstNode &node) const override
An internal function to determine equality to another node.
std::string unescape (const std::string &inputString) const
std::string unescape (const std::string &inputString, const std::string &needle, const std::string &replacement) const
Protected Attributes
std::map< std::string, std::string > kvps
kvp map
std::set< AstRelationIdentifier > names
Name of the kvp.
Detailed Description
Intermediate representation of IO operations.
Definition at line 31 of file AstIO.h.
Constructor & Destructor Documentation
souffle::AstIO::AstIO () default
Referenced by clone().
souffle::AstIO::~AstIO () override default
souffle::AstIO::AstIO (const AstIO & io) inline protected
Definition at line 110 of file AstIO.h.
 : names(io.names), kvps(io.kvps) {}
Member Function Documentation
void souffle::AstIO::addKVP (const std::string & key, const std::string & value) inline
Definition at line 101 of file AstIO.h.
References kvps, and unescape().
Referenced by souffle::AstPrintSize::AstPrintSize().
{
         kvps[key] = unescape(value);
     }
void souffle::AstIO::addName (const AstRelationIdentifier & name) inline
Set kvp map name.
Definition at line 92 of file AstIO.h.
References names.
{
         names.insert(name);
     }
void souffle::AstIO::apply (const AstNodeMapper &) inline override virtual
No nested nodes to apply to.
Implements souffle::AstNode.
Definition at line 52 of file AstIO.h.
 {}
AstIO* souffle::AstIO::clone () const inline override virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Reimplemented in souffle::AstPrintSize, souffle::AstLoad, and souffle::AstStore.
Definition at line 43 of file AstIO.h.
References AstIO(), souffle::AstNode::getSrcLoc(), kvps, and names.
{
         auto res = new AstIO();
         res->names = names;
         res->kvps = kvps;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstIO::equal (const AstNode & node) const inline override protected virtual
An internal function to determine equality to another node.
Implements souffle::AstNode.
Reimplemented in souffle::AstPrintSize, souffle::AstLoad, and souffle::AstStore.
Definition at line 113 of file AstIO.h.
References kvps, and names.
{
         assert(nullptr != dynamic_cast<const AstIO*>(&node));
         const auto& other = static_cast<const AstIO&>(node);
         return other.names == names && other.kvps == kvps;
     }
std::vector<const AstNode*> souffle::AstIO::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 37 of file AstIO.h.
{
         // type is just cached, not essential
         return std::vector<const AstNode*>();
     }
const std::map<std::string, std::string>& souffle::AstIO::getIODirectiveMap () const inline
Definition at line 105 of file AstIO.h.
References kvps.
Referenced by souffle::MagicSetTransformer::transform().
{
         return kvps;
     }
const AstRelationIdentifier& souffle::AstIO::getName () const inline
Return the name of this kvp map.
Definition at line 82 of file AstIO.h.
References names.
Referenced by souffle::MagicSetTransformer::transform().
{
         return *names.begin();
     }
const std::set<AstRelationIdentifier>& souffle::AstIO::getNames () const inline
Return the names of this kvp map.
Definition at line 87 of file AstIO.h.
References names.
Referenced by print().
{
         return names;
     }
void souffle::AstIO::print (std::ostream & os) const inline override virtual
Output to a given output stream.
Implements souffle::AstNode.
Reimplemented in souffle::AstPrintSize, souffle::AstLoad, and souffle::AstStore.
Definition at line 55 of file AstIO.h.
References getNames(), and kvps.
Referenced by souffle::AstStore::print(), souffle::AstLoad::print(), and souffle::AstPrintSize::print().
{
         bool first = true;
         for (auto& relationName : getNames()) {
             if (first) {
                 first = false;
             } else {
                 os << ',';
             }
             os << relationName;
         }
         if (kvps.empty()) {
             return;
         }
         os << "(";
         first = true;
         for (auto& pair : kvps) {
             if (first) {
                 first = false;
             } else {
                 os << ',';
             }
             os << pair.first << "=\"" << pair.second << "\"";
         }
         os << ')';
     }
void souffle::AstIO::setName (const AstRelationIdentifier & name) inline
Set kvp map name.
Definition at line 96 of file AstIO.h.
References names.
{
         names.clear();
         names.insert(name);
     }
std::string souffle::AstIO::unescape (const std::string & inputString) const inline protected
Definition at line 119 of file AstIO.h.
Referenced by addKVP().
{
         std::string unescaped = unescape(inputString, "\\\"", "\"");
         unescaped = unescape(unescaped, "\\t", "\t");
         unescaped = unescape(unescaped, "\\r", "\r");
         unescaped = unescape(unescaped, "\\n", "\n");
         return unescaped;
     }
std::string souffle::AstIO::unescape (const std::string & inputString, const std::string & needle, const std::string & replacement) const inline protected
Definition at line 127 of file AstIO.h.
{
         std::string result = inputString;
         size_t pos = 0;
         while ((pos = result.find(needle, pos)) != std::string::npos) {
             result = result.replace(pos, needle.length(), replacement);
             pos += replacement.length();
         }
         return result;
     }
Field Documentation
std::map<std::string, std::string> souffle::AstIO::kvps protected
kvp map
Definition at line 141 of file AstIO.h.
Referenced by addKVP(), clone(), souffle::AstStore::clone(), souffle::AstLoad::clone(), souffle::AstPrintSize::clone(), equal(), souffle::AstStore::equal(), souffle::AstLoad::equal(), getIODirectiveMap(), and print().
std::set<AstRelationIdentifier> souffle::AstIO::names protected
Name of the kvp.
Definition at line 138 of file AstIO.h.
Referenced by addName(), clone(), souffle::AstStore::clone(), souffle::AstLoad::clone(), souffle::AstPrintSize::clone(), equal(), souffle::AstStore::equal(), souffle::AstLoad::equal(), souffle::AstPrintSize::equal(), getName(), getNames(), and setName().
The documentation for this class was generated from the following file:
AstIO.h