souffle: souffle::AstLiteral Class Reference
souffle::AstLiteral Class Reference abstract
Intermediate representation of atoms, binary relations, and negated atoms in the body and head of a clause.
#include <AstLiteral.h>
Public Member Functions
AstLiteral ()=default
AstLiteral * clone () const override=0
Creates a clone of this AST sub-structure.
virtual const AstAtom * getAtom () const =0
Obtains the atom referenced by this literal - if any.
~AstLiteral () override=default
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &mapper)=0
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const =0
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::AstNode
virtual bool equal (const AstNode &other) const =0
Abstract equality check for two AST nodes.
Detailed Description
Intermediate representation of atoms, binary relations, and negated atoms in the body and head of a clause.
Definition at line 44 of file AstLiteral.h.
Constructor & Destructor Documentation
souffle::AstLiteral::AstLiteral () default
souffle::AstLiteral::~AstLiteral () override default
Member Function Documentation
AstLiteral* souffle::AstLiteral::clone () const override pure virtual
Creates a clone of this AST sub-structure.
Implements souffle::AstNode.
Implemented in souffle::AstBinaryConstraint, souffle::AstBooleanConstraint, souffle::AstConstraint, souffle::AstProvenanceNegation, souffle::AstNegation, and souffle::AstAtom.
Referenced by souffle::AstConstraint::getAtom().
virtual const AstAtom* souffle::AstLiteral::getAtom () const pure virtual
Obtains the atom referenced by this literal - if any.
Implemented in souffle::AstConstraint, souffle::AstProvenanceNegation, souffle::AstNegation, and souffle::AstAtom.
Referenced by souffle::AstSemanticChecker::checkLiteral(), and souffle::isValidMove().
The documentation for this class was generated from the following file:
AstLiteral.h