souffle: souffle::RamCreate Class Reference
souffle::RamCreate Class Reference
Create new RAM relation.
#include <RamStatement.h>
Public Member Functions
RamCreate * clone () const override
Create clone.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamCreate (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelation & getRelation () const
Get RAM relation.
RamRelationStatement (std::unique_ptr< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamRelationStatement
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr< RamRelationReference > relationRef
Relation.
Detailed Description
Create new RAM relation.
Definition at line 92 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamCreate::RamCreate (std::unique_ptr< RamRelationReference > relRef) inline
Definition at line 94 of file RamStatement.h.
 : RamRelationStatement(std::move(relRef)) {}
Member Function Documentation
RamCreate* souffle::RamCreate::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 104 of file RamStatement.h.
{
         RamCreate* res = new RamCreate(std::unique_ptr<RamRelationReference>(relationRef->clone()));
         return res;
     }
void souffle::RamCreate::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 97 of file RamStatement.h.
References souffle::RamRelation::getName(), souffle::RamRelation::getRepresentation(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "CREATE " << rel.getName() << " " << rel.getRepresentation() << std::endl;
     };
The documentation for this class was generated from the following file:
RamStatement.h