souffle: souffle::AstProvenanceNegation Class Reference
souffle::AstProvenanceNegation Class Reference
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
#include <AstLiteral.h>
Public Member Functions
void apply (const AstNodeMapper &map) override
Mutates this node.
AstProvenanceNegation (std::unique_ptr< AstAtom > atom)
AstProvenanceNegation * clone () const override
Creates a clone if this AST sub-structure.
const AstAtom * getAtom () const override
Returns the nested atom as the referenced atom.
AstAtom * getAtom ()
Return the negated atom.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
void print (std::ostream &os) const override
Output to a given stream.
~AstProvenanceNegation () override=default
Public Member Functions inherited from souffle::AstLiteral
AstLiteral ()=default
~AstLiteral () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::unique_ptr< AstAtom > atom
A pointer to the negated Atom.
Detailed Description
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
A Negated atom occurs in a body of clause and cannot occur in a head of a clause.
Specialised for provenance: used for existence check that tuple doesn't already exist
Definition at line 232 of file AstLiteral.h.
Constructor & Destructor Documentation
souffle::AstProvenanceNegation::AstProvenanceNegation (std::unique_ptr< AstAtom > atom) inline
Definition at line 234 of file AstLiteral.h.
 : atom(std::move(atom)) {}
souffle::AstProvenanceNegation::~AstProvenanceNegation () override default
Member Function Documentation
void souffle::AstProvenanceNegation::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 262 of file AstLiteral.h.
{
         atom = map(std::move(atom));
     }
AstProvenanceNegation* souffle::AstProvenanceNegation::clone () const inline override virtual
Creates a clone if this AST sub-structure.
Implements souffle::AstLiteral.
Definition at line 255 of file AstLiteral.h.
References souffle::AstNode::getSrcLoc(), and souffle::AstNode::setSrcLoc().
{
         AstProvenanceNegation* res = new AstProvenanceNegation(std::unique_ptr<AstAtom>(atom->clone()));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstProvenanceNegation::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 276 of file AstLiteral.h.
References atom.
{
         assert(dynamic_cast<const AstProvenanceNegation*>(&node));
         const auto& other = static_cast<const AstProvenanceNegation&>(node);
         return *atom == *other.atom;
     }
const AstAtom* souffle::AstProvenanceNegation::getAtom () const inline override virtual
Returns the nested atom as the referenced atom.
Implements souffle::AstLiteral.
Definition at line 239 of file AstLiteral.h.
Referenced by souffle::AstTranslator::translateConstraint().
{
         return atom.get();
     }
AstAtom* souffle::AstProvenanceNegation::getAtom () inline
Return the negated atom.
Definition at line 244 of file AstLiteral.h.
{
         return atom.get();
     }
std::vector<const AstNode*> souffle::AstProvenanceNegation::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Definition at line 267 of file AstLiteral.h.
{
         return {atom.get()};
     }
void souffle::AstProvenanceNegation::print (std::ostream & os) const inline override virtual
Output to a given stream.
Implements souffle::AstNode.
Definition at line 249 of file AstLiteral.h.
{
         os << "prov!";
         atom->print(os);
     }
Field Documentation
std::unique_ptr<AstAtom> souffle::AstProvenanceNegation::atom protected
A pointer to the negated Atom.
Definition at line 273 of file AstLiteral.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstLiteral.h