souffle: souffle::AstNode Class Reference
souffle::AstNode Class Reference abstract
Abstract class for syntactic elements in a Datalog program.
#include <AstNode.h>
Public Member Functions
virtual void apply (const AstNodeMapper &mapper)=0
Apply the mapper to all child nodes.
virtual AstNode * clone () const =0
Create a clone (i.e.
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const =0
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
virtual bool equal (const AstNode &other) const =0
Abstract equality check for two AST nodes.
Private Attributes
SrcLocation location
Source location of a syntactic element.
Friends
std::ostream & operator<< (std::ostream &out, const AstNode &node)
Print node onto an output stream.
Detailed Description
Abstract class for syntactic elements in a Datalog program.
Definition at line 40 of file AstNode.h.
Constructor & Destructor Documentation
virtual souffle::AstNode::~AstNode () virtual default
Member Function Documentation
virtual void souffle::AstNode::apply (const AstNodeMapper & mapper) pure virtual
Apply the mapper to all child nodes.
Implemented in souffle::AstSubroutineArgument, souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, souffle::AstBinaryConstraint, souffle::AstClause, souffle::AstIntrinsicFunctor, souffle::AstBooleanConstraint, souffle::AstComponent, souffle::AstProvenanceNegation, souffle::AstRelation, souffle::AstNegation, souffle::AstExecutionPlan, souffle::AstConstant, souffle::AstCounter, souffle::AstType, souffle::AstAtom, souffle::AstComponentInit, souffle::AstProgram, souffle::AstUnnamedVariable, souffle::AstFunctorDeclaration, souffle::AstVariable, souffle::AstExecutionOrder, souffle::AstComponentType, souffle::AstAttribute, souffle::AstPragma, and souffle::AstIO.
Referenced by operator!=(), and souffle::renameVariables().
virtual AstNode* souffle::AstNode::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::AstSubroutineArgument, souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, souffle::AstBinaryConstraint, souffle::AstClause, souffle::AstIntrinsicFunctor, souffle::AstBooleanConstraint, souffle::AstRecordType, souffle::AstConstraint, souffle::AstComponent, souffle::AstNullConstant, souffle::AstProvenanceNegation, souffle::AstPrintSize, souffle::AstNumberConstant, souffle::AstUnionType, souffle::AstStringConstant, souffle::AstRelation, souffle::AstLoad, souffle::AstNegation, souffle::AstPrimitiveType, souffle::AstExecutionPlan, souffle::AstStore, souffle::AstCounter, souffle::AstType, souffle::AstProgram, souffle::AstComponentInit, souffle::AstAtom, souffle::AstFunctorDeclaration, souffle::AstUnnamedVariable, souffle::AstVariable, souffle::AstExecutionOrder, souffle::AstComponentType, souffle::AstAttribute, souffle::AstLiteral, souffle::AstArgument, souffle::AstPragma, and souffle::AstIO.
Referenced by operator!=().
virtual bool souffle::AstNode::equal (const AstNode & other) const protected pure virtual
Abstract equality check for two AST nodes.
Implemented in souffle::AstSubroutineArgument, souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, souffle::AstClause, souffle::AstBinaryConstraint, souffle::AstComponent, souffle::AstIntrinsicFunctor, souffle::AstRelation, souffle::AstBooleanConstraint, souffle::AstRecordType, souffle::AstProvenanceNegation, souffle::AstUnionType, souffle::AstPrintSize, souffle::AstNegation, souffle::AstExecutionPlan, souffle::AstLoad, souffle::AstConstant, souffle::AstPrimitiveType, souffle::AstProgram, souffle::AstAtom, souffle::AstStore, souffle::AstCounter, souffle::AstComponentInit, souffle::AstUnnamedVariable, souffle::AstFunctorDeclaration, souffle::AstIO, souffle::AstExecutionOrder, souffle::AstVariable, souffle::AstComponentType, souffle::AstPragma, and souffle::AstAttribute.
Referenced by operator==().
std::string souffle::AstNode::extloc () const inline
Return source location of the syntactic element.
Definition at line 55 of file AstNode.h.
References souffle::SrcLocation::extloc(), and location.
{
         return location.extloc();
     }
virtual std::vector<const AstNode*> souffle::AstNode::getChildNodes () const pure virtual
Obtain a list of all embedded AST child nodes.
Implemented in souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, souffle::AstBinaryConstraint, souffle::AstClause, souffle::AstIntrinsicFunctor, souffle::AstComponent, souffle::AstBooleanConstraint, souffle::AstRelation, souffle::AstProvenanceNegation, souffle::AstNegation, souffle::AstExecutionPlan, souffle::AstAtom, souffle::AstComponentInit, souffle::AstProgram, souffle::AstType, souffle::AstFunctorDeclaration, souffle::AstExecutionOrder, souffle::AstAttribute, souffle::AstComponentType, souffle::AstArgument, souffle::AstPragma, and souffle::AstIO.
Referenced by souffle::AstSemanticChecker::checkInlining(), operator!=(), souffle::visitDepthFirstPostOrder(), and souffle::visitDepthFirstPreOrder().
SrcLocation souffle::AstNode::getSrcLoc () const inline
Return source location of the AstNode.
Definition at line 45 of file AstNode.h.
References location.
Referenced by souffle::AstLoad::AstLoad(), souffle::AstStore::AstStore(), souffle::AstSemanticChecker::checkAtom(), souffle::AstSemanticChecker::checkClause(), souffle::AstComponentChecker::checkComponent(), souffle::AstComponentChecker::checkComponentInit(), souffle::AstSemanticChecker::checkConstant(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkLiteral(), souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRecordType(), souffle::AstSemanticChecker::checkRelation(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstSemanticChecker::checkUnionType(), souffle::AstIO::clone(), souffle::AstPragma::clone(), souffle::AstAttribute::clone(), souffle::AstComponentType::clone(), souffle::AstVariable::clone(), souffle::AstExecutionOrder::clone(), souffle::AstUnnamedVariable::clone(), souffle::AstFunctorDeclaration::clone(), souffle::AstAtom::clone(), souffle::AstCounter::clone(), souffle::AstStore::clone(), souffle::AstExecutionPlan::clone(), souffle::AstNegation::clone(), souffle::AstLoad::clone(), souffle::AstRelation::clone(), souffle::AstStringConstant::clone(), souffle::AstNumberConstant::clone(), souffle::AstPrintSize::clone(), souffle::AstProvenanceNegation::clone(), souffle::AstNullConstant::clone(), souffle::AstBooleanConstraint::clone(), souffle::AstIntrinsicFunctor::clone(), souffle::AstClause::clone(), souffle::AstBinaryConstraint::clone(), souffle::AstUserDefinedFunctor::clone(), souffle::AstRecordInit::clone(), souffle::AstTypeCast::clone(), souffle::AstAggregator::clone(), souffle::AstSubroutineArgument::clone(), souffle::AstClause::cloneHead(), souffle::createNewRelation(), souffle::getInlinedClause(), souffle::AstRelation::setQualifier(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::translateNonRecursiveRelation(), and souffle::AstTranslator::translateRecursiveRelation().
{
         return location;
     }
bool souffle::AstNode::operator!= (const AstNode & other) const inline
Inequality check for two AST nodes.
Definition at line 65 of file AstNode.h.
References apply(), clone(), getChildNodes(), and print().
{
         return !(*this == other);
     }
bool souffle::AstNode::operator== (const AstNode & other) const inline
Equivalence check for two AST nodes.
Definition at line 60 of file AstNode.h.
References equal().
{
         return this == &other || (typeid(*this) == typeid(other) && equal(other));
     }
virtual void souffle::AstNode::print (std::ostream & os) const pure virtual
Output to a given output stream.
Implemented in souffle::AstSubroutineArgument, souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, souffle::AstBinaryConstraint, souffle::AstComponent, souffle::AstClause, souffle::AstIntrinsicFunctor, souffle::AstBooleanConstraint, souffle::AstRecordType, souffle::AstNullConstant, souffle::AstProvenanceNegation, souffle::AstNumberConstant, souffle::AstPrintSize, souffle::AstUnionType, souffle::AstStringConstant, souffle::AstRelation, souffle::AstLoad, souffle::AstNegation, souffle::AstPrimitiveType, souffle::AstExecutionPlan, souffle::AstStore, souffle::AstComponentInit, souffle::AstCounter, souffle::AstProgram, souffle::AstAtom, souffle::AstUnnamedVariable, souffle::AstExecutionOrder, souffle::AstFunctorDeclaration, souffle::AstComponentType, souffle::AstVariable, souffle::AstPragma, souffle::AstAttribute, and souffle::AstIO.
Referenced by souffle::AstAggregator::addBodyLiteral(), and operator!=().
void souffle::AstNode::setSrcLoc (const SrcLocation & l) inline
Set source location for the AstNode.
Definition at line 50 of file AstNode.h.
References l, and location.
Referenced by souffle::AstLoad::AstLoad(), souffle::AstStore::AstStore(), souffle::AstAttribute::clone(), souffle::AstComponentType::clone(), souffle::AstVariable::clone(), souffle::AstNegation::clone(), souffle::AstProvenanceNegation::clone(), souffle::AstBinaryConstraint::clone(), souffle::AstClause::cloneHead(), souffle::RuleBody::toClauseBodies(), and souffle::MagicSetTransformer::transform().
{
         location = l;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const AstNode & node) friend
Print node onto an output stream.
Definition at line 82 of file AstNode.h.
{
         node.print(out);
         return out;
     }
Field Documentation
SrcLocation souffle::AstNode::location private
Source location of a syntactic element.
Definition at line 93 of file AstNode.h.
Referenced by extloc(), getSrcLoc(), and setSrcLoc().
The documentation for this class was generated from the following file:
AstNode.h