souffle: souffle::TypeEnvironment Class Reference
souffle::TypeEnvironment Class Reference
A type environment is a set of types.
#include <TypeSystem.h>
Public Types
using identifier = AstTypeIdentifier
The type utilized for identifying types.
Public Member Functions
void clear ()
PrimitiveType & createNumericType (const identifier &name)
RecordType & createRecordType (const identifier &name)
PrimitiveType & createSymbolType (const identifier &name)
template<typename T , typename... Args>
T & createType (const identifier &name, const Args &...args)
UnionType & createUnionType (const identifier &name)
TypeSet getAllTypes () const
Type * getModifiableType (const identifier &name)
const Type & getNumberType () const
const Type & getSymbolType () const
const Type & getType (const identifier &ident) const
bool isType (const identifier &ident) const
bool isType (const Type &type) const
void print (std::ostream &out) const
void swap (TypeEnvironment &env)
TypeEnvironment ()
TypeEnvironment (const TypeEnvironment &)=delete
~TypeEnvironment ()
Private Member Functions
void addType (Type &type)
Register types created by one of the factory functions.
Private Attributes
std::map< identifier, Type * > types
The list of covered types.
Friends
std::ostream & operator<< (std::ostream &out, const TypeEnvironment &environment)
Detailed Description
A type environment is a set of types.
It's main purpose is to provide an enumeration of all all types within a given program. Additionally, it manages the life cycle of type instances.
Definition at line 306 of file TypeSystem.h.
Member Typedef Documentation
using souffle::TypeEnvironment::identifier = AstTypeIdentifier
The type utilized for identifying types.
Definition at line 309 of file TypeSystem.h.
Constructor & Destructor Documentation
souffle::TypeEnvironment::TypeEnvironment ()
Definition at line 61 of file TypeSystem.cpp.
{
     clear();
 }
souffle::TypeEnvironment::TypeEnvironment (const TypeEnvironment &) delete
souffle::TypeEnvironment::~TypeEnvironment ()
Definition at line 65 of file TypeSystem.cpp.
References types.
{
     for (const auto& cur : types) {
         delete cur.second;
     }
 }
Member Function Documentation
void souffle::TypeEnvironment::addType (Type & type) private
Register types created by one of the factory functions.
Definition at line 110 of file TypeSystem.cpp.
References souffle::Type::getName(), souffle::Type::name, and types.
{
     const identifier& name = type.getName();
     assert(types.find(name) == types.end() && "Error: registering present type!");
     types[name] = &type;
 }
void souffle::TypeEnvironment::clear ()
Definition at line 71 of file TypeSystem.cpp.
References types.
{
     // clear list of stored types
     for (const auto& cur : types) {
         delete cur.second;
     }
     types.clear();
     // re-initialize type environment
     createType<PredefinedType>("number");
     createType<PredefinedType>("symbol");
 }
PrimitiveType& souffle::TypeEnvironment::createNumericType (const identifier & name) inline
Definition at line 327 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<PrimitiveType>(name, getNumberType());
     }
RecordType& souffle::TypeEnvironment::createRecordType (const identifier & name) inline
Definition at line 339 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<RecordType>(name);
     }
PrimitiveType& souffle::TypeEnvironment::createSymbolType (const identifier & name) inline
Definition at line 331 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<PrimitiveType>(name, getSymbolType());
     }
template<typename T , typename... Args> T& souffle::TypeEnvironment::createType (const identifier & name, const Args &... args) inline
Definition at line 321 of file TypeSystem.h.
{
         auto* res = new T(*this, name, args...);
         addType(*res);
         return *res;
     }
UnionType& souffle::TypeEnvironment::createUnionType (const identifier & name) inline
Definition at line 335 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<UnionType>(name);
     }
TypeSet souffle::TypeEnvironment::getAllTypes () const
Definition at line 102 of file TypeSystem.cpp.
References souffle::TypeSet::insert(), and types.
Referenced by souffle::getLeastCommonSupertypes().
{
     TypeSet res;
     for (const auto& cur : types) {
         res.insert(*cur.second);
     }
     return res;
 }
Type * souffle::TypeEnvironment::getModifiableType (const identifier & name)
Definition at line 92 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     auto pos = types.find(name);
     return (pos == types.end()) ? nullptr : pos->second;
 }
const Type& souffle::TypeEnvironment::getNumberType () const inline
Definition at line 351 of file TypeSystem.h.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::isNumberType(), and souffle::isSubtypeOf().
{
         return getType("number");
     }
const Type& souffle::TypeEnvironment::getSymbolType () const inline
Definition at line 355 of file TypeSystem.h.
References souffle::Type::name, and souffle::Type::print().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::isSubtypeOf(), and souffle::isSymbolType().
{
         return getType("symbol");
     }
const Type & souffle::TypeEnvironment::getType (const identifier & ident) const
Definition at line 97 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstTranslator::translateRelation(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     assert(isType(ident));
     return *(types.find(ident)->second);
 }
bool souffle::TypeEnvironment::isType (const identifier & ident) const
Definition at line 83 of file TypeSystem.cpp.
References types.
Referenced by souffle::UnionType::add(), souffle::RecordType::add(), souffle::TypeAnalysis::analyseTypes(), souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::getGreatestCommonSubtypes(), souffle::getLeastCommonSupertypes(), souffle::isSubtypeOf(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     return types.find(ident) != types.end();
 }
bool souffle::TypeEnvironment::isType (const Type & type) const
Definition at line 87 of file TypeSystem.cpp.
References souffle::Type::getName().
{
     const Type& t = getType(type.getName());
     return t == type;
 }
void souffle::TypeEnvironment::print (std::ostream & out) const
Definition at line 402 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeEnvironmentAnalysis::print().
{
     out << "Types:\n";
     for (const auto& cur : types) {
         out << "\t" << *cur.second << "\n";
     }
 }
void souffle::TypeEnvironment::swap (TypeEnvironment & env) inline
Definition at line 372 of file TypeSystem.h.
References types, and types.
{
         types.swap(env.types);
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const TypeEnvironment & environment) friend
Definition at line 367 of file TypeSystem.h.
{
         environment.print(out);
         return out;
     }
Field Documentation
std::map<identifier, Type*> souffle::TypeEnvironment::types private
The list of covered types.
Definition at line 378 of file TypeSystem.h.
Referenced by swap().
The documentation for this class was generated from the following files:
TypeSystem.h
TypeSystem.cpp