souffle: souffle::RamStatement Class Reference
souffle::RamStatement Class Reference abstract
Abstract class for RAM statements.
#include <RamStatement.h>
Public Member Functions
RamStatement * clone () const override=0
Create clone.
virtual void print (std::ostream &os, int tabpos) const =0
Pretty print with indentation.
void print (std::ostream &os) const override
Print RAM statement.
RamStatement ()=default
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &mapper)=0
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const =0
Obtain list of all embedded child nodes.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamNode
virtual bool equal (const RamNode &other) const =0
Abstract equality check for two RAM nodes.
Detailed Description
Abstract class for RAM statements.
Definition at line 38 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamStatement::RamStatement () default
Member Function Documentation
RamStatement* souffle::RamStatement::clone () const override pure virtual
Create clone.
Implements souffle::RamNode.
Implemented in souffle::RamLogSize, souffle::RamStratum, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamExit, souffle::RamLoop, souffle::RamParallel, souffle::RamSequence, souffle::RamQuery, souffle::RamFact, souffle::RamSwap, souffle::RamMerge, souffle::RamDrop, souffle::RamClear, souffle::RamStore, souffle::RamLoad, and souffle::RamCreate.
Referenced by print().
virtual void souffle::RamStatement::print (std::ostream & os, int tabpos) const pure virtual
Pretty print with indentation.
Implemented in souffle::RamLogSize, souffle::RamStratum, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamExit, souffle::RamLoop, souffle::RamParallel, souffle::RamSequence, souffle::RamQuery, souffle::RamFact, souffle::RamSwap, souffle::RamMerge, souffle::RamDrop, souffle::RamClear, souffle::RamStore, souffle::RamLoad, and souffle::RamCreate.
Referenced by print().
void souffle::RamStatement::print (std::ostream & os) const inline override virtual
Print RAM statement.
Implements souffle::RamNode.
Definition at line 46 of file RamStatement.h.
References clone(), and print().
{
         print(os, 0);
     }
The documentation for this class was generated from the following file:
RamStatement.h