souffle: souffle::ReadFileCSV Class Reference
souffle::ReadFileCSV Class Reference
#include <ReadStreamCSV.h>
Public Member Functions
ReadFileCSV (const std::vector< bool > &symbolMask, SymbolTable &symbolTable, const IODirectives &ioDirectives, const bool provenance=false)
std::unique_ptr< RamDomain[]> readNextTuple () override
Read and return the next tuple.
~ReadFileCSV () override=default
Public Member Functions inherited from souffle::ReadStreamCSV
ReadStreamCSV (std::istream &file, const std::vector< bool > &symbolMask, SymbolTable &symbolTable, const IODirectives &ioDirectives, const bool provenance=false)
~ReadStreamCSV () override=default
Public Member Functions inherited from souffle::ReadStream
template<typename T >
void readAll (T &relation)
ReadStream (const std::vector< bool > &symbolMask, SymbolTable &symbolTable, const bool prov)
virtual ~ReadStream ()=default
Protected Member Functions
std::string getFileName (const IODirectives &ioDirectives) const
Protected Member Functions inherited from souffle::ReadStreamCSV
std::string getDelimiter (const IODirectives &ioDirectives) const
std::map< int, int > getInputColumnMap (const IODirectives &ioDirectives, const unsigned arity) const
Protected Attributes
std::string baseName
std::ifstream fileHandle
Protected Attributes inherited from souffle::ReadStreamCSV
const std::string delimiter
std::istream & file
std::map< int, int > inputMap
size_t lineNumber
Protected Attributes inherited from souffle::ReadStream
const uint8_t arity
const bool isProvenance
const std::vector< bool > & symbolMask
SymbolTable & symbolTable
Detailed Description
Definition at line 153 of file ReadStreamCSV.h.
Constructor & Destructor Documentation
souffle::ReadFileCSV::ReadFileCSV (const std::vector< bool > & symbolMask, SymbolTable & symbolTable, const IODirectives & ioDirectives, const bool provenance = false) inline
Definition at line 155 of file ReadStreamCSV.h.
References souffle::baseName(), souffle::ReadStreamCSV::file, souffle::IODirectives::get(), and souffle::IODirectives::has().
             : ReadStreamCSV(fileHandle, symbolMask, symbolTable, ioDirectives, provenance),
               baseName(souffle::baseName(getFileName(ioDirectives))),
               fileHandle(getFileName(ioDirectives), std::ios::in | std::ios::binary) {
         if (!ioDirectives.has("intermediate")) {
             if (!fileHandle.is_open()) {
                 throw std::invalid_argument("Cannot open fact file " + baseName + "\n");
             }
             // Strip headers if we're using them
             if (ioDirectives.has("headers") && ioDirectives.get("headers") == "true") {
                 std::string line;
                 getline(file, line);
             }
         }
     }
souffle::ReadFileCSV::~ReadFileCSV () override default
Member Function Documentation
std::string souffle::ReadFileCSV::getFileName (const IODirectives & ioDirectives) const inline protected
Definition at line 191 of file ReadStreamCSV.h.
References souffle::IODirectives::get(), souffle::IODirectives::getRelationName(), and souffle::IODirectives::has().
{
         if (ioDirectives.has("filename")) {
             return ioDirectives.get("filename");
         }
         return ioDirectives.getRelationName() + ".facts";
     }
std::unique_ptr<RamDomain[]> souffle::ReadFileCSV::readNextTuple () inline override virtual
Read and return the next tuple.
Returns nullptr if no tuple was readable.
Returns
Reimplemented from souffle::ReadStreamCSV.
Definition at line 177 of file ReadStreamCSV.h.
References souffle::baseName(), e, and souffle::ReadStreamCSV::readNextTuple().
{
         try {
             return ReadStreamCSV::readNextTuple();
         } catch (std::exception& e) {
             std::stringstream errorMessage;
             errorMessage << e.what();
             errorMessage << "cannot parse fact file " << baseName << "!\n";
             throw std::invalid_argument(errorMessage.str());
         }
     }
Field Documentation
std::string souffle::ReadFileCSV::baseName protected
Definition at line 197 of file ReadStreamCSV.h.
std::ifstream souffle::ReadFileCSV::fileHandle protected
Definition at line 201 of file ReadStreamCSV.h.
The documentation for this class was generated from the following file:
ReadStreamCSV.h