souffle: souffle::IndexSet Class Reference
souffle::IndexSet Class Reference
Computes the index set for a relation.
#include <IndexSetAnalysis.h>
Public Types
using Chain = std::set< SearchColumns >
using ChainOrderMap = std::vector< Chain >
using LexicographicalOrder = std::vector< int >
using OrderCollection = std::vector< LexicographicalOrder >
using SearchSet = std::set< SearchColumns >
Public Member Functions
void addSearch (SearchColumns cols)
Add new key to an Index Set.
const ChainOrderMap getAllChains () const
const OrderCollection getAllOrders () const
Get all indexes.
const LexicographicalOrder getLexOrder (SearchColumns cols) const
Get index for a search.
const RamRelation & getRelation () const
Get relation.
const SearchSet & getSearches () const
Get searches.
IndexSet (const RamRelation &rel)
bool isSubset (SearchColumns cols) const
check whether number of bits in k is not equal to number of columns in lexicographical order
void solve ()
map the keys in the key set to lexicographical order
Static Public Member Functions
static SearchColumns toA (SearchColumns b)
convert from a representation of B verticies to A verticies
static SearchColumns toB (SearchColumns a)
convert from a representation of A verticies to B verticies
Protected Member Functions
Chain getChain (const SearchColumns umn, const MaxMatching::Matchings &match)
given an unmapped node from set A we follow it from set B until it cannot be matched from B if not mateched from B then umn is a chain
const ChainOrderMap getChainsFromMatching (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all chains from the matching
const SearchSet getUnmatchedKeys (const MaxMatching::Matchings &match, const SearchSet &nodes)
get all nodes which are unmated from A-> B
void insertIndex (std::vector< int > &ids, SearchColumns delta)
insert an index based on the delta
int map (SearchColumns cols) const
maps search columns to an lexicographical order (labeled by a number)
Static Protected Member Functions
static size_t card (SearchColumns cols)
count the number of bits in key
static bool isStrictSubset (SearchColumns a, SearchColumns b)
determine if key a is a strict subset of key b
Protected Attributes
ChainOrderMap chainToOrder
MaxMatching matching
OrderCollection orders
const RamRelation & relation
SearchSet searches
Detailed Description
Computes the index set for a relation.
If the indexes of a relation can cover several searches, the minimal set of indexes is computed by Dilworth's problem. See
"Optimal On The Fly Index Selection in Polynomial Time" https://arxiv.org/abs/1709.03685
Definition at line 99 of file IndexSetAnalysis.h.
Member Typedef Documentation
using souffle::IndexSet::Chain = std::set<SearchColumns>
Definition at line 103 of file IndexSetAnalysis.h.
using souffle::IndexSet::ChainOrderMap = std::vector<Chain>
Definition at line 104 of file IndexSetAnalysis.h.
using souffle::IndexSet::LexicographicalOrder = std::vector<int>
Definition at line 101 of file IndexSetAnalysis.h.
using souffle::IndexSet::OrderCollection = std::vector<LexicographicalOrder>
Definition at line 102 of file IndexSetAnalysis.h.
using souffle::IndexSet::SearchSet = std::set<SearchColumns>
Definition at line 105 of file IndexSetAnalysis.h.
Constructor & Destructor Documentation
souffle::IndexSet::IndexSet (const RamRelation & rel) inline
Definition at line 107 of file IndexSetAnalysis.h.
 : relation(rel) {}
Member Function Documentation
void souffle::IndexSet::addSearch (SearchColumns cols) inline
Add new key to an Index Set.
Definition at line 110 of file IndexSetAnalysis.h.
Referenced by souffle::IndexSetAnalysis::run().
{
         if (cols != 0) {
             searches.insert(cols);
         }
     }
static size_t souffle::IndexSet::card (SearchColumns cols) inline static protected
count the number of bits in key
Definition at line 172 of file IndexSetAnalysis.h.
References i.
{
         size_t sz = 0, idx = 1;
         for (size_t i = 0; i < sizeof(SearchColumns) * 8; i++) {
             if (idx & cols) {
                 sz++;
             }
             idx *= 2;
         }
         return sz;
     }
const ChainOrderMap souffle::IndexSet::getAllChains () const inline
Definition at line 136 of file IndexSetAnalysis.h.
{
         return chainToOrder;
     }
const OrderCollection souffle::IndexSet::getAllOrders () const inline
Get all indexes.
Definition at line 132 of file IndexSetAnalysis.h.
Referenced by souffle::SynthesiserDirectRelation::computeIndices(), souffle::SynthesiserIndirectRelation::computeIndices(), souffle::SynthesiserBrieRelation::computeIndices(), souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), and souffle::IndexSetAnalysis::print().
{
         return orders;
     }
IndexSet::Chain souffle::IndexSet::getChain (const SearchColumns umn, const MaxMatching::Matchings & match) protected
given an unmapped node from set A we follow it from set B until it cannot be matched from B if not mateched from B then umn is a chain
Definition at line 227 of file IndexSetAnalysis.cpp.
{
     SearchColumns start = umn;  // start at an unmateched node
     Chain chain;
     // Assume : no circular mappings, i.e. a in A -> b in B -> ........ -> a in A is not allowed.
     // Given this, the loop will terminate
     while (true) {
         auto mit = match.find(toB(start));  // we start from B side
         chain.insert(start);
         if (mit == match.end()) {
             return chain;
         }
         SearchColumns a = mit->second;
         chain.insert(a);
         start = a;
     }
 }
const IndexSet::ChainOrderMap souffle::IndexSet::getChainsFromMatching (const MaxMatching::Matchings & match, const SearchSet & nodes) protected
get all chains from the matching
Definition at line 247 of file IndexSetAnalysis.cpp.
{
     assert(!nodes.empty());
     // Get all unmatched nodes from A
     const SearchSet& umKeys = getUnmatchedKeys(match, nodes);
     // Case: if no unmatched nodes then we have an anti-chain
     if (umKeys.empty()) {
         for (auto node : nodes) {
             std::set<SearchColumns> a;
             a.insert(node);
             chainToOrder.push_back(a);
             return chainToOrder;
         }
     }
     assert(!umKeys.empty());
     // A worklist of used nodes
     SearchSet usedKeys;
     // Case: nodes < umKeys or if nodes == umKeys then anti chain - this is handled by this loop
     for (auto umKey : umKeys) {
         Chain c = getChain(umKey, match);
         assert(!c.empty());
         chainToOrder.push_back(c);
     }
     assert(!chainToOrder.empty());
     return chainToOrder;
 }
const LexicographicalOrder souffle::IndexSet::getLexOrder (SearchColumns cols) const inline
Get index for a search.
Definition at line 126 of file IndexSetAnalysis.h.
Referenced by souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), and souffle::SynthesiserBrieRelation::generateTypeStruct().
{
         int idx = map(cols);
         return orders[idx];
     }
const RamRelation& souffle::IndexSet::getRelation () const inline
Get relation.
Definition at line 116 of file IndexSetAnalysis.h.
References relation.
Referenced by souffle::IndexSetAnalysis::print().
{
         return relation;
     }
const SearchSet& souffle::IndexSet::getSearches () const inline
Get searches.
Definition at line 121 of file IndexSetAnalysis.h.
Referenced by souffle::IndexSetAnalysis::print().
{
         return searches;
     }
const SearchSet souffle::IndexSet::getUnmatchedKeys (const MaxMatching::Matchings & match, const SearchSet & nodes) inline protected
get all nodes which are unmated from A-> B
Definition at line 225 of file IndexSetAnalysis.h.
{
         assert(!nodes.empty());
         SearchSet unmatched;
         // For all nodes n such that n is not in match
         for (auto node : nodes) {
             if (match.find(node) == match.end()) {
                 unmatched.insert(node);
             }
         }
         return unmatched;
     }
void souffle::IndexSet::insertIndex (std::vector< int > & ids, SearchColumns delta) inline protected
insert an index based on the delta
Definition at line 203 of file IndexSetAnalysis.h.
References souffle::MaxMatching::match.
{
         int pos = 0;
         SearchColumns mask = 0;
         while (mask < delta) {
             mask = SearchColumns(1 << (pos));
             SearchColumns result = (delta) & (mask);
             if (result) {
                 ids.push_back(pos);
             }
             pos++;
         }
     }
static bool souffle::IndexSet::isStrictSubset (SearchColumns a, SearchColumns b) inline static protected
determine if key a is a strict subset of key b
Definition at line 197 of file IndexSetAnalysis.h.
References b.
{
         auto tt = static_cast<SearchColumns>(std::numeric_limits<SearchColumns>::max());
         return (~(a) | (b)) == tt && a != b;
     }
bool souffle::IndexSet::isSubset (SearchColumns cols) const inline
check whether number of bits in k is not equal to number of columns in lexicographical order
Definition at line 142 of file IndexSetAnalysis.h.
References souffle::MaxMatching::solve().
{
         int idx = map(cols);
         return card(cols) < orders[idx].size();
     }
int souffle::IndexSet::map (SearchColumns cols) const inline protected
maps search columns to an lexicographical order (labeled by a number)
Definition at line 184 of file IndexSetAnalysis.h.
References i.
{
         assert(orders.size() == chainToOrder.size() && "Order and Chain Sizes do not match!!");
         int i = 0;
         for (auto it = chainToOrder.begin(); it != chainToOrder.end(); ++it, ++i) {
             if (it->find(cols) != it->end()) {
                 assert((size_t)i < orders.size());
                 return i;
             }
         }
         abort();
     }
void souffle::IndexSet::solve ()
map the keys in the key set to lexicographical order
Definition at line 136 of file IndexSetAnalysis.cpp.
References i, k, and l.
Referenced by souffle::IndexSetAnalysis::run().
                      {
     if (searches.empty()) {
         return;
     }
     // check whether one of the naive indexers should be used
     // two conditions: either set by environment or relation is a hash map
     static const char ENV_NAIVE_INDEX[] = "SOUFFLE_USE_NAIVE_INDEX";
     if (std::getenv(ENV_NAIVE_INDEX)) {
         static bool first = true;
         // print a warning - only the first time
         if (first) {
             std::cout << "WARNING: auto index selection disabled, naive indexes are utilized!!\n";
             first = false;
         }
         // every search pattern gets its naive index
         for (SearchColumns cur : searches) {
             // obtain order
             LexicographicalOrder order;
             SearchColumns mask = cur;
             for (int i = 0; mask != 0; i++) {
                 if (!(1 << i & mask)) {
                     continue;
                 }
                 order.push_back(i);
                 // clear bit
                 mask &= ~(1 << i);
             }
             // add new order
             orders.push_back(order);
             // register pseudo chain
             chainToOrder.push_back(Chain());
             chainToOrder.back().insert(cur);
         }
         return;
     }
     // Construct the matching poblem
     for (auto search : searches) {
         // For this node check if other nodes are strict subsets
         for (auto itt : searches) {
             if (isStrictSubset(search, itt)) {
                 matching.addEdge(search, toB(itt));
             }
         }
     }
     // Perform the Hopcroft-Karp on the graph and receive matchings (mapped A->B and B->A)
     // Assume: alg.calculate is not called on an empty graph
     assert(!searches.empty());
     const MaxMatching::Matchings& matchings = matching.solve();
     // Extract the chains given the nodes and matchings
     const ChainOrderMap chains = getChainsFromMatching(matchings, searches);
     // Should never get no chains back as we never call calculate on an empty graph
     assert(!chains.empty());
     for (const auto& chain : chains) {
         std::vector<int> ids;
         SearchColumns initDelta = *(chain.begin());
         insertIndex(ids, initDelta);
         for (auto iit = chain.begin(); next(iit) != chain.end(); ++iit) {
             SearchColumns delta = *(next(iit)) - *iit;
             insertIndex(ids, delta);
         }
         assert(!ids.empty());
         orders.push_back(ids);
     }
     // Construct the matching poblem
     for (auto search : searches) {
         int idx = map(search);
         size_t l = card(search);
         SearchColumns k = 0;
         for (size_t i = 0; i < l; i++) {
             k = k + (1 << (orders[idx][i]));
         }
         assert(k == search && "incorrect lexicographical order");
     }
 }
static SearchColumns souffle::IndexSet::toA (SearchColumns b) inline static
convert from a representation of B verticies to A verticies
Definition at line 158 of file IndexSetAnalysis.h.
{
         SearchColumns msb = 1;
         msb <<= (4 * 8 - 1);
         return (b xor msb);
     }
static SearchColumns souffle::IndexSet::toB (SearchColumns a) inline static
convert from a representation of A verticies to B verticies
Definition at line 151 of file IndexSetAnalysis.h.
{
         SearchColumns msb = 1;
         msb <<= (4 * 8 - 1);
         return (a | msb);
     }
Field Documentation
ChainOrderMap souffle::IndexSet::chainToOrder protected
Definition at line 167 of file IndexSetAnalysis.h.
MaxMatching souffle::IndexSet::matching protected
Definition at line 168 of file IndexSetAnalysis.h.
OrderCollection souffle::IndexSet::orders protected
Definition at line 166 of file IndexSetAnalysis.h.
const RamRelation& souffle::IndexSet::relation protected
Definition at line 169 of file IndexSetAnalysis.h.
SearchSet souffle::IndexSet::searches protected
Definition at line 165 of file IndexSetAnalysis.h.
The documentation for this class was generated from the following files:
IndexSetAnalysis.h
IndexSetAnalysis.cpp