souffle: souffle::InterpreterEqRelation Class Reference
souffle::InterpreterEqRelation Class Reference
Interpreter Equivalence Relation.
#include <InterpreterRelation.h>
Public Member Functions
std::vector< RamDomain * > extend (const RamDomain *tuple) override
Find the new knowledge generated by inserting a tuple.
void extend (const InterpreterRelation &rel) override
Extend this relation with new knowledge generated by inserting all tuples from a relation.
void insert (const RamDomain *tuple) override
Insert tuple.
InterpreterEqRelation (size_t relArity)
Public Member Functions inherited from souffle::InterpreterRelation
iterator begin () const
get iterator begin of relation
bool empty () const
Check whether relation is empty.
iterator end () const
get iterator begin of relation
bool exists (const RamDomain *tuple) const
check whether a tuple exists in the relation
size_t getArity () const
Get arity of relation.
std::vector< std::string > & getAttributeTypeQualifiers ()
Get AttributeType for the relation.
InterpreterIndex * getIndex (const SearchColumns &key, InterpreterIndex *cachedIndex) const
get index for a given set of keys using a cached index as a helper.
InterpreterIndex * getIndex (const SearchColumns &key) const
get index for a given set of keys.
InterpreterIndex * getIndex (const InterpreterIndexOrder &order) const
get index for a given order.
size_t getLevel ()
SearchColumns getTotalIndexKey () const
Obtains a full index-key for this relation.
void insert (const InterpreterRelation &other)
Merge another relation into this relation.
InterpreterRelation (size_t relArity)
InterpreterRelation (const InterpreterRelation &other)=delete
void purge ()
Purge table.
void setAttributes (const std::vector< std::string > attributeTypes)
Set AttributeType for the relation.
void setLevel (size_t level)
size_t size () const
Gets the number of contained tuples.
virtual ~InterpreterRelation ()=default
Detailed Description
Interpreter Equivalence Relation.
Definition at line 330 of file InterpreterRelation.h.
Constructor & Destructor Documentation
souffle::InterpreterEqRelation::InterpreterEqRelation (size_t relArity) inline
Definition at line 332 of file InterpreterRelation.h.
 : InterpreterRelation(relArity) {}
Member Function Documentation
std::vector<RamDomain*> souffle::InterpreterEqRelation::extend (const RamDomain * tuple) inline override virtual
Find the new knowledge generated by inserting a tuple.
Reimplemented from souffle::InterpreterRelation.
Definition at line 355 of file InterpreterRelation.h.
{
         std::vector<RamDomain*> newTuples;
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[0]});
         newTuples.push_back(new RamDomain[2]{tuple[0], tuple[1]});
         newTuples.push_back(new RamDomain[2]{tuple[1], tuple[0]});
         newTuples.push_back(new RamDomain[2]{tuple[1], tuple[1]});
         std::vector<const RamDomain*> relevantStored;
         for (const RamDomain* vals : *this) {
             if (vals[0] == tuple[0] || vals[0] == tuple[1] || vals[1] == tuple[0] || vals[1] == tuple[1]) {
                 relevantStored.push_back(vals);
             }
         }
         for (const auto vals : relevantStored) {
             newTuples.push_back(new RamDomain[2]{vals[0], tuple[0]});
             newTuples.push_back(new RamDomain[2]{vals[0], tuple[1]});
             newTuples.push_back(new RamDomain[2]{vals[1], tuple[0]});
             newTuples.push_back(new RamDomain[2]{vals[1], tuple[1]});
             newTuples.push_back(new RamDomain[2]{tuple[0], vals[0]});
             newTuples.push_back(new RamDomain[2]{tuple[0], vals[1]});
             newTuples.push_back(new RamDomain[2]{tuple[1], vals[0]});
             newTuples.push_back(new RamDomain[2]{tuple[1], vals[1]});
         }
         return newTuples;
     }
void souffle::InterpreterEqRelation::extend (const InterpreterRelation & rel) inline override virtual
Extend this relation with new knowledge generated by inserting all tuples from a relation.
Reimplemented from souffle::InterpreterRelation.
Definition at line 384 of file InterpreterRelation.h.
References souffle::InterpreterRelation::extend(), and souffle::InterpreterRelation::insert().
{
         std::vector<RamDomain*> newTuples;
         // store all values that will be implicitly relevant to the those that we will insert
         for (const auto* tuple : rel) {
             for (auto* newTuple : extend(tuple)) {
                 newTuples.push_back(newTuple);
             }
         }
         for (const auto* newTuple : newTuples) {
             InterpreterRelation::insert(newTuple);
             delete[] newTuple;
         }
     }
void souffle::InterpreterEqRelation::insert (const RamDomain * tuple) inline override virtual
Insert tuple.
Reimplemented from souffle::InterpreterRelation.
Definition at line 335 of file InterpreterRelation.h.
References souffle::InterpreterRelation::extend(), and souffle::InterpreterRelation::insert().
{
         // TODO: (pnappa) an eqrel check here is all that appears to be needed for implicit additions
         // TODO: future optimisation would require this as a member datatype
         // brave soul required to pass this quest
         // // specialisation for eqrel defs
         // std::unique_ptr<binaryrelation> eqreltuples;
         // in addition, it requires insert functions to insert into that, and functions
         // which allow reading of stored values must be changed to accommodate.
         // e.g. insert =>  eqRelTuples->insert(tuple[0], tuple[1]);
         // for now, we just have a naive & extremely slow version, otherwise known as a O(n^2) insertion
         // ):
         for (auto* newTuple : extend(tuple)) {
             InterpreterRelation::insert(newTuple);
             delete[] newTuple;
         }
     }
The documentation for this class was generated from the following file:
InterpreterRelation.h