souffle: souffle::SrcLocation Class Reference
souffle::SrcLocation Class Reference
A class describing a range in an input file.
#include <SrcLocation.h>
Data Structures
struct Point
A class locating a single point in an input file.
Public Member Functions
std::string extloc () const
An extended string describing this location in a end-user friendly way.
bool operator< (const SrcLocation &other) const
A comparison for source locations.
void print (std::ostream &out) const
Data Fields
Point end = {}
The End location.
std::string filename
The file referred to.
Point start = {}
The start location.
Friends
std::ostream & operator<< (std::ostream &out, const SrcLocation &range)
Enables ranges to be printed.
Detailed Description
A class describing a range in an input file.
Definition at line 25 of file SrcLocation.h.
Member Function Documentation
std::string souffle::SrcLocation::extloc () const
An extended string describing this location in a end-user friendly way.
Definition at line 27 of file SrcLocation.cpp.
References souffle::baseName(), souffle::SrcLocation::Point::column, filename, i, souffle::SrcLocation::Point::line, and start.
Referenced by souffle::AstNode::extloc(), operator<(), and souffle::DiagnosticMessage::print().
{
     std::ifstream in(filename);
     std::stringstream s;
     if (in.is_open()) {
         s << "file " << baseName(filename) << " at line " << start.line << "\n";
         for (int i = 0; i < start.line - 1; ++i) {
             in.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
         }
         int c;
         int lineLen = 0;
         int offsetColumn = start.column;
         bool prevWhitespace = false;
         bool afterFirstNonSpace = false;
         while ((c = in.get()) != '\n' && c != EOF) {
             s << (char)c;
             lineLen++;
             // Offset column to account for C preprocessor having reduced
             // consecutive non-leading whitespace chars to a single space.
             if (std::isspace(c)) {
                 if (afterFirstNonSpace && prevWhitespace && offsetColumn >= lineLen) {
                     offsetColumn++;
                 }
                 prevWhitespace = true;
             } else {
                 prevWhitespace = false;
                 afterFirstNonSpace = true;
             }
         }
         lineLen++;  // Add new line
         in.close();
         s << "\n";
         for (int i = 1; i <= lineLen; i++) {
             char ch = (i == offsetColumn) ? '^' : '-';
             s << ch;
         }
         in.close();
     } else {
         s << "unknown source location.";
     }
     return s.str();
 }
bool souffle::SrcLocation::operator< (const SrcLocation & other) const inline
A comparison for source locations.
Definition at line 65 of file SrcLocation.h.
References end, extloc(), filename, and start.
{
         if (filename < other.filename) {
             return true;
         }
         if (filename > other.filename) {
             return false;
         }
         if (start < other.start) {
             return true;
         }
         if (start > other.start) {
             return false;
         }
         if (end < other.end) {
             return true;
         }
         return false;
     }
void souffle::SrcLocation::print (std::ostream & out) const inline
Definition at line 87 of file SrcLocation.h.
{
         out << filename << " [" << start << "-" << end << "]";
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const SrcLocation & range) friend
Enables ranges to be printed.
Definition at line 92 of file SrcLocation.h.
{
         range.print(out);
         return out;
     }
Field Documentation
Point souffle::SrcLocation::end = {}
The End location.
Definition at line 62 of file SrcLocation.h.
Referenced by souffle::nextSrcLoc(), and operator<().
std::string souffle::SrcLocation::filename
The file referred to.
Definition at line 56 of file SrcLocation.h.
Referenced by extloc(), souffle::nextSrcLoc(), and operator<().
Point souffle::SrcLocation::start = {}
The start location.
Definition at line 59 of file SrcLocation.h.
Referenced by extloc(), souffle::nextSrcLoc(), and operator<().
The documentation for this class was generated from the following files:
SrcLocation.h
SrcLocation.cpp