souffle: souffle::SymbolTable Class Reference
souffle::SymbolTable Class Reference
Global pool of re-usable strings.
#include <SymbolTable.h>
Public Member Functions
Lock::Lease acquireLock () const
bool contains (const std::string &symbol) const
Check if the symbol table contains a string.
bool contains (const RamDomain index) const
Check if the symbol table contains an index.
void insert (const std::vector< std::string > &symbols)
Bulk insert symbols into the table, note that this operation is more efficient than repeated inserts of single symbols.
void insert (const std::string &symbol)
Insert a single symbol into the table, not that this operation should not be used if inserting symbols in bulk.
RamDomain lookup (const std::string &symbol)
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
RamDomain lookupExisting (const std::string &symbol) const
Finds the index of a symbol in the table, giving an error if it's not found.
SymbolTable & operator= (const SymbolTable &other)
Assignment operator, performs a deep copy and frees memory allocated for all strings.
SymbolTable & operator= (SymbolTable &&other) noexcept
Assignment operator for r-value references.
void print (std::ostream &out) const
Print the symbol table to the given stream.
const std::string & resolve (const RamDomain index) const
Find a symbol in the table by its index, note that this gives an error if the index is out of bounds.
size_t size () const
SymbolTable ()=default
Empty constructor.
SymbolTable (const SymbolTable &other)
Copy constructor, performs a deep copy.
SymbolTable (SymbolTable &&other) noexcept
Copy constructor for r-value reference.
SymbolTable (std::initializer_list< std::string > symbols)
RamDomain unsafeLookup (const std::string &symbol)
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
const std::string & unsafeResolve (const RamDomain index) const
virtual ~SymbolTable ()=default
Destructor, frees memory allocated for all strings.
Private Member Functions
void newSymbol (const std::string &symbol)
Convenience method to place a new symbol in the table, if it does not exist.
size_t newSymbolOfIndex (const std::string &symbol)
Convenience method to place a new symbol in the table, if it does not exist, and return the index of it.
Private Attributes
Lock access
A lock to synchronize parallel accesses.
std::deque< std::string > numToStr
Map indices to strings.
std::unordered_map< std::string, size_t > strToNum
Map strings to indices.
Friends
std::ostream & operator<< (std::ostream &out, const SymbolTable &table)
Stream operator, used as a convenience for print.
Detailed Description
Global pool of re-usable strings.
SymbolTable stores Datalog symbols and converts them to numbers and vice versa.
Definition at line 44 of file SymbolTable.h.
Constructor & Destructor Documentation
souffle::SymbolTable::SymbolTable () default
Empty constructor.
Referenced by newSymbol().
souffle::SymbolTable::SymbolTable (const SymbolTable & other) inline
Copy constructor, performs a deep copy.
Definition at line 215 of file SymbolTable.h.
 : numToStr(other.numToStr), strToNum(other.strToNum) {}
souffle::SymbolTable::SymbolTable (SymbolTable && other) inline noexcept
Copy constructor for r-value reference.
Definition at line 218 of file SymbolTable.h.
{
         numToStr.swap(other.numToStr);
         strToNum.swap(other.strToNum);
     }
souffle::SymbolTable::SymbolTable (std::initializer_list< std::string > symbols) inline
Definition at line 223 of file SymbolTable.h.
References newSymbol(), and ~SymbolTable().
{
         strToNum.reserve(symbols.size());
         for (const auto& symbol : symbols) {
             newSymbol(symbol);
         }
     }
virtual souffle::SymbolTable::~SymbolTable () virtual default
Destructor, frees memory allocated for all strings.
Referenced by SymbolTable().
Member Function Documentation
Lock::Lease souffle::SymbolTable::acquireLock () const inline
Definition at line 416 of file SymbolTable.h.
References souffle::Lock::acquire().
Referenced by souffle::ReadStream::readAll(), and souffle::WriteStream::writeAll().
{
         return access.acquire();
     }
bool souffle::SymbolTable::contains (const std::string & symbol) const inline
Check if the symbol table contains a string.
Definition at line 393 of file SymbolTable.h.
References souffle::Lock::acquire().
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         auto result = strToNum.find(symbol);
         if (result == strToNum.end()) {
             return false;
         } else {
             return true;
         }
     }
bool souffle::SymbolTable::contains (const RamDomain index) const inline
Check if the symbol table contains an index.
Definition at line 405 of file SymbolTable.h.
References souffle::Lock::acquire(), and size().
{
         auto lease = access.acquire();
         (void)lease;  // avoid warning;
         auto pos = static_cast<size_t>(index);
         if (pos >= size()) {
             return false;
         } else {
             return true;
         }
     }
void souffle::SymbolTable::insert (const std::vector< std::string > & symbols) inline
Bulk insert symbols into the table, note that this operation is more efficient than repeated inserts of single symbols.
Definition at line 342 of file SymbolTable.h.
References souffle::Lock::acquire(), newSymbol(), and size().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             mpi::send(symbols, 0, INSERT_VECTOR_STRING);
         } else
 #endif
         {
             auto lease = access.acquire();
             (void)lease;  // avoid warning;
             strToNum.reserve(size() + symbols.size());
             for (auto& symbol : symbols) {
                 newSymbol(symbol);
             }
         }
     }
void souffle::SymbolTable::insert (const std::string & symbol) inline
Insert a single symbol into the table, not that this operation should not be used if inserting symbols in bulk.
Definition at line 361 of file SymbolTable.h.
References souffle::Lock::acquire(), and newSymbol().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             mpi::send(symbol, 0, INSERT_STRING);
         } else
 #endif
         {
             auto lease = access.acquire();
             (void)lease;  // avoid warning;
             newSymbol(symbol);
         }
     }
RamDomain souffle::SymbolTable::lookup (const std::string & symbol) inline
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
Definition at line 252 of file SymbolTable.h.
References souffle::Lock::acquire(), and newSymbolOfIndex().
Referenced by souffle::ExplainProvenance::argsToNums(), souffle::RAMI::evalExpr(), souffle::ExplainProvenanceSLD::explainNegation(), souffle::tuple::operator<<(), souffle::LVMGenerator::visitAggregate(), souffle::LVMGenerator::visitChoice(), souffle::LVMGenerator::visitClear(), souffle::LVMGenerator::visitCreate(), souffle::LVMGenerator::visitDebugInfo(), souffle::LVMGenerator::visitDrop(), souffle::LVMGenerator::visitEmptinessCheck(), souffle::LVMGenerator::visitExistenceCheck(), souffle::LVMGenerator::visitFact(), souffle::LVMGenerator::visitFilter(), souffle::LVMGenerator::visitIndexAggregate(), souffle::LVMGenerator::visitIndexChoice(), souffle::LVMGenerator::visitIndexScan(), souffle::LVMGenerator::visitLoad(), souffle::LVMGenerator::visitLogSize(), souffle::LVMGenerator::visitLogTimer(), souffle::LVMGenerator::visitMerge(), souffle::LVMGenerator::visitProject(), souffle::LVMGenerator::visitProvenanceExistenceCheck(), souffle::LVMGenerator::visitReturnValue(), souffle::LVMGenerator::visitScan(), souffle::LVMGenerator::visitSearch(), souffle::LVMGenerator::visitStore(), souffle::LVMGenerator::visitSwap(), and souffle::LVMGenerator::visitUserDefinedOperator().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             return cacheLookup(symbol, LOOKUP);
         } else
 #endif
         {
             auto lease = access.acquire();
             (void)lease;  // avoid warning;
             return static_cast<RamDomain>(newSymbolOfIndex(symbol));
         }
     }
RamDomain souffle::SymbolTable::lookupExisting (const std::string & symbol) const inline
Finds the index of a symbol in the table, giving an error if it's not found.
Definition at line 266 of file SymbolTable.h.
References souffle::Lock::acquire().
Referenced by souffle::ExplainProvenanceSLD::findTuple(), and souffle::ExplainProvenanceSLD::measureRelation().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             return cacheLookup(symbol, LOOKUP_EXISTING);
         } else
 #endif
         {
             auto lease = access.acquire();
             (void)lease;  // avoid warning;
             auto result = strToNum.find(symbol);
             if (result == strToNum.end()) {
                 std::cerr << "Error string not found in call to SymbolTable::lookupExisting.\n";
                 exit(1);
             }
             return static_cast<RamDomain>(result->second);
         }
     }
void souffle::SymbolTable::newSymbol (const std::string & symbol) inline private
Convenience method to place a new symbol in the table, if it does not exist.
Definition at line 203 of file SymbolTable.h.
References SymbolTable().
Referenced by insert(), and SymbolTable().
{
         if (strToNum.find(symbol) == strToNum.end()) {
             strToNum[symbol] = numToStr.size();
             numToStr.push_back(symbol);
         }
     }
size_t souffle::SymbolTable::newSymbolOfIndex (const std::string & symbol) inline private
Convenience method to place a new symbol in the table, if it does not exist, and return the index of it.
Definition at line 189 of file SymbolTable.h.
Referenced by lookup(), and unsafeLookup().
{
         size_t index;
         auto it = strToNum.find(symbol);
         if (it == strToNum.end()) {
             index = numToStr.size();
             strToNum[symbol] = index;
             numToStr.push_back(symbol);
         } else {
             index = it->second;
         }
         return index;
     }
SymbolTable& souffle::SymbolTable::operator= (const SymbolTable & other) inline
Assignment operator, performs a deep copy and frees memory allocated for all strings.
Definition at line 234 of file SymbolTable.h.
References numToStr, and strToNum.
{
         if (this == &other) {
             return *this;
         }
         numToStr = other.numToStr;
         strToNum = other.strToNum;
         return *this;
     }
SymbolTable& souffle::SymbolTable::operator= (SymbolTable && other) inline noexcept
Assignment operator for r-value references.
Definition at line 244 of file SymbolTable.h.
{
         numToStr.swap(other.numToStr);
         strToNum.swap(other.strToNum);
         return *this;
     }
void souffle::SymbolTable::print (std::ostream & out) const inline
Print the symbol table to the given stream.
Definition at line 375 of file SymbolTable.h.
References souffle::join().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             mpi::send(0, PRINT);
         } else
 #endif
         {
             out << "SymbolTable: {\n\t";
             out << join(strToNum, "\n\t",
                            [](std::ostream& out, const std::pair<std::string, std::size_t>& entry) {
                                out << entry.first << "\t => " << entry.second;
                            })
                 << "\n";
             out << "}\n";
         }
     }
const std::string& souffle::SymbolTable::resolve (const RamDomain index) const inline
Find a symbol in the table by its index, note that this gives an error if the index is out of bounds.
Definition at line 298 of file SymbolTable.h.
References souffle::Lock::acquire(), and size().
Referenced by souffle::RAMI::evalCond(), souffle::RAMI::evalExpr(), souffle::ExplainProvenanceSLD::explain(), souffle::ExplainProvenanceSLD::explainNegation(), souffle::Synthesiser::generateCode(), souffle::ExplainProvenance::numsToArgs(), souffle::InterpreterRelInterface::iterator_base::operator*(), souffle::tuple::operator>>(), and souffle::LVMCode::print().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             return cacheResolve(index, RESOLVE);
         } else
 #endif
         {
             auto lease = access.acquire();
             (void)lease;  // avoid warning;
             auto pos = static_cast<size_t>(index);
             if (pos >= size()) {
                 // TODO: use different error reporting here!!
                 std::cerr << "Error index out of bounds in call to SymbolTable::resolve.\n";
                 exit(1);
             }
             return numToStr[pos];
         }
     }
size_t souffle::SymbolTable::size () const inline
Definition at line 327 of file SymbolTable.h.
Referenced by contains(), souffle::Synthesiser::generateCode(), insert(), and resolve().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             mpi::send(0, SIZE);
             size_t size;
             mpi::recv(size, 0, SIZE);
             return size;
         } else
 #endif
             return numToStr.size();
     }
RamDomain souffle::SymbolTable::unsafeLookup (const std::string & symbol) inline
Find the index of a symbol in the table, inserting a new symbol if it does not exist there already.
Definition at line 286 of file SymbolTable.h.
References newSymbolOfIndex().
Referenced by souffle::ReadStreamSQLite::readNextTuple(), and souffle::ReadStreamCSV::readNextTuple().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             return cacheLookup(symbol, UNSAFE_LOOKUP);
         } else
 #endif
             return newSymbolOfIndex(symbol);
     }
const std::string& souffle::SymbolTable::unsafeResolve (const RamDomain index) const inline
Definition at line 317 of file SymbolTable.h.
Referenced by souffle::WriteStreamSQLite::getSymbolTableID(), souffle::WriteStreamSQLite::getSymbolTableIDFromDB(), and souffle::WriteFileCSV::writeNextTuple().
{
 #ifdef USE_MPI
         if (mpi::commRank() != 0) {
             return cacheResolve(index, UNSAFE_RESOLVE);
         } else
 #endif
             return numToStr[static_cast<size_t>(index)];
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const SymbolTable & table) friend
Stream operator, used as a convenience for print.
Definition at line 421 of file SymbolTable.h.
{
         table.print(out);
         return out;
     }
Field Documentation
Lock souffle::SymbolTable::access mutable private
A lock to synchronize parallel accesses.
Definition at line 179 of file SymbolTable.h.
std::deque<std::string> souffle::SymbolTable::numToStr private
Map indices to strings.
Definition at line 182 of file SymbolTable.h.
Referenced by operator=().
std::unordered_map<std::string, size_t> souffle::SymbolTable::strToNum private
Map strings to indices.
Definition at line 185 of file SymbolTable.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
SymbolTable.h