souffle: souffle::detail::RecordMap< Tuple > Class Template Reference
souffle::detail::RecordMap< Tuple > Class Template Reference
A bidirectional mapping between tuples and reference indices.
#include <CompiledRecord.h>
Public Member Functions
RamDomain pack (const tuple_type &tuple)
Packs the given tuple – and may create a new reference if necessary.
RecordMap ()=default
const tuple_type & unpack (RamDomain index)
Obtains a pointer to the tuple addressed by the given index.
Private Types
using block_index_type = std::vector< std::unique_ptr< block_type >>
The type utilized for the block index.
using block_type = std::array< tuple_type, BLOCK_SIZE >
The definition of the type of a tuple block.
using tuple_type = Tuple
The definition of the tuple type handled by this instance.
Private Attributes
block_index_type i2r
The mapping from indices to tuples.
Lock pack_lock
a lock for the pack operation
std::unordered_map< tuple_type, RamDomain > r2i
The mapping from tuples to references/indices.
Static Private Attributes
static const std::size_t BLOCK_SIZE = 1 << 20
Detailed Description
template<typename Tuple>
class souffle::detail::RecordMap< Tuple >
A bidirectional mapping between tuples and reference indices.
Definition at line 79 of file CompiledRecord.h.
Member Typedef Documentation
template<typename Tuple> using souffle::detail::RecordMap< Tuple >::block_index_type = std::vector<std::unique_ptr<block_type>> private
The type utilized for the block index.
Definition at line 90 of file CompiledRecord.h.
template<typename Tuple> using souffle::detail::RecordMap< Tuple >::block_type = std::array<tuple_type, BLOCK_SIZE> private
The definition of the type of a tuple block.
Definition at line 87 of file CompiledRecord.h.
template<typename Tuple> using souffle::detail::RecordMap< Tuple >::tuple_type = Tuple private
The definition of the tuple type handled by this instance.
Definition at line 84 of file CompiledRecord.h.
Constructor & Destructor Documentation
template<typename Tuple> souffle::detail::RecordMap< Tuple >::RecordMap () default
Member Function Documentation
template<typename Tuple> RamDomain souffle::detail::RecordMap< Tuple >::pack (const tuple_type & tuple) inline
Packs the given tuple – and may create a new reference if necessary.
Definition at line 107 of file CompiledRecord.h.
References souffle::Lock::acquire(), and souffle::detail::RecordMap< Tuple >::BLOCK_SIZE.
Referenced by souffle::pack().
{
         RamDomain index;
         {
             // lock pack operation
             auto leas = pack_lock.acquire();  // lock hold till end of scope
             (void)leas;                       // avoid warning
             // try lookup
             auto pos = r2i.find(tuple);
             if (pos != r2i.end()) {
                 // take the previously assigned value
                 index = pos->second;
             } else {
                 // add tuple to index
                 index = r2i.size() + 1;  // since 0 is skipped for the Nil element
                 r2i[tuple] = index;
                 // assert that new index is smaller than the range
                 assert(index != std::numeric_limits<RamDomain>::max());
                 if (index / BLOCK_SIZE == i2r.size()) {
                     i2r.push_back(std::make_unique<block_type>());
                 }
                 // create entry for unpacking
                 auto& list = i2r[index / BLOCK_SIZE];
                 // insert tuple
                 (*list)[index % BLOCK_SIZE] = tuple;
             }
         }
         // done
         return index;
     }
template<typename Tuple> const tuple_type& souffle::detail::RecordMap< Tuple >::unpack (RamDomain index) inline
Obtains a pointer to the tuple addressed by the given index.
Definition at line 147 of file CompiledRecord.h.
References souffle::detail::RecordMap< Tuple >::BLOCK_SIZE.
Referenced by souffle::unpack().
{
         // just look up the right spot
         return (*(i2r[index / BLOCK_SIZE]))[index % BLOCK_SIZE];
     }
Field Documentation
template<typename Tuple> const std::size_t souffle::detail::RecordMap< Tuple >::BLOCK_SIZE = 1 << 20 static private
Definition at line 81 of file CompiledRecord.h.
Referenced by souffle::detail::RecordMap< Tuple >::pack(), and souffle::detail::RecordMap< Tuple >::unpack().
template<typename Tuple> block_index_type souffle::detail::RecordMap< Tuple >::i2r private
The mapping from indices to tuples.
Definition at line 96 of file CompiledRecord.h.
template<typename Tuple> Lock souffle::detail::RecordMap< Tuple >::pack_lock private
a lock for the pack operation
Definition at line 99 of file CompiledRecord.h.
template<typename Tuple> std::unordered_map<tuple_type, RamDomain> souffle::detail::RecordMap< Tuple >::r2i private
The mapping from tuples to references/indices.
Definition at line 93 of file CompiledRecord.h.
The documentation for this class was generated from the following file:
CompiledRecord.h