souffle: souffle::InterpreterIndexOrder Class Reference
souffle::InterpreterIndexOrder Class Reference
A class describing the sorting order of tuples within an index.
#include <InterpreterIndex.h>
Public Member Functions
void append (unsigned char column)
Append an additional column to the end of this order.
bool covers (unsigned char column) const
Determines whether the given column is covered or not.
InterpreterIndexOrder (std::vector< unsigned char > order=std::vector< unsigned char >())
InterpreterIndexOrder (const InterpreterIndexOrder &)=default
InterpreterIndexOrder (InterpreterIndexOrder &&)=default
bool isCompatible (const InterpreterIndexOrder &other) const
Tests whether this order is compatible with the given order.
bool isComplete () const
Tests whether the given order covers a complete list of columns.
bool isPrefixOf (const InterpreterIndexOrder &other) const
Tests whether this order is a prefix of the given order.
bool operator< (const InterpreterIndexOrder &other) const
Enables orders to be the key of a set or map.
InterpreterIndexOrder & operator= (const InterpreterIndexOrder &)=default
InterpreterIndexOrder & operator= (InterpreterIndexOrder &&)=default
unsigned char operator[] (std::size_t pos) const
Provides access to the order of columns.
void print (std::ostream &out) const
Enables the index order to be printed.
std::size_t size () const
Provides access to the size of this order.
Data Fields
std::vector< unsigned char > columns
Friends
std::ostream & operator<< (std::ostream &out, const InterpreterIndexOrder &order)
Detailed Description
A class describing the sorting order of tuples within an index.
Definition at line 32 of file InterpreterIndex.h.
Constructor & Destructor Documentation
souffle::InterpreterIndexOrder::InterpreterIndexOrder (std::vector< unsigned char > order = std::vector<unsigned char>()) inline
Definition at line 36 of file InterpreterIndex.h.
References operator=().
             : columns(std::move(order)) {}
souffle::InterpreterIndexOrder::InterpreterIndexOrder (const InterpreterIndexOrder &) default
souffle::InterpreterIndexOrder::InterpreterIndexOrder (InterpreterIndexOrder &&) default
Member Function Documentation
void souffle::InterpreterIndexOrder::append (unsigned char column) inline
Append an additional column to the end of this order.
Definition at line 62 of file InterpreterIndex.h.
References columns, and souffle::contains().
Referenced by souffle::InterpreterRelation::getIndex().
{
         assert(!contains(columns, column));
         columns.push_back(column);
     }
bool souffle::InterpreterIndexOrder::covers (unsigned char column) const inline
Determines whether the given column is covered or not.
Definition at line 73 of file InterpreterIndex.h.
References columns, and souffle::contains().
{
         return contains(columns, column);
     }
bool souffle::InterpreterIndexOrder::isCompatible (const InterpreterIndexOrder & other) const inline
Tests whether this order is compatible with the given order.
A order A is compatible with an order B if the first |A| elements of B are a permutation of A.
Definition at line 107 of file InterpreterIndex.h.
References columns, souffle::contains(), and i.
Referenced by souffle::InterpreterRelation::getIndex().
{
         // this one must be shorter
         if (columns.size() > other.columns.size()) {
             return false;
         }
         // check overlapping prefix
         for (unsigned i = 0; i < columns.size(); ++i) {
             if (!contains(columns, other.columns[i])) {
                 return false;
             }
         }
         return true;
     }
bool souffle::InterpreterIndexOrder::isComplete () const inline
Tests whether the given order covers a complete list of columns.
Definition at line 78 of file InterpreterIndex.h.
References columns, souffle::contains(), and i.
Referenced by souffle::InterpreterRelation::getIndex().
{
         // the columns must contain the values 0 ... |length|
         for (unsigned i = 0; i < columns.size(); i++) {
             if (!contains(columns, i)) {
                 return false;
             }
         }
         return true;
     }
bool souffle::InterpreterIndexOrder::isPrefixOf (const InterpreterIndexOrder & other) const inline
Tests whether this order is a prefix of the given order.
Definition at line 89 of file InterpreterIndex.h.
References columns, and i.
{
         // this one must not be longer
         if (columns.size() > other.columns.size()) {
             return false;
         }
         for (unsigned i = 0; i < columns.size(); i++) {
             if (columns[i] != other.columns[i]) {
                 return false;
             }
         }
         return true;
     }
bool souffle::InterpreterIndexOrder::operator< (const InterpreterIndexOrder & other) const inline
Enables orders to be the key of a set or map.
Definition at line 55 of file InterpreterIndex.h.
References columns.
{
         return columns < other.columns;
     }
InterpreterIndexOrder& souffle::InterpreterIndexOrder::operator= (const InterpreterIndexOrder &) default
Referenced by InterpreterIndexOrder().
InterpreterIndexOrder& souffle::InterpreterIndexOrder::operator= (InterpreterIndexOrder &&) default
unsigned char souffle::InterpreterIndexOrder::operator[] (std::size_t pos) const inline
Provides access to the order of columns.
Definition at line 50 of file InterpreterIndex.h.
References columns.
{
         return columns[pos];
     }
void souffle::InterpreterIndexOrder::print (std::ostream & out) const inline
Enables the index order to be printed.
Definition at line 122 of file InterpreterIndex.h.
References columns, i, and souffle::join().
{
         out << "[" << join(columns, ",", [](std::ostream& out, int i) { out << i; }) << "]";
     }
std::size_t souffle::InterpreterIndexOrder::size () const inline
Provides access to the size of this order.
Definition at line 68 of file InterpreterIndex.h.
References columns.
Referenced by souffle::InterpreterIndex::comparator::equal(), and souffle::InterpreterIndex::comparator::operator()().
{
         return columns.size();
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const InterpreterIndexOrder & order) friend
Definition at line 126 of file InterpreterIndex.h.
{
         order.print(out);
         return out;
     }
Field Documentation
std::vector<unsigned char> souffle::InterpreterIndexOrder::columns
Definition at line 131 of file InterpreterIndex.h.
Referenced by append(), covers(), isCompatible(), isComplete(), isPrefixOf(), operator<(), operator[](), print(), and size().
The documentation for this class was generated from the following file:
InterpreterIndex.h