souffle: souffle::IndexSetAnalysis Class Reference
souffle::IndexSetAnalysis Class Reference
Analysis pass computing the index sets of RAM relations.
#include <IndexSetAnalysis.h>
Public Member Functions
IndexSet & getIndexes (const RamRelation &rel)
get indexes
void print (std::ostream &os) const override
print analysis
void run (const RamTranslationUnit &translationUnit) override
run analysis
Public Member Functions inherited from souffle::RamAnalysis
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "index-analysis"
Private Attributes
std::map< std::string, IndexSet > data
Detailed Description
Analysis pass computing the index sets of RAM relations.
Definition at line 242 of file IndexSetAnalysis.h.
Member Function Documentation
IndexSet& souffle::IndexSetAnalysis::getIndexes (const RamRelation & rel) inline
get indexes
Definition at line 253 of file IndexSetAnalysis.h.
References souffle::RamRelation::getName().
{
         auto pos = data.find(rel.getName());
         if (pos != data.end()) {
             return pos->second;
         } else {
             auto ret = data.insert(make_pair(rel.getName(), IndexSet(rel)));
             assert(ret.second);
             return ret.first->second;
         }
     }
void souffle::IndexSetAnalysis::print (std::ostream & os) const override virtual
print analysis
Print indexes.
Reimplemented from souffle::RamAnalysis.
Definition at line 309 of file IndexSetAnalysis.cpp.
References souffle::IndexSet::getAllOrders(), souffle::RamRelation::getArg(), souffle::RamRelation::getArity(), souffle::IndexSet::getRelation(), souffle::IndexSet::getSearches(), and i.
{
     os << "------ Auto-Index-Generation Report -------\n";
     for (auto& cur : data) {
         const std::string& relName = cur.first;
         const IndexSet& indexes = cur.second;
         const RamRelation& rel = indexes.getRelation();
         /* Print searches */
         os << "Relation " << relName << "\n";
         os << "\tNumber of Search Patterns: " << indexes.getSearches().size() << "\n";
         /* print searches */
         for (auto& cols : indexes.getSearches()) {
             os << "\t\t";
             for (uint32_t i = 0; i < rel.getArity(); i++) {
                 if ((1UL << i) & cols) {
                     os << rel.getArg(i) << " ";
                 }
             }
             os << "\n";
         }
         os << "\tNumber of Indexes: " << indexes.getAllOrders().size() << "\n";
         for (auto& order : indexes.getAllOrders()) {
             os << "\t\t";
             for (auto& i : order) {
                 os << rel.getArg(i) << " ";
             }
             os << "\n";
         }
     }
     os << "------ End of Auto-Index-Generation Report -------\n";
 }
void souffle::IndexSetAnalysis::run (const RamTranslationUnit & translationUnit) override virtual
run analysis
Compute indexes.
Implements souffle::RamAnalysis.
Definition at line 282 of file IndexSetAnalysis.cpp.
References souffle::IndexSet::addSearch(), souffle::RamTranslationUnit::getAnalysis(), souffle::RamExistenceCheckAnalysis::getKey(), souffle::RamTranslationUnit::getProgram(), souffle::IndexSet::solve(), and souffle::visitDepthFirst().
{
     const auto* indexKeysAnalysis = translationUnit.getAnalysis<RamIndexKeysAnalysis>();
     const auto* existCheckAnalysis = translationUnit.getAnalysis<RamExistenceCheckAnalysis>();
     const auto* provExistCheckAnalysis = translationUnit.getAnalysis<RamProvenanceExistenceCheckAnalysis>();
     // visit all nodes to collect searches of each relation
     visitDepthFirst(*translationUnit.getProgram(), [&](const RamNode& node) {
         if (const auto* indexSearch = dynamic_cast<const RamIndexRelationSearch*>(&node)) {
             IndexSet& indexes = getIndexes(indexSearch->getRelation());
             indexes.addSearch(indexKeysAnalysis->getRangeQueryColumns(indexSearch));
         } else if (const auto* exists = dynamic_cast<const RamExistenceCheck*>(&node)) {
             IndexSet& indexes = getIndexes(exists->getRelation());
             indexes.addSearch(existCheckAnalysis->getKey(exists));
         } else if (const auto* provExists = dynamic_cast<const RamProvenanceExistenceCheck*>(&node)) {
             IndexSet& indexes = getIndexes(provExists->getRelation());
             indexes.addSearch(provExistCheckAnalysis->getKey(provExists));
         }
     });
     // find optimal indexes for relations
     for (auto& cur : data) {
         IndexSet& indexes = cur.second;
         indexes.solve();
     }
 }
Field Documentation
std::map<std::string, IndexSet> souffle::IndexSetAnalysis::data private
Definition at line 265 of file IndexSetAnalysis.h.
constexpr const char* souffle::IndexSetAnalysis::name = "index-analysis" static
Definition at line 244 of file IndexSetAnalysis.h.
The documentation for this class was generated from the following files:
IndexSetAnalysis.h
IndexSetAnalysis.cpp