souffle: souffle::RamIndexAggregate Class Reference
souffle::RamIndexAggregate Class Reference
Index Aggregation.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamIndexAggregate * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition * getCondition () const
Get condition.
const RamExpression * getExpression () const
Get target expression.
AggregateFunction getFunction () const
Get aggregation function.
void print (std::ostream &os, int tabpos) const override
RamIndexAggregate (std::unique_ptr< RamOperation > nested, AggregateFunction fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, std::vector< std::unique_ptr< RamExpression >> queryPattern, int ident)
Public Member Functions inherited from souffle::RamIndexRelationSearch
std::vector< RamExpression * > getRangePattern () const
Get range pattern.
RamIndexRelationSearch (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationSearch
const RamRelation & getRelation () const
Get search relation.
RamRelationSearch (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamSearch
int getTupleId () const
Get identifier.
RamSearch (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
RamOperation ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Abstract equality check for two RAM nodes.
Protected Attributes
std::unique_ptr< RamCondition > condition
Aggregation tuple condition.
std::unique_ptr< RamExpression > expression
Aggregation expression.
AggregateFunction function
Aggregation function.
Protected Attributes inherited from souffle::RamIndexRelationSearch
std::vector< std::unique_ptr< RamExpression > > queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationSearch
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamSearch
const int identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Index Aggregation.
Definition at line 431 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamIndexAggregate::RamIndexAggregate (std::unique_ptr< RamOperation > nested, AggregateFunction fun, std::unique_ptr< RamRelationReference > relRef, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamCondition > condition, std::vector< std::unique_ptr< RamExpression >> queryPattern, int ident) inline
Definition at line 433 of file RamOperation.h.
             : RamIndexRelationSearch(std::move(relRef), ident, std::move(queryPattern), std::move(nested)),
               function(fun), expression(std::move(expression)), condition(std::move(condition)) {}
Member Function Documentation
void souffle::RamIndexAggregate::apply (const RamNodeMapper & mapper) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamIndexRelationSearch.
Definition at line 523 of file RamOperation.h.
References souffle::RamIndexRelationSearch::apply().
{
         RamIndexRelationSearch::apply(map);
         if (condition != nullptr) {
             condition = map(std::move(condition));
         }
         if (expression != nullptr) {
             expression = map(std::move(expression));
         }
     }
RamIndexAggregate* souffle::RamIndexAggregate::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 510 of file RamOperation.h.
References souffle::RamOperation::clone(), and e.
{
         std::vector<std::unique_ptr<RamExpression>> pattern;
         for (auto const& e : queryPattern) {
             pattern.push_back(std::unique_ptr<RamExpression>((e != nullptr) ? e->clone() : nullptr));
         }
         RamIndexAggregate* res = new RamIndexAggregate(std::unique_ptr<RamOperation>(getOperation().clone()),
                 function, std::unique_ptr<RamRelationReference>(relationRef->clone()),
                 expression == nullptr ? nullptr : std::unique_ptr<RamExpression>(expression->clone()),
                 condition == nullptr ? nullptr : std::unique_ptr<RamCondition>(condition->clone()),
                 std::move(pattern), getTupleId());
         return res;
     }
bool souffle::RamIndexAggregate::equal (const RamNode & other) const inline override protected virtual
Abstract equality check for two RAM nodes.
Reimplemented from souffle::RamIndexRelationSearch.
Definition at line 543 of file RamOperation.h.
References souffle::RamIndexRelationSearch::equal().
{
         assert(nullptr != dynamic_cast<const RamIndexAggregate*>(&node));
         const auto& other = static_cast<const RamIndexAggregate&>(node);
         if (getCondition() != nullptr && other.getCondition() != nullptr &&
                 *getCondition() != *other.getCondition()) {
             return false;
         }
         return RamIndexRelationSearch::equal(other) && getCondition() == other.getCondition() &&
                getFunction() == other.getFunction() && getExpression() == other.getExpression();
     }
std::vector<const RamNode*> souffle::RamIndexAggregate::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamIndexRelationSearch.
Definition at line 499 of file RamOperation.h.
References souffle::RamIndexRelationSearch::getChildNodes().
{
         auto res = RamIndexRelationSearch::getChildNodes();
         if (expression != nullptr) {
             res.push_back(expression.get());
         }
         if (condition != nullptr) {
             res.push_back(condition.get());
         }
         return res;
     }
const RamCondition* souffle::RamIndexAggregate::getCondition () const inline
Get condition.
Definition at line 441 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), and souffle::LVMGenerator::visitIndexAggregate().
{
         return condition.get();
     }
const RamExpression* souffle::RamIndexAggregate::getExpression () const inline
Get target expression.
Definition at line 451 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), and souffle::LVMGenerator::visitIndexAggregate().
{
         return expression.get();
     }
AggregateFunction souffle::RamIndexAggregate::getFunction () const inline
Get aggregation function.
Definition at line 446 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalOp(), and souffle::LVMGenerator::visitIndexAggregate().
{
         return function;
     }
void souffle::RamIndexAggregate::print (std::ostream & os, int tabpos) const inline override virtual
Reimplemented from souffle::RamNestedOperation.
Definition at line 455 of file RamOperation.h.
References souffle::COUNT, souffle::RamRelation::getArg(), souffle::RamRelation::getArity(), i, souffle::MAX, souffle::MIN, souffle::RamNestedOperation::print(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "t" << getTupleId() << ".0=";
         switch (function) {
             case MIN:
                 os << "MIN ";
                 break;
             case MAX:
                 os << "MAX ";
                 break;
             case COUNT:
                 os << "COUNT ";
                 break;
             case SUM:
                 os << "SUM ";
                 break;
         }
         if (function != COUNT) {
             os << *expression << " ";
         }
         os << " SEARCH t" << getTupleId() << "  " << getRelation().getName();
         bool first = true;
         os << " INDEX ";
         for (unsigned int i = 0; i < rel.getArity(); ++i) {
             if (queryPattern[i] != nullptr) {
                 if (first) {
                     first = false;
                 } else {
                     os << " and ";
                 }
                 os << "t" << getTupleId() << "." << rel.getArg(i) << "=" << *queryPattern[i];
             }
         }
         if (first) {
             os << "none";
         }
         if (condition != nullptr) {
             os << " WHERE " << *getCondition();
         }
         os << std::endl;
         RamIndexRelationSearch::print(os, tabpos + 1);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamIndexAggregate::condition protected
Aggregation tuple condition.
Definition at line 541 of file RamOperation.h.
std::unique_ptr<RamExpression> souffle::RamIndexAggregate::expression protected
Aggregation expression.
Definition at line 538 of file RamOperation.h.
AggregateFunction souffle::RamIndexAggregate::function protected
Aggregation function.
Definition at line 535 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h