souffle: souffle::IODirectives Class Reference
souffle::IODirectives Class Reference
#include <IODirectives.h>
Public Member Functions
const std::string & get (const std::string &key) const
const std::string & getFileName () const
const std::string & getIOType () const
const std::string & getRelationName () const
bool has (const std::string &key) const
IODirectives ()=default
IODirectives (const std::map< std::string, std::string > &directiveMap)
bool isEmpty ()
bool operator!= (const IODirectives &other) const
bool operator== (const IODirectives &other) const
void print (std::ostream &out) const
void set (const std::string &key, const std::string &value)
void setFileName (const std::string &filename)
void setIOType (const std::string &type)
void setRelationName (const std::string &name)
~IODirectives ()=default
Private Member Functions
std::string escape (const std::string &inputString) const
std::string escape (const std::string &inputString, const std::string &needle, const std::string &replacement) const
Private Attributes
std::map< std::string, std::string > directives
Friends
std::ostream & operator<< (std::ostream &out, const IODirectives &ioDirectives)
Detailed Description
Definition at line 23 of file IODirectives.h.
Constructor & Destructor Documentation
souffle::IODirectives::IODirectives () default
souffle::IODirectives::IODirectives (const std::map< std::string, std::string > & directiveMap) inline
Definition at line 27 of file IODirectives.h.
References directives, and ~IODirectives().
{
         for (const auto& pair : directiveMap) {
             directives[pair.first] = pair.second;
         }
     }
souffle::IODirectives::~IODirectives () default
Referenced by IODirectives().
Member Function Documentation
std::string souffle::IODirectives::escape (const std::string & inputString) const inline private
Definition at line 106 of file IODirectives.h.
Referenced by print().
{
         std::string escaped = escape(inputString, "\"", "\\\"");
         escaped = escape(escaped, "\t", "\\t");
         escaped = escape(escaped, "\r", "\\r");
         escaped = escape(escaped, "\n", "\\n");
         return escaped;
     }
std::string souffle::IODirectives::escape (const std::string & inputString, const std::string & needle, const std::string & replacement) const inline private
Definition at line 114 of file IODirectives.h.
{
         std::string result = inputString;
         size_t pos = 0;
         while ((pos = result.find(needle, pos)) != std::string::npos) {
             result = result.replace(pos, needle.length(), replacement);
             pos += replacement.length();
         }
         return result;
     }
const std::string& souffle::IODirectives::get (const std::string & key) const inline
Definition at line 43 of file IODirectives.h.
References directives.
Referenced by souffle::WriteStreamCSV::getDelimiter(), souffle::ReadStreamCSV::getDelimiter(), souffle::ReadFileCSV::getFileName(), souffle::ReadStreamCSV::getInputColumnMap(), souffle::ReadSQLiteFactory::getReader(), souffle::WriteSQLiteFactory::getWriter(), souffle::ReadFileCSV::ReadFileCSV(), souffle::WriteCoutCSV::WriteCoutCSV(), souffle::WriteFileCSV::WriteFileCSV(), and souffle::WriteFileCSV::writeNextTuple().
{
         if (directives.count(key) == 0) {
             throw std::invalid_argument("Requested IO directive <" + key + "> was not specified");
         }
         return directives.at(key);
     }
const std::string& souffle::IODirectives::getFileName () const inline
Definition at line 58 of file IODirectives.h.
Referenced by souffle::AstTranslator::makeIODirective(), and souffle::WriteFileCSV::writeNextTuple().
{
         return get("filename");
     }
const std::string& souffle::IODirectives::getIOType () const inline
Definition at line 35 of file IODirectives.h.
Referenced by souffle::IOSystem::getReader(), souffle::IOSystem::getWriter(), souffle::AstTranslator::makeIODirective(), and souffle::MagicSetTransformer::transform().
{
         return get("IO");
     }
const std::string& souffle::IODirectives::getRelationName () const inline
Definition at line 66 of file IODirectives.h.
Referenced by souffle::ReadFileCSV::getFileName(), souffle::ReadSQLiteFactory::getReader(), souffle::WriteSQLiteFactory::getWriter(), souffle::AstTranslator::makeIODirective(), and souffle::WriteCoutCSV::WriteCoutCSV().
{
         return get("name");
     }
bool souffle::IODirectives::has (const std::string & key) const inline
Definition at line 54 of file IODirectives.h.
References directives.
Referenced by souffle::WriteStreamCSV::getDelimiter(), souffle::ReadStreamCSV::getDelimiter(), souffle::ReadFileCSV::getFileName(), souffle::ReadStreamCSV::getInputColumnMap(), souffle::WriteFileCSVFactory::getWriter(), souffle::AstTranslator::makeIODirective(), souffle::ReadFileCSV::ReadFileCSV(), souffle::MagicSetTransformer::transform(), souffle::WriteCoutCSV::WriteCoutCSV(), souffle::WriteFileCSV::WriteFileCSV(), and souffle::WriteFileCSV::writeNextTuple().
{
         return directives.count(key) > 0;
     }
bool souffle::IODirectives::isEmpty () inline
Definition at line 74 of file IODirectives.h.
References directives.
                    {
         return directives.empty();
     }
bool souffle::IODirectives::operator!= (const IODirectives & other) const inline
Definition at line 101 of file IODirectives.h.
References directives.
{
         return directives != other.directives;
     }
bool souffle::IODirectives::operator== (const IODirectives & other) const inline
Definition at line 97 of file IODirectives.h.
References directives.
{
         return directives == other.directives;
     }
void souffle::IODirectives::print (std::ostream & out) const inline
Definition at line 78 of file IODirectives.h.
References directives, and escape().
{
         auto cur = directives.begin();
         if (cur == directives.end()) {
             return;
         }
         out << "{{\"" << cur->first << "\",\"" << escape(cur->second) << "\"}";
         ++cur;
         for (; cur != directives.end(); ++cur) {
             out << ",{\"" << cur->first << "\",\"" << escape(cur->second) << "\"}";
         }
         out << '}';
     }
void souffle::IODirectives::set (const std::string & key, const std::string & value) inline
Definition at line 50 of file IODirectives.h.
References directives.
Referenced by souffle::AstTranslator::getInputIODirectives(), souffle::AstTranslator::getOutputIODirectives(), souffle::AstTranslator::makeIODirective(), and souffle::MagicSetTransformer::transform().
{
         directives[key] = value;
     }
void souffle::IODirectives::setFileName (const std::string & filename) inline
Definition at line 62 of file IODirectives.h.
References directives.
Referenced by souffle::AstTranslator::makeIODirective().
{
         directives["filename"] = filename;
     }
void souffle::IODirectives::setIOType (const std::string & type) inline
Definition at line 39 of file IODirectives.h.
References directives.
Referenced by souffle::AstTranslator::getOutputIODirectives(), souffle::AstTranslator::makeIODirective(), and souffle::MagicSetTransformer::transform().
{
         directives["IO"] = type;
     }
void souffle::IODirectives::setRelationName (const std::string & name) inline
Definition at line 70 of file IODirectives.h.
References directives.
Referenced by souffle::ExplainProvenance::getRelationOutput(), souffle::AstTranslator::makeIODirective(), and souffle::MagicSetTransformer::transform().
{
         directives["name"] = name;
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const IODirectives & ioDirectives) friend
Definition at line 92 of file IODirectives.h.
{
         ioDirectives.print(out);
         return out;
     }
Field Documentation
std::map<std::string, std::string> souffle::IODirectives::directives private
Definition at line 125 of file IODirectives.h.
Referenced by get(), has(), IODirectives(), isEmpty(), operator!=(), operator==(), print(), set(), setFileName(), setIOType(), and setRelationName().
The documentation for this class was generated from the following file:
IODirectives.h