souffle: souffle::RamElementAccess Class Reference
souffle::RamElementAccess Class Reference
Access element from the current tuple in a tuple environment.
#include <RamExpression.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamElementAccess * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getElement () const
Get element.
int getTupleId () const
Get identifier.
void print (std::ostream &os) const override
Print.
RamElementAccess (size_t ident, size_t elem, std::unique_ptr< RamRelationReference > relRef=nullptr)
Public Member Functions inherited from souffle::RamExpression
RamExpression ()=default
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode ()=default
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
const size_t element
Element number.
const size_t identifier
Identifier for the tuple.
std::unique_ptr< RamRelationReference > relationRef
Relation for debugging purposes Set to nullptr for non-existent relations.
Detailed Description
Access element from the current tuple in a tuple environment.
Definition at line 230 of file RamExpression.h.
Constructor & Destructor Documentation
souffle::RamElementAccess::RamElementAccess (size_t ident, size_t elem, std::unique_ptr< RamRelationReference > relRef = nullptr) inline
Definition at line 232 of file RamExpression.h.
             : RamExpression(), identifier(ident), element(elem), relationRef(std::move(relRef)) {}
Member Function Documentation
void souffle::RamElementAccess::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 270 of file RamExpression.h.
{
         if (relationRef != nullptr) {
             relationRef = map(std::move(relationRef));
         }
     }
RamElementAccess* souffle::RamElementAccess::clone () const inline override virtual
Create clone.
Implements souffle::RamExpression.
Definition at line 260 of file RamExpression.h.
References souffle::identifier().
{
         if (relationRef != nullptr) {
             return new RamElementAccess(
                     identifier, element, std::unique_ptr<RamRelationReference>(relationRef->clone()));
         } else {
             return new RamElementAccess(identifier, element);
         }
     }
bool souffle::RamElementAccess::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 289 of file RamExpression.h.
References getTupleId().
{
         assert(nullptr != dynamic_cast<const RamElementAccess*>(&node));
         const auto& other = static_cast<const RamElementAccess&>(node);
         return getTupleId() == other.getTupleId() && getElement() == other.getElement();
     }
std::vector<const RamNode*> souffle::RamElementAccess::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 255 of file RamExpression.h.
{
         return {relationRef.get()};
     }
size_t souffle::RamElementAccess::getElement () const inline
Get element.
Definition at line 250 of file RamExpression.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RAMI::evalExpr(), and souffle::LVMGenerator::visitElementAccess().
{
         return element;
     }
int souffle::RamElementAccess::getTupleId () const inline
Get identifier.
Definition at line 245 of file RamExpression.h.
References souffle::identifier().
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::RAMI::evalExpr(), souffle::RamLevelAnalysis::getLevel(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), and souffle::LVMGenerator::visitElementAccess().
{
         return identifier;
     }
void souffle::RamElementAccess::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 236 of file RamExpression.h.
References souffle::identifier().
{
         if (nullptr == relationRef) {
             os << "t" << identifier << "." << element;
         } else {
             os << "t" << identifier << "." << relationRef->get()->getArg(element);
         }
     }
Field Documentation
const size_t souffle::RamElementAccess::element protected
Element number.
Definition at line 281 of file RamExpression.h.
const size_t souffle::RamElementAccess::identifier protected
Identifier for the tuple.
Definition at line 278 of file RamExpression.h.
std::unique_ptr<RamRelationReference> souffle::RamElementAccess::relationRef protected
Relation for debugging purposes Set to nullptr for non-existent relations.
Definition at line 286 of file RamExpression.h.
The documentation for this class was generated from the following file:
RamExpression.h