souffle: souffle::MaxMatching Class Reference
souffle::MaxMatching Class Reference
Computes a maximum matching with Hopcroft-Karp algorithm Source: http://en.wikipedia.org/wiki/Hopcroft%E2%80%93Karp_algorithm#Pseudocode.
#include <IndexSetAnalysis.h>
Public Types
using Matchings = std::map< SearchColumns, SearchColumns, std::greater< SearchColumns >>
using Nodes = std::set< SearchColumns, std::greater< SearchColumns >>
Public Member Functions
void addEdge (SearchColumns u, SearchColumns v)
Add edge.
int getNumMatchings () const
Get number of matches.
const Matchings & solve ()
Solve.
Protected Member Functions
bool bfSearch ()
breadth first search
bool dfSearch (SearchColumns u)
depth first search
int getDistance (int v)
Get distance.
SearchColumns getMatch (SearchColumns v)
Get match.
Private Types
using Distance = std::map< SearchColumns, int >
using Edges = std::set< SearchColumns >
using Graph = std::map< SearchColumns, Edges >
Private Attributes
Distance distance
Graph graph
Matchings match
Detailed Description
Computes a maximum matching with Hopcroft-Karp algorithm Source: http://en.wikipedia.org/wiki/Hopcroft%E2%80%93Karp_algorithm#Pseudocode.
Definition at line 48 of file IndexSetAnalysis.h.
Member Typedef Documentation
using souffle::MaxMatching::Distance = std::map<SearchColumns, int> private
Definition at line 81 of file IndexSetAnalysis.h.
using souffle::MaxMatching::Edges = std::set<SearchColumns> private
Definition at line 79 of file IndexSetAnalysis.h.
using souffle::MaxMatching::Graph = std::map<SearchColumns, Edges> private
Definition at line 80 of file IndexSetAnalysis.h.
using souffle::MaxMatching::Matchings = std::map<SearchColumns, SearchColumns, std::greater<SearchColumns>>
Definition at line 50 of file IndexSetAnalysis.h.
using souffle::MaxMatching::Nodes = std::set<SearchColumns, std::greater<SearchColumns>>
Definition at line 51 of file IndexSetAnalysis.h.
Member Function Documentation
void souffle::MaxMatching::addEdge (SearchColumns u, SearchColumns v)
Add edge.
Class MaxMatching.
Add edge
Definition at line 39 of file IndexSetAnalysis.cpp.
References graph.
Referenced by getNumMatchings().
{
     if (graph.find(u) == graph.end()) {
         Edges vals;
         vals.insert(v);
         graph.insert(make_pair(u, vals));
     } else {
         graph[u].insert(v);
     }
 }
bool souffle::MaxMatching::bfSearch () protected
breadth first search
Breadth first search.
Definition at line 68 of file IndexSetAnalysis.cpp.
References distance, getDistance(), getMatch(), graph, INF, and NIL.
Referenced by getNumMatchings(), and solve().
{
     SearchColumns u;
     std::queue<SearchColumns> bfQueue;
     // Build layers
     for (auto& it : graph) {
         if (getMatch(it.first) == NIL) {
             distance[it.first] = 0;
             bfQueue.push(it.first);
         } else {
             distance[it.first] = INF;
         }
     }
     distance[NIL] = INF;
     while (!bfQueue.empty()) {
         u = bfQueue.front();
         bfQueue.pop();
         assert(u != NIL);
         const Edges& children = graph[u];
         for (auto it : children) {
             SearchColumns mv = getMatch(it);
             if (getDistance(mv) == INF) {
                 distance[mv] = getDistance(u) + 1;
                 if (mv != NIL) {
                     bfQueue.push(mv);
                 }
             }
         }
     }
     return (getDistance(0) != INF);
 }
bool souffle::MaxMatching::dfSearch (SearchColumns u) protected
depth first search
Depth first search.
Definition at line 100 of file IndexSetAnalysis.cpp.
References distance, getDistance(), getMatch(), graph, INF, and match.
Referenced by getNumMatchings(), and solve().
{
     if (u != 0) {
         Edges& children = graph[u];
         for (auto v : children) {
             if (getDistance(getMatch(v)) == getDistance(u) + 1) {
                 if (dfSearch(getMatch(v))) {
                     match[u] = v;
                     match[v] = u;
                     return true;
                 }
             }
         }
         distance[u] = INF;
         return false;
     }
     return true;
 }
int souffle::MaxMatching::getDistance (int v) protected
Get distance.
Get Distance.
Definition at line 59 of file IndexSetAnalysis.cpp.
References distance, and INF.
Referenced by bfSearch(), dfSearch(), and getNumMatchings().
{
     auto it = distance.find(v);
     if (it == distance.end()) {
         return INF;
     }
     return it->second;
 }
SearchColumns souffle::MaxMatching::getMatch (SearchColumns v) protected
Get match.
Definition at line 50 of file IndexSetAnalysis.cpp.
References match, and NIL.
Referenced by bfSearch(), dfSearch(), getNumMatchings(), and solve().
{
     auto it = match.find(v);
     if (it == match.end()) {
         return NIL;
     }
     return it->second;
 }
int souffle::MaxMatching::getNumMatchings () const inline
Get number of matches.
Definition at line 58 of file IndexSetAnalysis.h.
References addEdge(), bfSearch(), dfSearch(), getDistance(), getMatch(), and match.
{
         return match.size() / 2;
     }
const MaxMatching::Matchings & souffle::MaxMatching::solve ()
Solve.
Calculate max-matching.
Definition at line 120 of file IndexSetAnalysis.cpp.
References bfSearch(), dfSearch(), getMatch(), graph, match, and NIL.
Referenced by souffle::IndexSet::isSubset().
{
     while (bfSearch()) {
         for (auto& it : graph) {
             if (getMatch(it.first) == NIL) {
                 dfSearch(it.first);
             }
         }
     }
     return match;
 }
Field Documentation
Distance souffle::MaxMatching::distance private
Definition at line 85 of file IndexSetAnalysis.h.
Referenced by bfSearch(), dfSearch(), and getDistance().
Graph souffle::MaxMatching::graph private
Definition at line 84 of file IndexSetAnalysis.h.
Referenced by addEdge(), bfSearch(), dfSearch(), and solve().
Matchings souffle::MaxMatching::match private
Definition at line 83 of file IndexSetAnalysis.h.
Referenced by dfSearch(), getMatch(), getNumMatchings(), souffle::IndexSet::insertIndex(), and solve().
The documentation for this class was generated from the following files:
IndexSetAnalysis.h
IndexSetAnalysis.cpp