souffle: souffle::AstProfileUse Class Reference
souffle::AstProfileUse Class Reference
AstAnalysis that loads profile data and has a profile query interface.
#include <AstProfileUse.h>
Public Member Functions
AstProfileUse ()
size_t getRelationSize (const AstRelationIdentifier &rel)
Return size of relation in the profile.
bool hasRelationSize (const AstRelationIdentifier &rel)
Check whether the relation size exists in profile.
void print (std::ostream &os) const override
Output some profile information.
void run (const AstTranslationUnit &translationUnit) override
Run analysis.
Public Member Functions inherited from souffle::AstAnalysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "profile-use"
Name of analysis.
Private Attributes
std::shared_ptr< profile::ProgramRun > programRun
performance model of profile run
Detailed Description
AstAnalysis that loads profile data and has a profile query interface.
Definition at line 32 of file AstProfileUse.h.
Constructor & Destructor Documentation
souffle::AstProfileUse::AstProfileUse () inline
Definition at line 41 of file AstProfileUse.h.
References getRelationSize(), hasRelationSize(), print(), and run().
 : programRun(std::make_shared<profile::ProgramRun>(profile::ProgramRun())) {}
Member Function Documentation
size_t souffle::AstProfileUse::getRelationSize (const AstRelationIdentifier & rel)
Return size of relation in the profile.
Get relation size from profile.
Definition at line 56 of file AstProfileUse.cpp.
References souffle::AstRelationIdentifier::getName(), and programRun.
Referenced by AstProfileUse().
{
     if (const auto* profRel = programRun->getRelation(rel.getName())) {
         return profRel->size();
     } else {
         return std::numeric_limits<size_t>::max();
     }
 }
bool souffle::AstProfileUse::hasRelationSize (const AstRelationIdentifier & rel)
Check whether the relation size exists in profile.
Check whether relation size is defined in profile.
Definition at line 49 of file AstProfileUse.cpp.
References souffle::AstRelationIdentifier::getName(), and programRun.
Referenced by AstProfileUse().
{
     return programRun->getRelation(rel.getName()) != nullptr;
 }
void souffle::AstProfileUse::print (std::ostream & os) const override virtual
Output some profile information.
Print analysis.
Reimplemented from souffle::AstAnalysis.
Definition at line 44 of file AstProfileUse.cpp.
Referenced by AstProfileUse().
 {}
void souffle::AstProfileUse::run (const AstTranslationUnit & translationUnit) override virtual
Run analysis.
Run analysis, i.e., retrieve profile information.
Implements souffle::AstAnalysis.
Definition at line 34 of file AstProfileUse.cpp.
References souffle::Global::config(), souffle::profile::Reader::processFile(), and programRun.
Referenced by AstProfileUse().
{
     if (Global::config().has("profile-use")) {
         std::string filename = Global::config().get("profile-use");
         profile::Reader(filename, programRun).processFile();
     }
 }
Field Documentation
constexpr const char* souffle::AstProfileUse::name = "profile-use" static
Name of analysis.
Definition at line 39 of file AstProfileUse.h.
std::shared_ptr<profile::ProgramRun> souffle::AstProfileUse::programRun private
performance model of profile run
Definition at line 35 of file AstProfileUse.h.
Referenced by getRelationSize(), hasRelationSize(), and run().
The documentation for this class was generated from the following files:
AstProfileUse.h
AstProfileUse.cpp