souffle: souffle::AstArgument Class Reference
souffle::AstArgument Class Reference abstract
Intermediate representation of an argument.
#include <AstArgument.h>
Public Member Functions
AstArgument * clone () const override=0
Create clone.
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &mapper)=0
Apply the mapper to all child nodes.
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
virtual void print (std::ostream &os) const =0
Output to a given output stream.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Additional Inherited Members
Protected Member Functions inherited from souffle::AstNode
virtual bool equal (const AstNode &other) const =0
Abstract equality check for two AST nodes.
Detailed Description
Intermediate representation of an argument.
Definition at line 43 of file AstArgument.h.
Constructor & Destructor Documentation
souffle::AstArgument::~AstArgument () override default
Member Function Documentation
AstArgument* souffle::AstArgument::clone () const override pure virtual
Create clone.
Implements souffle::AstNode.
Implemented in souffle::AstSubroutineArgument, souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, souffle::AstIntrinsicFunctor, souffle::AstNullConstant, souffle::AstNumberConstant, souffle::AstStringConstant, souffle::AstCounter, souffle::AstUnnamedVariable, and souffle::AstVariable.
Referenced by souffle::BindingStore::addBinding(), souffle::AstAggregator::addBodyLiteral(), souffle::BindingStore::cloneOriginalArgument(), and getChildNodes().
std::vector<const AstNode*> souffle::AstArgument::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Implements souffle::AstNode.
Reimplemented in souffle::AstAggregator, souffle::AstTypeCast, souffle::AstRecordInit, souffle::AstUserDefinedFunctor, and souffle::AstIntrinsicFunctor.
Definition at line 48 of file AstArgument.h.
References clone().
Referenced by souffle::AstAggregator::addBodyLiteral(), souffle::AstIntrinsicFunctor::getChildNodes(), souffle::AstUserDefinedFunctor::getChildNodes(), souffle::AstRecordInit::getChildNodes(), souffle::AstTypeCast::getChildNodes(), and souffle::AstAggregator::getChildNodes().
{
         return std::vector<const AstNode*>();  // type is just cached, not essential
     }
The documentation for this class was generated from the following file:
AstArgument.h