souffle: souffle::TypeBinding Class Reference
souffle::TypeBinding Class Reference
Class that encapsulates std::map of types binding that comes from .init c = Comp<MyType> Type binding in this example would be T->MyType if the component code is .comp Comp<T> ...
#include <ComponentModel.h>
Public Member Functions
TypeBinding extend (const std::vector< AstTypeIdentifier > &formalParams, const std::vector< AstTypeIdentifier > &actualParams) const
const AstTypeIdentifier & find (const AstTypeIdentifier &name) const
Returns binding for given name or empty string if such binding does not exist.
Private Attributes
std::map< AstTypeIdentifier, AstTypeIdentifier > binding
Key value pair.
Detailed Description
Class that encapsulates std::map of types binding that comes from .init c = Comp<MyType> Type binding in this example would be T->MyType if the component code is .comp Comp<T> ...
Definition at line 35 of file ComponentModel.h.
Member Function Documentation
TypeBinding souffle::TypeBinding::extend (const std::vector< AstTypeIdentifier > & formalParams, const std::vector< AstTypeIdentifier > & actualParams) const inline
Definition at line 49 of file ComponentModel.h.
References binding, and i.
Referenced by souffle::AstComponentChecker::checkComponent().
{
         TypeBinding result;
         if (formalParams.size() != actualParams.size()) {
             return *this;  // invalid init => will trigger a semantic error
         }
         for (std::size_t i = 0; i < formalParams.size(); i++) {
             auto pos = binding.find(actualParams[i]);
             if (pos != binding.end()) {
                 result.binding[formalParams[i]] = pos->second;
             } else {
                 result.binding[formalParams[i]] = actualParams[i];
             }
         }
         return result;
     }
const AstTypeIdentifier& souffle::TypeBinding::find (const AstTypeIdentifier & name) const inline
Returns binding for given name or empty string if such binding does not exist.
Definition at line 40 of file ComponentModel.h.
References binding.
Referenced by souffle::AstComponentChecker::checkComponentNameReference(), and souffle::ComponentLookup::getComponent().
{
         const static AstTypeIdentifier unknown;
         auto pos = binding.find(name);
         if (pos == binding.end()) {
             return unknown;
         }
         return pos->second;
     }
Field Documentation
std::map<AstTypeIdentifier, AstTypeIdentifier> souffle::TypeBinding::binding private
Key value pair.
Keys are names that should be forwarded to value, which is the actual name. Example T->MyImplementation.
Definition at line 73 of file ComponentModel.h.
Referenced by extend(), and find().
The documentation for this class was generated from the following file:
ComponentModel.h