souffle: souffle::SouffleProgram Class Reference
souffle::SouffleProgram Class Reference abstract
Abstract base class for generated Datalog programs.
#include <SouffleInterface.h>
Public Member Functions
virtual void dumpInputs (std::ostream &out=std::cout)=0
virtual void dumpOutputs (std::ostream &out=std::cout)=0
virtual void executeSubroutine (std::string name, const std::vector< RamDomain > &args, std::vector< RamDomain > &ret, std::vector< bool > &retErr)
std::vector< Relation * > getAllRelations () const
std::vector< Relation * > getInputRelations () const
std::vector< Relation * > getInternalRelations () const
std::vector< Relation * > getOutputRelations () const
Relation * getRelation (const std::string &name) const
virtual SymbolTable & getSymbolTable ()=0
virtual void loadAll (std::string inputDirectory=".")=0
virtual void printAll (std::string outputDirectory=".")=0
void purgeInputRelations ()
void purgeInternalRelations ()
void purgeOutputRelations ()
virtual void run (size_t stratumIndex=-1)
virtual void runAll (std::string inputDirectory=".", std::string outputDirectory=".", size_t stratumIndex=-1)=0
virtual ~SouffleProgram ()=default
Protected Member Functions
void addRelation (const std::string &name, Relation *rel, bool isInput, bool isOutput)
Private Attributes
std::vector< Relation * > inputRelations
std::vector< Relation * > internalRelations
std::vector< Relation * > outputRelations
std::map< std::string, Relation * > relationMap
Detailed Description
Abstract base class for generated Datalog programs.
Definition at line 237 of file SouffleInterface.h.
Constructor & Destructor Documentation
virtual souffle::SouffleProgram::~SouffleProgram () virtual default
Member Function Documentation
void souffle::SouffleProgram::addRelation (const std::string & name, Relation * rel, bool isInput, bool isOutput) inline protected
Definition at line 247 of file SouffleInterface.h.
{
         relationMap[name] = rel;
         if (isInput) {
             inputRelations.push_back(rel);
         }
         if (isOutput) {
             outputRelations.push_back(rel);
         }
         if (!isInput && !isOutput) {
             internalRelations.push_back(rel);
         }
     }
virtual void souffle::SouffleProgram::dumpInputs (std::ostream & out = std::cout) pure virtual
Implemented in souffle::InterpreterProgInterface.
virtual void souffle::SouffleProgram::dumpOutputs (std::ostream & out = std::cout) pure virtual
Implemented in souffle::InterpreterProgInterface.
virtual void souffle::SouffleProgram::executeSubroutine (std::string name, const std::vector< RamDomain > & args, std::vector< RamDomain > & ret, std::vector< bool > & retErr) inline virtual
Reimplemented in souffle::InterpreterProgInterface.
Definition at line 312 of file SouffleInterface.h.
References souffle::Relation::getSymbolTable().
Referenced by souffle::ExplainProvenanceSLD::explain(), and souffle::ExplainProvenanceSLD::explainNegation().
                                                                 {}
std::vector<Relation*> souffle::SouffleProgram::getAllRelations () const inline
Definition at line 304 of file SouffleInterface.h.
Referenced by souffle::ExplainProvenanceSLD::setup().
{
         std::vector<Relation*> allRelations;
         allRelations.insert(allRelations.end(), inputRelations.begin(), inputRelations.end());
         allRelations.insert(allRelations.end(), internalRelations.begin(), internalRelations.end());
         allRelations.insert(allRelations.end(), outputRelations.begin(), outputRelations.end());
         return allRelations;
     }
std::vector<Relation*> souffle::SouffleProgram::getInputRelations () const inline
Definition at line 296 of file SouffleInterface.h.
{
         return inputRelations;
     }
std::vector<Relation*> souffle::SouffleProgram::getInternalRelations () const inline
Definition at line 300 of file SouffleInterface.h.
{
         return internalRelations;
     }
std::vector<Relation*> souffle::SouffleProgram::getOutputRelations () const inline
Definition at line 292 of file SouffleInterface.h.
{
         return outputRelations;
     }
Relation* souffle::SouffleProgram::getRelation (const std::string & name) const inline
Definition at line 283 of file SouffleInterface.h.
Referenced by souffle::ExplainProvenance::argsToNums(), souffle::ExplainProvenanceSLD::explain(), souffle::ExplainProvenanceSLD::explainNegation(), souffle::ExplainProvenanceSLD::findTuple(), souffle::ExplainProvenance::getRelationOutput(), souffle::ExplainProvenanceSLD::measureRelation(), and souffle::ExplainProvenance::numsToArgs().
{
         auto it = relationMap.find(name);
         if (it != relationMap.end()) {
             return (*it).second;
         } else {
             return nullptr;
         }
     };
virtual SymbolTable& souffle::SouffleProgram::getSymbolTable () pure virtual
Implemented in souffle::InterpreterProgInterface.
Referenced by souffle::ExplainProvenanceSLD::printRelationOutput().
virtual void souffle::SouffleProgram::loadAll (std::string inputDirectory = ".") pure virtual
Implemented in souffle::InterpreterProgInterface.
virtual void souffle::SouffleProgram::printAll (std::string outputDirectory = ".") pure virtual
Implemented in souffle::InterpreterProgInterface.
void souffle::SouffleProgram::purgeInputRelations () inline
Definition at line 322 of file SouffleInterface.h.
References relation.
{
         for (Relation* relation : inputRelations) relation->purge();
     }
void souffle::SouffleProgram::purgeInternalRelations () inline
Definition at line 327 of file SouffleInterface.h.
References relation.
{
         for (Relation* relation : internalRelations) relation->purge();
     }
void souffle::SouffleProgram::purgeOutputRelations () inline
Definition at line 317 of file SouffleInterface.h.
References relation.
{
         for (Relation* relation : outputRelations) relation->purge();
     }
virtual void souffle::SouffleProgram::run (size_t stratumIndex = -1) inline virtual
Reimplemented in souffle::InterpreterProgInterface.
Definition at line 264 of file SouffleInterface.h.
 {}
virtual void souffle::SouffleProgram::runAll (std::string inputDirectory = ".", std::string outputDirectory = ".", size_t stratumIndex = -1) pure virtual
Implemented in souffle::InterpreterProgInterface.
Field Documentation
std::vector<Relation*> souffle::SouffleProgram::inputRelations private
Definition at line 241 of file SouffleInterface.h.
std::vector<Relation*> souffle::SouffleProgram::internalRelations private
Definition at line 243 of file SouffleInterface.h.
std::vector<Relation*> souffle::SouffleProgram::outputRelations private
Definition at line 242 of file SouffleInterface.h.
std::map<std::string, Relation*> souffle::SouffleProgram::relationMap private
Definition at line 240 of file SouffleInterface.h.
The documentation for this class was generated from the following file:
SouffleInterface.h