souffle: souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper Class Reference
souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper Class Reference
Public Member Functions
iterator_base * clone () const override
iterator_wrapper (uint32_t arg_id, const Relation *rel, const typename RelType::iterator &arg_it)
tuple & operator* () override
void operator++ () override
Protected Member Functions
bool equal (const iterator_base &o) const override
Private Attributes
RelType::iterator it
const Relation * relation
tuple t
Detailed Description
template<uint32_t id, class RelType, class TupleType, size_t Arity>
class souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper
Definition at line 78 of file CompiledSouffle.h.
Constructor & Destructor Documentation
template<uint32_t id, class RelType , class TupleType , size_t Arity> souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::iterator_wrapper (uint32_t arg_id, const Relation * rel, const typename RelType::iterator & arg_it) inline
Definition at line 84 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity >::begin(), souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::clone(), and souffle::RelationWrapper< id, RelType, TupleType, Arity >::end().
                 : iterator_base(arg_id), it(arg_it), relation(rel), t(rel) {}
Member Function Documentation
template<uint32_t id, class RelType , class TupleType , size_t Arity> iterator_base* souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::clone () const inline override
Definition at line 96 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::iterator_wrapper().
{
             return new iterator_wrapper(*this);
         }
template<uint32_t id, class RelType , class TupleType , size_t Arity> bool souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::equal (const iterator_base & o) const inline override protected
Definition at line 101 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::it, and o.
{
             const auto& casted = static_cast<const iterator_wrapper&>(o);
             return it == casted.it;
         }
template<uint32_t id, class RelType , class TupleType , size_t Arity> tuple& souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::operator* () inline override
Definition at line 89 of file CompiledSouffle.h.
References i, souffle::tuple::rewind(), and souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::t.
{
             t.rewind();
             for (size_t i = 0; i < Arity; i++) {
                 t[i] = (*it)[i];
             }
             return t;
         }
template<uint32_t id, class RelType , class TupleType , size_t Arity> void souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::operator++ () inline override
Definition at line 86 of file CompiledSouffle.h.
References souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::it.
{
             ++it;
         }
Field Documentation
template<uint32_t id, class RelType , class TupleType , size_t Arity> RelType::iterator souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::it private
Definition at line 79 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::equal(), and souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::operator++().
template<uint32_t id, class RelType , class TupleType , size_t Arity> const Relation* souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::relation private
Definition at line 80 of file CompiledSouffle.h.
template<uint32_t id, class RelType , class TupleType , size_t Arity> tuple souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::t private
Definition at line 81 of file CompiledSouffle.h.
Referenced by souffle::RelationWrapper< id, RelType, TupleType, Arity >::contains(), souffle::RelationWrapper< id, RelType, TupleType, Arity >::insert(), and souffle::RelationWrapper< id, RelType, TupleType, Arity >::iterator_wrapper::operator*().
The documentation for this class was generated from the following file:
CompiledSouffle.h