souffle: json11 Namespace Reference
json11 Namespace Reference
Data Structures
class Json
class JsonArray
class JsonBoolean
class JsonDouble
class JsonInt
class JsonNull
class JsonObject
class JsonString
class JsonValue
struct NullStruct
struct Statics
class Value
Enumerations
enum JsonParse { STANDARD, COMMENTS }
Functions
static void dump (NullStruct, string &out)
static void dump (double value, string &out)
static void dump (long long value, string &out)
static void dump (bool value, string &out)
static void dump (const string &value, string &out)
static void dump (const Json::array &values, string &out)
static void dump (const Json::object &values, string &out)
static string esc (char c)
static bool in_range (long x, long lower, long upper)
static const Json & static_null ()
static const Statics & statics ()
Variables
static const int max_depth = 200
Enumeration Type Documentation
enum json11::JsonParse
Enumerator
STANDARD
COMMENTS
Definition at line 79 of file json11.h.
 { STANDARD, COMMENTS };
Function Documentation
static void json11::dump (NullStruct , string & out) static
Definition at line 298 of file json11.h.
Referenced by json11::Value< Json::STRING, string >::dump(), and souffle::SparseArray< value_t, BITS, merge_op >::dump().
{
     out += "null";
 }
static void json11::dump (double value, string & out) static
Definition at line 302 of file json11.h.
{
     if (std::isfinite(value)) {
         char buf[32];
         snprintf(buf, sizeof buf, "%.17g", value);
         out += buf;
     } else {
         out += "null";
     }
 }
static void json11::dump (long long value, string & out) static
Definition at line 312 of file json11.h.
{
     char buf[32];
     snprintf(buf, sizeof buf, "%lld", value);
     out += buf;
 }
static void json11::dump (bool value, string & out) static
Definition at line 318 of file json11.h.
{
     out += value ? "true" : "false";
 }
static void json11::dump (const string & value, string & out) static
Definition at line 322 of file json11.h.
References i.
{
     out += '"';
     for (size_t i = 0; i < value.length(); i++) {
         const char ch = value[i];
         if (ch == '\\') {
             out += "\\\\";
         } else if (ch == '"') {
             out += "\\\"";
         } else if (ch == '\b') {
             out += "\\b";
         } else if (ch == '\f') {
             out += "\\f";
         } else if (ch == '\n') {
             out += "\\n";
         } else if (ch == '\r') {
             out += "\\r";
         } else if (ch == '\t') {
             out += "\\t";
         } else if (static_cast<uint8_t>(ch) <= 0x1f) {
             char buf[8];
             snprintf(buf, sizeof buf, "\\u%04x", ch);
             out += buf;
         } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i + 1]) == 0x80 &&
                    static_cast<uint8_t>(value[i + 2]) == 0xa8) {
             out += "\\u2028";
             i += 2;
         } else if (static_cast<uint8_t>(ch) == 0xe2 && static_cast<uint8_t>(value[i + 1]) == 0x80 &&
                    static_cast<uint8_t>(value[i + 2]) == 0xa9) {
             out += "\\u2029";
             i += 2;
         } else {
             out += ch;
         }
     }
     out += '"';
 }
static void json11::dump (const Json::array & values, string & out) static
Definition at line 359 of file json11.h.
{
     bool first = true;
     out += "[";
     for (const auto& value : values) {
         if (!first) out += ", ";
         value.dump(out);
         first = false;
     }
     out += "]";
 }
static void json11::dump (const Json::object & values, string & out) static
Definition at line 370 of file json11.h.
References json11::Json::dump(), and json11::Json::m_ptr.
{
     bool first = true;
     out += "{";
     for (const auto& kv : values) {
         if (!first) out += ", ";
         dump(kv.first, out);
         out += ": ";
         kv.second.dump(out);
         first = false;
     }
     out += "}";
 }
static string json11::esc (char c) inline static
Definition at line 646 of file json11.h.
{
     char buf[12];
     if (static_cast<uint8_t>(c) >= 0x20 && static_cast<uint8_t>(c) <= 0x7f) {
         snprintf(buf, sizeof buf, "'%c' (%d)", c, c);
     } else {
         snprintf(buf, sizeof buf, "(%d)", c);
     }
     return string(buf);
 }
static bool json11::in_range (long x, long lower, long upper) inline static
Definition at line 656 of file json11.h.
{
     return (x >= lower && x <= upper);
 }
static const Json& json11::static_null () static
Definition at line 523 of file json11.h.
Referenced by json11::JsonValue::operator[](), json11::JsonArray::operator[](), and json11::JsonObject::operator[]().
{
     // This has to be separate, not in Statics, because Json() accesses statics().null.
     static const Json json_null;
     return json_null;
 }
static const Statics& json11::statics () static
Definition at line 518 of file json11.h.
Referenced by json11::JsonValue::array_items(), json11::JsonValue::object_items(), and json11::JsonValue::string_value().
{
     static const Statics s{};
     return s;
 }
Variable Documentation
const int json11::max_depth = 200 static
Definition at line 272 of file json11.h.