souffle: souffle::detail Namespace Reference
souffle::detail Namespace Reference
Data Structures
struct binary
struct binary_search
A binary search strategy for looking up keys in b-tree nodes.
class btree
The actual implementation of a b-tree data structure.
struct comparator
A generic comparator implementation as it is used by a b-tree based on types that can be less-than and equality comparable.
struct default_bottom_factory
struct default_factory
A templated functor to obtain default values for unspecified elements of sparse array instances.
struct default_meet_op
struct default_merge
A operation to be utilized by the sparse map when merging elements associated to different values.
struct default_strategy
struct default_strategy< int >
struct default_strategy< std::tuple< Ts... > >
struct fix_binding
A functor initializing an iterator upon creation to reference the first element exhibiting a given prefix within a given Trie.
struct fix_binding< 0, Dim, Dim >
struct fix_binding< 0, Pos, Dim >
struct fix_first
A functor initializing an iterator upon creation to reference the first element in the associated Trie.
struct fix_first< Dim, Dim >
struct get_nested_iter_core
A functor extracting a reference to a nested iterator core from an enclosing iterator core.
struct get_nested_iter_core< 0 >
struct identity
A functor representing the identity function.
struct is_ast_visitor
A type trait determining whether a given type is a visitor or not.
struct is_ast_visitor< const T >
struct is_ast_visitor< T & >
struct is_printable
A type trait to check whether a given type is printable.
struct is_ram_visitor
A type trait determining whether a given type is a visitor or not.
struct is_ram_visitor< const T >
struct is_ram_visitor< T & >
class joined_sequence
A auxiliary class to be returned by the join function aggregating the information required to print a list of elements as well as the implementation of the printing itself.
struct lambda_traits_helper
struct lambda_traits_helper< R(A0)>
struct lambda_traits_helper< R(A0, A1)>
struct lambda_traits_helper< R(Args...)>
struct lambda_traits_helper< R(C::*)(Args...) const >
struct lambda_traits_helper< R(C::*)(Args...)>
struct LambdaAstVisitor
A specialized visitor wrapping a lambda function – an auxiliary type required for visitor convenience functions.
class LambdaBTree
The actual implementation of a b-tree data structure.
class LambdaNodeMapper
A special AstNodeMapper wrapping a lambda conducting node transformations.
class LambdaRamNodeMapper
A special RamNodeMapper wrapping a lambda conducting node transformations.
struct LambdaRamVisitor
A specialized visitor wrapping a lambda function – an auxiliary type required for visitor convenience functions.
struct linear
struct linear_search
A linear search strategy for looking up keys in b-tree nodes.
struct multiplying_printer
A utility class required for the implementation of the times function.
struct print
A generic element printer.
class RecordMap
A bidirectional mapping between tuples and reference indices.
struct search_strategy
A common base class for search strategies in b-trees.
struct set_meet_assign_op
A meet operator for set-based property spaces based on the sub-set lattices.
struct strategy_selection
A template-meta class to select search strategies for b-trees depending on the key type.
class TrieBase
A base class for the Trie implementation allowing various specializations of the Trie template to inherit common functionality.
struct updater
The default non-updater.
Functions
template<typename Tuple >
RecordMap< Tuple > & getRecordMap ()
The static access function for record of a certain type.
template<typename R , typename N >
LambdaAstVisitor< R, N > makeLambdaAstVisitor (const std::function< R(const N &)> &fun)
A factory function for creating LambdaAstVisitor instances.
template<typename R , typename N >
LambdaRamVisitor< R, N > makeLambdaRamVisitor (const std::function< R(const N &)> &fun)
A factory function for creating LambdaRamVisitor instances.
Function Documentation
template<typename Tuple > RecordMap<Tuple>& souffle::detail::getRecordMap ()
The static access function for record of a certain type.
Definition at line 157 of file CompiledRecord.h.
{
     static RecordMap<Tuple> map;
     return map;
 }
template<typename R , typename N > LambdaAstVisitor<R, N> souffle::detail::makeLambdaAstVisitor (const std::function< R(const N &)> & fun)
A factory function for creating LambdaAstVisitor instances.
Definition at line 259 of file AstVisitor.h.
Referenced by souffle::visitDepthFirst(), and souffle::visitDepthFirstPostOrder().
{
     return LambdaAstVisitor<R, N>(fun);
 }
template<typename R , typename N > LambdaRamVisitor<R, N> souffle::detail::makeLambdaRamVisitor (const std::function< R(const N &)> & fun)
A factory function for creating LambdaRamVisitor instances.
Definition at line 300 of file RamVisitor.h.
Referenced by souffle::visitDepthFirst().
{
     return LambdaRamVisitor<R, N>(fun);
 }