souffle: souffle::IterDerefWrapper< Iter, T > Struct Template Reference
souffle::IterDerefWrapper< Iter, T > Struct Template Reference
A wrapper for an iterator obtaining pointers of a certain type, dereferencing values before forwarding them to the consumer.
#include <IterUtils.h>
Public Member Functions
IterDerefWrapper ()=default
IterDerefWrapper (const Iter &iter)
IterDerefWrapper (const IterDerefWrapper &)=default
IterDerefWrapper (IterDerefWrapper &&)=default
bool operator!= (const IterDerefWrapper &other) const
const T & operator* () const
IterDerefWrapper & operator++ ()
const T * operator-> () const
IterDerefWrapper & operator= (const IterDerefWrapper &)=default
IterDerefWrapper & operator= (IterDerefWrapper &&)=default
bool operator== (const IterDerefWrapper &other) const
Data Fields
Iter iter
Detailed Description
template<typename Iter, typename T = typename std::remove_pointer<typename Iter::value_type>::type>
struct souffle::IterDerefWrapper< Iter, T >
A wrapper for an iterator obtaining pointers of a certain type, dereferencing values before forwarding them to the consumer.
Template Parameters
Iter ... the type of wrapped iterator
T ... the value to be accessed by the resulting iterator
Definition at line 31 of file IterUtils.h.
Constructor & Destructor Documentation
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper () default
Referenced by souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper().
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper (const Iter & iter) inline
Definition at line 38 of file IterUtils.h.
References souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper(), and souffle::IterDerefWrapper< Iter, T >::operator=().
 : iter(iter) {}
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper (const IterDerefWrapper< Iter, T > &) default
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper (IterDerefWrapper< Iter, T > &&) default
Member Function Documentation
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> bool souffle::IterDerefWrapper< Iter, T >::operator!= (const IterDerefWrapper< Iter, T > & other) const inline
Definition at line 54 of file IterUtils.h.
References souffle::IterDerefWrapper< Iter, T >::iter.
{
         return iter != other.iter;
     }
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> const T& souffle::IterDerefWrapper< Iter, T >::operator* () const inline
Definition at line 59 of file IterUtils.h.
References souffle::IterDerefWrapper< Iter, T >::iter.
{
         return **iter;
     }
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> IterDerefWrapper& souffle::IterDerefWrapper< Iter, T >::operator++ () inline
Definition at line 69 of file IterUtils.h.
References souffle::IterDerefWrapper< Iter, T >::iter.
{
         ++iter;
         return *this;
     }
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> const T* souffle::IterDerefWrapper< Iter, T >::operator-> () const inline
Definition at line 64 of file IterUtils.h.
{
         return &(**iter);
     }
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> IterDerefWrapper& souffle::IterDerefWrapper< Iter, T >::operator= (const IterDerefWrapper< Iter, T > &) default
Referenced by souffle::IterDerefWrapper< Iter, T >::IterDerefWrapper(), and souffle::SingleValueIterator< T >::SingleValueIterator().
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> IterDerefWrapper& souffle::IterDerefWrapper< Iter, T >::operator= (IterDerefWrapper< Iter, T > &&) default
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> bool souffle::IterDerefWrapper< Iter, T >::operator== (const IterDerefWrapper< Iter, T > & other) const inline
Definition at line 49 of file IterUtils.h.
References souffle::IterDerefWrapper< Iter, T >::iter.
{
         return iter == other.iter;
     }
Field Documentation
template<typename Iter , typename T = typename std::remove_pointer<typename Iter::value_type>::type> Iter souffle::IterDerefWrapper< Iter, T >::iter
Definition at line 33 of file IterUtils.h.
Referenced by souffle::derefIter(), souffle::IterDerefWrapper< Iter, T >::operator!=(), souffle::IterDerefWrapper< Iter, T >::operator*(), souffle::IterDerefWrapper< Iter, T >::operator++(), and souffle::IterDerefWrapper< Iter, T >::operator==().
The documentation for this struct was generated from the following file:
IterUtils.h