souffle: souffle::Lock Struct Reference
souffle::Lock Struct Reference
A small utility class for implementing simple locks.
#include <ParallelUtils.h>
Data Structures
class Lease
Public Member Functions
Lease acquire ()
void lock ()
bool try_lock ()
void unlock ()
Detailed Description
A small utility class for implementing simple locks.
Definition at line 506 of file ParallelUtils.h.
Member Function Documentation
Lease souffle::Lock::acquire () inline
Definition at line 510 of file ParallelUtils.h.
Referenced by souffle::SymbolTable::acquireLock(), souffle::SymbolTable::contains(), souffle::RAMI::evalStmt(), souffle::InterpreterRelation::getIndex(), souffle::SymbolTable::insert(), souffle::ram::detail::AutoRelation< arity, index_utils::get_full_index< arity >::type >::insert(), souffle::SymbolTable::lookup(), souffle::SymbolTable::lookupExisting(), souffle::detail::RecordMap< Tuple >::pack(), souffle::SymbolTable::resolve(), and souffle::WriteCoutPrintSize::WriteCoutPrintSize().
                     {
         return Lease();
     }
void souffle::Lock::lock () inline
Definition at line 514 of file ParallelUtils.h.
 {}
bool souffle::Lock::try_lock () inline
Definition at line 516 of file ParallelUtils.h.
                     {
         return true;
     }
void souffle::Lock::unlock () inline
Definition at line 520 of file ParallelUtils.h.
 {}
The documentation for this struct was generated from the following file:
ParallelUtils.h