souffle: souffle::ram::index_utils::DirectIndex< Tuple, Index > Struct Template Reference
souffle::ram::index_utils::DirectIndex< Tuple, Index > Struct Template Reference
A direct index storing the indexed elements directly within the maintained index structure.
#include <CompiledIndexUtils.h>
Public Types
using data_structure = btree_set< Tuple, typename Index::comparator >
using iterator = typename data_structure::const_iterator
using key_type = typename data_structure::key_type
using operation_hints = typename data_structure::operation_hints
Public Member Functions
iterator begin () const
void clear ()
bool contains (const key_type &key, operation_hints &hints) const
bool empty () const
iterator end () const
template<typename SubIndex >
range< iterator > equalRange (const key_type &key, operation_hints &hints) const
iterator find (const key_type &key, operation_hints &hints) const
bool insert (const key_type &key, operation_hints &hints)
void insertAll (const DirectIndex &other)
std::vector< range< iterator > > partition () const
void printHintStatistics (std::ostream &out, const std::string &prefix) const
std::size_t size () const
Static Public Member Functions
static void printDescription (std::ostream &out)
Private Attributes
data_structure index
Detailed Description
template<typename Tuple, typename Index>
struct souffle::ram::index_utils::DirectIndex< Tuple, Index >
A direct index storing the indexed elements directly within the maintained index structure.
Template Parameters
Tuple .. the type of tuple to be maintained by this index
Index .. the index to be internally utilized.
Definition at line 583 of file CompiledIndexUtils.h.
Member Typedef Documentation
template<typename Tuple , typename Index > using souffle::ram::index_utils::DirectIndex< Tuple, Index >::data_structure = btree_set<Tuple, typename Index::comparator>
Definition at line 584 of file CompiledIndexUtils.h.
template<typename Tuple , typename Index > using souffle::ram::index_utils::DirectIndex< Tuple, Index >::iterator = typename data_structure::const_iterator
Definition at line 588 of file CompiledIndexUtils.h.
template<typename Tuple , typename Index > using souffle::ram::index_utils::DirectIndex< Tuple, Index >::key_type = typename data_structure::key_type
Definition at line 586 of file CompiledIndexUtils.h.
template<typename Tuple , typename Index > using souffle::ram::index_utils::DirectIndex< Tuple, Index >::operation_hints = typename data_structure::operation_hints
Definition at line 590 of file CompiledIndexUtils.h.
Member Function Documentation
template<typename Tuple , typename Index > iterator souffle::ram::index_utils::DirectIndex< Tuple, Index >::begin () const inline
Definition at line 641 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::begin().
{
         return index.begin();
     }
template<typename Tuple , typename Index > void souffle::ram::index_utils::DirectIndex< Tuple, Index >::clear () inline
Definition at line 649 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::clear().
                  {
         index.clear();
     }
template<typename Tuple , typename Index > bool souffle::ram::index_utils::DirectIndex< Tuple, Index >::contains (const key_type & key, operation_hints & hints) const inline
Definition at line 614 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::contains().
{
         return index.contains(key, hints);
     }
template<typename Tuple , typename Index > bool souffle::ram::index_utils::DirectIndex< Tuple, Index >::empty () const inline
Definition at line 596 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::empty().
{
         return index.empty();
     }
template<typename Tuple , typename Index > iterator souffle::ram::index_utils::DirectIndex< Tuple, Index >::end () const inline
Definition at line 645 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::end().
{
         return index.end();
     }
template<typename Tuple , typename Index > template<typename SubIndex > range<iterator> souffle::ram::index_utils::DirectIndex< Tuple, Index >::equalRange (const key_type & key, operation_hints & hints) const inline
Definition at line 623 of file CompiledIndexUtils.h.
References arity, souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::end(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::lower_bound(), souffle::make_range(), and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::upper_bound().
{
         // more efficient support for full-indices
         if (int(SubIndex::size) == int(Index::size) && int(Index::size) == int(key_type::arity)) {
             // in this case there is at most one element with this value
             auto pos = find(key, hints);
             auto end = index.end();
             if (pos != end) {
                 end = pos;
                 ++end;
             }
             return make_range(pos, end);
         }
         // compute lower and upper bounds
         return make_range(index.lower_bound(lower<Index, SubIndex>(key), hints),
                 index.upper_bound(raise<Index, SubIndex>(key), hints));
     }
template<typename Tuple , typename Index > iterator souffle::ram::index_utils::DirectIndex< Tuple, Index >::find (const key_type & key, operation_hints & hints) const inline
Definition at line 618 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::find().
{
         return index.find(key, hints);
     }
template<typename Tuple , typename Index > bool souffle::ram::index_utils::DirectIndex< Tuple, Index >::insert (const key_type & key, operation_hints & hints) inline
Definition at line 604 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insert().
{
         // insert the element (insert is synchronized internally)
         return index.insert(key, hints);
     }
template<typename Tuple , typename Index > void souffle::ram::index_utils::DirectIndex< Tuple, Index >::insertAll (const DirectIndex< Tuple, Index > & other) inline
Definition at line 609 of file CompiledIndexUtils.h.
References souffle::ram::index_utils::DirectIndex< Tuple, Index >::index, and souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::insertAll().
{
         // use index's insert-all
         index.insertAll(other.index);
     }
template<typename Tuple , typename Index > std::vector<range<iterator> > souffle::ram::index_utils::DirectIndex< Tuple, Index >::partition () const inline
Definition at line 653 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getChunks().
{
         return index.getChunks(400);
     }
template<typename Tuple , typename Index > static void souffle::ram::index_utils::DirectIndex< Tuple, Index >::printDescription (std::ostream & out) inline static
Definition at line 657 of file CompiledIndexUtils.h.
{
         out << "direct-btree-index(" << Index() << ")";
     }
template<typename Tuple , typename Index > void souffle::ram::index_utils::DirectIndex< Tuple, Index >::printHintStatistics (std::ostream & out, const std::string & prefix) const inline
Definition at line 661 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::getHintStatistics().
{
         const auto& stats = index.getHintStatistics();
         out << prefix << "Direct B-Tree Index: (Hits/Misses/Total)\n";
         out << prefix << "       Insert: " << stats.inserts.getHits() << "/" << stats.inserts.getMisses()
             << "/" << stats.inserts.getAccesses() << "\n";
         out << prefix << "     Contains: " << stats.contains.getHits() << "/" << stats.contains.getMisses()
             << "/" << stats.contains.getAccesses() << "\n";
         out << prefix << "  lower bound: " << stats.lower_bound.getHits() << "/"
             << stats.lower_bound.getMisses() << "/" << stats.lower_bound.getAccesses() << "\n";
         out << prefix << "  upper bound: " << stats.upper_bound.getHits() << "/"
             << stats.upper_bound.getMisses() << "/" << stats.upper_bound.getAccesses() << "\n";
     }
template<typename Tuple , typename Index > std::size_t souffle::ram::index_utils::DirectIndex< Tuple, Index >::size () const inline
Definition at line 600 of file CompiledIndexUtils.h.
References souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::size().
{
         return index.size();
     }
Field Documentation
template<typename Tuple , typename Index > data_structure souffle::ram::index_utils::DirectIndex< Tuple, Index >::index private
Definition at line 593 of file CompiledIndexUtils.h.
Referenced by souffle::ram::index_utils::DirectIndex< Tuple, Index >::insertAll().
The documentation for this struct was generated from the following file:
CompiledIndexUtils.h