souffle: souffle::TypeSet Struct Reference
souffle::TypeSet Struct Reference
A collection to represent sets of types.
#include <TypeSystem.h>
Public Types
using const_iterator = IterDerefWrapper< typename std::set< const Type * >::const_iterator >
Public Member Functions
const_iterator begin () const
Allows to iterate over the types contained in this set (only if not universal)
bool contains (const Type &type) const
Determines whether a given type is included or not.
bool empty () const
Emptiness check.
const_iterator end () const
Allows to iterate over the types contained in this set (only if not universal)
void insert (const Type &type)
Adds the given type to this set.
void insert (const TypeSet &set)
Inserts all the types of the given set into this set.
bool isAll () const
Universality check.
bool isSubsetOf (const TypeSet &b) const
Determines whether this set is a subset of the given set.
bool operator!= (const TypeSet &other) const
Determines inequality between type sets.
TypeSet & operator= (const TypeSet &other)=default
bool operator== (const TypeSet &other) const
Determines equality between type sets.
void print (std::ostream &out) const
Adds print support for type sets.
std::size_t size () const
Determines the size of this set unless it is the universal set.
TypeSet (bool all=false)
TypeSet (const TypeSet &other)=default
TypeSet (TypeSet &&other) noexcept
template<typename... Types>
TypeSet (const Types &...types)
Static Public Member Functions
static TypeSet getAllTypes ()
A factory function for the all-types set.
Private Attributes
bool all
True if it is the all-types set, false otherwise.
std::set< const Type *, deref_less< Type > > types
The enumeration of types in case it is not the all-types set.
Friends
std::ostream & operator<< (std::ostream &out, const TypeSet &set)
Detailed Description
A collection to represent sets of types.
In addition to ordinary set capabilities it may also represent the set of all types – without being capable of iterating over those.
It is the basic entity to conduct sub- and super-type computations.
Definition at line 171 of file TypeSystem.h.
Member Typedef Documentation
using souffle::TypeSet::const_iterator = IterDerefWrapper<typename std::set<const Type*>::const_iterator>
Definition at line 173 of file TypeSystem.h.
Constructor & Destructor Documentation
souffle::TypeSet::TypeSet (bool all = false) inline
Definition at line 177 of file TypeSystem.h.
 : all(all) {}
souffle::TypeSet::TypeSet (const TypeSet & other) default
souffle::TypeSet::TypeSet (TypeSet && other) inline noexcept
Definition at line 181 of file TypeSystem.h.
References types.
                                       : all(other.all), types() {
         types.swap(other.types);
     }
template<typename... Types> souffle::TypeSet::TypeSet (const Types &... types) inline
Definition at line 186 of file TypeSystem.h.
                                    : all(false) {
         for (const Type* cur : toVector<const Type*>(&types...)) {
             this->types.insert(cur);
         }
     }
Member Function Documentation
const_iterator souffle::TypeSet::begin () const inline
Allows to iterate over the types contained in this set (only if not universal)
Definition at line 248 of file TypeSystem.h.
References souffle::derefIter(), and types.
Referenced by souffle::getGreatestCommonSubtypes(), and souffle::getLeastCommonSupertypes().
{
         assert(!all && "Unable to enumerate universe.");
         return derefIter(types.begin());
     }
bool souffle::TypeSet::contains (const Type & type) const inline
Determines whether a given type is included or not.
Definition at line 216 of file TypeSystem.h.
References types.
Referenced by isSubsetOf().
{
         return all || types.find(&type) != types.end();
     }
bool souffle::TypeSet::empty () const inline
Emptiness check.
Definition at line 200 of file TypeSystem.h.
References types.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::getGreatestCommonSubtypes(), souffle::getLeastCommonSupertypes(), souffle::isNumberType(), souffle::isRecordType(), and souffle::isSymbolType().
{
         return !all && types.empty();
     }
const_iterator souffle::TypeSet::end () const inline
Allows to iterate over the types contained in this set (only if not universal)
Definition at line 254 of file TypeSystem.h.
References souffle::derefIter(), and types.
{
         assert(!all && "Unable to enumerate universe.");
         return derefIter(types.end());
     }
static TypeSet souffle::TypeSet::getAllTypes () inline static
A factory function for the all-types set.
Definition at line 195 of file TypeSystem.h.
{
         return TypeSet(true);
     }
void souffle::TypeSet::insert (const Type & type) inline
Adds the given type to this set.
Definition at line 221 of file TypeSystem.h.
References types.
Referenced by souffle::TypeEnvironment::getAllTypes(), souffle::getGreatestCommonSubtypes(), and souffle::getLeastCommonSupertypes().
{
         if (all) {
             return;
         }
         types.insert(&type);
     }
void souffle::TypeSet::insert (const TypeSet & set) inline
Inserts all the types of the given set into this set.
Definition at line 229 of file TypeSystem.h.
References types.
{
         if (all) {
             return;
         }
         // if the other set is universal => make this one universal
         if (set.isAll()) {
             all = true;
             types.clear();
             return;
         }
         // add types one by one
         for (const auto& t : set) {
             insert(t);
         }
     }
bool souffle::TypeSet::isAll () const inline
Universality check.
Definition at line 205 of file TypeSystem.h.
Referenced by souffle::getGreatestCommonSubtypes(), souffle::getLeastCommonSupertypes(), souffle::isNumberType(), souffle::isRecordType(), isSubsetOf(), and souffle::isSymbolType().
{
         return all;
     }
bool souffle::TypeSet::isSubsetOf (const TypeSet & b) const inline
Determines whether this set is a subset of the given set.
Definition at line 260 of file TypeSystem.h.
References souffle::all_of(), contains(), and isAll().
{
         if (all) {
             return b.isAll();
         }
         return all_of(*this, [&](const Type& cur) { return b.contains(cur); });
     }
bool souffle::TypeSet::operator!= (const TypeSet & other) const inline
Determines inequality between type sets.
Definition at line 273 of file TypeSystem.h.
{
         return !(*this == other);
     }
TypeSet& souffle::TypeSet::operator= (const TypeSet & other) default
bool souffle::TypeSet::operator== (const TypeSet & other) const inline
Determines equality between type sets.
Definition at line 268 of file TypeSystem.h.
References all, types, and types.
{
         return all == other.all && types == other.types;
     }
void souffle::TypeSet::print (std::ostream & out) const inline
Adds print support for type sets.
Definition at line 278 of file TypeSystem.h.
References souffle::Type::getName(), souffle::join(), and types.
{
         if (all) {
             out << "{ - all types - }";
         } else {
             out << "{"
                 << join(types, ",", [](std::ostream& out, const Type* type) { out << type->getName(); })
                 << "}";
         }
     }
std::size_t souffle::TypeSet::size () const inline
Determines the size of this set unless it is the universal set.
Definition at line 210 of file TypeSystem.h.
References types.
{
         assert(!all && "Unable to give size of universe.");
         return types.size();
     }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const TypeSet & set) friend
Definition at line 288 of file TypeSystem.h.
{
         set.print(out);
         return out;
     }
Field Documentation
bool souffle::TypeSet::all private
True if it is the all-types set, false otherwise.
Definition at line 295 of file TypeSystem.h.
Referenced by operator==().
std::set<const Type*, deref_less<Type> > souffle::TypeSet::types private
The enumeration of types in case it is not the all-types set.
Definition at line 298 of file TypeSystem.h.
Referenced by operator==(), and TypeSet().
The documentation for this struct was generated from the following file:
TypeSystem.h